export const smithersSpanAttributeAliases: Record<string, string> = {
  runId: "smithers.run_id",
  run_id: "smithers.run_id",
  workflowName: "smithers.workflow_name",
  workflow_name: "smithers.workflow_name",
  nodeId: "smithers.node_id",
  node_id: "smithers.node_id",
  iteration: "smithers.iteration",
  attempt: "smithers.attempt",
  nodeLabel: "smithers.node_label",
  node_label: "smithers.node_label",
  toolName: "smithers.tool_name",
  tool_name: "smithers.tool_name",
  agent: "smithers.agent",
  model: "smithers.model",
  status: "smithers.status",
  waitReason: "smithers.wait_reason",
  wait_reason: "smithers.wait_reason",
};
