import type { GenerateTextResult } from "ai";
import { BaseCliAgent, type CliOutputInterpreter } from "./BaseCliAgent";
import type { BaseCliAgentOptions, PiExtensionUiRequest, PiExtensionUiResponse } from "./BaseCliAgent";
import { type AgentCapabilityRegistry } from "./capability-registry";
export type { PiExtensionUiRequest, PiExtensionUiResponse };
export type PiAgentOptions = BaseCliAgentOptions & {
    provider?: string;
    model?: string;
    apiKey?: string;
    systemPrompt?: string;
    appendSystemPrompt?: string;
    mode?: "text" | "json" | "rpc";
    print?: boolean;
    continue?: boolean;
    resume?: boolean;
    session?: string;
    sessionDir?: string;
    noSession?: boolean;
    models?: string | string[];
    listModels?: boolean | string;
    tools?: string[];
    noTools?: boolean;
    extension?: string[];
    noExtensions?: boolean;
    skill?: string[];
    noSkills?: boolean;
    promptTemplate?: string[];
    noPromptTemplates?: boolean;
    theme?: string[];
    noThemes?: boolean;
    thinking?: "off" | "minimal" | "low" | "medium" | "high" | "xhigh";
    export?: string;
    files?: string[];
    verbose?: boolean;
    onExtensionUiRequest?: (request: PiExtensionUiRequest) => Promise<PiExtensionUiResponse | null> | PiExtensionUiResponse | null;
};
export declare function createPiCapabilityRegistry(opts?: PiAgentOptions): AgentCapabilityRegistry;
export declare class PiAgent extends BaseCliAgent {
    private readonly opts;
    readonly capabilities: AgentCapabilityRegistry;
    readonly cliEngine = "pi";
    private issuedSessionRef?;
    constructor(opts?: PiAgentOptions);
    private resolveMode;
    private buildArgs;
    protected createOutputInterpreter(): CliOutputInterpreter;
    generate(options: any): Promise<GenerateTextResult<any, any>>;
    protected buildCommand(params: {
        prompt: string;
        systemPrompt?: string;
        cwd: string;
        options: any;
    }): Promise<{
        command: string;
        args: string[];
        stdin?: string;
        outputFormat?: string;
        outputFile?: string;
        cleanup?: () => Promise<void>;
    }>;
}
