import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { generateAgentsTs } from "./agent-detection";

type InitOptions = {
  force?: boolean;
  rootDir?: string;
};

type InitResult = {
  rootDir: string;
  writtenFiles: string[];
  skippedFiles: string[];
  preservedPaths: string[];
};

type DependencyVersions = {
  smithersVersion: string;
  zodVersion: string;
  typescriptVersion: string;
  reactTypesVersion: string;
  reactDomTypesVersion: string;
  mdxTypesVersion: string;
};

type TemplateFile = {
  path: string;
  contents: string;
};

function ensureDir(path: string) {
  mkdirSync(path, { recursive: true });
}

function ensureParent(path: string) {
  ensureDir(dirname(path));
}

function readJson(path: string) {
  return JSON.parse(readFileSync(path, "utf8")) as Record<string, any>;
}

function readPackageVersion(path: string, fallback: string) {
  try {
    return String(readJson(path).version ?? fallback);
  } catch {
    return fallback;
  }
}

function readDependencyVersions(): DependencyVersions {
  const rootPackage = readJson(new URL("../../package.json", import.meta.url).pathname);
  const nodeModulesRoot = new URL("../../node_modules/", import.meta.url).pathname;

  return {
    smithersVersion: String(rootPackage.version ?? "0.0.0"),
    zodVersion: readPackageVersion(resolve(nodeModulesRoot, "zod", "package.json"), "4.0.0"),
    typescriptVersion: readPackageVersion(resolve(nodeModulesRoot, "typescript", "package.json"), "5.0.0"),
    reactTypesVersion: readPackageVersion(resolve(nodeModulesRoot, "@types", "react", "package.json"), "19.0.0"),
    reactDomTypesVersion: readPackageVersion(resolve(nodeModulesRoot, "@types", "react-dom", "package.json"), "19.0.0"),
    mdxTypesVersion: readPackageVersion(resolve(nodeModulesRoot, "@types", "mdx", "package.json"), "2.0.0"),
  };
}

function renderPackageJson(versions: DependencyVersions) {
  return JSON.stringify(
    {
      name: "smithers-workflows",
      private: true,
      type: "module",
      scripts: {
        typecheck: "tsc --noEmit",
        "workflow:list": "smithers workflow list",
        "workflow:run": "smithers workflow run",
        "workflow:implement": "smithers workflow implement",
      },
      dependencies: {
        "smithers-orchestrator": versions.smithersVersion,
        zod: versions.zodVersion,
      },
      devDependencies: {
        typescript: versions.typescriptVersion,
        "@types/react": versions.reactTypesVersion,
        "@types/react-dom": versions.reactDomTypesVersion,
        "@types/mdx": versions.mdxTypesVersion,
      },
    },
    null,
    2,
  ) + "\n";
}

function renderTsconfig() {
  return JSON.stringify(
    {
      compilerOptions: {
        lib: ["ESNext", "DOM", "DOM.Iterable"],
        target: "ESNext",
        module: "ESNext",
        moduleDetection: "force",
        jsx: "react-jsx",
        jsxImportSource: "smithers-orchestrator",
        moduleResolution: "bundler",
        allowImportingTsExtensions: true,
        verbatimModuleSyntax: true,
        noEmit: true,
        strict: true,
        skipLibCheck: true,
      },
      include: ["./**/*"],
      exclude: ["./executions/**/*"],
    },
    null,
    2,
  ) + "\n";
}

function renderPrompts(): TemplateFile[] {
  return [
    {
      path: ".smithers/prompts/review.mdx",
      contents: [
        "# Review",
        "",
        "Reviewer: {props.reviewer}",
        "",
        "Review the following request and respond with a concise JSON object.",
        "",
        "REQUEST:",
        "{props.prompt}",
        "",
        "REQUIRED OUTPUT:",
        "{props.schema}",
        "",
      ].join("\n"),
    },
    {
      path: ".smithers/prompts/plan.mdx",
      contents: [
        "# Plan",
        "",
        "Create a practical implementation plan for the following request.",
        "",
        "REQUEST:",
        "{props.prompt}",
        "",
        "REQUIRED OUTPUT:",
        "{props.schema}",
        "",
      ].join("\n"),
    },
    {
      path: ".smithers/prompts/implement.mdx",
      contents: [
        "# Implement",
        "",
        "Carry out the following request in the current repository.",
        "",
        "REQUEST:",
        "{props.prompt}",
        "",
        "REQUIRED OUTPUT:",
        "{props.schema}",
        "",
      ].join("\n"),
    },
    {
      path: ".smithers/prompts/validate.mdx",
      contents: [
        "# Validate",
        "",
        "Validate the current repository state for the following request.",
        "",
        "REQUEST:",
        "{props.prompt}",
        "",
        "REQUIRED OUTPUT:",
        "{props.schema}",
        "",
      ].join("\n"),
    },
    {
      path: ".smithers/prompts/coverage.mdx",
      contents: [
        "# Improve Test Coverage",
        "",
        "Identify the highest-impact missing tests for this request and add them.",
        "",
        "REQUEST:",
        "{props.prompt}",
        "",
        "REQUIRED OUTPUT:",
        "{props.schema}",
        "",
      ].join("\n"),
    },
    {
      path: ".smithers/prompts/ticket.mdx",
      contents: [
        "# Ticket",
        "",
        "Create a well-structured ticket for the following request.",
        "Include a clear title, detailed description, and acceptance criteria.",
        "",
        "REQUEST:",
        "{props.prompt}",
        "",
        "REQUIRED OUTPUT:",
        "{props.schema}",
        "",
      ].join("\n"),
    },
    {
      path: ".smithers/prompts/research.mdx",
      contents: [
        "# Research",
        "",
        "Research the following request thoroughly. Gather relevant context,",
        "prior art, and technical details needed to inform the implementation.",
        "",
        "REQUEST:",
        "{props.prompt}",
        "",
        "REQUIRED OUTPUT:",
        "{props.schema}",
        "",
      ].join("\n"),
    },
    {
      path: ".smithers/prompts/ask-user-instructions.mdx",
      contents: [
        "## Asking the User Questions",
        "",
        "When you need to ask the user a question, run this command in bash:",
        "",
        "```bash",
        'bun .smithers/scripts/ask-user.ts "Your question here" --recommended "Your recommended answer"',
        "```",
        "",
        "The command will block and return the user's answer on stdout.",
        "You MUST use this tool to ask questions — do not just print questions to the output.",
        "Ask one question at a time, wait for the answer, then proceed.",
        "",
        "Options:",
        "  --recommended, -r  Your recommended answer (shown to the user)",
        "  --branch, -b       Which decision branch this question relates to",
        "  --timeout, -t      Seconds to wait for answer (default: 300)",
        "",
      ].join("\n"),
    },
    {
      path: ".smithers/prompts/write-a-prd.mdx",
      contents: [
        "# Write a PRD",
        "",
        "You are writing a Product Requirements Document. Follow these steps,",
        "skipping any you consider unnecessary:",
        "",
        "1. Ask the user for a long, detailed description of the problem they",
        "   want to solve and any potential ideas for solutions.",
        "",
        "2. Explore the repo to verify their assertions and understand the",
        "   current state of the codebase.",
        "",
        "3. Interview the user relentlessly about every aspect of this plan",
        "   until you reach a shared understanding. Walk down each branch of",
        "   the design tree, resolving dependencies between decisions",
        "   one-by-one. Ask questions one at a time. For each question,",
        "   provide your recommended answer. If a question can be answered",
        "   by exploring the codebase, explore the codebase instead.",
        "",
        "4. Sketch out the major modules you will need to build or modify.",
        "   Actively look for opportunities to extract deep modules that can",
        "   be tested in isolation. A deep module (as opposed to a shallow",
        "   module) is one which encapsulates a lot of functionality in a",
        "   simple, testable interface which rarely changes. Check with the",
        "   user that these modules match their expectations and which ones",
        "   they want tests written for.",
        "",
        "5. Once you have a complete understanding, write the PRD using the",
        "   template below.",
        "",
        "{props.additionalInstructions}",
        "",
        "CONTEXT:",
        "{props.context}",
        "",
        "## PRD Template",
        "",
        "### Problem Statement",
        "The problem from the user's perspective.",
        "",
        "### Solution",
        "The solution from the user's perspective.",
        "",
        "### User Stories",
        "A LONG numbered list. Format: As an <actor>, I want a <feature>,",
        "so that <benefit>. Be extremely extensive.",
        "",
        "### Implementation Decisions",
        "Modules to build/modify, interfaces, technical clarifications,",
        "architectural decisions, schema changes, API contracts, and",
        "specific interactions. Do NOT include file paths or code snippets.",
        "",
        "### Testing Decisions",
        "What makes a good test (external behavior, not implementation",
        "details), which modules will be tested, and prior art for tests.",
        "",
        "### Out of Scope",
        "What is explicitly not covered.",
        "",
        "### Further Notes",
        "Any additional context.",
        "",
      ].join("\n"),
    },
    {
      path: ".smithers/prompts/feature-enum-scan.mdx",
      contents: [
        "# Feature Enum Scan",
        "",
        "Analyze the entire repository and produce an exhaustive feature inventory.",
        "Scan routes, services, CLI commands, UI views, SDK modules, jobs, workflows,",
        "and any other shipped or materially stubbed product surface you can find.",
        "",
        "Rules:",
        "",
        "1. Be exhaustive. Prefer missing nothing over being overly concise.",
        "2. Group features by domain using SCREAMING_SNAKE_CASE group names.",
        "3. Use SCREAMING_SNAKE_CASE feature names that are specific and code-backed.",
        "4. Split broad buckets into concrete, independently auditable features.",
        "5. Run `git rev-parse HEAD` and include the commit hash in `lastCommitHash`.",
        "6. Include a markdownBody that explains the grouping and notable edge cases.",
        "",
        "{props.additionalContext ? `ADDITIONAL CONTEXT:\\n${props.additionalContext}\\n` : \"\"}",
        "",
        "Example format (truncated from a larger production feature enum):",
        "",
        "```ts",
        "export const FeatureGroups = {",
        "  PLATFORM_RUNTIME: [",
        "    \"PLATFORM_SERVER_BOOTSTRAP\",",
        "    \"PLATFORM_DB_INITIALIZATION\",",
        "    \"PLATFORM_SERVICE_REGISTRY_INITIALIZATION\",",
        "    \"PLATFORM_HTTP_MIDDLEWARE_REQUEST_ID\",",
        "    \"PLATFORM_HEALTHCHECK_ENDPOINTS\",",
        "  ],",
        "",
        "  AUTH_AND_IDENTITY: [",
        "    \"AUTH_SIGN_IN_WITH_GITHUB_OAUTH\",",
        "    \"AUTH_SIGN_IN_WITH_PERSONAL_ACCESS_TOKEN\",",
        "    \"AUTH_SESSION_COOKIE_ISSUANCE\",",
        "    \"AUTH_PERSONAL_ACCESS_TOKEN_CREATE\",",
        "    \"AUTH_CLI_BROWSER_LOGIN\",",
        "  ],",
        "",
        "  USER_ACCOUNT_AND_SETTINGS: [",
        "    \"USER_SELF_PROFILE_VIEW\",",
        "    \"USER_PROFILE_UPDATE\",",
        "    \"USER_SSH_KEY_ADD\",",
        "    \"USER_NOTIFICATION_SETTINGS_UPDATE\",",
        "    \"USER_API_TOKENS_UI\",",
        "  ],",
        "};",
        "```",
        "",
        "REQUIRED OUTPUT:",
        "{props.schema}",
        "",
      ].join("\n"),
    },
    {
      path: ".smithers/prompts/feature-enum-refine.mdx",
      contents: [
        "# Feature Enum Refine",
        "",
        "Refine the existing feature inventory. Find missing features, split overly",
        "broad items into concrete code-backed features, and keep the grouping stable",
        "unless there is a strong repo-backed reason to reorganize it.",
        "",
        "Iteration: {props.iteration}",
        "",
        "{props.lastCommitHash ? `A previous inventory exists. Inspect repo deltas with:\\ngit log --oneline ${props.lastCommitHash}..HEAD\\n` : \"\"}",
        "",
        "CURRENT FEATURE GROUPS:",
        "```json",
        "{JSON.stringify(props.existingFeatures ?? {}, null, 2)}",
        "```",
        "",
        "Checklist:",
        "",
        "1. Add any concrete missing features you can prove from the code.",
        "2. Decompose vague or overloaded feature names into auditable units.",
        "3. Preserve naming discipline: SCREAMING_SNAKE_CASE groups and features.",
        "4. Remove only entries that are clearly unsupported by the current codebase.",
        "5. Keep `lastCommitHash` current by running `git rev-parse HEAD`.",
        "",
        "REQUIRED OUTPUT:",
        "{props.schema}",
        "",
      ].join("\n"),
    },
    {
      path: ".smithers/prompts/audit-feature.mdx",
      contents: [
        "# Audit Feature Group",
        "",
        "Audit the feature group below for the requested focus area.",
        "",
        "Group: {props.groupName}",
        "Focus: {props.focus}",
        "",
        "Features:",
        "{(props.features ?? []).map((feature) => `- ${feature}`).join(\"\\n\")}",
        "",
        "{props.additionalContext ? `ADDITIONAL CONTEXT:\\n${props.additionalContext}\\n` : \"\"}",
        "",
        "Review the code paths that implement these features. Identify concrete gaps,",
        "risks, missing safeguards, and the most important follow-up actions.",
        "",
        "REQUIRED OUTPUT:",
        "{props.schema}",
        "",
      ].join("\n"),
    },
  ];
}

function renderComponents(): TemplateFile[] {
  return [
    {
      path: ".smithers/components/Review.tsx",
      contents: [
        "// smithers-source: seeded",
        "/** @jsxImportSource smithers-orchestrator */",
        'import { Parallel, Task, type AgentLike } from "smithers-orchestrator";',
        'import { z } from "zod/v4";',
        'import ReviewPrompt from "../prompts/review.mdx";',
        "",
        "const reviewIssueSchema = z.object({",
        '  severity: z.enum(["critical", "major", "minor", "nit"]),',
        "  title: z.string(),",
        "  file: z.string().nullable().default(null),",
        "  description: z.string(),",
        "});",
        "",
        "export const reviewOutputSchema = z.object({",
        "  reviewer: z.string(),",
        "  approved: z.boolean(),",
        "  feedback: z.string(),",
        "  issues: z.array(reviewIssueSchema).default([]),",
        "});",
        "",
        "type ReviewProps = {",
        "  idPrefix: string;",
        "  prompt: unknown;",
        "  agents: AgentLike[];",
        "};",
        "",
        "export function Review({ idPrefix, prompt, agents }: ReviewProps) {",
        '  const promptText = typeof prompt === "string" ? prompt : JSON.stringify(prompt ?? null);',
        "  return (",
        "    <Parallel>",
        "      {agents.map((agent, index) => (",
        "        <Task",
        "          key={`${idPrefix}:${index}`}",
        "          id={`${idPrefix}:${index}`}",
        "          output={reviewOutputSchema}",
        "          agent={agent}",
        "          continueOnFail",
        "        >",
        '          <ReviewPrompt reviewer={`reviewer-${index + 1}`} prompt={promptText} />',
        "        </Task>",
        "      ))}",
        "    </Parallel>",
        "  );",
        "}",
        "",
      ].join("\n"),
    },
    {
      path: ".smithers/components/ValidationLoop.tsx",
      contents: [
        "// smithers-source: seeded",
        "/** @jsxImportSource smithers-orchestrator */",
        'import { Sequence, Loop, Task, type AgentLike } from "smithers-orchestrator";',
        'import { z } from "zod/v4";',
        'import ImplementPrompt from "../prompts/implement.mdx";',
        'import ValidatePrompt from "../prompts/validate.mdx";',
        'import { Review, reviewOutputSchema } from "./Review";',
        "",
        "export const implementOutputSchema = z.object({",
        "  summary: z.string(),",
        "  filesChanged: z.array(z.string()).default([]),",
        "  allTestsPassing: z.boolean().default(true),",
        "});",
        "",
        "export const validateOutputSchema = z.object({",
        "  summary: z.string(),",
        "  allPassed: z.boolean().default(true),",
        "  failingSummary: z.string().nullable().default(null),",
        "});",
        "",
        "type ValidationLoopProps = {",
        "  idPrefix: string;",
        "  prompt: unknown;",
        "  implementAgents: AgentLike[];",
        "  reviewAgents: AgentLike[];",
        "  validateAgents?: AgentLike[];",
        "  /** Prior validation/review feedback to incorporate (set by parent on re-render). */",
        "  feedback?: string | null;",
        "  /** Whether the loop is done (validation passed AND review approved). */",
        "  done?: boolean;",
        "  /** Max iterations before giving up. Defaults to 3. */",
        "  maxIterations?: number;",
        "};",
        "",
        "export function ValidationLoop({",
        "  idPrefix,",
        "  prompt,",
        "  implementAgents,",
        "  reviewAgents,",
        "  validateAgents,",
        "  feedback,",
        "  done = false,",
        "  maxIterations = 3,",
        "}: ValidationLoopProps) {",
        "  const validationChain = validateAgents && validateAgents.length > 0",
        "    ? validateAgents",
        "    : implementAgents;",
        '  const promptText = typeof prompt === "string" ? prompt : JSON.stringify(prompt ?? null);',
        "",
        "  const implementPrompt = feedback",
        "    ? `${promptText}\\n\\n---\\nPREVIOUS ATTEMPT FEEDBACK (fix these issues):\\n${feedback}`",
        "    : promptText;",
        "",
        "  return (",
        '    <Loop id={`${idPrefix}:loop`} until={done} maxIterations={maxIterations} onMaxReached="return-last">',
        "      <Sequence>",
        "        <Task id={`${idPrefix}:implement`} output={implementOutputSchema} agent={implementAgents} timeoutMs={1_800_000} heartbeatTimeoutMs={600_000}>",
        "          <ImplementPrompt prompt={implementPrompt} />",
        "        </Task>",
        "        <Task id={`${idPrefix}:validate`} output={validateOutputSchema} agent={validationChain} timeoutMs={1_800_000} heartbeatTimeoutMs={600_000}>",
        "          <ValidatePrompt prompt={promptText} />",
        "        </Task>",
        "        <Review idPrefix={`${idPrefix}:review`} prompt={promptText} agents={reviewAgents} />",
        "      </Sequence>",
        "    </Loop>",
        "  );",
        "}",
        "",
      ].join("\n"),
    },
    {
      path: ".smithers/components/CommandProbe.tsx",
      contents: [
        "// smithers-source: seeded",
        "/** @jsxImportSource smithers-orchestrator */",
        'import { Task } from "smithers-orchestrator";',
        'import { z } from "zod/v4";',
        "",
        "export const commandProbeOutputSchema = z.object({",
        "  command: z.string(),",
        "  available: z.boolean(),",
        "}).passthrough();",
        "",
        "export function CommandProbe({ id, command }: { id: string; command: string }) {",
        "  return (",
        "    <Task id={id} output={commandProbeOutputSchema}>",
        "      {{ command, available: true }}",
        "    </Task>",
        "  );",
        "}",
        "",
      ].join("\n"),
    },
    {
      path: ".smithers/components/GrillMe.tsx",
      contents: [
        "/** @jsxImportSource smithers-orchestrator */",
        'import { Loop, Sequence, Task, type AgentLike, type OutputTarget } from "smithers-orchestrator";',
        'import { z } from "zod/v4";',
        'import GrillMeSkill from "skills/grill-me/SKILL.md";',
        'import AskUserInstructions from "../prompts/ask-user-instructions.mdx";',
        "",
        "export const grillOutputSchema = z.looseObject({",
        "  question: z.string(),",
        "  recommendedAnswer: z.string().nullable().default(null),",
        "  branch: z.string().nullable().default(null),",
        "  resolved: z.boolean().default(false),",
        "  questionsAsked: z.number().int().default(0),",
        "  sharedUnderstanding: z.string().nullable().default(null),",
        "});",
        "",
        "type GrillMeProps = {",
        "  idPrefix: string;",
        "  context: string;",
        "  currentDraft?: any;",
        "  agent: AgentLike | AgentLike[];",
        "  output: OutputTarget;",
        "  maxIterations?: number;",
        "  children?: React.ReactNode;",
        "  until?: boolean;",
        "};",
        "",
        "export function GrillMe({",
        "  idPrefix,",
        "  context,",
        "  currentDraft,",
        "  agent,",
        "  output,",
        "  maxIterations = 1,",
        "  children,",
        "  until = false,",
        "}: GrillMeProps) {",
        "  return (",
        "    <Sequence>",
        "      <Loop until={until} maxIterations={maxIterations}>",
        "        <Task id={`${idPrefix}:grill`} output={output} agent={agent}>",
        "          <GrillMeSkill />",
        "          <AskUserInstructions />",
        "          {context}",
        "          {currentDraft && `",
        "",
        "## Current Progress",
        "Here is the result of the previous iteration:",
        "",
        "\\`\\`\\`json",
        "${JSON.stringify(currentDraft, null, 2)}",
        "\\`\\`\\`",
        "",
        "Review this result. If it completely fulfills the requirements, you can stop asking questions and mark resolved: true. Otherwise, I want you to further grill me so we can improve it.`}",
        "        </Task>",
        "        {children}",
        "      </Loop>",
        "    </Sequence>",
        "  );",
        "}",
        "",
      ].join("\n"),
    },
    {
      path: ".smithers/components/WriteAPrd.tsx",
      contents: [
        "// smithers-source: seeded",
        "// Inspired by Matt Pocock's write-a-prd skill (https://github.com/mattpocock/skills)",
        "/** @jsxImportSource smithers-orchestrator */",
        'import { Sequence, Task, type AgentLike } from "smithers-orchestrator";',
        'import { z } from "zod/v4";',
        'import WriteAPrdPrompt from "../prompts/write-a-prd.mdx";',
        "",
        "const userStorySchema = z.object({",
        "  actor: z.string(),",
        "  feature: z.string(),",
        "  benefit: z.string(),",
        "});",
        "",
        "const moduleSketchSchema = z.object({",
        "  name: z.string(),",
        "  description: z.string(),",
        "  isDeepModule: z.boolean().default(false),",
        "  needsTests: z.boolean().default(false),",
        "});",
        "",
        "export const prdOutputSchema = z.object({",
        "  title: z.string(),",
        "  problemStatement: z.string(),",
        "  solution: z.string(),",
        "  userStories: z.array(userStorySchema).default([]),",
        "  implementationDecisions: z.array(z.string()).default([]),",
        "  testingDecisions: z.array(z.string()).default([]),",
        "  modules: z.array(moduleSketchSchema).default([]),",
        "  outOfScope: z.array(z.string()).default([]),",
        "  furtherNotes: z.string().nullable().default(null),",
        "  markdownBody: z.string(),",
        "}).passthrough();",
        "",
        "type WriteAPrdProps = {",
        "  idPrefix: string;",
        "  context: string;",
        "  agent: AgentLike | AgentLike[];",
        "  exploreCodebase?: boolean;",
        "  interviewFirst?: boolean;",
        "  maxInterviewQuestions?: number;",
        "  moduleDepthGuidance?: boolean;",
        "  outputFormat?: \"markdown\" | \"json\";",
        "};",
        "",
        "export function WriteAPrd({",
        "  idPrefix,",
        "  context,",
        "  agent,",
        "  exploreCodebase = true,",
        "  interviewFirst = true,",
        "  maxInterviewQuestions = 20,",
        "  moduleDepthGuidance = true,",
        '  outputFormat = "markdown",',
        "}: WriteAPrdProps) {",
        "  const additionalInstructions = [",
        "    exploreCodebase && \"Explore the codebase to verify assertions before writing.\",",
        "    interviewFirst && `Interview the user first (up to ${maxInterviewQuestions} questions).`,",
        "    moduleDepthGuidance && \"Prefer deep modules over shallow ones when sketching architecture.\",",
        "    outputFormat === \"json\" && \"Return structured JSON in addition to the markdown body.\",",
        "  ].filter(Boolean).join(\"\\n\");",
        "",
        "  return (",
        "    <Sequence>",
        "      <Task",
        "        id={`${idPrefix}:prd`}",
        "        output={prdOutputSchema}",
        "        agent={agent}",
        "      >",
        "        <WriteAPrdPrompt context={context} additionalInstructions={additionalInstructions} />",
        "      </Task>",
        "    </Sequence>",
        "  );",
        "}",
        "",
      ].join("\n"),
    },
    {
      path: ".smithers/components/ForEachFeature.tsx",
      contents: [
        "// smithers-source: seeded",
        "/** @jsxImportSource smithers-orchestrator */",
        'import { Parallel, Sequence, Task, type AgentLike } from "smithers-orchestrator";',
        'import { z } from "zod/v4";',
        "",
        "export const forEachFeatureResultSchema = z.object({",
        "  groupName: z.string(),",
        "  result: z.string(),",
        "  featuresCovered: z.array(z.string()).default([]),",
        "  score: z.number().min(0).max(100).optional(),",
        "}).passthrough();",
        "",
        "export const forEachFeatureMergeSchema = z.object({",
        "  totalGroups: z.number().int(),",
        "  summary: z.string(),",
        "  mergedResult: z.string(),",
        "  markdownBody: z.string(),",
        "}).passthrough();",
        "",
        "type ForEachFeatureProps = {",
        "  idPrefix: string;",
        "  agent: AgentLike | AgentLike[];",
        "  features: Record<string, string[]>;",
        "  prompt: string;",
        "  maxConcurrency?: number;",
        "  mergeAgent?: AgentLike | AgentLike[];",
        "  granularity?: \"group\" | \"feature\";",
        "};",
        "",
        "type FeatureWorkItem = {",
        "  id: string;",
        "  groupName: string;",
        "  features: string[];",
        "};",
        "",
        "function slugifyFeatureToken(value: string) {",
        "  const normalized = value",
        '    .toLowerCase()',
        '    .replace(/[^a-z0-9]+/g, "-")',
        '    .replace(/^-+|-+$/g, "");',
        '  return normalized.length > 0 ? normalized : "item";',
        "}",
        "",
        "export function ForEachFeature({",
        "  idPrefix,",
        "  agent,",
        "  features,",
        "  prompt,",
        "  maxConcurrency = 5,",
        "  mergeAgent,",
        '  granularity = "group",',
        "}: ForEachFeatureProps) {",
        "  const featureEntries = Object.entries(features ?? {}).filter(([, groupFeatures]) => Array.isArray(groupFeatures) && groupFeatures.length > 0);",
        "  const workItems: FeatureWorkItem[] = granularity === \"feature\"",
        "    ? featureEntries.flatMap(([groupName, groupFeatures]) =>",
        "        groupFeatures.map((feature, index) => ({",
        "          id: `${slugifyFeatureToken(groupName)}:${slugifyFeatureToken(feature)}:${index}`,",
        "          groupName,",
        "          features: [feature],",
        "        })),",
        "      )",
        "    : featureEntries.map(([groupName, groupFeatures], index) => ({",
        "        id: `${slugifyFeatureToken(groupName)}:${index}`,",
        "        groupName,",
        "        features: groupFeatures,",
        "      }));",
        "",
        "  const mergeNeeds: Record<string, string> = Object.fromEntries(",
        "    workItems.map((item, index) => [`item${index}`, `${idPrefix}:group:${item.id}`]),",
        "  );",
        "  const mergeDeps = Object.fromEntries(",
        "    workItems.map((_, index) => [`item${index}`, forEachFeatureResultSchema]),",
        "  ) as Record<string, typeof forEachFeatureResultSchema>;",
        "",
        "  if (workItems.length === 0) {",
        "    return (",
        "      <Sequence>",
        "        <Task id={`${idPrefix}:merge`} output={forEachFeatureMergeSchema}>",
        "          {{",
        "            totalGroups: 0,",
        '            summary: "No feature groups were provided.",',
        '            mergedResult: "",',
        '            markdownBody: "# Feature Audit\\n\\nNo feature groups were provided.",',
        "          }}",
        "        </Task>",
        "      </Sequence>",
        "    );",
        "  }",
        "",
        "  return (",
        "    <Sequence>",
        "      <Parallel maxConcurrency={maxConcurrency}>",
        "        {workItems.map((item) => (",
        "          <Task",
        "            key={`${idPrefix}:${item.id}`}",
        "            id={`${idPrefix}:group:${item.id}`}",
        "            output={forEachFeatureResultSchema}",
        "            agent={agent}",
        "            continueOnFail",
        "          >",
        "            {[",
        '              `# ${granularity === "feature" ? "Feature" : "Feature Group"} Task`,',
        '              "",',
        '              `Group: ${item.groupName}`,',
        '              `Granularity: ${granularity}`,',
        '              "",',
        '              "Features:",',
        '              ...item.features.map((feature) => `- ${feature}`),',
        '              "",',
        '              "REQUEST:",',
        '              prompt,',
        "            ].join(\"\\n\")}",
        "          </Task>",
        "        ))}",
        "      </Parallel>",
        "      <Task",
        "        id={`${idPrefix}:merge`}",
        "        output={forEachFeatureMergeSchema}",
        "        agent={mergeAgent ?? agent}",
        "        needs={mergeNeeds}",
        "        deps={mergeDeps}",
        "      >",
        "        {(deps) => {",
        "          const results = workItems.map((_, index) => deps[`item${index}`]);",
        "          const totalGroups = new Set(workItems.map((item) => item.groupName)).size;",
        "          return [",
        '            "# Merge Feature Results",',
        '            "",',
        '            `Granularity: ${granularity}`,',
        '            `Distinct groups: ${totalGroups}`,',
        '            `Work items: ${workItems.length}`,' ,
        '            `Set totalGroups to ${totalGroups}.`,',
        '            "",',
        '            "Combine the per-group results below into a single coherent output.",',
        '            "Preserve group boundaries, highlight the most important gaps, and produce a markdownBody suitable for a report.",',
        '            "",',
        "            ...results.flatMap((result, index) => {",
        "              const groupLabel = workItems[index]?.groupName ?? `Group ${index + 1}`;",
        "              return [",
        "                `## ${groupLabel}`,",
        "                `Features covered: ${(result?.featuresCovered ?? []).join(\", \") || \"none\"}`,",
        "                result?.score != null ? `Score: ${result.score}` : null,",
        "                result?.result ?? \"\",",
        "                \"\",",
        "              ].filter(Boolean);",
        "            }),",
        "          ].join(\"\\n\");",
        "        }}",
        "      </Task>",
        "    </Sequence>",
        "  );",
        "}",
        "",
      ].join("\n"),
    },
    {
      path: ".smithers/components/FeatureEnum.tsx",
      contents: [
        "// smithers-source: seeded",
        "/** @jsxImportSource smithers-orchestrator */",
        'import { Sequence, Task, type AgentLike } from "smithers-orchestrator";',
        'import { z } from "zod/v4";',
        'import FeatureEnumScanPrompt from "../prompts/feature-enum-scan.mdx";',
        'import FeatureEnumRefinePrompt from "../prompts/feature-enum-refine.mdx";',
        "",
        "export const featureEnumOutputSchema = z.object({",
        "  featureGroups: z.record(z.string(), z.array(z.string())).default({}),",
        "  totalFeatures: z.number().int().default(0),",
        "  lastCommitHash: z.string().nullable().optional(),",
        "  markdownBody: z.string(),",
        "}).passthrough();",
        "",
        "type FeatureEnumProps = {",
        "  idPrefix: string;",
        "  agent: AgentLike | AgentLike[];",
        "  refineIterations?: number;",
        "  existingFeatures?: Record<string, string[]> | null;",
        "  lastCommitHash?: string | null;",
        "  additionalContext?: string;",
        "};",
        "",
        'const memoryNamespace = { kind: "workflow", id: "feature-enum" } as const;',
        "",
        "export function FeatureEnum({",
        "  idPrefix,",
        "  agent,",
        "  refineIterations,",
        "  existingFeatures = null,",
        "  lastCommitHash = null,",
        '  additionalContext = "",',
        "}: FeatureEnumProps) {",
        "  const isFirstRun = !existingFeatures;",
        "  const totalRefineIterations = Math.max(1, refineIterations ?? (isFirstRun ? 5 : 1));",
        "  const scanTaskId = `${idPrefix}:scan`;",
        "  const refineTaskIds = Array.from({ length: totalRefineIterations }, (_, index) => `${idPrefix}:refine:${index + 1}`);",
        "  const finalTaskId = `${idPrefix}:result`;",
        "",
        "  return (",
        "    <Sequence>",
        "      {isFirstRun && (",
        "        <Task",
        "          id={scanTaskId}",
        "          output={featureEnumOutputSchema}",
        "          agent={agent}",
        "          memory={{",
        "            remember: {",
        "              namespace: memoryNamespace,",
        "              key: scanTaskId,",
        "            },",
        "          }}",
        "        >",
        "          <FeatureEnumScanPrompt additionalContext={additionalContext} />",
        "        </Task>",
        "      )}",
        "",
        "      {refineTaskIds.map((taskId, index) => {",
        "        const previousTaskId = index === 0",
        "          ? (isFirstRun ? scanTaskId : null)",
        "          : refineTaskIds[index - 1];",
        "",
        "        if (previousTaskId) {",
        "          return (",
        "            <Task",
        "              key={taskId}",
        "              id={taskId}",
        "              output={featureEnumOutputSchema}",
        "              agent={agent}",
        "              needs={{ previous: previousTaskId }}",
        "              deps={{ previous: featureEnumOutputSchema }}",
        "              memory={{",
        "                recall: {",
        "                  namespace: memoryNamespace,",
        '                  query: "feature inventory feature enum grouped features",',
        "                  topK: 5,",
        "                },",
        "                remember: {",
        "                  namespace: memoryNamespace,",
        "                  key: taskId,",
        "                },",
        "              }}",
        "            >",
        "              {(deps) => (",
        "                <FeatureEnumRefinePrompt",
        "                  existingFeatures={deps.previous.featureGroups}",
        "                  lastCommitHash={deps.previous.lastCommitHash ?? lastCommitHash}",
        "                  iteration={index + 1}",
        "                />",
        "              )}",
        "            </Task>",
        "          );",
        "        }",
        "",
        "        return (",
        "          <Task",
        "            key={taskId}",
        "            id={taskId}",
        "            output={featureEnumOutputSchema}",
        "            agent={agent}",
        "            memory={{",
        "              recall: {",
        "                namespace: memoryNamespace,",
        '                query: "feature inventory feature enum grouped features",',
        "                topK: 5,",
        "              },",
        "              remember: {",
        "                namespace: memoryNamespace,",
        "                key: taskId,",
        "              },",
        "            }}",
        "          >",
        "            <FeatureEnumRefinePrompt",
        "              existingFeatures={existingFeatures ?? {}}",
        "              lastCommitHash={lastCommitHash}",
        "              iteration={index + 1}",
        "            />",
        "          </Task>",
        "        );",
        "      })}",
        "",
        "      <Task",
        "        id={finalTaskId}",
        "        output={featureEnumOutputSchema}",
        "        needs={{ final: refineTaskIds[refineTaskIds.length - 1] ?? scanTaskId }}",
        "        deps={{ final: featureEnumOutputSchema }}",
        "      >",
        "        {(deps) => deps.final}",
        "      </Task>",
        "    </Sequence>",
        "  );",
        "}",
        "",
      ].join("\n"),
    },
  ];
}

function renderWorkflowFile(
  id: string,
  displayName: string,
  body: string[],
) {
  return {
    path: `.smithers/workflows/${id}.tsx`,
    contents: [
      "// smithers-source: seeded",
      `// smithers-display-name: ${displayName}`,
      "/** @jsxImportSource smithers-orchestrator */",
      ...body,
      "",
    ].join("\n"),
  };
}

function renderWorkflows(): TemplateFile[] {
  const sharedImports = [
    'import { createSmithers } from "smithers-orchestrator";',
    'import { z } from "zod/v4";',
    'import { agents } from "../agents";',
  ];

  return [
    renderWorkflowFile("implement", "Implement", [
      ...sharedImports,
      'import { implementOutputSchema, validateOutputSchema } from "../components/ValidationLoop";',
      'import { Review, reviewOutputSchema } from "../components/Review";',
      'import ResearchPrompt from "../prompts/research.mdx";',
      'import PlanPrompt from "../prompts/plan.mdx";',
      'import ImplementPrompt from "../prompts/implement.mdx";',
      'import ValidatePrompt from "../prompts/validate.mdx";',
      "",
      "const researchOutputSchema = z.object({",
      "  summary: z.string(),",
      "  keyFindings: z.array(z.string()).default([]),",
      "}).passthrough();",
      "",
      "const planOutputSchema = z.object({",
      "  summary: z.string(),",
      "  steps: z.array(z.string()).default([]),",
      "}).passthrough();",
      "",
      "const inputSchema = z.object({",
      '  prompt: z.string().default("Implement the requested change."),',
      "});",
      "",
      "const { Workflow, Task, Sequence, smithers } = createSmithers({",
      "  input: inputSchema,",
      "  research: researchOutputSchema,",
      "  plan: planOutputSchema,",
      "  implement: implementOutputSchema,",
      "  validate: validateOutputSchema,",
      "  review: reviewOutputSchema,",
      "});",
      "",
      "export default smithers((ctx) => {",
      "  const prompt = ctx.input.prompt;",
      "  return (",
      '    <Workflow name="implement">',
      "      <Sequence>",
      '        <Task id="research" output={researchOutputSchema} agent={agents.smartTool}>',
      "          <ResearchPrompt prompt={prompt} />",
      "        </Task>",
      '        <Task id="plan" output={planOutputSchema} agent={agents.smart}>',
      "          <PlanPrompt prompt={prompt} />",
      "        </Task>",
      '        <Task id="implement" output={implementOutputSchema} agent={agents.smart}>',
      "          <ImplementPrompt prompt={prompt} />",
      "        </Task>",
      '        <Task id="validate" output={validateOutputSchema} agent={agents.cheapFast}>',
      "          <ValidatePrompt prompt={prompt} />",
      "        </Task>",
      '        <Review idPrefix="review" prompt={prompt} agents={agents.smart} />',
      "      </Sequence>",
      "    </Workflow>",
      "  );",
      "});",
    ]),
    renderWorkflowFile("review", "Review", [
      ...sharedImports,
      'import { Review, reviewOutputSchema } from "../components/Review";',
      "",
      "const inputSchema = z.object({",
      '  prompt: z.string().default("Review the current repository changes."),',
      "});",
      "",
      "const { Workflow, smithers } = createSmithers({",
      "  input: inputSchema,",
      "  review: reviewOutputSchema,",
      "});",
      "",
      "export default smithers((ctx) => (",
      '  <Workflow name="review">',
      "    <Review",
      '      idPrefix="review"',
      "      prompt={ctx.input.prompt}",
      "      agents={agents.smart}",
      "    />",
      "  </Workflow>",
      "));",
    ]),
    renderWorkflowFile("plan", "Plan", [
      ...sharedImports,
      'import PlanPrompt from "../prompts/plan.mdx";',
      "",
      "const planOutputSchema = z.object({",
      "  summary: z.string(),",
      "  steps: z.array(z.string()).default([]),",
      "}).passthrough();",
      "",
      "const inputSchema = z.object({",
      '  prompt: z.string().default("Create an implementation plan."),',
      "});",
      "",
      "const { Workflow, Task, smithers } = createSmithers({",
      "  input: inputSchema,",
      "  plan: planOutputSchema,",
      "});",
      "",
      "export default smithers((ctx) => (",
      '  <Workflow name="plan">',
      '    <Task id="plan" output={planOutputSchema} agent={agents.smart}>',
      "      <PlanPrompt prompt={ctx.input.prompt} />",
      "    </Task>",
      "  </Workflow>",
      "));",
    ]),
    renderWorkflowFile("research", "Research", [
      ...sharedImports,
      'import ResearchPrompt from "../prompts/research.mdx";',
      "",
      "const researchOutputSchema = z.object({",
      "  summary: z.string(),",
      "  keyFindings: z.array(z.string()).default([]),",
      "}).passthrough();",
      "",
      "const inputSchema = z.object({",
      '  prompt: z.string().default("Research the given topic."),',
      "});",
      "",
      "const { Workflow, Task, smithers } = createSmithers({",
      "  input: inputSchema,",
      "  research: researchOutputSchema,",
      "});",
      "",
      "export default smithers((ctx) => (",
      '  <Workflow name="research">',
      '    <Task id="research" output={researchOutputSchema} agent={agents.smartTool}>',
      "      <ResearchPrompt prompt={ctx.input.prompt} />",
      "    </Task>",
      "  </Workflow>",
      "));",
    ]),
    renderWorkflowFile("ticket-create", "Ticket Create", [
      ...sharedImports,
      'import TicketPrompt from "../prompts/ticket.mdx";',
      "",
      "const ticketCreateOutputSchema = z.object({",
      "  title: z.string(),",
      "  description: z.string(),",
      "  acceptanceCriteria: z.array(z.string()).default([]),",
      "}).passthrough();",
      "",
      "const inputSchema = z.object({",
      '  prompt: z.string().default("Create a ticket for the requested work."),',
      "});",
      "",
      "const { Workflow, Task, smithers } = createSmithers({",
      "  input: inputSchema,",
      "  ticket: ticketCreateOutputSchema,",
      "});",
      "",
      "export default smithers((ctx) => (",
      '  <Workflow name="ticket-create">',
      '    <Task id="ticket" output={ticketCreateOutputSchema} agent={agents.smart}>',
      "      <TicketPrompt prompt={ctx.input.prompt} />",
      "    </Task>",
      "  </Workflow>",
      "));",
    ]),
    renderWorkflowFile("ticket-implement", "Ticket Implement", [
      ...sharedImports,
      'import { ValidationLoop, implementOutputSchema, validateOutputSchema } from "../components/ValidationLoop";',
      'import { reviewOutputSchema } from "../components/Review";',
      "",
      "const { Workflow, smithers } = createSmithers({",
      "  implement: implementOutputSchema,",
      "  validate: validateOutputSchema,",
      "  review: reviewOutputSchema,",
      "});",
      "",
      "export default smithers((ctx) => {",
      '  const validate = ctx.outputMaybe("validate", { nodeId: "ticket:validate" });',
      "  const reviews = ctx.outputs.review ?? [];",
      "",
      "  // done = false until validate has actually run AND passed, AND at least one reviewer approved",
      "  const hasValidated = validate !== undefined;",
      "  const validationPassed = hasValidated && validate.allPassed !== false;",
      "  const anyApproved = reviews.length > 0 && reviews.some((r: any) => r.approved === true);",
      "  const done = validationPassed && anyApproved;",
      "",
      "  const feedbackParts: string[] = [];",
      "  if (validate && !validationPassed && validate.failingSummary) {",
      "    feedbackParts.push(`VALIDATION FAILED:\\n${validate.failingSummary}`);",
      "  }",
      "  for (const review of reviews) {",
      "    if (review.approved === false) {",
      "      feedbackParts.push(`REVIEWER REJECTED:\\n${review.feedback}`);",
      "      if (review.issues?.length) {",
      "        for (const issue of review.issues) {",
      "          feedbackParts.push(`  [${issue.severity}] ${issue.title}: ${issue.description}${issue.file ? ` (${issue.file})` : \"\"}`);",
      "        }",
      "      }",
      "    }",
      "  }",
      "  const feedback = feedbackParts.length > 0 ? feedbackParts.join(\"\\n\\n\") : null;",
      "",
      "  return (",
      '    <Workflow name="ticket-implement">',
      "      <ValidationLoop",
      '        idPrefix="ticket"',
      "        prompt={ctx.input.prompt}",
      "        implementAgents={agents.smart}",
      "        validateAgents={agents.smart}",
      "        reviewAgents={agents.smart}",
      "        feedback={feedback}",
      "        done={done}",
      "        maxIterations={3}",
      "      />",
      "    </Workflow>",
      "  );",
      "});",
    ]),
    renderWorkflowFile("tickets-create", "Tickets Create", [
      ...sharedImports,
      "",
      "const ticketsCreateOutputSchema = z.object({",
      "  summary: z.string(),",
      "  tickets: z.array(z.object({",
      "    title: z.string(),",
      "    description: z.string(),",
      "    acceptanceCriteria: z.array(z.string()).default([]),",
      "  })).default([]),",
      "}).passthrough();",
      "",
      "const inputSchema = z.object({",
      '  prompt: z.string().default("Create tickets for the requested work."),',
      "});",
      "",
      "const { Workflow, Task, smithers } = createSmithers({",
      "  input: inputSchema,",
      "  tickets: ticketsCreateOutputSchema,",
      "});",
      "",
      "export default smithers((ctx) => (",
      '  <Workflow name="tickets-create">',
      '    <Task id="tickets" output={ticketsCreateOutputSchema} agent={agents.smart}>',
      "      {`Break the following request into well-defined tickets with titles, descriptions, and acceptance criteria.\\n\\nRequest: ${ctx.input.prompt}`}",
      "    </Task>",
      "  </Workflow>",
      "));",
    ]),
    renderWorkflowFile("ralph", "Ralph", [
      ...sharedImports,
      "",
      "const ralphOutputSchema = z.object({",
      "  summary: z.string(),",
      "}).passthrough();",
      "",
      "const inputSchema = z.object({",
      '  prompt: z.string().default("Continue working on the current task."),',
      "});",
      "",
      "const { Workflow, Task, Loop, smithers } = createSmithers({",
      "  input: inputSchema,",
      "  ralph: ralphOutputSchema,",
      "});",
      "",
      "export default smithers((ctx) => (",
      '  <Workflow name="ralph">',
      "    <Loop until={false} maxIterations={Infinity}>",
      '      <Task id="ralph" output={ralphOutputSchema} agent={agents.smart}>',
      "        {ctx.input.prompt}",
      "      </Task>",
      "    </Loop>",
      "  </Workflow>",
      "));",
    ]),
    renderWorkflowFile("improve-test-coverage", "Improve Test Coverage", [
      ...sharedImports,
      'import { ValidationLoop, implementOutputSchema, validateOutputSchema } from "../components/ValidationLoop";',
      'import { reviewOutputSchema } from "../components/Review";',
      "",
      "const inputSchema = z.object({",
      '  prompt: z.string().default("Improve the test coverage for the current repository."),',
      "});",
      "",
      "const { Workflow, smithers } = createSmithers({",
      "  input: inputSchema,",
      "  implement: implementOutputSchema,",
      "  validate: validateOutputSchema,",
      "  review: reviewOutputSchema,",
      "});",
      "",
      "export default smithers((ctx) => (",
      '  <Workflow name="improve-test-coverage">',
      "    <ValidationLoop",
      '      idPrefix="improve-test-coverage"',
      "      prompt={ctx.input.prompt}",
      "      implementAgents={agents.smart}",
      "      validateAgents={agents.cheapFast}",
      "      reviewAgents={agents.smart}",
      "    />",
      "  </Workflow>",
      "));",
    ]),
    renderWorkflowFile("test-first", "Test First", [
      ...sharedImports,
      'import { ValidationLoop, implementOutputSchema, validateOutputSchema } from "../components/ValidationLoop";',
      'import { reviewOutputSchema } from "../components/Review";',
      "",
      "const inputSchema = z.object({",
      '  prompt: z.string().default("Write or update tests before implementation."),',
      "});",
      "",
      "const { Workflow, smithers } = createSmithers({",
      "  input: inputSchema,",
      "  implement: implementOutputSchema,",
      "  validate: validateOutputSchema,",
      "  review: reviewOutputSchema,",
      "});",
      "",
      "export default smithers((ctx) => (",
      '  <Workflow name="test-first">',
      "    <ValidationLoop",
      '      idPrefix="test-first"',
      "      prompt={ctx.input.prompt}",
      "      implementAgents={agents.smart}",
      "      validateAgents={agents.cheapFast}",
      "      reviewAgents={agents.smart}",
      "    />",
      "  </Workflow>",
      "));",
    ]),
    renderWorkflowFile("debug", "Debug", [
      ...sharedImports,
      'import { ValidationLoop, implementOutputSchema, validateOutputSchema } from "../components/ValidationLoop";',
      'import { reviewOutputSchema } from "../components/Review";',
      "",
      "const inputSchema = z.object({",
      '  prompt: z.string().default("Reproduce and fix the reported bug."),',
      "});",
      "",
      "const { Workflow, smithers } = createSmithers({",
      "  input: inputSchema,",
      "  implement: implementOutputSchema,",
      "  validate: validateOutputSchema,",
      "  review: reviewOutputSchema,",
      "});",
      "",
      "export default smithers((ctx) => (",
      '  <Workflow name="debug">',
      "    <ValidationLoop",
      '      idPrefix="debug"',
      "      prompt={ctx.input.prompt}",
      "      implementAgents={agents.smart}",
      "      validateAgents={agents.cheapFast}",
      "      reviewAgents={agents.smart}",
      "    />",
      "  </Workflow>",
      "));",
    ]),
    renderWorkflowFile("grill-me", "Grill Me", [
      ...sharedImports,
      'import { GrillMe, grillOutputSchema } from "../components/GrillMe";',
      "",
      'const WORKFLOW_ID = "grill-me";',
      "",
      "const { Workflow, smithers, outputs } = createSmithers({",
      "  input: z.object({",
      '    prompt: z.string().default("Describe what you want to get grilled on."),',
      "    maxIterations: z.number().int().default(30),",
      "  }),",
      "  grill: grillOutputSchema,",
      "});",
      "",
      "export default smithers((ctx) => (",
      "  <Workflow name={WORKFLOW_ID}>",
      "    <GrillMe",
      "      idPrefix={WORKFLOW_ID}",
      "      context={ctx.input.prompt}",
      "      agent={agents.smart}",
      "      output={outputs.grill}",
      "      maxIterations={ctx.input.maxIterations}",
      "    />",
      "  </Workflow>",
      "));",
    ]),
    renderWorkflowFile("write-a-prd", "Write a PRD", [
      "// Inspired by Matt Pocock's write-a-prd skill (https://github.com/mattpocock/skills)",
      ...sharedImports,
      'import { GrillMe, grillOutputSchema } from "../components/GrillMe";',
      'import WriteAPrdPrompt from "../prompts/write-a-prd.mdx";',
      "",
      'const WORKFLOW_ID = "write-a-prd";',
      "",
      "const { Workflow, Task, smithers, outputs } = createSmithers({",
      "  input: z.object({",
      '    prompt: z.string().default("Describe the feature or product you want to specify."),',
      "    maxIterations: z.number().int().default(10),",
      "  }),",
      "  grill: grillOutputSchema,",
      "  prd: z.object({",
      "    title: z.string(),",
      "    problemStatement: z.string(),",
      "    solution: z.string(),",
      "    userStories: z.array(z.object({",
      "      actor: z.string(),",
      "      feature: z.string(),",
      "      benefit: z.string(),",
      "    })).default([]),",
      "    implementationDecisions: z.array(z.string()).default([]),",
      "    testingDecisions: z.array(z.string()).default([]),",
      "    observabilityRequirements: z.array(z.string()).default([]),",
      "    metrics: z.array(z.string()).default([]),",
      "    verificationStrategy: z.array(z.string()).default([]),",
      "    modules: z.array(z.object({",
      "      name: z.string(),",
      "      description: z.string(),",
      "      isDeepModule: z.boolean().default(false),",
      "      needsTests: z.boolean().default(false),",
      "    })).default([]),",
      "    outOfScope: z.array(z.string()).default([]),",
      "    furtherNotes: z.string().nullable().default(null),",
      "    markdownBody: z.string(),",
      "  }).passthrough(),",
      "});",
      "",
      "export default smithers((ctx) => {",
      "  const prdHistory = ctx.outputs.prd || [];",
      "  const currentDraft = prdHistory[prdHistory.length - 1];",
      "  const previousDraft = prdHistory[prdHistory.length - 2];",
      "  const isUnchanged = prdHistory.length > 1 && JSON.stringify(currentDraft) === JSON.stringify(previousDraft);",
      "",
      "  return (",
      "    <Workflow name={WORKFLOW_ID}>",
      "      <GrillMe",
      "        until={isUnchanged}",
      "        idPrefix={WORKFLOW_ID}",
      "        context={ctx.input.prompt}",
      "        currentDraft={currentDraft}",
      "        agent={agents.smart}",
      "        output={outputs.grill}",
      "        maxIterations={ctx.input.maxIterations}",
      "      >",
      "        <Task id={`${WORKFLOW_ID}:prd`} output={outputs.prd} agent={agents.smart}>",
      "          <WriteAPrdPrompt",
      "            context={ctx.input.prompt}",
      "            additionalInstructions={`Explore the codebase to verify assertions before writing.",
      "Prefer deep modules over shallow ones when sketching architecture.`}",
      "          />",
      "        </Task>",
      "      </GrillMe>",
      "    </Workflow>",
      "  );",
      "});",
    ]),
    renderWorkflowFile("feature-enum", "Feature Enum", [
      ...sharedImports,
      'import { FeatureEnum, featureEnumOutputSchema } from "../components/FeatureEnum";',
      "",
      "const inputSchema = z.object({",
      "  refineIterations: z.number().int().default(1),",
      "  existingFeatures: z.record(z.string(), z.string()).nullable().default(null),",
      "  lastCommitHash: z.string().nullable().default(null),",
      '  additionalContext: z.string().default(""),',
      "});",
      "",
      "const { Workflow, smithers } = createSmithers({",
      "  input: inputSchema,",
      "  featureEnum: featureEnumOutputSchema,",
      "});",
      "",
      "export default smithers((ctx) => (",
      '  <Workflow name="feature-enum">',
      "    <FeatureEnum",
      '      idPrefix="feature-enum"',
      "      agent={agents.smartTool}",
      "      refineIterations={ctx.input.refineIterations}",
      "      existingFeatures={ctx.input.existingFeatures}",
      "      lastCommitHash={ctx.input.lastCommitHash}",
      "      additionalContext={ctx.input.additionalContext}",
      "    />",
      "  </Workflow>",
      "));",
    ]),
    renderWorkflowFile("audit", "Audit", [
      ...sharedImports,
      'import { ForEachFeature, forEachFeatureMergeSchema, forEachFeatureResultSchema } from "../components/ForEachFeature";',
      "",
      "const inputSchema = z.object({",
      "  features: z.record(z.string(), z.string()).default({}),",
      '  focus: z.string().default("code review"),',
      "  additionalContext: z.string().nullable().default(null),",
      "  maxConcurrency: z.number().int().default(5),",
      "});",
      "",
      "const { Workflow, smithers } = createSmithers({",
      "  input: inputSchema,",
      "  auditFeature: forEachFeatureResultSchema,",
      "  audit: forEachFeatureMergeSchema,",
      "});",
      "",
      "export default smithers((ctx) => (",
      '  <Workflow name="audit">',
      "    <ForEachFeature",
      '      idPrefix="audit"',
      "      agent={agents.smart}",
      "      features={ctx.input.features}",
      "      prompt={[",
      "        `Audit for: ${ctx.input.focus}.`,",
      '        "Evaluate the provided feature scope for gaps in testing, observability, error handling, operational safety, and maintainability.",',
      '        "Use the repository as the source of truth and report concrete findings with actionable next steps.",',
      '        ctx.input.additionalContext ? `Additional context:\\n${ctx.input.additionalContext}` : null,',
      '      ].filter(Boolean).join("\\n\\n")}',
      "      maxConcurrency={ctx.input.maxConcurrency}",
      "      mergeAgent={agents.smart}",
      "    />",
      "  </Workflow>",
      "));",
    ]),
  ];
}

function renderTemplateFiles(versions: DependencyVersions, env: NodeJS.ProcessEnv): TemplateFile[] {
  return [
    {
      path: ".smithers/.gitignore",
      contents: ["node_modules/", "executions/", "*.db", "*.sqlite", "dist/", ".DS_Store", ""].join("\n"),
    },
    {
      path: ".smithers/package.json",
      contents: renderPackageJson(versions),
    },
    {
      path: ".smithers/tsconfig.json",
      contents: renderTsconfig(),
    },
    {
      path: ".smithers/bunfig.toml",
      contents: ['preload = ["./preload.ts"]', ""].join("\n"),
    },
    {
      path: ".smithers/preload.ts",
      contents: ['import { mdxPlugin } from "smithers-orchestrator";', "", "mdxPlugin();", ""].join("\n"),
    },
    {
      path: ".smithers/agents.ts",
      contents: generateAgentsTs(env),
    },
    {
      path: ".smithers/smithers.config.ts",
      contents: [
        "export const repoCommands = {",
        "  lint: null,",
        "  test: null,",
        "  coverage: null,",
        "} as const;",
        "",
        "export default { repoCommands };",
        "",
      ].join("\n"),
    },
    ...renderPrompts(),
    ...renderComponents(),
    ...renderWorkflows(),
    {
      path: ".smithers/tickets/.gitkeep",
      contents: "",
    },
  ];
}

export function initWorkflowPack(options: InitOptions = {}): InitResult {
  const rootDir = resolve(options.rootDir ?? process.cwd(), ".smithers");
  const writtenFiles: string[] = [];
  const skippedFiles: string[] = [];
  const preservedPaths: string[] = [];
  const versions = readDependencyVersions();
  const env = process.env;

  ensureDir(rootDir);
  ensureDir(resolve(rootDir, "prompts"));
  ensureDir(resolve(rootDir, "components"));
  ensureDir(resolve(rootDir, "workflows"));
  ensureDir(resolve(rootDir, "tickets"));

  const executionsDir = resolve(rootDir, "executions");
  if (existsSync(executionsDir)) {
    preservedPaths.push(executionsDir);
  } else {
    ensureDir(executionsDir);
  }

  for (const file of renderTemplateFiles(versions, env)) {
    const absolutePath = resolve(options.rootDir ?? process.cwd(), file.path);
    ensureParent(absolutePath);
    if (existsSync(absolutePath) && !options.force) {
      skippedFiles.push(absolutePath);
      continue;
    }
    writeFileSync(absolutePath, file.contents, "utf8");
    writtenFiles.push(absolutePath);
  }

  return {
    rootDir,
    writtenFiles,
    skippedFiles,
    preservedPaths,
  };
}

// ---------------------------------------------------------------------------
// Workflow follow-up CTAs
// ---------------------------------------------------------------------------

type WorkflowCta = { command: string; description: string };

const WORKFLOW_FOLLOW_UPS: Record<string, WorkflowCta[]> = {
  "research": [
    { command: "workflow run write-a-prd", description: "Formalize findings into a PRD" },
    { command: "workflow run plan", description: "Turn research into an implementation plan" },
  ],
  "plan": [
    { command: "workflow run implement", description: "Execute the plan" },
    { command: "workflow run tickets-create", description: "Break plan into tickets" },
    { command: "workflow run grill-me", description: "Stress-test the plan first" },
  ],
  "ticket-create": [
    { command: "workflow run ticket-implement", description: "Implement the ticket" },
  ],
  "tickets-create": [
    { command: "workflow run ticket-implement", description: "Implement a ticket" },
    { command: "workflow run implement", description: "Build tickets as a batch" },
  ],
  "grill-me": [
    { command: "workflow run write-a-prd", description: "Turn shared understanding into a PRD" },
    { command: "workflow run tickets-create", description: "Break directly into tickets" },
  ],
  "write-a-prd": [
    { command: "workflow run tickets-create", description: "Break PRD into implementable tickets" },
    { command: "workflow run plan", description: "Turn PRD into a phased plan" },
    { command: "workflow run implement", description: "Start building from the PRD" },
  ],
  "debug": [
    { command: "workflow run review", description: "Review the fix" },
    { command: "workflow run improve-test-coverage", description: "Add regression tests" },
  ],
  "implement": [
    { command: "workflow run review", description: "Review the changes" },
    { command: "workflow run improve-test-coverage", description: "Improve test coverage" },
  ],
  "review": [
    { command: "workflow run implement", description: "Address review feedback" },
  ],
  "feature-enum": [
    { command: "workflow run audit", description: "Audit all features" },
    { command: "workflow run implement", description: "Implement missing features" },
  ],
  "audit": [
    { command: "workflow run implement", description: "Address audit findings" },
    { command: "workflow run tickets-create", description: "Create tickets from findings" },
  ],
};

export function getWorkflowFollowUpCtas(workflowPath: string): WorkflowCta[] {
  const id = workflowPath
    .replace(/^.*\//, "")
    .replace(/\.(tsx?|toon)$/, "");
  return WORKFLOW_FOLLOW_UPS[id] ?? [];
}
