package services

import (
	"context"
	"os"
	"testing"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/stretchr/testify/require"

	"github.com/smithersai/smithers/packages/backend/internal/db"
)

// Exercise the generated CTE against PostgreSQL, including an audit failure.
// Temporary tables keep this test independent of the db package's schema reset.
func TestAdminCLITokenSQLAtomicAudit(t *testing.T) {
	databaseURL := os.Getenv("SMITHERS_TEST_ADMIN_CLI_DATABASE_URL")
	if databaseURL == "" {
		t.Skip("SMITHERS_TEST_ADMIN_CLI_DATABASE_URL is not configured")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
	defer cancel()
	conn, err := pgx.Connect(ctx, databaseURL)
	require.NoError(t, err)
	defer conn.Close(context.Background())
	_, err = conn.Exec(ctx, `CREATE TEMP TABLE access_tokens (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL,
 name varchar(255) NOT NULL DEFAULT '', token_hash varchar(255) NOT NULL UNIQUE,
 token_last_eight varchar(8) NOT NULL DEFAULT '', scopes text NOT NULL DEFAULT '',
 expires_at timestamptz, last_used_at timestamptz,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
 CREATE TEMP TABLE audit_log (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_type varchar(64) NOT NULL,
 actor_id bigint, actor_name varchar(255) NOT NULL DEFAULT '', target_type varchar(64) NOT NULL DEFAULT '',
 target_id bigint, target_name varchar(255) NOT NULL DEFAULT '', action varchar(32) NOT NULL,
 metadata jsonb NOT NULL DEFAULT '{}', ip_address varchar(45) NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now());`)
	require.NoError(t, err)
	q := db.New(conn)
	expires := time.Now().UTC().Add(time.Hour).Truncate(time.Microsecond)
	arg := db.CreateAdminCLIAccessTokenParams{UserID: 7, TokenHash: "hash-1", TokenLastEight: "hash0001", Scopes: "read:admin,write:admin", ExpiresAt: pgtype.Timestamptz{Time: expires, Valid: true}, ActorName: "operator", Metadata: []byte(`{"ttl":"1h0m0s","callback_port":4321,"ip":"127.0.0.1"}`), IpAddress: "127.0.0.1"}
	token, err := q.CreateAdminCLIAccessToken(ctx, arg)
	require.NoError(t, err)
	require.Equal(t, "smithers-cli-admin", token.Name)
	require.Equal(t, expires, token.ExpiresAt.Time.UTC())
	var event, actor, target, action, metadata, ip string
	var actorID, targetID int64
	err = conn.QueryRow(ctx, `SELECT event_type,actor_id,actor_name,target_id,target_name,action,metadata::text,ip_address FROM audit_log`).Scan(&event, &actorID, &actor, &targetID, &target, &action, &metadata, &ip)
	require.NoError(t, err)
	require.Equal(t, "auth.cli_admin_login", event)
	require.Equal(t, int64(7), actorID)
	require.Equal(t, token.ID, targetID)
	require.Equal(t, "operator", actor)
	require.Equal(t, token.Name, target)
	require.Equal(t, "login", action)
	require.JSONEq(t, string(arg.Metadata), metadata)
	require.Equal(t, arg.IpAddress, ip)
	_, err = conn.Exec(ctx, `ALTER TABLE audit_log ADD CONSTRAINT reject_new_audits CHECK (false) NOT VALID`)
	require.NoError(t, err)
	arg.TokenHash = "hash-2"
	_, err = q.CreateAdminCLIAccessToken(ctx, arg)
	require.Error(t, err)
	var count int
	require.NoError(t, conn.QueryRow(ctx, `SELECT count(*) FROM access_tokens`).Scan(&count))
	require.Equal(t, 1, count, "failed audit must roll back PAT insertion")
	require.NoError(t, conn.QueryRow(ctx, `SELECT count(*) FROM audit_log`).Scan(&count))
	require.Equal(t, 1, count)
}
