/**
 * Alchemy infrastructure-as-code for gateway.smithers.sh, the @smthrs/gateway docs site.
 * Generated by apps/docs/shared/gen-sites.mjs from apps/docs/shared/manifest.mjs. Edit the generator, then rerun it: node apps/docs/shared/gen-sites.mjs
 *
 * Plan:     pnpm -C apps/docs/gateway run plan
 * Deploy:   pnpm -C apps/docs/gateway run deploy
 * Destroy:  pnpm -C apps/docs/gateway run destroy
 * Stage prod; state lives in the account's alchemy-state-store. The first
 * Alchemy 2 plan and deploy of a live site add `--adopt`. See apps/docs/README.md.
 */
import { makeDocsSiteStack } from "@smithers/docs-shared/alchemy-site"

export default makeDocsSiteStack({ slug: "gateway" })
