// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_analytics.sql

package clusterdb

import (
	"context"
	"time"
)

const analyticsGoldenSnapshots = `-- name: AnalyticsGoldenSnapshots :many

SELECT g.kind,g.status,count(*)::bigint AS count FROM sandbox_golden_snapshots g WHERE g.created_at >= $1::timestamptz AND g.created_at < $2::timestamptz GROUP BY g.kind,g.status ORDER BY g.kind,g.status
`

type AnalyticsGoldenSnapshotsParams struct {
	RangeStart time.Time `json:"range_start"`
	RangeEnd   time.Time `json:"range_end"`
}

type AnalyticsGoldenSnapshotsRow struct {
	Kind   string `json:"kind"`
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

// Private cluster queries kept separate from the product graph.
// Current kind/status counts for platform golden snapshots created in range. These rows have no user owner and are never synthetic-filtered.
func (q *Queries) AnalyticsGoldenSnapshots(ctx context.Context, arg AnalyticsGoldenSnapshotsParams) ([]AnalyticsGoldenSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, analyticsGoldenSnapshots, arg.RangeStart, arg.RangeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsGoldenSnapshotsRow{}
	for rows.Next() {
		var i AnalyticsGoldenSnapshotsRow
		if err := rows.Scan(&i.Kind, &i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
