// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alert_incidents.sql

package clusterdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminMutateAlertIncidents = `-- name: AdminMutateAlertIncidents :many
UPDATE alert_incidents
SET acknowledged_at = CASE
      WHEN $1::text = 'acknowledge' THEN COALESCE(acknowledged_at, now())
      WHEN $1::text = 'unacknowledge' THEN NULL ELSE acknowledged_at END,
    acknowledged_by = CASE
      WHEN $1::text = 'acknowledge' THEN COALESCE(acknowledged_by, $2::text)
      WHEN $1::text = 'unacknowledge' THEN NULL ELSE acknowledged_by END,
    state = CASE WHEN $1::text = 'resolve' THEN 'resolved' ELSE state END,
    resolved_at = CASE WHEN $1::text = 'resolve' THEN now() ELSE resolved_at END,
    resolved_by = CASE WHEN $1::text = 'resolve' THEN $2::text ELSE resolved_by END,
    resolution_note = CASE WHEN $1::text = 'resolve' THEN $3::text ELSE resolution_note END,
    snoozed_until = CASE WHEN $1::text = 'snooze' THEN $4::timestamptz ELSE snoozed_until END,
    updated_at = now()
WHERE (id = ANY($5::bigint[]) OR policy_name = $6::text)
  AND (state IN ('open', 'remediating', 'pr_opened') OR ($1::text = 'resolve' AND state = 'failed'))
RETURNING id, incident_id, policy_name, condition_name, state, summary, incident_url, runbook, workflow, remediation_pr_url, attempts, created_at, resolved_at, updated_at, source, occurrences, last_seen_at, acknowledged_at, acknowledged_by, snoozed_until, resolved_by, resolution_note
`

type AdminMutateAlertIncidentsParams struct {
	Action string             `json:"action"`
	Actor  string             `json:"actor"`
	Note   pgtype.Text        `json:"note"`
	Until  pgtype.Timestamptz `json:"until"`
	Ids    []int64            `json:"ids"`
	Policy pgtype.Text        `json:"policy"`
}

// Single and bulk operations share state transitions. A resolved row is never
// rewritten; bulk selections operate on active rows (resolve also accepts failed).
func (q *Queries) AdminMutateAlertIncidents(ctx context.Context, arg AdminMutateAlertIncidentsParams) ([]AlertIncident, error) {
	rows, err := q.db.Query(ctx, adminMutateAlertIncidents,
		arg.Action,
		arg.Actor,
		arg.Note,
		arg.Until,
		arg.Ids,
		arg.Policy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertIncident{}
	for rows.Next() {
		var i AlertIncident
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.PolicyName,
			&i.ConditionName,
			&i.State,
			&i.Summary,
			&i.IncidentUrl,
			&i.Runbook,
			&i.Workflow,
			&i.RemediationPrUrl,
			&i.Attempts,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.UpdatedAt,
			&i.Source,
			&i.Occurrences,
			&i.LastSeenAt,
			&i.AcknowledgedAt,
			&i.AcknowledgedBy,
			&i.SnoozedUntil,
			&i.ResolvedBy,
			&i.ResolutionNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authorizeAlertRemediationOutcomeRun = `-- name: AuthorizeAlertRemediationOutcomeRun :execrows
UPDATE alert_remediation_jobs AS j
SET workflow_run_id = wr.id,
    updated_at = NOW()
FROM alert_incidents AS i,
     workflow_runs AS wr,
     workflow_definitions AS wd,
     workflow_tasks AS wt,
     workflow_steps AS ws
WHERE j.id = $1
  AND j.incident_id = $2
  AND j.dispatch_token = $3
  AND (j.workflow_run_id IS NULL OR j.workflow_run_id = $4)
  AND i.id = j.incident_id
  AND i.incident_id = $5
  AND wr.id = $4
  AND wr.repository_id = $6
  AND wr.workflow_definition_id = $7
  AND wr.trigger_event = 'monitoring_alert'
  AND wr.execution_plane = 'runner'
  AND wr.dispatch_inputs ->> 'incident_row_id' = j.incident_id::text
  AND wr.dispatch_inputs ->> 'incident_id' = i.incident_id
  AND wr.dispatch_inputs ->> 'remediation_job_id' = j.id::text
  AND wr.dispatch_inputs ->> 'remediation_dispatch_token' = j.dispatch_token
  AND wd.id = wr.workflow_definition_id
  AND wd.repository_id = wr.repository_id
  AND i.workflow <> ''
  AND wd.path = i.workflow
  AND wt.id = $8
  AND wt.workflow_run_id = wr.id
  AND wt.repository_id = wr.repository_id
  AND wt.status = 'running'
  AND wt.runner_id = $9
  AND wt.attempt = $10
  AND wt.payload ->> 'job' = $11::text
  AND ws.id = wt.workflow_step_id
  AND ws.workflow_run_id = wr.id
  AND ws.repository_id = wr.repository_id
  AND ws.name = $11::text
`

type AuthorizeAlertRemediationOutcomeRunParams struct {
	JobID                int64       `json:"job_id"`
	IncidentRowID        int64       `json:"incident_row_id"`
	DispatchToken        string      `json:"dispatch_token"`
	WorkflowRunID        pgtype.Int8 `json:"workflow_run_id"`
	IncidentID           string      `json:"incident_id"`
	RepositoryID         int64       `json:"repository_id"`
	WorkflowDefinitionID int64       `json:"workflow_definition_id"`
	TaskID               int64       `json:"task_id"`
	RunnerID             pgtype.Int8 `json:"runner_id"`
	TaskAttempt          int32       `json:"task_attempt"`
	ExpectedJob          string      `json:"expected_job"`
}

// The HTTP layer supplies a workflow run loaded from a verified, currently
// running task token. Re-check every persisted relationship here and bind the
// job atomically before allowing its incident to be updated.
func (q *Queries) AuthorizeAlertRemediationOutcomeRun(ctx context.Context, arg AuthorizeAlertRemediationOutcomeRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, authorizeAlertRemediationOutcomeRun,
		arg.JobID,
		arg.IncidentRowID,
		arg.DispatchToken,
		arg.WorkflowRunID,
		arg.IncidentID,
		arg.RepositoryID,
		arg.WorkflowDefinitionID,
		arg.TaskID,
		arg.RunnerID,
		arg.TaskAttempt,
		arg.ExpectedJob,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveAlertIncidentsForPolicy = `-- name: CountActiveAlertIncidentsForPolicy :one
SELECT COUNT(*) FROM alert_incidents
WHERE policy_name = $1
  AND state IN ('open', 'remediating', 'pr_opened')
  AND id <> $2
`

type CountActiveAlertIncidentsForPolicyParams struct {
	PolicyName string `json:"policy_name"`
	ID         int64  `json:"id"`
}

func (q *Queries) CountActiveAlertIncidentsForPolicy(ctx context.Context, arg CountActiveAlertIncidentsForPolicyParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAlertIncidentsForPolicy, arg.PolicyName, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAlertRemediationJobsForPolicySince = `-- name: CountAlertRemediationJobsForPolicySince :one
SELECT COUNT(*)
FROM alert_remediation_jobs j
JOIN alert_incidents i ON i.id = j.incident_id
WHERE i.policy_name = $1
  AND j.created_at >= $2
`

type CountAlertRemediationJobsForPolicySinceParams struct {
	PolicyName string    `json:"policy_name"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) CountAlertRemediationJobsForPolicySince(ctx context.Context, arg CountAlertRemediationJobsForPolicySinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAlertRemediationJobsForPolicySince, arg.PolicyName, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlertIncident = `-- name: CreateAlertIncident :one
WITH created AS (
    INSERT INTO alert_incidents (
        incident_id, policy_name, condition_name, state, summary, incident_url, runbook, workflow, source
    )
    SELECT $1, $2, $3, 'open', $4, $5, $6, $7,
           CASE WHEN $1 LIKE 'canary-%' THEN 'canary' ELSE 'monitoring' END
    WHERE NOT EXISTS (SELECT 1 FROM alert_incident_deliveries WHERE incident_id = $1)
    ON CONFLICT (incident_id) DO NOTHING
    RETURNING id, incident_id, policy_name, condition_name, state, summary, incident_url, runbook, workflow, remediation_pr_url, attempts, created_at, resolved_at, updated_at, source, occurrences, last_seen_at, acknowledged_at, acknowledged_by, snoozed_until, resolved_by, resolution_note
), recorded AS (
    INSERT INTO alert_incident_deliveries (incident_id, canonical_incident_id)
    SELECT incident_id, id FROM created
)
SELECT id, incident_id, policy_name, condition_name, state, summary, incident_url, runbook, workflow, remediation_pr_url, attempts, created_at, resolved_at, updated_at, source, occurrences, last_seen_at, acknowledged_at, acknowledged_by, snoozed_until, resolved_by, resolution_note FROM created
`

type CreateAlertIncidentParams struct {
	IncidentID    string `json:"incident_id"`
	PolicyName    string `json:"policy_name"`
	ConditionName string `json:"condition_name"`
	Summary       string `json:"summary"`
	IncidentUrl   string `json:"incident_url"`
	Runbook       string `json:"runbook"`
	Workflow      string `json:"workflow"`
}

type CreateAlertIncidentRow struct {
	ID               int64              `json:"id"`
	IncidentID       string             `json:"incident_id"`
	PolicyName       string             `json:"policy_name"`
	ConditionName    string             `json:"condition_name"`
	State            string             `json:"state"`
	Summary          string             `json:"summary"`
	IncidentUrl      string             `json:"incident_url"`
	Runbook          string             `json:"runbook"`
	Workflow         string             `json:"workflow"`
	RemediationPrUrl string             `json:"remediation_pr_url"`
	Attempts         int32              `json:"attempts"`
	CreatedAt        time.Time          `json:"created_at"`
	ResolvedAt       pgtype.Timestamptz `json:"resolved_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	Source           string             `json:"source"`
	Occurrences      int32              `json:"occurrences"`
	LastSeenAt       time.Time          `json:"last_seen_at"`
	AcknowledgedAt   pgtype.Timestamptz `json:"acknowledged_at"`
	AcknowledgedBy   pgtype.Text        `json:"acknowledged_by"`
	SnoozedUntil     pgtype.Timestamptz `json:"snoozed_until"`
	ResolvedBy       pgtype.Text        `json:"resolved_by"`
	ResolutionNote   pgtype.Text        `json:"resolution_note"`
}

// An already-associated delivery must never create a new canonical incident.
func (q *Queries) CreateAlertIncident(ctx context.Context, arg CreateAlertIncidentParams) (CreateAlertIncidentRow, error) {
	row := q.db.QueryRow(ctx, createAlertIncident,
		arg.IncidentID,
		arg.PolicyName,
		arg.ConditionName,
		arg.Summary,
		arg.IncidentUrl,
		arg.Runbook,
		arg.Workflow,
	)
	var i CreateAlertIncidentRow
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.PolicyName,
		&i.ConditionName,
		&i.State,
		&i.Summary,
		&i.IncidentUrl,
		&i.Runbook,
		&i.Workflow,
		&i.RemediationPrUrl,
		&i.Attempts,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.Occurrences,
		&i.LastSeenAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.SnoozedUntil,
		&i.ResolvedBy,
		&i.ResolutionNote,
	)
	return i, err
}

const createAlertRemediationJob = `-- name: CreateAlertRemediationJob :one
INSERT INTO alert_remediation_jobs (incident_id)
VALUES ($1)
RETURNING id,
          incident_id,
          status,
          attempts,
          error,
          available_at,
          processed_at,
          created_at,
          updated_at,
          dispatch_token,
          workflow_run_id
`

func (q *Queries) CreateAlertRemediationJob(ctx context.Context, incidentID int64) (AlertRemediationJob, error) {
	row := q.db.QueryRow(ctx, createAlertRemediationJob, incidentID)
	var i AlertRemediationJob
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Status,
		&i.Attempts,
		&i.Error,
		&i.AvailableAt,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DispatchToken,
		&i.WorkflowRunID,
	)
	return i, err
}

const failTerminalAlertRemediationIncidents = `-- name: FailTerminalAlertRemediationIncidents :many
UPDATE alert_incidents AS i
SET state = 'failed',
    updated_at = NOW()
FROM alert_remediation_jobs AS j,
     workflow_runs AS wr
WHERE j.incident_id = i.id
  AND j.workflow_run_id = wr.id
  AND wr.status IN ('success', 'failure', 'cancelled')
  AND i.state IN ('open', 'remediating')
RETURNING i.id
`

// The workflow normally reports its outcome while its final task is still
// running. If the run reaches any terminal state without that callback (runner
// crash, cancellation, setup failure, or a failed callback), fail the still-open
// incident so it can never remain remediating forever. A concurrent successful
// callback may still promote failed -> resolved; resolved itself is never
// overwritten.
func (q *Queries) FailTerminalAlertRemediationIncidents(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, failTerminalAlertRemediationIncidents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAlertRemediationWorkflowRun = `-- name: FindAlertRemediationWorkflowRun :one
SELECT wr.id, wr.repository_id, wr.workflow_definition_id, wr.status, wr.trigger_event, wr.trigger_ref, wr.trigger_commit_sha, wr.dispatch_inputs, wr.agent_token_hash, wr.agent_token_expires_at, wr.jjhub_token_id, wr.check_run_id, wr.check_run_url, wr.started_at, wr.completed_at, wr.created_at, wr.updated_at, wr.execution_plane, wr.log_bytes, wr.log_entry_count, wr.cancel_reason
FROM workflow_runs AS wr
WHERE wr.trigger_event = 'monitoring_alert'
  AND wr.execution_plane = 'runner'
  AND wr.dispatch_inputs ->> 'remediation_job_id' = $1::text
  AND wr.dispatch_inputs ->> 'remediation_dispatch_token' = $2
ORDER BY wr.id ASC
LIMIT 1
`

type FindAlertRemediationWorkflowRunParams struct {
	JobID         string `json:"job_id"`
	DispatchToken []byte `json:"dispatch_token"`
}

// Recover a committed dispatch after a worker stops before it can bind the run
// ID back to the job. The unguessable token was allocated with the job, before
// dispatch, so a retry adopts the original run instead of creating another.
func (q *Queries) FindAlertRemediationWorkflowRun(ctx context.Context, arg FindAlertRemediationWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, findAlertRemediationWorkflowRun, arg.JobID, arg.DispatchToken)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.WorkflowDefinitionID,
		&i.Status,
		&i.TriggerEvent,
		&i.TriggerRef,
		&i.TriggerCommitSha,
		&i.DispatchInputs,
		&i.AgentTokenHash,
		&i.AgentTokenExpiresAt,
		&i.JjhubTokenID,
		&i.CheckRunID,
		&i.CheckRunUrl,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExecutionPlane,
		&i.LogBytes,
		&i.LogEntryCount,
		&i.CancelReason,
	)
	return i, err
}

const getAlertIncident = `-- name: GetAlertIncident :one
SELECT id, incident_id, policy_name, condition_name, state, summary, incident_url, runbook, workflow, remediation_pr_url, attempts, created_at, resolved_at, updated_at, source, occurrences, last_seen_at, acknowledged_at, acknowledged_by, snoozed_until, resolved_by, resolution_note FROM alert_incidents WHERE id = $1
`

func (q *Queries) GetAlertIncident(ctx context.Context, id int64) (AlertIncident, error) {
	row := q.db.QueryRow(ctx, getAlertIncident, id)
	var i AlertIncident
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.PolicyName,
		&i.ConditionName,
		&i.State,
		&i.Summary,
		&i.IncidentUrl,
		&i.Runbook,
		&i.Workflow,
		&i.RemediationPrUrl,
		&i.Attempts,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.Occurrences,
		&i.LastSeenAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.SnoozedUntil,
		&i.ResolvedBy,
		&i.ResolutionNote,
	)
	return i, err
}

const getAlertIncidentByIncidentID = `-- name: GetAlertIncidentByIncidentID :one
SELECT id, incident_id, policy_name, condition_name, state, summary, incident_url, runbook, workflow, remediation_pr_url, attempts, created_at, resolved_at, updated_at, source, occurrences, last_seen_at, acknowledged_at, acknowledged_by, snoozed_until, resolved_by, resolution_note FROM alert_incidents WHERE incident_id = $1
`

func (q *Queries) GetAlertIncidentByIncidentID(ctx context.Context, incidentID string) (AlertIncident, error) {
	row := q.db.QueryRow(ctx, getAlertIncidentByIncidentID, incidentID)
	var i AlertIncident
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.PolicyName,
		&i.ConditionName,
		&i.State,
		&i.Summary,
		&i.IncidentUrl,
		&i.Runbook,
		&i.Workflow,
		&i.RemediationPrUrl,
		&i.Attempts,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.Occurrences,
		&i.LastSeenAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.SnoozedUntil,
		&i.ResolvedBy,
		&i.ResolutionNote,
	)
	return i, err
}

const getAlertIncidentForUpdate = `-- name: GetAlertIncidentForUpdate :one
SELECT id, incident_id, policy_name, condition_name, state, summary, incident_url, runbook, workflow, remediation_pr_url, attempts, created_at, resolved_at, updated_at, source, occurrences, last_seen_at, acknowledged_at, acknowledged_by, snoozed_until, resolved_by, resolution_note FROM alert_incidents WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAlertIncidentForUpdate(ctx context.Context, id int64) (AlertIncident, error) {
	row := q.db.QueryRow(ctx, getAlertIncidentForUpdate, id)
	var i AlertIncident
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.PolicyName,
		&i.ConditionName,
		&i.State,
		&i.Summary,
		&i.IncidentUrl,
		&i.Runbook,
		&i.Workflow,
		&i.RemediationPrUrl,
		&i.Attempts,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.Occurrences,
		&i.LastSeenAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.SnoozedUntil,
		&i.ResolvedBy,
		&i.ResolutionNote,
	)
	return i, err
}

const hasLegacyAlertRemediationWorkflowRun = `-- name: HasLegacyAlertRemediationWorkflowRun :one
SELECT EXISTS (
    SELECT 1
    FROM workflow_runs AS wr
    WHERE wr.trigger_event = 'monitoring_alert'
      AND wr.execution_plane = 'runner'
      AND NOT (wr.dispatch_inputs ? 'remediation_dispatch_token')
      AND wr.dispatch_inputs ->> 'incident_row_id' = $1::text
      AND wr.dispatch_inputs ->> 'incident_id' = $2::text
)
`

type HasLegacyAlertRemediationWorkflowRunParams struct {
	IncidentRowID string `json:"incident_row_id"`
	IncidentID    string `json:"incident_id"`
}

// During the one-release rollout, a previous-version worker can commit a run
// before it records incident state. Such runs have no dispatch token, so the
// new worker must fence on the immutable incident identities instead of
// treating a token lookup miss as permission to dispatch again.
func (q *Queries) HasLegacyAlertRemediationWorkflowRun(ctx context.Context, arg HasLegacyAlertRemediationWorkflowRunParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasLegacyAlertRemediationWorkflowRun, arg.IncidentRowID, arg.IncidentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const incrementActiveAlertIncident = `-- name: IncrementActiveAlertIncident :execrows
WITH active AS (
    SELECT i.id FROM alert_incidents AS i
    WHERE i.state IN ('open', 'remediating', 'pr_opened')
      AND (
          EXISTS (
              SELECT 1 FROM alert_incident_deliveries AS delivered
              WHERE delivered.incident_id = $2
                AND delivered.canonical_incident_id = i.id AND delivered.closed_at IS NULL
          )
          OR (
              i.policy_name = $3 AND i.condition_name = $4
              AND NOT EXISTS (
                  SELECT 1 FROM alert_incident_deliveries WHERE incident_id = $2
              )
              AND NOT EXISTS (
                  SELECT 1 FROM alert_incidents AS delivered
                  WHERE delivered.incident_id = $2 AND delivered.state IN ('resolved', 'failed')
              )
          )
      )
    ORDER BY i.id LIMIT 1 FOR UPDATE
), recorded AS (
    INSERT INTO alert_incident_deliveries (incident_id, canonical_incident_id)
    SELECT $2, id FROM active
    ON CONFLICT (incident_id) DO NOTHING
)
UPDATE alert_incidents
SET occurrences = occurrences + 1, last_seen_at = now(),
    summary = $1, updated_at = now()
WHERE id IN (SELECT id FROM active)
  AND state IN ('open', 'remediating', 'pr_opened')
`

type IncrementActiveAlertIncidentParams struct {
	Summary       string `json:"summary"`
	IncidentID    string `json:"incident_id"`
	PolicyName    string `json:"policy_name"`
	ConditionName string `json:"condition_name"`
}

// Called inside the per-policy advisory lock. Recorded IDs can only refresh
// their original canonical incident, never a newer incident with the same key.
func (q *Queries) IncrementActiveAlertIncident(ctx context.Context, arg IncrementActiveAlertIncidentParams) (int64, error) {
	result, err := q.db.Exec(ctx, incrementActiveAlertIncident,
		arg.Summary,
		arg.IncidentID,
		arg.PolicyName,
		arg.ConditionName,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordAlertIncidentRemediationOutcome = `-- name: RecordAlertIncidentRemediationOutcome :exec
UPDATE alert_incidents
SET state = $2,
    remediation_pr_url = $3,
    attempts = attempts + 1,
    resolved_at = CASE WHEN $2 = 'resolved' THEN NOW() ELSE resolved_at END,
    updated_at = NOW()
WHERE id = $1
`

type RecordAlertIncidentRemediationOutcomeParams struct {
	ID               int64  `json:"id"`
	State            string `json:"state"`
	RemediationPrUrl string `json:"remediation_pr_url"`
}

func (q *Queries) RecordAlertIncidentRemediationOutcome(ctx context.Context, arg RecordAlertIncidentRemediationOutcomeParams) error {
	_, err := q.db.Exec(ctx, recordAlertIncidentRemediationOutcome, arg.ID, arg.State, arg.RemediationPrUrl)
	return err
}

const resolveAlertIncidentByIncidentID = `-- name: ResolveAlertIncidentByIncidentID :exec
WITH closed AS (
    UPDATE alert_incident_deliveries
    SET closed_at = COALESCE(closed_at, now())
    WHERE alert_incident_deliveries.incident_id = $1
    RETURNING canonical_incident_id
), resolved AS (
    UPDATE alert_incidents
    SET state = 'resolved', resolved_at = COALESCE(resolved_at, now()), updated_at = now()
    WHERE id IN (SELECT canonical_incident_id FROM closed)
      AND state IN ('open', 'remediating', 'pr_opened')
      AND NOT EXISTS (
          SELECT 1 FROM alert_incident_deliveries AS other
          WHERE other.canonical_incident_id = alert_incidents.id
            AND other.incident_id <> $1 AND other.closed_at IS NULL
      )
), tombstone AS (
    INSERT INTO alert_incidents (
        incident_id, policy_name, condition_name, state, summary,
        incident_url, runbook, workflow, resolved_at, source
    )
    SELECT $1, '', '', 'resolved', '', '', '', '', now(),
           CASE WHEN $1 LIKE 'canary-%' THEN 'canary' ELSE 'monitoring' END
    WHERE NOT EXISTS (SELECT 1 FROM closed)
    ON CONFLICT (incident_id) DO NOTHING
    RETURNING id, incident_id
)
INSERT INTO alert_incident_deliveries (incident_id, canonical_incident_id, closed_at)
SELECT incident_id, id, now() FROM tombstone
`

// Run under the admission lock. CTEs share a snapshot, so exclude this delivery
// explicitly when checking for other live occurrences. Unknown closes retain
// a tombstone to prevent a delayed open from resurrecting the incident.
func (q *Queries) ResolveAlertIncidentByIncidentID(ctx context.Context, incidentID string) error {
	_, err := q.db.Exec(ctx, resolveAlertIncidentByIncidentID, incidentID)
	return err
}

const resolveCanaryAlertIncidents = `-- name: ResolveCanaryAlertIncidents :execrows
UPDATE alert_incidents
SET state = 'resolved', resolved_at = now(), updated_at = now(),
    resolved_by = $1, resolution_note = 'suite passed'
WHERE source = 'canary' AND condition_name = $2
  AND state IN ('open', 'remediating', 'pr_opened')
`

type ResolveCanaryAlertIncidentsParams struct {
	ResolvedBy    pgtype.Text `json:"resolved_by"`
	ConditionName string      `json:"condition_name"`
}

func (q *Queries) ResolveCanaryAlertIncidents(ctx context.Context, arg ResolveCanaryAlertIncidentsParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveCanaryAlertIncidents, arg.ResolvedBy, arg.ConditionName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAlertIncidentState = `-- name: UpdateAlertIncidentState :exec
UPDATE alert_incidents
SET state = $2,
    resolved_at = CASE WHEN $2 = 'resolved' THEN NOW() ELSE resolved_at END,
    updated_at = NOW()
WHERE id = $1
`

type UpdateAlertIncidentStateParams struct {
	ID    int64  `json:"id"`
	State string `json:"state"`
}

func (q *Queries) UpdateAlertIncidentState(ctx context.Context, arg UpdateAlertIncidentStateParams) error {
	_, err := q.db.Exec(ctx, updateAlertIncidentState, arg.ID, arg.State)
	return err
}
