// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: approvals.sql

package clusterdb

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApproval = `-- name: CreateApproval :one

INSERT INTO approvals (
    id, session_id, repository_id, state, kind, title, description, expires_at, payload
)
VALUES (
    $1, $2, $3, 'pending', $4, $5, $6, $7, $8
)
RETURNING id, session_id, repository_id, state, kind, title, description, created_at, decided_at, decided_by, expires_at, payload
`

type CreateApprovalParams struct {
	ID           string             `json:"id"`
	SessionID    string             `json:"session_id"`
	RepositoryID int64              `json:"repository_id"`
	Kind         string             `json:"kind"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	Payload      json.RawMessage    `json:"payload"`
}

// Ticket 0110: approvals flow queries.
//
// Emission path: guest-agent -> plue host -> CreateApproval.
// Decide path: client -> POST /decide -> DecideApproval (state='pending' guard
// enforces idempotency + conflict detection at the SQL level).
// Read path: GetApproval for the decide route preflight; ListApprovalsByRepo
// for repo-scoped inbox clients; ListApprovalsBySession for admin/debug.
// Insert a fresh pending-state approval. Caller supplies repository_id from
// the session context (NOT NULL: realtime stream auth requires it).
func (q *Queries) CreateApproval(ctx context.Context, arg CreateApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, createApproval,
		arg.ID,
		arg.SessionID,
		arg.RepositoryID,
		arg.Kind,
		arg.Title,
		arg.Description,
		arg.ExpiresAt,
		arg.Payload,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RepositoryID,
		&i.State,
		&i.Kind,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.ExpiresAt,
		&i.Payload,
	)
	return i, err
}

const decideApproval = `-- name: DecideApproval :one
UPDATE approvals
SET state       = $2,
    decided_at  = NOW(),
    decided_by  = $3
WHERE id = $1
  AND repository_id = $4
  AND state = 'pending'
RETURNING id, session_id, repository_id, state, kind, title, description, created_at, decided_at, decided_by, expires_at, payload
`

type DecideApprovalParams struct {
	ID           string      `json:"id"`
	State        string      `json:"state"`
	DecidedBy    pgtype.Int8 `json:"decided_by"`
	RepositoryID int64       `json:"repository_id"`
}

// Transitions a pending approval to 'approved' or 'rejected'. The
// `state = 'pending'` guard is the idempotency / conflict detection gate:
//   - If the caller tries to transition a non-pending row, zero rows match
//     and sqlc returns ErrNoRows. The service layer then re-reads the row
//     and decides "idempotent same decision" vs "409 conflict" based on the
//     persisted state.
//
// repository_id predicate scopes the update to the route's repo context so
// a malicious caller can't flip an approval in a different repo by ID.
func (q *Queries) DecideApproval(ctx context.Context, arg DecideApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, decideApproval,
		arg.ID,
		arg.State,
		arg.DecidedBy,
		arg.RepositoryID,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RepositoryID,
		&i.State,
		&i.Kind,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.ExpiresAt,
		&i.Payload,
	)
	return i, err
}

const getApproval = `-- name: GetApproval :one
SELECT id, session_id, repository_id, state, kind, title, description, created_at, decided_at, decided_by, expires_at, payload FROM approvals WHERE id = $1
`

// Returns a single approval row. Does NOT filter on repository_id; the route
// layer enforces repo scoping using the row's repository_id value.
func (q *Queries) GetApproval(ctx context.Context, id string) (Approval, error) {
	row := q.db.QueryRow(ctx, getApproval, id)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RepositoryID,
		&i.State,
		&i.Kind,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.ExpiresAt,
		&i.Payload,
	)
	return i, err
}

const listApprovalsByRepo = `-- name: ListApprovalsByRepo :many
SELECT id, session_id, repository_id, state, kind, title, description, created_at, decided_at, decided_by, expires_at, payload FROM approvals
WHERE repository_id = $1
  AND ($2::text = '' OR state = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListApprovalsByRepoParams struct {
	RepositoryID int64  `json:"repository_id"`
	State        string `json:"state"`
	PageOffset   int32  `json:"page_offset"`
	PageSize     int32  `json:"page_size"`
}

// Repo-scoped approval inbox. Empty state_filter returns all approvals.
func (q *Queries) ListApprovalsByRepo(ctx context.Context, arg ListApprovalsByRepoParams) ([]Approval, error) {
	rows, err := q.db.Query(ctx, listApprovalsByRepo,
		arg.RepositoryID,
		arg.State,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Approval{}
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RepositoryID,
			&i.State,
			&i.Kind,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.DecidedBy,
			&i.ExpiresAt,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingApprovalsBySession = `-- name: ListPendingApprovalsBySession :many
SELECT id, session_id, repository_id, state, kind, title, description, created_at, decided_at, decided_by, expires_at, payload FROM approvals
WHERE repository_id = $1 AND session_id = $2 AND state = 'pending'
ORDER BY created_at DESC
`

type ListPendingApprovalsBySessionParams struct {
	RepositoryID int64  `json:"repository_id"`
	SessionID    string `json:"session_id"`
}

// Admin / debug helper; not on the hot path. realtime stream is the
// production read path for connected clients.
func (q *Queries) ListPendingApprovalsBySession(ctx context.Context, arg ListPendingApprovalsBySessionParams) ([]Approval, error) {
	rows, err := q.db.Query(ctx, listPendingApprovalsBySession, arg.RepositoryID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Approval{}
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RepositoryID,
			&i.State,
			&i.Kind,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.DecidedBy,
			&i.ExpiresAt,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
