// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: changesets.sql

package clusterdb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChangesetMember = `-- name: AddChangesetMember :one
INSERT INTO changeset_members (changeset_id, repository_id, path, change_id, commit_id, target_bookmark)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, changeset_id, repository_id, path, change_id, commit_id, target_bookmark, previous_commit_id, landed_commit_id, created_at, updated_at
`

type AddChangesetMemberParams struct {
	ChangesetID    int64  `json:"changeset_id"`
	RepositoryID   int64  `json:"repository_id"`
	Path           string `json:"path"`
	ChangeID       string `json:"change_id"`
	CommitID       string `json:"commit_id"`
	TargetBookmark string `json:"target_bookmark"`
}

func (q *Queries) AddChangesetMember(ctx context.Context, arg AddChangesetMemberParams) (ChangesetMember, error) {
	row := q.db.QueryRow(ctx, addChangesetMember,
		arg.ChangesetID,
		arg.RepositoryID,
		arg.Path,
		arg.ChangeID,
		arg.CommitID,
		arg.TargetBookmark,
	)
	var i ChangesetMember
	err := row.Scan(
		&i.ID,
		&i.ChangesetID,
		&i.RepositoryID,
		&i.Path,
		&i.ChangeID,
		&i.CommitID,
		&i.TargetBookmark,
		&i.PreviousCommitID,
		&i.LandedCommitID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearChangesetMemberLanded = `-- name: ClearChangesetMemberLanded :exec
UPDATE changeset_members
SET landed_commit_id = '', updated_at = NOW()
WHERE changeset_id = $1
`

func (q *Queries) ClearChangesetMemberLanded(ctx context.Context, changesetID int64) error {
	_, err := q.db.Exec(ctx, clearChangesetMemberLanded, changesetID)
	return err
}

const createChangeset = `-- name: CreateChangeset :one
INSERT INTO changesets (organization_id, superproject_repository_id, change_id, commit_id, parent_change_ids, target_bookmark, description, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, superproject_repository_id, change_id, commit_id, parent_change_ids, target_bookmark, description, state, failure_reason, landing_plan, landed_commit_id, created_by, landed_at, created_at, updated_at
`

type CreateChangesetParams struct {
	OrganizationID           int64           `json:"organization_id"`
	SuperprojectRepositoryID int64           `json:"superproject_repository_id"`
	ChangeID                 string          `json:"change_id"`
	CommitID                 string          `json:"commit_id"`
	ParentChangeIds          json.RawMessage `json:"parent_change_ids"`
	TargetBookmark           string          `json:"target_bookmark"`
	Description              string          `json:"description"`
	CreatedBy                pgtype.Int8     `json:"created_by"`
}

func (q *Queries) CreateChangeset(ctx context.Context, arg CreateChangesetParams) (Changeset, error) {
	row := q.db.QueryRow(ctx, createChangeset,
		arg.OrganizationID,
		arg.SuperprojectRepositoryID,
		arg.ChangeID,
		arg.CommitID,
		arg.ParentChangeIds,
		arg.TargetBookmark,
		arg.Description,
		arg.CreatedBy,
	)
	var i Changeset
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SuperprojectRepositoryID,
		&i.ChangeID,
		&i.CommitID,
		&i.ParentChangeIds,
		&i.TargetBookmark,
		&i.Description,
		&i.State,
		&i.FailureReason,
		&i.LandingPlan,
		&i.LandedCommitID,
		&i.CreatedBy,
		&i.LandedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createChangesetWithMembers = `-- name: CreateChangesetWithMembers :one
WITH created AS (
    INSERT INTO changesets (organization_id, superproject_repository_id, change_id, commit_id, parent_change_ids, target_bookmark, description, created_by)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
    RETURNING id, organization_id, superproject_repository_id, change_id, commit_id, parent_change_ids, target_bookmark, description, state, failure_reason, landing_plan, landed_commit_id, created_by, landed_at, created_at, updated_at
), members AS (
    INSERT INTO changeset_members (changeset_id, repository_id, path, change_id, commit_id, target_bookmark)
    SELECT created.id, m.repository_id, m.path, m.change_id, m.commit_id, m.target_bookmark
    FROM created CROSS JOIN jsonb_to_recordset($9::jsonb)
        AS m(repository_id bigint, path text, change_id text, commit_id text, target_bookmark text)
    RETURNING id
)
SELECT created.id, created.organization_id, created.superproject_repository_id, created.change_id, created.commit_id, created.parent_change_ids, created.target_bookmark, created.description, created.state, created.failure_reason, created.landing_plan, created.landed_commit_id, created.created_by, created.landed_at, created.created_at, created.updated_at FROM created
`

type CreateChangesetWithMembersParams struct {
	OrganizationID           int64           `json:"organization_id"`
	SuperprojectRepositoryID int64           `json:"superproject_repository_id"`
	ChangeID                 string          `json:"change_id"`
	CommitID                 string          `json:"commit_id"`
	ParentChangeIds          json.RawMessage `json:"parent_change_ids"`
	TargetBookmark           string          `json:"target_bookmark"`
	Description              string          `json:"description"`
	CreatedBy                pgtype.Int8     `json:"created_by"`
	Members                  json.RawMessage `json:"members"`
}

type CreateChangesetWithMembersRow struct {
	ID                       int64              `json:"id"`
	OrganizationID           int64              `json:"organization_id"`
	SuperprojectRepositoryID int64              `json:"superproject_repository_id"`
	ChangeID                 string             `json:"change_id"`
	CommitID                 string             `json:"commit_id"`
	ParentChangeIds          json.RawMessage    `json:"parent_change_ids"`
	TargetBookmark           string             `json:"target_bookmark"`
	Description              string             `json:"description"`
	State                    string             `json:"state"`
	FailureReason            string             `json:"failure_reason"`
	LandingPlan              json.RawMessage    `json:"landing_plan"`
	LandedCommitID           string             `json:"landed_commit_id"`
	CreatedBy                pgtype.Int8        `json:"created_by"`
	LandedAt                 pgtype.Timestamptz `json:"landed_at"`
	CreatedAt                time.Time          `json:"created_at"`
	UpdatedAt                time.Time          `json:"updated_at"`
}

func (q *Queries) CreateChangesetWithMembers(ctx context.Context, arg CreateChangesetWithMembersParams) (CreateChangesetWithMembersRow, error) {
	row := q.db.QueryRow(ctx, createChangesetWithMembers,
		arg.OrganizationID,
		arg.SuperprojectRepositoryID,
		arg.ChangeID,
		arg.CommitID,
		arg.ParentChangeIds,
		arg.TargetBookmark,
		arg.Description,
		arg.CreatedBy,
		arg.Members,
	)
	var i CreateChangesetWithMembersRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SuperprojectRepositoryID,
		&i.ChangeID,
		&i.CommitID,
		&i.ParentChangeIds,
		&i.TargetBookmark,
		&i.Description,
		&i.State,
		&i.FailureReason,
		&i.LandingPlan,
		&i.LandedCommitID,
		&i.CreatedBy,
		&i.LandedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChangesetByID = `-- name: GetChangesetByID :one
SELECT id, organization_id, superproject_repository_id, change_id, commit_id, parent_change_ids, target_bookmark, description, state, failure_reason, landing_plan, landed_commit_id, created_by, landed_at, created_at, updated_at
FROM changesets
WHERE id = $1
`

func (q *Queries) GetChangesetByID(ctx context.Context, id int64) (Changeset, error) {
	row := q.db.QueryRow(ctx, getChangesetByID, id)
	var i Changeset
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SuperprojectRepositoryID,
		&i.ChangeID,
		&i.CommitID,
		&i.ParentChangeIds,
		&i.TargetBookmark,
		&i.Description,
		&i.State,
		&i.FailureReason,
		&i.LandingPlan,
		&i.LandedCommitID,
		&i.CreatedBy,
		&i.LandedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChangesetByOrgAndID = `-- name: GetChangesetByOrgAndID :one
SELECT id, organization_id, superproject_repository_id, change_id, commit_id, parent_change_ids, target_bookmark, description, state, failure_reason, landing_plan, landed_commit_id, created_by, landed_at, created_at, updated_at
FROM changesets
WHERE organization_id = $1
  AND id = $2
`

type GetChangesetByOrgAndIDParams struct {
	OrganizationID int64 `json:"organization_id"`
	ID             int64 `json:"id"`
}

func (q *Queries) GetChangesetByOrgAndID(ctx context.Context, arg GetChangesetByOrgAndIDParams) (Changeset, error) {
	row := q.db.QueryRow(ctx, getChangesetByOrgAndID, arg.OrganizationID, arg.ID)
	var i Changeset
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SuperprojectRepositoryID,
		&i.ChangeID,
		&i.CommitID,
		&i.ParentChangeIds,
		&i.TargetBookmark,
		&i.Description,
		&i.State,
		&i.FailureReason,
		&i.LandingPlan,
		&i.LandedCommitID,
		&i.CreatedBy,
		&i.LandedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLandedChangesetForChange = `-- name: GetLandedChangesetForChange :one
SELECT cs.id, cs.organization_id, cs.superproject_repository_id, cs.change_id, cs.commit_id, cs.parent_change_ids, cs.target_bookmark, cs.description, cs.state, cs.failure_reason, cs.landing_plan, cs.landed_commit_id, cs.created_by, cs.landed_at, cs.created_at, cs.updated_at
FROM changesets AS cs
WHERE cs.state = 'landed'
  AND (
    (cs.superproject_repository_id = $1
      AND cs.change_id = $2)
    OR EXISTS (
      SELECT 1
      FROM changeset_members AS member
      WHERE member.changeset_id = cs.id
        AND member.repository_id = $1
        AND member.change_id = $2
    )
  )
ORDER BY cs.landed_at DESC, cs.id DESC
LIMIT 1
`

type GetLandedChangesetForChangeParams struct {
	RepositoryID int64  `json:"repository_id"`
	ChangeID     string `json:"change_id"`
}

func (q *Queries) GetLandedChangesetForChange(ctx context.Context, arg GetLandedChangesetForChangeParams) (Changeset, error) {
	row := q.db.QueryRow(ctx, getLandedChangesetForChange, arg.RepositoryID, arg.ChangeID)
	var i Changeset
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SuperprojectRepositoryID,
		&i.ChangeID,
		&i.CommitID,
		&i.ParentChangeIds,
		&i.TargetBookmark,
		&i.Description,
		&i.State,
		&i.FailureReason,
		&i.LandingPlan,
		&i.LandedCommitID,
		&i.CreatedBy,
		&i.LandedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChangesetMembers = `-- name: ListChangesetMembers :many
SELECT id, changeset_id, repository_id, path, change_id, commit_id, target_bookmark, previous_commit_id, landed_commit_id, created_at, updated_at
FROM changeset_members
WHERE changeset_id = $1
ORDER BY path ASC
`

func (q *Queries) ListChangesetMembers(ctx context.Context, changesetID int64) ([]ChangesetMember, error) {
	rows, err := q.db.Query(ctx, listChangesetMembers, changesetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangesetMember{}
	for rows.Next() {
		var i ChangesetMember
		if err := rows.Scan(
			&i.ID,
			&i.ChangesetID,
			&i.RepositoryID,
			&i.Path,
			&i.ChangeID,
			&i.CommitID,
			&i.TargetBookmark,
			&i.PreviousCommitID,
			&i.LandedCommitID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangesetsByOrg = `-- name: ListChangesetsByOrg :many
SELECT id, organization_id, superproject_repository_id, change_id, commit_id, parent_change_ids, target_bookmark, description, state, failure_reason, landing_plan, landed_commit_id, created_by, landed_at, created_at, updated_at
FROM changesets
WHERE organization_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListChangesetsByOrgParams struct {
	OrganizationID int64 `json:"organization_id"`
	PageOffset     int32 `json:"page_offset"`
	PageSize       int32 `json:"page_size"`
}

func (q *Queries) ListChangesetsByOrg(ctx context.Context, arg ListChangesetsByOrgParams) ([]Changeset, error) {
	rows, err := q.db.Query(ctx, listChangesetsByOrg, arg.OrganizationID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Changeset{}
	for rows.Next() {
		var i Changeset
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SuperprojectRepositoryID,
			&i.ChangeID,
			&i.CommitID,
			&i.ParentChangeIds,
			&i.TargetBookmark,
			&i.Description,
			&i.State,
			&i.FailureReason,
			&i.LandingPlan,
			&i.LandedCommitID,
			&i.CreatedBy,
			&i.LandedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChangesetFailed = `-- name: MarkChangesetFailed :one
UPDATE changesets
SET state = 'failed', failure_reason = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, superproject_repository_id, change_id, commit_id, parent_change_ids, target_bookmark, description, state, failure_reason, landing_plan, landed_commit_id, created_by, landed_at, created_at, updated_at
`

type MarkChangesetFailedParams struct {
	ID            int64  `json:"id"`
	FailureReason string `json:"failure_reason"`
}

func (q *Queries) MarkChangesetFailed(ctx context.Context, arg MarkChangesetFailedParams) (Changeset, error) {
	row := q.db.QueryRow(ctx, markChangesetFailed, arg.ID, arg.FailureReason)
	var i Changeset
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SuperprojectRepositoryID,
		&i.ChangeID,
		&i.CommitID,
		&i.ParentChangeIds,
		&i.TargetBookmark,
		&i.Description,
		&i.State,
		&i.FailureReason,
		&i.LandingPlan,
		&i.LandedCommitID,
		&i.CreatedBy,
		&i.LandedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markChangesetLanded = `-- name: MarkChangesetLanded :one
UPDATE changesets
SET state = 'landed', failure_reason = '', landed_commit_id = $2, landed_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, superproject_repository_id, change_id, commit_id, parent_change_ids, target_bookmark, description, state, failure_reason, landing_plan, landed_commit_id, created_by, landed_at, created_at, updated_at
`

type MarkChangesetLandedParams struct {
	ID             int64  `json:"id"`
	LandedCommitID string `json:"landed_commit_id"`
}

func (q *Queries) MarkChangesetLanded(ctx context.Context, arg MarkChangesetLandedParams) (Changeset, error) {
	row := q.db.QueryRow(ctx, markChangesetLanded, arg.ID, arg.LandedCommitID)
	var i Changeset
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SuperprojectRepositoryID,
		&i.ChangeID,
		&i.CommitID,
		&i.ParentChangeIds,
		&i.TargetBookmark,
		&i.Description,
		&i.State,
		&i.FailureReason,
		&i.LandingPlan,
		&i.LandedCommitID,
		&i.CreatedBy,
		&i.LandedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markChangesetLanding = `-- name: MarkChangesetLanding :one
UPDATE changesets
SET state = 'landing', failure_reason = '', updated_at = NOW()
WHERE id = $1
  AND state IN ('pending', 'failed')
RETURNING id, organization_id, superproject_repository_id, change_id, commit_id, parent_change_ids, target_bookmark, description, state, failure_reason, landing_plan, landed_commit_id, created_by, landed_at, created_at, updated_at
`

func (q *Queries) MarkChangesetLanding(ctx context.Context, id int64) (Changeset, error) {
	row := q.db.QueryRow(ctx, markChangesetLanding, id)
	var i Changeset
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SuperprojectRepositoryID,
		&i.ChangeID,
		&i.CommitID,
		&i.ParentChangeIds,
		&i.TargetBookmark,
		&i.Description,
		&i.State,
		&i.FailureReason,
		&i.LandingPlan,
		&i.LandedCommitID,
		&i.CreatedBy,
		&i.LandedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordChangesetMemberLanded = `-- name: RecordChangesetMemberLanded :exec
UPDATE changeset_members
SET landed_commit_id = $2, updated_at = NOW()
WHERE id = $1
`

type RecordChangesetMemberLandedParams struct {
	ID             int64  `json:"id"`
	LandedCommitID string `json:"landed_commit_id"`
}

func (q *Queries) RecordChangesetMemberLanded(ctx context.Context, arg RecordChangesetMemberLandedParams) error {
	_, err := q.db.Exec(ctx, recordChangesetMemberLanded, arg.ID, arg.LandedCommitID)
	return err
}

const recordChangesetMemberPreviousCommit = `-- name: RecordChangesetMemberPreviousCommit :exec
UPDATE changeset_members
SET previous_commit_id = $2, updated_at = NOW()
WHERE id = $1
`

type RecordChangesetMemberPreviousCommitParams struct {
	ID               int64  `json:"id"`
	PreviousCommitID string `json:"previous_commit_id"`
}

func (q *Queries) RecordChangesetMemberPreviousCommit(ctx context.Context, arg RecordChangesetMemberPreviousCommitParams) error {
	_, err := q.db.Exec(ctx, recordChangesetMemberPreviousCommit, arg.ID, arg.PreviousCommitID)
	return err
}

const saveChangesetLandingPlan = `-- name: SaveChangesetLandingPlan :one
UPDATE changesets
SET state = $1, landing_plan = $2, failure_reason = $3, updated_at = NOW()
WHERE id = $4
RETURNING id, organization_id, superproject_repository_id, change_id, commit_id, parent_change_ids, target_bookmark, description, state, failure_reason, landing_plan, landed_commit_id, created_by, landed_at, created_at, updated_at
`

type SaveChangesetLandingPlanParams struct {
	State         string          `json:"state"`
	LandingPlan   json.RawMessage `json:"landing_plan"`
	FailureReason string          `json:"failure_reason"`
	ID            int64           `json:"id"`
}

func (q *Queries) SaveChangesetLandingPlan(ctx context.Context, arg SaveChangesetLandingPlanParams) (Changeset, error) {
	row := q.db.QueryRow(ctx, saveChangesetLandingPlan,
		arg.State,
		arg.LandingPlan,
		arg.FailureReason,
		arg.ID,
	)
	var i Changeset
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SuperprojectRepositoryID,
		&i.ChangeID,
		&i.CommitID,
		&i.ParentChangeIds,
		&i.TargetBookmark,
		&i.Description,
		&i.State,
		&i.FailureReason,
		&i.LandingPlan,
		&i.LandedCommitID,
		&i.CreatedBy,
		&i.LandedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
