// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issue_state_facts.sql

package clusterdb

import (
	"context"
)

const getIssueStateJournal = `-- name: GetIssueStateJournal :one
SELECT repository_id, head, coverage_kind, coverage_started_at FROM issue_state_journals WHERE repository_id = $1
`

func (q *Queries) GetIssueStateJournal(ctx context.Context, repositoryID int64) (IssueStateJournal, error) {
	row := q.db.QueryRow(ctx, getIssueStateJournal, repositoryID)
	var i IssueStateJournal
	err := row.Scan(
		&i.RepositoryID,
		&i.Head,
		&i.CoverageKind,
		&i.CoverageStartedAt,
	)
	return i, err
}

const listIssueStateFacts = `-- name: ListIssueStateFacts :many
SELECT repository_id, sequence, event_id, schema_version, entity_type, operation, issue_id, entity_key, post_image, recorded_at FROM issue_state_facts
WHERE repository_id = $1
  AND sequence > $2
  AND sequence <= $3
ORDER BY sequence ASC
LIMIT $4
`

type ListIssueStateFactsParams struct {
	RepositoryID    int64 `json:"repository_id"`
	AfterSequence   int64 `json:"after_sequence"`
	ThroughSequence int64 `json:"through_sequence"`
	PageSize        int32 `json:"page_size"`
}

func (q *Queries) ListIssueStateFacts(ctx context.Context, arg ListIssueStateFactsParams) ([]IssueStateFact, error) {
	rows, err := q.db.Query(ctx, listIssueStateFacts,
		arg.RepositoryID,
		arg.AfterSequence,
		arg.ThroughSequence,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueStateFact{}
	for rows.Next() {
		var i IssueStateFact
		if err := rows.Scan(
			&i.RepositoryID,
			&i.Sequence,
			&i.EventID,
			&i.SchemaVersion,
			&i.EntityType,
			&i.Operation,
			&i.IssueID,
			&i.EntityKey,
			&i.PostImage,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
