// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jj_operations.sql

package clusterdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countJjOperationsByRepo = `-- name: CountJjOperationsByRepo :one
SELECT COUNT(*)
FROM jj_operations
WHERE repository_id = $1
`

func (q *Queries) CountJjOperationsByRepo(ctx context.Context, repositoryID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countJjOperationsByRepo, repositoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLaterJjOperationsInWorkspace = `-- name: CountLaterJjOperationsInWorkspace :one
SELECT COUNT(*)
FROM jj_operations AS later
WHERE later.repository_id = $1
  AND later.workspace_id = $2::uuid
  AND (
      later.created_at > $3
      OR (later.created_at = $3 AND later.id > $4)
  )
`

type CountLaterJjOperationsInWorkspaceParams struct {
	RepositoryID int64     `json:"repository_id"`
	WorkspaceID  string    `json:"workspace_id"`
	CreatedAt    time.Time `json:"created_at"`
	ID           int64     `json:"id"`
}

func (q *Queries) CountLaterJjOperationsInWorkspace(ctx context.Context, arg CountLaterJjOperationsInWorkspaceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLaterJjOperationsInWorkspace,
		arg.RepositoryID,
		arg.WorkspaceID,
		arg.CreatedAt,
		arg.ID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJjOperation = `-- name: CreateJjOperation :one
INSERT INTO jj_operations (
    repository_id,
    operation_id,
    operation_type,
    description,
    user_id,
    parent_operation_id,
    workspace_id,
    change_ids
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    NULLIF($7::text, '')::uuid,
    COALESCE($8::text[], '{}'::text[])
)
RETURNING id, repository_id, operation_id, operation_type, description, user_id, parent_operation_id, workspace_id, change_ids, created_at
`

type CreateJjOperationParams struct {
	RepositoryID      int64    `json:"repository_id"`
	OperationID       string   `json:"operation_id"`
	OperationType     string   `json:"operation_type"`
	Description       string   `json:"description"`
	UserID            int64    `json:"user_id"`
	ParentOperationID string   `json:"parent_operation_id"`
	WorkspaceID       string   `json:"workspace_id"`
	ChangeIds         []string `json:"change_ids"`
}

func (q *Queries) CreateJjOperation(ctx context.Context, arg CreateJjOperationParams) (JjOperation, error) {
	row := q.db.QueryRow(ctx, createJjOperation,
		arg.RepositoryID,
		arg.OperationID,
		arg.OperationType,
		arg.Description,
		arg.UserID,
		arg.ParentOperationID,
		arg.WorkspaceID,
		arg.ChangeIds,
	)
	var i JjOperation
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.OperationID,
		&i.OperationType,
		&i.Description,
		&i.UserID,
		&i.ParentOperationID,
		&i.WorkspaceID,
		&i.ChangeIds,
		&i.CreatedAt,
	)
	return i, err
}

const getJjOperationByOperationID = `-- name: GetJjOperationByOperationID :one
SELECT id, repository_id, operation_id, operation_type, description, user_id, parent_operation_id, workspace_id, change_ids, created_at
FROM jj_operations
WHERE repository_id = $1
  AND operation_id = $2
`

type GetJjOperationByOperationIDParams struct {
	RepositoryID int64  `json:"repository_id"`
	OperationID  string `json:"operation_id"`
}

func (q *Queries) GetJjOperationByOperationID(ctx context.Context, arg GetJjOperationByOperationIDParams) (JjOperation, error) {
	row := q.db.QueryRow(ctx, getJjOperationByOperationID, arg.RepositoryID, arg.OperationID)
	var i JjOperation
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.OperationID,
		&i.OperationType,
		&i.Description,
		&i.UserID,
		&i.ParentOperationID,
		&i.WorkspaceID,
		&i.ChangeIds,
		&i.CreatedAt,
	)
	return i, err
}

const getJjOperationForWorkspace = `-- name: GetJjOperationForWorkspace :one
SELECT id, repository_id, operation_id, operation_type, description, user_id, parent_operation_id, workspace_id, change_ids, created_at
FROM jj_operations
WHERE repository_id = $1
  AND operation_id = $2
  AND workspace_id = NULLIF($3::text, '')::uuid
`

type GetJjOperationForWorkspaceParams struct {
	RepositoryID int64  `json:"repository_id"`
	OperationID  string `json:"operation_id"`
	WorkspaceID  string `json:"workspace_id"`
}

func (q *Queries) GetJjOperationForWorkspace(ctx context.Context, arg GetJjOperationForWorkspaceParams) (JjOperation, error) {
	row := q.db.QueryRow(ctx, getJjOperationForWorkspace, arg.RepositoryID, arg.OperationID, arg.WorkspaceID)
	var i JjOperation
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.OperationID,
		&i.OperationType,
		&i.Description,
		&i.UserID,
		&i.ParentOperationID,
		&i.WorkspaceID,
		&i.ChangeIds,
		&i.CreatedAt,
	)
	return i, err
}

const listJjOperationsByRepo = `-- name: ListJjOperationsByRepo :many
SELECT id, repository_id, operation_id, operation_type, description, user_id, parent_operation_id, workspace_id, change_ids, created_at
FROM jj_operations
WHERE repository_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListJjOperationsByRepoParams struct {
	RepositoryID int64 `json:"repository_id"`
	PageOffset   int32 `json:"page_offset"`
	PageSize     int32 `json:"page_size"`
}

func (q *Queries) ListJjOperationsByRepo(ctx context.Context, arg ListJjOperationsByRepoParams) ([]JjOperation, error) {
	rows, err := q.db.Query(ctx, listJjOperationsByRepo, arg.RepositoryID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JjOperation{}
	for rows.Next() {
		var i JjOperation
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.OperationID,
			&i.OperationType,
			&i.Description,
			&i.UserID,
			&i.ParentOperationID,
			&i.WorkspaceID,
			&i.ChangeIds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJjOperationsForChange = `-- name: ListJjOperationsForChange :many
SELECT operation.id, operation.repository_id, operation.operation_id, operation.operation_type, operation.description, operation.user_id, operation.parent_operation_id, operation.workspace_id, operation.change_ids, operation.created_at
FROM jj_operations AS operation
WHERE operation.repository_id = $1
  AND (
      $2::bigint IS NULL
      AND $3::text = ANY(operation.change_ids)
      OR EXISTS (
          SELECT 1
          FROM change_revisions AS revision
          WHERE revision.repository_id = operation.repository_id
            AND revision.change_id = $3
            AND ($2::bigint IS NULL OR revision.seq = $2::bigint)
            AND operation.operation_id = ANY(revision.operation_ids)
      )
  )
ORDER BY operation.created_at DESC, operation.id DESC
`

type ListJjOperationsForChangeParams struct {
	RepositoryID int64       `json:"repository_id"`
	RevisionSeq  pgtype.Int8 `json:"revision_seq"`
	ChangeID     string      `json:"change_id"`
}

func (q *Queries) ListJjOperationsForChange(ctx context.Context, arg ListJjOperationsForChangeParams) ([]JjOperation, error) {
	rows, err := q.db.Query(ctx, listJjOperationsForChange, arg.RepositoryID, arg.RevisionSeq, arg.ChangeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JjOperation{}
	for rows.Next() {
		var i JjOperation
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.OperationID,
			&i.OperationType,
			&i.Description,
			&i.UserID,
			&i.ParentOperationID,
			&i.WorkspaceID,
			&i.ChangeIds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordWorkspaceCodingOperation = `-- name: RecordWorkspaceCodingOperation :one
INSERT INTO jj_operations (
    repository_id, operation_id, operation_type, description, user_id,
    parent_operation_id, workspace_id, change_ids, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7::uuid,
        $8::text[], $9::timestamptz)
ON CONFLICT (repository_id, operation_id) DO UPDATE
SET operation_id = jj_operations.operation_id
WHERE jj_operations.user_id = EXCLUDED.user_id
  AND jj_operations.workspace_id = EXCLUDED.workspace_id
  AND jj_operations.parent_operation_id = EXCLUDED.parent_operation_id
  AND jj_operations.operation_type = EXCLUDED.operation_type
  AND jj_operations.change_ids = EXCLUDED.change_ids
RETURNING id, repository_id, operation_id, operation_type, description, user_id, parent_operation_id, workspace_id, change_ids, created_at
`

type RecordWorkspaceCodingOperationParams struct {
	RepositoryID      int64     `json:"repository_id"`
	OperationID       string    `json:"operation_id"`
	OperationType     string    `json:"operation_type"`
	Description       string    `json:"description"`
	UserID            int64     `json:"user_id"`
	ParentOperationID string    `json:"parent_operation_id"`
	WorkspaceID       string    `json:"workspace_id"`
	ChangeIds         []string  `json:"change_ids"`
	CreatedAt         time.Time `json:"created_at"`
}

// Projection of a native JJ receipt, not an execution ledger. Identical retry
// is safe; a different actor/workspace/operation may never claim the same ID.
func (q *Queries) RecordWorkspaceCodingOperation(ctx context.Context, arg RecordWorkspaceCodingOperationParams) (JjOperation, error) {
	row := q.db.QueryRow(ctx, recordWorkspaceCodingOperation,
		arg.RepositoryID,
		arg.OperationID,
		arg.OperationType,
		arg.Description,
		arg.UserID,
		arg.ParentOperationID,
		arg.WorkspaceID,
		arg.ChangeIds,
		arg.CreatedAt,
	)
	var i JjOperation
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.OperationID,
		&i.OperationType,
		&i.Description,
		&i.UserID,
		&i.ParentOperationID,
		&i.WorkspaceID,
		&i.ChangeIds,
		&i.CreatedAt,
	)
	return i, err
}
