// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package clusterdb

import (
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"

	"github.com/smithersai/smithers/packages/backend/internal/db"
)

type AccessToken = db.AccessToken

type AgentMessage = db.AgentMessage

type AgentPart = db.AgentPart

type AgentSession = db.AgentSession

type AlertIncident struct {
	ID               int64              `json:"id"`
	IncidentID       string             `json:"incident_id"`
	PolicyName       string             `json:"policy_name"`
	ConditionName    string             `json:"condition_name"`
	State            string             `json:"state"`
	Summary          string             `json:"summary"`
	IncidentUrl      string             `json:"incident_url"`
	Runbook          string             `json:"runbook"`
	Workflow         string             `json:"workflow"`
	RemediationPrUrl string             `json:"remediation_pr_url"`
	Attempts         int32              `json:"attempts"`
	CreatedAt        time.Time          `json:"created_at"`
	ResolvedAt       pgtype.Timestamptz `json:"resolved_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	Source           string             `json:"source"`
	Occurrences      int32              `json:"occurrences"`
	LastSeenAt       time.Time          `json:"last_seen_at"`
	AcknowledgedAt   pgtype.Timestamptz `json:"acknowledged_at"`
	AcknowledgedBy   pgtype.Text        `json:"acknowledged_by"`
	SnoozedUntil     pgtype.Timestamptz `json:"snoozed_until"`
	ResolvedBy       pgtype.Text        `json:"resolved_by"`
	ResolutionNote   pgtype.Text        `json:"resolution_note"`
}

type AlertIncidentDelivery struct {
	IncidentID          string             `json:"incident_id"`
	CanonicalIncidentID int64              `json:"canonical_incident_id"`
	CreatedAt           time.Time          `json:"created_at"`
	ClosedAt            pgtype.Timestamptz `json:"closed_at"`
}

type AlertRemediationJob struct {
	ID            int64              `json:"id"`
	IncidentID    int64              `json:"incident_id"`
	Status        string             `json:"status"`
	Attempts      int32              `json:"attempts"`
	Error         string             `json:"error"`
	AvailableAt   time.Time          `json:"available_at"`
	ProcessedAt   pgtype.Timestamptz `json:"processed_at"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	DispatchToken string             `json:"dispatch_token"`
	WorkflowRunID pgtype.Int8        `json:"workflow_run_id"`
}

type AlphaWaitlistEntry = db.AlphaWaitlistEntry

type AlphaWhitelistEntry = db.AlphaWhitelistEntry

type AnalyzerRun = db.AnalyzerRun

type AnonSandbox = db.AnonSandbox

type AppTimeline = db.AppTimeline

type AppTimelineBranch = db.AppTimelineBranch

type AppTimelineEvent = db.AppTimelineEvent

type AppTimelineMember = db.AppTimelineMember

type AppTimelineSnapshot = db.AppTimelineSnapshot

type Approval = db.Approval

type AuditLog = db.AuditLog

type AuthNonce = db.AuthNonce

type AuthSession = db.AuthSession

type BillingAccount = db.BillingAccount

type BillingCreditBalance = db.BillingCreditBalance

type BillingCreditLedger = db.BillingCreditLedger

type BillingEntitlement = db.BillingEntitlement

type BillingSubscription = db.BillingSubscription

type BillingUsageCounter = db.BillingUsageCounter

type Bookmark = db.Bookmark

type BranchLock = db.BranchLock

type BranchLockJoinRequest = db.BranchLockJoinRequest

type BuildCacheArtifact = db.BuildCacheArtifact

type BuildCacheEntry = db.BuildCacheEntry

type BuildCacheEntryArtifact = db.BuildCacheEntryArtifact

type BuildCacheReadToken = db.BuildCacheReadToken

type CanaryResult struct {
	ID              int64     `json:"id"`
	Suite           string    `json:"suite"`
	TestName        string    `json:"test_name"`
	Status          string    `json:"status"`
	DurationSeconds float64   `json:"duration_seconds"`
	ErrorMessage    string    `json:"error_message"`
	RunID           string    `json:"run_id"`
	ReportedAt      time.Time `json:"reported_at"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type Change = db.Change

type ChangeRevision = db.ChangeRevision

type ChangeWalkthrough = db.ChangeWalkthrough

type Changeset = db.Changeset

type ChangesetMember = db.ChangesetMember

type ChatTurn = db.ChatTurn

type ChatTurnBatch = db.ChatTurnBatch

type ChatTurnErasure = db.ChatTurnErasure

type CodeSearchDocument = db.CodeSearchDocument

type CodeSearchIndexState = db.CodeSearchIndexState

type Collaborator = db.Collaborator

type CommitStatus = db.CommitStatus

type Conflict = db.Conflict

type DeployKey = db.DeployKey

type DevtoolsSnapshot = db.DevtoolsSnapshot

type EmailAddress = db.EmailAddress

type EmailVerificationToken = db.EmailVerificationToken

type FileDraft = db.FileDraft

type Finding = db.Finding

type FindingFeedback = db.FindingFeedback

type FlowRuntimeHostBinding = db.FlowRuntimeHostBinding

type GithubAppInstallation = db.GithubAppInstallation

type GithubAppInstallationRepository = db.GithubAppInstallationRepository

type GithubMirrorSyncRefResult = db.GithubMirrorSyncRefResult

type GithubMirrorSyncRun = db.GithubMirrorSyncRun

type GithubProxyAuditLog struct {
	ID            int64     `json:"id"`
	WorkflowRunID int64     `json:"workflow_run_id"`
	Method        string    `json:"method"`
	Path          string    `json:"path"`
	StatusCode    int32     `json:"status_code"`
	Decision      string    `json:"decision"`
	Reason        string    `json:"reason"`
	CreatedAt     time.Time `json:"created_at"`
}

type GithubRepoListing = db.GithubRepoListing

type GithubSyncedIssue = db.GithubSyncedIssue

type GithubSyncedIssueComment = db.GithubSyncedIssueComment

type GithubSyncedRepo = db.GithubSyncedRepo

type GithubWebhookJob = db.GithubWebhookJob

type IDRemap struct {
	LocalID      string             `json:"local_id"`
	RemoteID     pgtype.Text        `json:"remote_id"`
	ResourceType string             `json:"resource_type"`
	CreatedAt    time.Time          `json:"created_at"`
	RemappedAt   pgtype.Timestamptz `json:"remapped_at"`
}

type ImportJob = db.ImportJob

type Issue = db.Issue

type IssueArtifact = db.IssueArtifact

type IssueAssignee = db.IssueAssignee

type IssueChangeLink = db.IssueChangeLink

type IssueComment = db.IssueComment

type IssueDependency = db.IssueDependency

type IssueEvent = db.IssueEvent

type IssueLabel = db.IssueLabel

type IssueStateFact = db.IssueStateFact

type IssueStateJournal = db.IssueStateJournal

type JjOperation = db.JjOperation

type Label = db.Label

type LandingRequest = db.LandingRequest

type LandingRequestChange = db.LandingRequestChange

type LandingRequestComment = db.LandingRequestComment

type LandingRequestReview = db.LandingRequestReview

type LandingReviewRequest = db.LandingReviewRequest

type LandingTask = db.LandingTask

type LegacyMutationFenceControl struct {
	Singleton                bool      `json:"singleton"`
	EnforceRepositoryStorage bool      `json:"enforce_repository_storage"`
	EnforceReleaseDeletion   bool      `json:"enforce_release_deletion"`
	UpdatedAt                time.Time `json:"updated_at"`
}

type LfsLock = db.LfsLock

type LfsMetaObject = db.LfsMetaObject

type LfsObject = db.LfsObject

type LfsUploadReservation = db.LfsUploadReservation

type LinearCommentMap = db.LinearCommentMap

type LinearIntegration = db.LinearIntegration

type LinearIssueMap = db.LinearIssueMap

type LinearOauthSetup = db.LinearOauthSetup

type LinearSyncOp = db.LinearSyncOp

type LinearSyncRun = db.LinearSyncRun

type LocalCredential = db.LocalCredential

type MemoryCleanupItem struct {
	CleanupTaskID int64              `json:"cleanup_task_id"`
	MemoryID      string             `json:"memory_id"`
	CapturedAt    time.Time          `json:"captured_at"`
	InvalidatedAt pgtype.Timestamptz `json:"invalidated_at"`
}

type MemoryCleanupTask struct {
	ID                  int64              `json:"id"`
	TaskKind            string             `json:"task_kind"`
	TargetID            int64              `json:"target_id"`
	Bookmark            pgtype.Text        `json:"bookmark"`
	SourceRevision      pgtype.Text        `json:"source_revision"`
	DeletionEventAt     time.Time          `json:"deletion_event_at"`
	SnapshotCompletedAt pgtype.Timestamptz `json:"snapshot_completed_at"`
	IdempotencyKey      string             `json:"idempotency_key"`
	Status              string             `json:"status"`
	Attempt             int32              `json:"attempt"`
	LastErrorClass      pgtype.Text        `json:"last_error_class"`
	AvailableAt         time.Time          `json:"available_at"`
	LeaseExpiresAt      pgtype.Timestamptz `json:"lease_expires_at"`
	FinishedAt          pgtype.Timestamptz `json:"finished_at"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
}

type MemoryIngestBatch struct {
	ID                     int64              `json:"id"`
	SessionID              string             `json:"session_id"`
	FromMessageSequence    int64              `json:"from_message_sequence"`
	ThroughMessageSequence int64              `json:"through_message_sequence"`
	DocumentID             string             `json:"document_id"`
	PayloadSha256          string             `json:"payload_sha256"`
	Status                 string             `json:"status"`
	OperationID            pgtype.Text        `json:"operation_id"`
	AcceptedAt             pgtype.Timestamptz `json:"accepted_at"`
	CursorAdvancedAt       pgtype.Timestamptz `json:"cursor_advanced_at"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
}

type MemoryIngestCursor struct {
	SessionID           string      `json:"session_id"`
	DocumentID          string      `json:"document_id"`
	LastMessageSequence int64       `json:"last_message_sequence"`
	LastOperationID     pgtype.Text `json:"last_operation_id"`
	AcceptedAt          time.Time   `json:"accepted_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
}

type MemoryMaintenanceCursor struct {
	MaintenanceKind string    `json:"maintenance_kind"`
	LastBankID      string    `json:"last_bank_id"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type MemoryPromotionItem struct {
	PromotionTaskID int64              `json:"promotion_task_id"`
	MemoryID        string             `json:"memory_id"`
	StreamTags      []string           `json:"stream_tags"`
	CapturedAt      time.Time          `json:"captured_at"`
	InvalidatedAt   pgtype.Timestamptz `json:"invalidated_at"`
}

type MemoryPromotionTask struct {
	ID               int64              `json:"id"`
	LandingRequestID int64              `json:"landing_request_id"`
	RepositoryID     int64              `json:"repository_id"`
	SourceBookmark   string             `json:"source_bookmark"`
	TargetBookmark   string             `json:"target_bookmark"`
	Status           string             `json:"status"`
	Phase            string             `json:"phase"`
	Outcome          pgtype.Text        `json:"outcome"`
	Attempt          int32              `json:"attempt"`
	LastError        pgtype.Text        `json:"last_error"`
	OperationID      pgtype.Text        `json:"operation_id"`
	AvailableAt      time.Time          `json:"available_at"`
	LeaseExpiresAt   pgtype.Timestamptz `json:"lease_expires_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

type MemoryProvisioningTask struct {
	ID             int64              `json:"id"`
	TargetKind     string             `json:"target_kind"`
	TargetID       int64              `json:"target_id"`
	Status         string             `json:"status"`
	Attempt        int32              `json:"attempt"`
	LastError      pgtype.Text        `json:"last_error"`
	AvailableAt    time.Time          `json:"available_at"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

type MemoryRestoreManifest struct {
	RestoreID      string             `json:"restore_id"`
	TargetKind     string             `json:"target_kind"`
	TargetID       int64              `json:"target_id"`
	OperationID    string             `json:"operation_id"`
	SourceManifest json.RawMessage    `json:"source_manifest"`
	VerifiedAt     pgtype.Timestamptz `json:"verified_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

type MemoryWriteFreeze struct {
	ID         int64              `json:"id"`
	TargetKind string             `json:"target_kind"`
	TargetID   pgtype.Int8        `json:"target_id"`
	LeaseToken string             `json:"lease_token"`
	OperatorID string             `json:"operator_id"`
	Reason     string             `json:"reason"`
	AcquiredAt time.Time          `json:"acquired_at"`
	ExpiresAt  time.Time          `json:"expires_at"`
	ReleasedAt pgtype.Timestamptz `json:"released_at"`
}

type Mention = db.Mention

type Milestone = db.Milestone

type Notification = db.Notification

type NotificationFact = db.NotificationFact

type NotificationJournal = db.NotificationJournal

type Oauth2AccessToken = db.Oauth2AccessToken

type Oauth2Application = db.Oauth2Application

type Oauth2AuthorizationCode = db.Oauth2AuthorizationCode

type Oauth2RefreshToken = db.Oauth2RefreshToken

type OauthAccount = db.OauthAccount

type OauthState = db.OauthState

type OnboardingAnswer = db.OnboardingAnswer

type OrgMember = db.OrgMember

type Organization = db.Organization

type OrganizationSecret = db.OrganizationSecret

type OrganizationVariable = db.OrganizationVariable

type OwnerModelCredential = db.OwnerModelCredential

type OwnerModelCredentialReceipt = db.OwnerModelCredentialReceipt

type OwnerModelDefault = db.OwnerModelDefault

type OwnerNamespace = db.OwnerNamespace

type PairPromptQueue = db.PairPromptQueue

type PairSession = db.PairSession

type PairSessionDraft = db.PairSessionDraft

type PairSessionInvite = db.PairSessionInvite

type PairSessionLink = db.PairSessionLink

type PairSessionMember = db.PairSessionMember

type PairShareLink = db.PairShareLink

type PairState = db.PairState

type PinnedIssue = db.PinnedIssue

type PlueStorageRepositoryPlacement struct {
	RepositoryID        int64              `json:"repository_id"`
	ReservationToken    string             `json:"reservation_token"`
	StorageSetID        string             `json:"storage_set_id"`
	State               string             `json:"state"`
	CapacityBytes       int64              `json:"capacity_bytes"`
	PlacementGeneration int64              `json:"placement_generation"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	PublishedAt         pgtype.Timestamptz `json:"published_at"`
	ReleasedAt          pgtype.Timestamptz `json:"released_at"`
	ReleaseToken        pgtype.Text        `json:"release_token"`
}

type PlueStorageStorageNode struct {
	ID                   string             `json:"id"`
	StorageSetID         string             `json:"storage_set_id"`
	BaseUrl              string             `json:"base_url"`
	Zone                 string             `json:"zone"`
	ActivationGeneration int64              `json:"activation_generation"`
	State                string             `json:"state"`
	LastSeenAt           pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
}

type PlueStorageStorageSet struct {
	ID                string      `json:"id"`
	State             string      `json:"state"`
	RoutingGeneration int64       `json:"routing_generation"`
	ActiveNodeID      pgtype.Text `json:"active_node_id"`
	CapacityBytes     int64       `json:"capacity_bytes"`
	ReservedBytes     int64       `json:"reserved_bytes"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
}

type ProductJobDispatch = db.ProductJobDispatch

type ProductJobEvent = db.ProductJobEvent

type ProductJobRequest = db.ProductJobRequest

type ProductJobStream = db.ProductJobStream

type ProtectedBookmark = db.ProtectedBookmark

type ProviderConnection = db.ProviderConnection

type ProviderConnectionGrant = db.ProviderConnectionGrant

type Reaction = db.Reaction

type Release = db.Release

type ReleaseAsset = db.ReleaseAsset

type ReleaseDeletionIntent = db.ReleaseDeletionIntent

type ReleaseDeletionTagTombstone = db.ReleaseDeletionTagTombstone

type RepoConnection = db.RepoConnection

type RepoGateway struct {
	ID                  string             `json:"id"`
	RepositoryID        int64              `json:"repository_id"`
	UserID              int64              `json:"user_id"`
	WorkspaceID         pgtype.UUID        `json:"workspace_id"`
	VmID                string             `json:"vm_id"`
	BaseUrl             string             `json:"base_url"`
	AuthTokenHash       string             `json:"auth_token_hash"`
	AuthTokenCiphertext string             `json:"auth_token_ciphertext"`
	LandingTokenID      pgtype.Int8        `json:"landing_token_id"`
	Status              string             `json:"status"`
	LastActivityAt      time.Time          `json:"last_activity_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
}

type RepoReplica struct {
	RepositoryID   int64              `json:"repository_id"`
	NodeID         string             `json:"node_id"`
	Generation     int64              `json:"generation"`
	StateHash      string             `json:"state_hash"`
	State          string             `json:"state"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

type RepoReplicationJob struct {
	ID           int64       `json:"id"`
	RepositoryID int64       `json:"repository_id"`
	SourceNodeID pgtype.Text `json:"source_node_id"`
	TargetNodeID string      `json:"target_node_id"`
	Generation   int64       `json:"generation"`
	State        string      `json:"state"`
	Attempts     int32       `json:"attempts"`
	Error        string      `json:"error"`
	RunAfter     time.Time   `json:"run_after"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type RepoStorageNode struct {
	ID           string             `json:"id"`
	StorageSetID string             `json:"storage_set_id"`
	Url          string             `json:"url"`
	Zone         string             `json:"zone"`
	State        string             `json:"state"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type RepoStorageSet struct {
	ID              string    `json:"id"`
	DesiredReplicas int32     `json:"desired_replicas"`
	WriteQuorum     int32     `json:"write_quorum"`
	State           string    `json:"state"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type RepoWriteLock struct {
	RepositoryID int64     `json:"repository_id"`
	Generation   int64     `json:"generation"`
	LockedBy     string    `json:"locked_by"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Repository = db.Repository

type RepositoryAgentEnvironment = db.RepositoryAgentEnvironment

type RepositoryAgentEnvironmentSecret = db.RepositoryAgentEnvironmentSecret

type RepositoryCiCheckReceipt = db.RepositoryCiCheckReceipt

type RepositoryCreationJob = db.RepositoryCreationJob

type RepositoryJobApproval = db.RepositoryJobApproval

type RepositoryJobComment = db.RepositoryJobComment

type RepositoryJobDispatch = db.RepositoryJobDispatch

type RepositoryJobEvent = db.RepositoryJobEvent

type RepositoryJobRegistration = db.RepositoryJobRegistration

type RepositoryJobTrial = db.RepositoryJobTrial

type RepositoryProvisioningControl struct {
	Singleton          bool      `json:"singleton"`
	EnforceInsertFence bool      `json:"enforce_insert_fence"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type RepositoryProvisioningOperation struct {
	RepositoryID       int64              `json:"repository_id"`
	OperationType      string             `json:"operation_type"`
	Token              string             `json:"token"`
	ActorID            int64              `json:"actor_id"`
	StorageSetID       string             `json:"storage_set_id"`
	OwnerName          string             `json:"owner_name"`
	UserID             pgtype.Int8        `json:"user_id"`
	OrgID              pgtype.Int8        `json:"org_id"`
	Name               string             `json:"name"`
	LowerName          string             `json:"lower_name"`
	Description        string             `json:"description"`
	IsPublic           bool               `json:"is_public"`
	DefaultBookmark    string             `json:"default_bookmark"`
	AutoInit           bool               `json:"auto_init"`
	IsFork             bool               `json:"is_fork"`
	ForkID             pgtype.Int8        `json:"fork_id"`
	SourceRepositoryID pgtype.Int8        `json:"source_repository_id"`
	SourceOwner        pgtype.Text        `json:"source_owner"`
	SourceRepo         pgtype.Text        `json:"source_repo"`
	SourceStorageSetID pgtype.Text        `json:"source_storage_set_id"`
	PublishReady       bool               `json:"publish_ready"`
	ClaimToken         pgtype.Text        `json:"claim_token"`
	ClaimedAt          pgtype.Timestamptz `json:"claimed_at"`
	Attempts           int32              `json:"attempts"`
	LastError          pgtype.Text        `json:"last_error"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

type RepositorySecret = db.RepositorySecret

type RepositoryStorageOperation = db.RepositoryStorageOperation

type RepositoryVariable = db.RepositoryVariable

type RevocationEvent = db.RevocationEvent

type RunnerPool struct {
	ID              int64              `json:"id"`
	Name            string             `json:"name"`
	Status          string             `json:"status"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	Metadata        json.RawMessage    `json:"metadata"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type SandboxAccessGrant struct {
	ID         string             `json:"id"`
	IdentityID string             `json:"identity_id"`
	TokenHash  []byte             `json:"token_hash"`
	Protocol   string             `json:"protocol"`
	ExpiresAt  time.Time          `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

type SandboxAccessIdentity struct {
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

type SandboxAccessPermission struct {
	ID                  string    `json:"id"`
	IdentityID          string    `json:"identity_id"`
	SandboxID           string    `json:"sandbox_id"`
	AllowedUsers        []string  `json:"allowed_users"`
	PlacementGeneration int64     `json:"placement_generation"`
	CreatedAt           time.Time `json:"created_at"`
}

type SandboxAccessToken struct {
	ID          string             `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	VmID        string             `json:"vm_id"`
	UserID      int64              `json:"user_id"`
	LinuxUser   string             `json:"linux_user"`
	TokenHash   []byte             `json:"token_hash"`
	TokenType   string             `json:"token_type"`
	ExpiresAt   time.Time          `json:"expires_at"`
	UsedAt      pgtype.Timestamptz `json:"used_at"`
	CreatedAt   time.Time          `json:"created_at"`
}

type SandboxDomainMapping struct {
	Domain              string    `json:"domain"`
	SandboxID           string    `json:"sandbox_id"`
	GuestPort           int32     `json:"guest_port"`
	PlacementGeneration int64     `json:"placement_generation"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

type SandboxEgressAudit struct {
	ID                 int64           `json:"id"`
	SandboxID          string          `json:"sandbox_id"`
	ResourceKind       string          `json:"resource_kind"`
	ResourceID         string          `json:"resource_id"`
	RepositoryID       pgtype.Int8     `json:"repository_id"`
	OccurredAt         time.Time       `json:"occurred_at"`
	Host               string          `json:"host"`
	Method             string          `json:"method"`
	Path               string          `json:"path"`
	Status             int32           `json:"status"`
	Allowed            bool            `json:"allowed"`
	SwappedSecretNames []string        `json:"swapped_secret_names"`
	TransformSummary   json.RawMessage `json:"transform_summary"`
	CreatedAt          time.Time       `json:"created_at"`
}

type SandboxEnvironmentImage struct {
	ID             string      `json:"id"`
	RepositoryID   pgtype.Int8 `json:"repository_id"`
	Kind           string      `json:"kind"`
	Source         string      `json:"source"`
	SourceRevision string      `json:"source_revision"`
	ClosureHash    string      `json:"closure_hash"`
	Image          string      `json:"image"`
	Status         string      `json:"status"`
	CreatedBy      pgtype.Int8 `json:"created_by"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type SandboxGoldenSnapshot struct {
	ID         string    `json:"id"`
	Kind       string    `json:"kind"`
	SnapshotID string    `json:"snapshot_id"`
	Status     string    `json:"status"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type SandboxHost struct {
	ID                           string          `json:"id"`
	Provider                     string          `json:"provider"`
	IdentityPublicKey            []byte          `json:"identity_public_key"`
	IdentitySignedAt             time.Time       `json:"identity_signed_at"`
	BaseUrl                      string          `json:"base_url"`
	BootID                       string          `json:"boot_id"`
	State                        string          `json:"state"`
	PlacementGeneration          int64           `json:"placement_generation"`
	CapacityCpuMillis            int64           `json:"capacity_cpu_millis"`
	CapacityMemoryBytes          int64           `json:"capacity_memory_bytes"`
	CapacityDiskBytes            int64           `json:"capacity_disk_bytes"`
	CapacityVms                  int32           `json:"capacity_vms"`
	AllocatedCpuMillis           int64           `json:"allocated_cpu_millis"`
	AllocatedMemoryBytes         int64           `json:"allocated_memory_bytes"`
	AllocatedDiskBytes           int64           `json:"allocated_disk_bytes"`
	AllocatedVms                 int32           `json:"allocated_vms"`
	ObservedAllocatedCpuMillis   int64           `json:"observed_allocated_cpu_millis"`
	ObservedAllocatedMemoryBytes int64           `json:"observed_allocated_memory_bytes"`
	ObservedAllocatedDiskBytes   int64           `json:"observed_allocated_disk_bytes"`
	ObservedAllocatedVms         int32           `json:"observed_allocated_vms"`
	Capabilities                 json.RawMessage `json:"capabilities"`
	RuntimeVersion               string          `json:"runtime_version"`
	WorkerImage                  string          `json:"worker_image"`
	HeartbeatAt                  time.Time       `json:"heartbeat_at"`
	LeaseExpiresAt               time.Time       `json:"lease_expires_at"`
	CreatedAt                    time.Time       `json:"created_at"`
	UpdatedAt                    time.Time       `json:"updated_at"`
}

type SandboxInstance struct {
	ID                   string             `json:"id"`
	Provider             string             `json:"provider"`
	ProviderLocalID      string             `json:"provider_local_id"`
	WorkerID             pgtype.Text        `json:"worker_id"`
	PlacementGeneration  int64              `json:"placement_generation"`
	DesiredState         string             `json:"desired_state"`
	ObservedState        string             `json:"observed_state"`
	ResourceKind         pgtype.Text        `json:"resource_kind"`
	ResourceID           pgtype.Text        `json:"resource_id"`
	ImageRef             string             `json:"image_ref"`
	SnapshotID           pgtype.Text        `json:"snapshot_id"`
	RecoverySnapshotID   pgtype.Text        `json:"recovery_snapshot_id"`
	RecoveryPointAt      pgtype.Timestamptz `json:"recovery_point_at"`
	RequestSpec          json.RawMessage    `json:"request_spec"`
	RecoveryServices     json.RawMessage    `json:"recovery_services"`
	RequestedCpuMillis   int64              `json:"requested_cpu_millis"`
	RequestedMemoryBytes int64              `json:"requested_memory_bytes"`
	RequestedDiskBytes   int64              `json:"requested_disk_bytes"`
	LeaseOwner           pgtype.Text        `json:"lease_owner"`
	LeaseExpiresAt       pgtype.Timestamptz `json:"lease_expires_at"`
	LastHeartbeatAt      pgtype.Timestamptz `json:"last_heartbeat_at"`
	ComputeObservedAt    pgtype.Timestamptz `json:"compute_observed_at"`
	CleanupPending       bool               `json:"cleanup_pending"`
	ReservationHeld      bool               `json:"reservation_held"`
	RecoveryReason       string             `json:"recovery_reason"`
	LastError            string             `json:"last_error"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

type SandboxOperation struct {
	IdempotencyKey string      `json:"idempotency_key"`
	SandboxID      pgtype.Text `json:"sandbox_id"`
	Operation      string      `json:"operation"`
	Status         string      `json:"status"`
	RequestDigest  string      `json:"request_digest"`
	Response       []byte      `json:"response"`
	ErrorCode      string      `json:"error_code"`
	LeaseExpiresAt time.Time   `json:"lease_expires_at"`
	ExpiresAt      time.Time   `json:"expires_at"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type SandboxOrphan struct {
	WorkerID            string    `json:"worker_id"`
	ProviderLocalID     string    `json:"provider_local_id"`
	PlacementGeneration int64     `json:"placement_generation"`
	FirstSeenAt         time.Time `json:"first_seen_at"`
	LastSeenAt          time.Time `json:"last_seen_at"`
	DeleteAfter         time.Time `json:"delete_after"`
}

type SandboxSnapshot struct {
	ID                    string             `json:"id"`
	Provider              string             `json:"provider"`
	ProviderLocalID       string             `json:"provider_local_id"`
	SourceSandboxID       pgtype.Text        `json:"source_sandbox_id"`
	WorkerID              pgtype.Text        `json:"worker_id"`
	PlacementGeneration   int64              `json:"placement_generation"`
	State                 string             `json:"state"`
	Scope                 string             `json:"scope"`
	ObjectUri             pgtype.Text        `json:"object_uri"`
	Digest                pgtype.Text        `json:"digest"`
	SizeBytes             pgtype.Int8        `json:"size_bytes"`
	CleanupOwner          pgtype.Text        `json:"cleanup_owner"`
	CleanupLeaseExpiresAt pgtype.Timestamptz `json:"cleanup_lease_expires_at"`
	GarbageCollectible    bool               `json:"garbage_collectible"`
	LastError             string             `json:"last_error"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
}

type SandboxUsageInterval = db.SandboxUsageInterval

type SandboxVolume struct {
	ID                  string             `json:"id"`
	Provider            string             `json:"provider"`
	ProviderLocalID     string             `json:"provider_local_id"`
	WorkerID            pgtype.Text        `json:"worker_id"`
	PlacementGeneration int64              `json:"placement_generation"`
	State               string             `json:"state"`
	QuotaBytes          pgtype.Int8        `json:"quota_bytes"`
	ObjectUri           pgtype.Text        `json:"object_uri"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
}

type SearchRateLimit = db.SearchRateLimit

type SelfHostOwner = db.SelfHostOwner

type ShareListing = db.ShareListing

type ShareListingEventCooldown = db.ShareListingEventCooldown

type SseTicket = db.SseTicket

type SshKey = db.SshKey

type Stack = db.Stack

type StackChange = db.StackChange

type Star = db.Star

type StorageDeletionQueue struct {
	ID                   int64              `json:"id"`
	RepositoryID         int64              `json:"repository_id"`
	OwnerType            string             `json:"owner_type"`
	OwnerID              int64              `json:"owner_id"`
	AllocationKey        string             `json:"allocation_key"`
	ObjectKey            string             `json:"object_key"`
	SizeBytes            int64              `json:"size_bytes"`
	DeleteAfter          time.Time          `json:"delete_after"`
	RequestedDeleteAfter pgtype.Timestamptz `json:"requested_delete_after"`
	ClaimToken           pgtype.Text        `json:"claim_token"`
	ClaimedAt            pgtype.Timestamptz `json:"claimed_at"`
	Attempts             int32              `json:"attempts"`
	LastError            pgtype.Text        `json:"last_error"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
}

type StorageLegacyCapabilityHorizon struct {
	CapabilityKind string             `json:"capability_kind"`
	ValidUntil     pgtype.Timestamptz `json:"valid_until"`
	AttestedAt     pgtype.Timestamptz `json:"attested_at"`
	AttestedBy     pgtype.Text        `json:"attested_by"`
	Attestation    pgtype.Text        `json:"attestation"`
}

type StripeProcessedEvent = db.StripeProcessedEvent

type SyncQueue struct {
	ID           string             `json:"id"`
	Method       string             `json:"method"`
	Path         string             `json:"path"`
	Body         []byte             `json:"body"`
	LocalID      pgtype.Text        `json:"local_id"`
	RemoteID     pgtype.Text        `json:"remote_id"`
	Status       string             `json:"status"`
	ErrorMessage string             `json:"error_message"`
	CreatedAt    time.Time          `json:"created_at"`
	SyncedAt     pgtype.Timestamptz `json:"synced_at"`
}

type Team = db.Team

type TeamMember = db.TeamMember

type TeamRepo = db.TeamRepo

type User = db.User

type UserAiKey = db.UserAiKey

type UserDevice = db.UserDevice

type UserNotificationPreference = db.UserNotificationPreference

type Watch = db.Watch

type Webhook = db.Webhook

type WebhookDelivery = db.WebhookDelivery

type WikiPage = db.WikiPage

type WikiPageRevision = db.WikiPageRevision

type WorkflowArtifact = db.WorkflowArtifact

type WorkflowCach = db.WorkflowCach

type WorkflowDefinition = db.WorkflowDefinition

type WorkflowInvocation = db.WorkflowInvocation

type WorkflowLog = db.WorkflowLog

type WorkflowLogBudgetInitialization = db.WorkflowLogBudgetInitialization

type WorkflowRun = db.WorkflowRun

type WorkflowRunCodingHost = db.WorkflowRunCodingHost

type WorkflowRunCodingReconciliation struct {
	WorkflowRunID        int64              `json:"workflow_run_id"`
	SessionID            string             `json:"session_id"`
	WorkspaceID          string             `json:"workspace_id"`
	RunRequest           []byte             `json:"run_request"`
	AttemptedAt          pgtype.Timestamptz `json:"attempted_at"`
	LeaseOwner           string             `json:"lease_owner"`
	LeaseExpiresAt       pgtype.Timestamptz `json:"lease_expires_at"`
	NextAttemptAt        time.Time          `json:"next_attempt_at"`
	CancelAcknowledgedAt pgtype.Timestamptz `json:"cancel_acknowledged_at"`
	ReconciledAt         pgtype.Timestamptz `json:"reconciled_at"`
}

type WorkflowRunLog = db.WorkflowRunLog

type WorkflowSandboxClaim struct {
	WorkflowRunID  int64              `json:"workflow_run_id"`
	Generation     int64              `json:"generation"`
	ClaimToken     pgtype.UUID        `json:"claim_token"`
	ClaimedAt      pgtype.Timestamptz `json:"claimed_at"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
}

type WorkflowScheduleSpec = db.WorkflowScheduleSpec

type WorkflowStep = db.WorkflowStep

type WorkflowTask = db.WorkflowTask

type WorkflowTrigger = db.WorkflowTrigger

type Workspace = db.Workspace

type WorkspaceCapabilityBinding = db.WorkspaceCapabilityBinding

type WorkspaceSession = db.WorkspaceSession

type WorkspaceSetupJob = db.WorkspaceSetupJob

type WorkspaceShare = db.WorkspaceShare

type WorkspaceSnapshot = db.WorkspaceSnapshot
