// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pair.sql

package clusterdb

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPairShareLink = `-- name: CreatePairShareLink :one
INSERT INTO pair_share_links (token_hash, room_id, level, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, token_hash, room_id, level, created_by, expires_at, revoked_at, created_at
`

type CreatePairShareLinkParams struct {
	TokenHash string             `json:"token_hash"`
	RoomID    string             `json:"room_id"`
	Level     string             `json:"level"`
	CreatedBy int64              `json:"created_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePairShareLink(ctx context.Context, arg CreatePairShareLinkParams) (PairShareLink, error) {
	row := q.db.QueryRow(ctx, createPairShareLink,
		arg.TokenHash,
		arg.RoomID,
		arg.Level,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i PairShareLink
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.RoomID,
		&i.Level,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPairShareLinkByTokenHash = `-- name: GetPairShareLinkByTokenHash :one
SELECT id, token_hash, room_id, level, created_by, expires_at, revoked_at, created_at FROM pair_share_links
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) GetPairShareLinkByTokenHash(ctx context.Context, tokenHash string) (PairShareLink, error) {
	row := q.db.QueryRow(ctx, getPairShareLinkByTokenHash, tokenHash)
	var i PairShareLink
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.RoomID,
		&i.Level,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPairState = `-- name: GetPairState :one
SELECT state, version FROM pair_state WHERE room_id = $1
`

type GetPairStateRow struct {
	State   json.RawMessage `json:"state"`
	Version int64           `json:"version"`
}

func (q *Queries) GetPairState(ctx context.Context, roomID string) (GetPairStateRow, error) {
	row := q.db.QueryRow(ctx, getPairState, roomID)
	var i GetPairStateRow
	err := row.Scan(&i.State, &i.Version)
	return i, err
}

const getPairStateForUpdate = `-- name: GetPairStateForUpdate :one
SELECT state, version FROM pair_state WHERE room_id = $1 FOR UPDATE
`

type GetPairStateForUpdateRow struct {
	State   json.RawMessage `json:"state"`
	Version int64           `json:"version"`
}

func (q *Queries) GetPairStateForUpdate(ctx context.Context, roomID string) (GetPairStateForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getPairStateForUpdate, roomID)
	var i GetPairStateForUpdateRow
	err := row.Scan(&i.State, &i.Version)
	return i, err
}

const listPairShareLinksByRoom = `-- name: ListPairShareLinksByRoom :many
SELECT id, token_hash, room_id, level, created_by, expires_at, revoked_at, created_at FROM pair_share_links
WHERE room_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListPairShareLinksByRoom(ctx context.Context, roomID string) ([]PairShareLink, error) {
	rows, err := q.db.Query(ctx, listPairShareLinksByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PairShareLink{}
	for rows.Next() {
		var i PairShareLink
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.RoomID,
			&i.Level,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifyPairRoom = `-- name: NotifyPairRoom :exec
SELECT pg_notify('pair_room_' || $1::text, $2::text)
`

type NotifyPairRoomParams struct {
	RoomID  string `json:"room_id"`
	Payload string `json:"payload"`
}

func (q *Queries) NotifyPairRoom(ctx context.Context, arg NotifyPairRoomParams) error {
	_, err := q.db.Exec(ctx, notifyPairRoom, arg.RoomID, arg.Payload)
	return err
}

const revokePairShareLink = `-- name: RevokePairShareLink :execrows
UPDATE pair_share_links
SET revoked_at = NOW()
WHERE id = $1
  AND created_by = $2
  AND revoked_at IS NULL
`

type RevokePairShareLinkParams struct {
	ID        int64 `json:"id"`
	CreatedBy int64 `json:"created_by"`
}

func (q *Queries) RevokePairShareLink(ctx context.Context, arg RevokePairShareLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokePairShareLink, arg.ID, arg.CreatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPairState = `-- name: UpsertPairState :exec
INSERT INTO pair_state (room_id, state, version, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (room_id) DO UPDATE
    SET state = EXCLUDED.state,
        version = EXCLUDED.version,
        updated_at = NOW()
`

type UpsertPairStateParams struct {
	RoomID  string          `json:"room_id"`
	State   json.RawMessage `json:"state"`
	Version int64           `json:"version"`
}

func (q *Queries) UpsertPairState(ctx context.Context, arg UpsertPairStateParams) error {
	_, err := q.db.Exec(ctx, upsertPairState, arg.RoomID, arg.State, arg.Version)
	return err
}
