// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repo_gateways.sql

package clusterdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDiscardedWorkspaceGatewayCredential = `-- name: ClearDiscardedWorkspaceGatewayCredential :exec
UPDATE repo_gateways
SET auth_token_hash = '', auth_token_ciphertext = '', landing_token_id = NULL, updated_at = NOW()
WHERE id = $1 AND workspace_id IS NOT NULL AND deleted_at IS NOT NULL
`

// Only after the named service is verified stopped and ingress revoked. The
// landing token row is deleted separately; this only drops the reference.
func (q *Queries) ClearDiscardedWorkspaceGatewayCredential(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, clearDiscardedWorkspaceGatewayCredential, id)
	return err
}

const createRepoGateway = `-- name: CreateRepoGateway :one

INSERT INTO repo_gateways (
    repository_id,
    user_id,
    workspace_id,
    status
)
VALUES ($1, $2, $3::uuid, $4::text)
RETURNING id, repository_id, user_id, workspace_id, vm_id, base_url, auth_token_hash, auth_token_ciphertext, landing_token_id, status, last_activity_at, deleted_at, created_at, updated_at
`

type CreateRepoGatewayParams struct {
	RepositoryID int64       `json:"repository_id"`
	UserID       int64       `json:"user_id"`
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	Status       string      `json:"status"`
}

// Private cluster queries kept separate from the product graph.
func (q *Queries) CreateRepoGateway(ctx context.Context, arg CreateRepoGatewayParams) (RepoGateway, error) {
	row := q.db.QueryRow(ctx, createRepoGateway,
		arg.RepositoryID,
		arg.UserID,
		arg.WorkspaceID,
		arg.Status,
	)
	var i RepoGateway
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.UserID,
		&i.WorkspaceID,
		&i.VmID,
		&i.BaseUrl,
		&i.AuthTokenHash,
		&i.AuthTokenCiphertext,
		&i.LandingTokenID,
		&i.Status,
		&i.LastActivityAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveRepoGatewayForUserRepo = `-- name: GetActiveRepoGatewayForUserRepo :one
SELECT id, repository_id, user_id, workspace_id, vm_id, base_url, auth_token_hash, auth_token_ciphertext, landing_token_id, status, last_activity_at, deleted_at, created_at, updated_at
FROM repo_gateways
WHERE repository_id = $1
  AND user_id = $2
  AND workspace_id IS NOT DISTINCT FROM $3::uuid
  AND deleted_at IS NULL
  AND (
    status IN ('running', 'suspended')
    OR (status = 'starting' AND vm_id <> '')
  )
LIMIT 1
`

type GetActiveRepoGatewayForUserRepoParams struct {
	RepositoryID int64       `json:"repository_id"`
	UserID       int64       `json:"user_id"`
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
}

// Returns the reusable gateway row for a user+repo pair. Mirrors
// GetActiveWorkspaceForUserRepo: starting rows only count once a VM exists,
// so a crashed provision does not permanently shadow the slot.
func (q *Queries) GetActiveRepoGatewayForUserRepo(ctx context.Context, arg GetActiveRepoGatewayForUserRepoParams) (RepoGateway, error) {
	row := q.db.QueryRow(ctx, getActiveRepoGatewayForUserRepo, arg.RepositoryID, arg.UserID, arg.WorkspaceID)
	var i RepoGateway
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.UserID,
		&i.WorkspaceID,
		&i.VmID,
		&i.BaseUrl,
		&i.AuthTokenHash,
		&i.AuthTokenCiphertext,
		&i.LandingTokenID,
		&i.Status,
		&i.LastActivityAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDiscardedWorkspaceGateways = `-- name: ListDiscardedWorkspaceGateways :many
SELECT id, repository_id, user_id, workspace_id, vm_id, base_url, auth_token_hash, auth_token_ciphertext, landing_token_id, status, last_activity_at, deleted_at, created_at, updated_at FROM repo_gateways
WHERE workspace_id = $1::uuid
  AND vm_id = $2::text
  AND deleted_at IS NOT NULL
ORDER BY created_at, id
`

type ListDiscardedWorkspaceGatewaysParams struct {
	WorkspaceID string `json:"workspace_id"`
	VmID        string `json:"vm_id"`
}

// Row-scoped cleanup survives a failed stop while the owning VM was asleep.
func (q *Queries) ListDiscardedWorkspaceGateways(ctx context.Context, arg ListDiscardedWorkspaceGatewaysParams) ([]RepoGateway, error) {
	rows, err := q.db.Query(ctx, listDiscardedWorkspaceGateways, arg.WorkspaceID, arg.VmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RepoGateway{}
	for rows.Next() {
		var i RepoGateway
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.UserID,
			&i.WorkspaceID,
			&i.VmID,
			&i.BaseUrl,
			&i.AuthTokenHash,
			&i.AuthTokenCiphertext,
			&i.LandingTokenID,
			&i.Status,
			&i.LastActivityAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingWorkspaceGatewayCleanup = `-- name: ListPendingWorkspaceGatewayCleanup :many
SELECT id, repository_id, user_id, workspace_id, vm_id, base_url, auth_token_hash, auth_token_ciphertext, landing_token_id, status, last_activity_at, deleted_at, created_at, updated_at FROM repo_gateways
WHERE workspace_id IS NOT NULL AND deleted_at IS NOT NULL
  AND auth_token_hash <> ''
ORDER BY updated_at, id
LIMIT 20
`

func (q *Queries) ListPendingWorkspaceGatewayCleanup(ctx context.Context) ([]RepoGateway, error) {
	rows, err := q.db.Query(ctx, listPendingWorkspaceGatewayCleanup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RepoGateway{}
	for rows.Next() {
		var i RepoGateway
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.UserID,
			&i.WorkspaceID,
			&i.VmID,
			&i.BaseUrl,
			&i.AuthTokenHash,
			&i.AuthTokenCiphertext,
			&i.LandingTokenID,
			&i.Status,
			&i.LastActivityAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleRepoGateways = `-- name: ListStaleRepoGateways :many
SELECT id, repository_id, user_id, workspace_id, vm_id, base_url, auth_token_hash, auth_token_ciphertext, landing_token_id, status, last_activity_at, deleted_at, created_at, updated_at
FROM repo_gateways
WHERE deleted_at IS NULL
  AND status IN ('pending', 'starting', 'failed')
  AND updated_at < NOW() - make_interval(secs => $1::bigint)
`

// Reaper input: non-terminal gateway rows whose provision is presumed crashed
// (older than the caller-supplied age in seconds, $1). 'starting' rows carry a
// live VM + domain mapping to tear down; 'pending' rows crashed before the VM
// existed; 'failed' rows had their VM torn down on the provision path but still
// need soft-deleting. The age must exceed the worst-case provision wall-clock so
// an in-flight provision is never reclaimed.
func (q *Queries) ListStaleRepoGateways(ctx context.Context, ageSeconds int64) ([]RepoGateway, error) {
	rows, err := q.db.Query(ctx, listStaleRepoGateways, ageSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RepoGateway{}
	for rows.Next() {
		var i RepoGateway
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.UserID,
			&i.WorkspaceID,
			&i.VmID,
			&i.BaseUrl,
			&i.AuthTokenHash,
			&i.AuthTokenCiphertext,
			&i.LandingTokenID,
			&i.Status,
			&i.LastActivityAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRepoGatewayLandingTokenID = `-- name: SetRepoGatewayLandingTokenID :exec
UPDATE repo_gateways
SET landing_token_id = $2::bigint,
    updated_at = NOW()
WHERE id = $1
`

type SetRepoGatewayLandingTokenIDParams struct {
	ID             string      `json:"id"`
	LandingTokenID pgtype.Int8 `json:"landing_token_id"`
}

// Records (or clears, with a NULL argument) the repository-scoped landing
// credential a workspace gateway owns, so teardown revokes exactly that token.
func (q *Queries) SetRepoGatewayLandingTokenID(ctx context.Context, arg SetRepoGatewayLandingTokenIDParams) error {
	_, err := q.db.Exec(ctx, setRepoGatewayLandingTokenID, arg.ID, arg.LandingTokenID)
	return err
}

const softDeleteRepoGateway = `-- name: SoftDeleteRepoGateway :one
UPDATE repo_gateways
SET deleted_at = NOW(),
    status = 'stopped',
    updated_at = NOW()
WHERE id = $1
RETURNING id, repository_id, user_id, workspace_id, vm_id, base_url, auth_token_hash, auth_token_ciphertext, landing_token_id, status, last_activity_at, deleted_at, created_at, updated_at
`

func (q *Queries) SoftDeleteRepoGateway(ctx context.Context, id string) (RepoGateway, error) {
	row := q.db.QueryRow(ctx, softDeleteRepoGateway, id)
	var i RepoGateway
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.UserID,
		&i.WorkspaceID,
		&i.VmID,
		&i.BaseUrl,
		&i.AuthTokenHash,
		&i.AuthTokenCiphertext,
		&i.LandingTokenID,
		&i.Status,
		&i.LastActivityAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchDiscardedWorkspaceGatewayCleanup = `-- name: TouchDiscardedWorkspaceGatewayCleanup :exec
UPDATE repo_gateways SET updated_at = NOW()
WHERE id = $1 AND workspace_id IS NOT NULL AND deleted_at IS NOT NULL
`

// Rotate failed attempts so sleeping VMs cannot starve later cleanup rows.
func (q *Queries) TouchDiscardedWorkspaceGatewayCleanup(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchDiscardedWorkspaceGatewayCleanup, id)
	return err
}

const touchRepoGatewayActivity = `-- name: TouchRepoGatewayActivity :exec
UPDATE repo_gateways
SET last_activity_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchRepoGatewayActivity(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchRepoGatewayActivity, id)
	return err
}

const updateRepoGatewayExecutionInfo = `-- name: UpdateRepoGatewayExecutionInfo :one
UPDATE repo_gateways
SET vm_id = $2::text,
    base_url = $3::text,
    auth_token_hash = $4::text,
    auth_token_ciphertext = $5::text,
    status = $6::text,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, repository_id, user_id, workspace_id, vm_id, base_url, auth_token_hash, auth_token_ciphertext, landing_token_id, status, last_activity_at, deleted_at, created_at, updated_at
`

type UpdateRepoGatewayExecutionInfoParams struct {
	ID                  string `json:"id"`
	VmID                string `json:"vm_id"`
	BaseUrl             string `json:"base_url"`
	AuthTokenHash       string `json:"auth_token_hash"`
	AuthTokenCiphertext string `json:"auth_token_ciphertext"`
	Status              string `json:"status"`
}

func (q *Queries) UpdateRepoGatewayExecutionInfo(ctx context.Context, arg UpdateRepoGatewayExecutionInfoParams) (RepoGateway, error) {
	row := q.db.QueryRow(ctx, updateRepoGatewayExecutionInfo,
		arg.ID,
		arg.VmID,
		arg.BaseUrl,
		arg.AuthTokenHash,
		arg.AuthTokenCiphertext,
		arg.Status,
	)
	var i RepoGateway
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.UserID,
		&i.WorkspaceID,
		&i.VmID,
		&i.BaseUrl,
		&i.AuthTokenHash,
		&i.AuthTokenCiphertext,
		&i.LandingTokenID,
		&i.Status,
		&i.LastActivityAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRepoGatewayStatus = `-- name: UpdateRepoGatewayStatus :one
UPDATE repo_gateways
SET status = $2::text,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, repository_id, user_id, workspace_id, vm_id, base_url, auth_token_hash, auth_token_ciphertext, landing_token_id, status, last_activity_at, deleted_at, created_at, updated_at
`

type UpdateRepoGatewayStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateRepoGatewayStatus(ctx context.Context, arg UpdateRepoGatewayStatusParams) (RepoGateway, error) {
	row := q.db.QueryRow(ctx, updateRepoGatewayStatus, arg.ID, arg.Status)
	var i RepoGateway
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.UserID,
		&i.WorkspaceID,
		&i.VmID,
		&i.BaseUrl,
		&i.AuthTokenHash,
		&i.AuthTokenCiphertext,
		&i.LandingTokenID,
		&i.Status,
		&i.LastActivityAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
