// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repository_source_retention.sql

package clusterdb

import (
	"context"
	"encoding/json"
)

const getRepositorySourcePushEvent = `-- name: GetRepositorySourcePushEvent :one
SELECT payload FROM repository_job_events
WHERE repository_id = $1 AND delivery_key = $2
  AND source = 'github' AND event_type = 'push'
`

type GetRepositorySourcePushEventParams struct {
	RepositoryID int64  `json:"repository_id"`
	DeliveryKey  string `json:"delivery_key"`
}

func (q *Queries) GetRepositorySourcePushEvent(ctx context.Context, arg GetRepositorySourcePushEventParams) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getRepositorySourcePushEvent, arg.RepositoryID, arg.DeliveryKey)
	var payload json.RawMessage
	err := row.Scan(&payload)
	return payload, err
}
