// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: revocations.sql

package clusterdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccessTokenHashByID = `-- name: GetAccessTokenHashByID :one
SELECT token_hash, user_id
FROM access_tokens
WHERE id = $1
`

type GetAccessTokenHashByIDRow struct {
	TokenHash string `json:"token_hash"`
	UserID    int64  `json:"user_id"`
}

func (q *Queries) GetAccessTokenHashByID(ctx context.Context, id int64) (GetAccessTokenHashByIDRow, error) {
	row := q.db.QueryRow(ctx, getAccessTokenHashByID, id)
	var i GetAccessTokenHashByIDRow
	err := row.Scan(&i.TokenHash, &i.UserID)
	return i, err
}

const insertRevocationEvent = `-- name: InsertRevocationEvent :one
WITH event_lock AS MATERIALIZED (SELECT pg_advisory_xact_lock(1548769901))
INSERT INTO revocation_events (
    kind, user_id, token_id, token_hash, repository_id, organization_id,
    workspace_id, session_id, gateway_id, sandbox_ids, reason, actor_id
)
SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12 FROM event_lock
RETURNING id, kind, user_id, token_id, token_hash, repository_id, organization_id, workspace_id, session_id, gateway_id, sandbox_ids, reason, actor_id, created_at
`

type InsertRevocationEventParams struct {
	Kind           string      `json:"kind"`
	UserID         pgtype.Int8 `json:"user_id"`
	TokenID        pgtype.Int8 `json:"token_id"`
	TokenHash      string      `json:"token_hash"`
	RepositoryID   pgtype.Int8 `json:"repository_id"`
	OrganizationID pgtype.Int8 `json:"organization_id"`
	WorkspaceID    string      `json:"workspace_id"`
	SessionID      string      `json:"session_id"`
	GatewayID      string      `json:"gateway_id"`
	SandboxIds     []string    `json:"sandbox_ids"`
	Reason         string      `json:"reason"`
	ActorID        pgtype.Int8 `json:"actor_id"`
}

// Serialize allocation and commit of event IDs so a scan cannot skip a lower
// sequence ID that commits after a higher one. The lock precedes nextval().
func (q *Queries) InsertRevocationEvent(ctx context.Context, arg InsertRevocationEventParams) (RevocationEvent, error) {
	row := q.db.QueryRow(ctx, insertRevocationEvent,
		arg.Kind,
		arg.UserID,
		arg.TokenID,
		arg.TokenHash,
		arg.RepositoryID,
		arg.OrganizationID,
		arg.WorkspaceID,
		arg.SessionID,
		arg.GatewayID,
		arg.SandboxIds,
		arg.Reason,
		arg.ActorID,
	)
	var i RevocationEvent
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.UserID,
		&i.TokenID,
		&i.TokenHash,
		&i.RepositoryID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.SessionID,
		&i.GatewayID,
		&i.SandboxIds,
		&i.Reason,
		&i.ActorID,
		&i.CreatedAt,
	)
	return i, err
}

const latestRevocationEventID = `-- name: LatestRevocationEventID :one
SELECT COALESCE(MAX(id), 0)::bigint AS id FROM revocation_events
`

func (q *Queries) LatestRevocationEventID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, latestRevocationEventID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listRevocationEventsAfter = `-- name: ListRevocationEventsAfter :many
SELECT id, kind, user_id, token_id, token_hash, repository_id, organization_id, workspace_id, session_id, gateway_id, sandbox_ids, reason, actor_id, created_at
FROM revocation_events
WHERE id > $1::bigint
ORDER BY id ASC
LIMIT $2::int
`

type ListRevocationEventsAfterParams struct {
	AfterID    int64 `json:"after_id"`
	LimitCount int32 `json:"limit_count"`
}

func (q *Queries) ListRevocationEventsAfter(ctx context.Context, arg ListRevocationEventsAfterParams) ([]RevocationEvent, error) {
	rows, err := q.db.Query(ctx, listRevocationEventsAfter, arg.AfterID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevocationEvent{}
	for rows.Next() {
		var i RevocationEvent
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.UserID,
			&i.TokenID,
			&i.TokenHash,
			&i.RepositoryID,
			&i.OrganizationID,
			&i.WorkspaceID,
			&i.SessionID,
			&i.GatewayID,
			&i.SandboxIds,
			&i.Reason,
			&i.ActorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifyRevocation = `-- name: NotifyRevocation :exec
SELECT pg_notify('revocations', $1::text)
`

func (q *Queries) NotifyRevocation(ctx context.Context, payload string) error {
	_, err := q.db.Exec(ctx, notifyRevocation, payload)
	return err
}

const pruneRevocationEvents = `-- name: PruneRevocationEvents :execrows
DELETE FROM revocation_events
WHERE created_at < NOW() - make_interval(secs => $1::bigint)
`

func (q *Queries) PruneRevocationEvents(ctx context.Context, maxAgeSeconds int64) (int64, error) {
	result, err := q.db.Exec(ctx, pruneRevocationEvents, maxAgeSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
