// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sandbox_usage_gateways.sql

package clusterdb

import (
	"context"
)

const closeOrphanedRepoGatewaySandboxUsageIntervals = `-- name: CloseOrphanedRepoGatewaySandboxUsageIntervals :exec
UPDATE sandbox_usage_intervals AS usage
SET ended_at = GREATEST(usage.started_at, LEAST(now(), COALESCE(
    (SELECT COALESCE(g.deleted_at, g.last_activity_at, g.updated_at)
     FROM repo_gateways g WHERE g.id::text = usage.sandbox_id), now())))
WHERE usage.ended_at IS NULL
  AND usage.sandbox_kind = 'gateway'
  AND NOT EXISTS (
    SELECT 1 FROM repo_gateways g WHERE g.id::text = usage.sandbox_id
      AND g.status IN ('pending', 'starting', 'running') AND g.deleted_at IS NULL
  )
`

func (q *Queries) CloseOrphanedRepoGatewaySandboxUsageIntervals(ctx context.Context) error {
	_, err := q.db.Exec(ctx, closeOrphanedRepoGatewaySandboxUsageIntervals)
	return err
}
