// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sandbox_environment_image.sql

package clusterdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestReadySandboxEnvironmentImage = `-- name: GetLatestReadySandboxEnvironmentImage :one
SELECT id, repository_id, kind, source, source_revision, closure_hash, image, status, created_by, created_at, updated_at
FROM sandbox_environment_images
WHERE COALESCE(repository_id, 0) = COALESCE($1::bigint, 0)
  AND kind = $2::text
  AND status = 'ready'
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestReadySandboxEnvironmentImageParams struct {
	RepositoryID pgtype.Int8 `json:"repository_id"`
	Kind         string      `json:"kind"`
}

// repository_id NULL selects the platform base image for the kind.
func (q *Queries) GetLatestReadySandboxEnvironmentImage(ctx context.Context, arg GetLatestReadySandboxEnvironmentImageParams) (SandboxEnvironmentImage, error) {
	row := q.db.QueryRow(ctx, getLatestReadySandboxEnvironmentImage, arg.RepositoryID, arg.Kind)
	var i SandboxEnvironmentImage
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Kind,
		&i.Source,
		&i.SourceRevision,
		&i.ClosureHash,
		&i.Image,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProtectedWorkerSnapshotLocalIDs = `-- name: ListProtectedWorkerSnapshotLocalIDs :many
SELECT DISTINCT ss.provider_local_id
FROM sandbox_snapshots ss
WHERE ss.worker_id = $1::text
  AND ss.deleted_at IS NULL
  AND ss.state NOT IN ('deleting', 'deleted')
  AND (
    ss.state IN ('creating', 'exporting')
    OR ss.updated_at > NOW() - INTERVAL '1 hour'
    OR EXISTS (
        SELECT 1 FROM sandbox_instances i
        WHERE i.deleted_at IS NULL
          AND (i.snapshot_id = ss.id OR i.recovery_snapshot_id = ss.id)
    )
    OR EXISTS (SELECT 1 FROM workspace_snapshots ws WHERE ws.snapshot_id = ss.id)
    OR EXISTS (SELECT 1 FROM sandbox_golden_snapshots gs WHERE gs.snapshot_id = ss.id)
  )
ORDER BY ss.provider_local_id
`

// The one-hour handoff protects a provider snapshot while the API service is
// persisting its workspace/golden owner after the controller created it.
func (q *Queries) ListProtectedWorkerSnapshotLocalIDs(ctx context.Context, workerID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listProtectedWorkerSnapshotLocalIDs, workerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var provider_local_id string
		if err := rows.Scan(&provider_local_id); err != nil {
			return nil, err
		}
		items = append(items, provider_local_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadySandboxEnvironmentImageReferences = `-- name: ListReadySandboxEnvironmentImageReferences :many

SELECT image
FROM sandbox_environment_images
WHERE status = 'ready'
ORDER BY image
`

// Private cluster queries kept separate from the product graph.
func (q *Queries) ListReadySandboxEnvironmentImageReferences(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listReadySandboxEnvironmentImageReferences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var image string
		if err := rows.Scan(&image); err != nil {
			return nil, err
		}
		items = append(items, image)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxEnvironmentImages = `-- name: ListSandboxEnvironmentImages :many
SELECT id, repository_id, kind, source, source_revision, closure_hash, image, status, created_by, created_at, updated_at
FROM sandbox_environment_images
WHERE COALESCE(repository_id, 0) = COALESCE($1::bigint, 0)
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) ListSandboxEnvironmentImages(ctx context.Context, repositoryID pgtype.Int8) ([]SandboxEnvironmentImage, error) {
	rows, err := q.db.Query(ctx, listSandboxEnvironmentImages, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SandboxEnvironmentImage{}
	for rows.Next() {
		var i SandboxEnvironmentImage
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Kind,
			&i.Source,
			&i.SourceRevision,
			&i.ClosureHash,
			&i.Image,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireSandboxEnvironmentImage = `-- name: RetireSandboxEnvironmentImage :one
UPDATE sandbox_environment_images
SET status = 'retired', updated_at = NOW()
WHERE id = $1
  AND COALESCE(repository_id, 0) = COALESCE($2::bigint, 0)
RETURNING id, repository_id, kind, source, source_revision, closure_hash, image, status, created_by, created_at, updated_at
`

type RetireSandboxEnvironmentImageParams struct {
	ID           string      `json:"id"`
	RepositoryID pgtype.Int8 `json:"repository_id"`
}

func (q *Queries) RetireSandboxEnvironmentImage(ctx context.Context, arg RetireSandboxEnvironmentImageParams) (SandboxEnvironmentImage, error) {
	row := q.db.QueryRow(ctx, retireSandboxEnvironmentImage, arg.ID, arg.RepositoryID)
	var i SandboxEnvironmentImage
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Kind,
		&i.Source,
		&i.SourceRevision,
		&i.ClosureHash,
		&i.Image,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
