// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow_schedules.sql

package clusterdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueWorkflowScheduleSpecs = `-- name: ClaimDueWorkflowScheduleSpecs :many
WITH claimable AS (
    SELECT id
    FROM workflow_schedule_specs
    WHERE next_fire_at <= NOW()
    ORDER BY next_fire_at ASC, id ASC
    FOR UPDATE SKIP LOCKED
    LIMIT $1
)
UPDATE workflow_schedule_specs wss
SET prev_fire_at = NOW(),
    next_fire_at = NOW() + INTERVAL '5 minutes',
    updated_at = NOW()
FROM claimable
WHERE wss.id = claimable.id
RETURNING wss.id, wss.workflow_definition_id, wss.repository_id, wss.cron_expression, wss.next_fire_at, wss.prev_fire_at, wss.created_at, wss.updated_at
`

// Atomically claim due schedule specs using FOR UPDATE SKIP LOCKED to prevent
// concurrent pollers from double-firing the same spec. Sets next_fire_at to a
// short (5 minute) reclaim lease -- not a far-future sentinel -- so the spec
// is invisible to other pollers only while this poller is expected to be
// working on it. The caller computes and writes the real next fire time after
// a successful dispatch. If the worker crashes or errors before that write,
// the spec becomes due again automatically once the lease expires and the
// occurrence is retried (at-least-once: a crash after dispatch but before the
// reschedule write may cause one duplicate fire). The lease must comfortably
// exceed one poll's per-spec work (a single DispatchForEvent DB write, poll
// interval 30s, claim limit 50).
func (q *Queries) ClaimDueWorkflowScheduleSpecs(ctx context.Context, limitCount int32) ([]WorkflowScheduleSpec, error) {
	rows, err := q.db.Query(ctx, claimDueWorkflowScheduleSpecs, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowScheduleSpec{}
	for rows.Next() {
		var i WorkflowScheduleSpec
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowDefinitionID,
			&i.RepositoryID,
			&i.CronExpression,
			&i.NextFireAt,
			&i.PrevFireAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteWorkflowScheduleSpecsByDefinition = `-- name: DeleteWorkflowScheduleSpecsByDefinition :exec
DELETE FROM workflow_schedule_specs
WHERE workflow_definition_id = $1
`

func (q *Queries) DeleteWorkflowScheduleSpecsByDefinition(ctx context.Context, workflowDefinitionID int64) error {
	_, err := q.db.Exec(ctx, deleteWorkflowScheduleSpecsByDefinition, workflowDefinitionID)
	return err
}

const updateWorkflowScheduleFireTimes = `-- name: UpdateWorkflowScheduleFireTimes :exec
UPDATE workflow_schedule_specs
SET prev_fire_at = $2,
    next_fire_at = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateWorkflowScheduleFireTimesParams struct {
	ID         int64              `json:"id"`
	PrevFireAt pgtype.Timestamptz `json:"prev_fire_at"`
	NextFireAt time.Time          `json:"next_fire_at"`
}

func (q *Queries) UpdateWorkflowScheduleFireTimes(ctx context.Context, arg UpdateWorkflowScheduleFireTimesParams) error {
	_, err := q.db.Exec(ctx, updateWorkflowScheduleFireTimes, arg.ID, arg.PrevFireAt, arg.NextFireAt)
	return err
}

const upsertWorkflowScheduleSpec = `-- name: UpsertWorkflowScheduleSpec :exec
INSERT INTO workflow_schedule_specs (
    workflow_definition_id,
    repository_id,
    cron_expression,
    next_fire_at
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (workflow_definition_id, cron_expression)
DO UPDATE SET
    repository_id = EXCLUDED.repository_id,
    next_fire_at = EXCLUDED.next_fire_at,
    updated_at = NOW()
`

type UpsertWorkflowScheduleSpecParams struct {
	WorkflowDefinitionID int64     `json:"workflow_definition_id"`
	RepositoryID         int64     `json:"repository_id"`
	CronExpression       string    `json:"cron_expression"`
	NextFireAt           time.Time `json:"next_fire_at"`
}

func (q *Queries) UpsertWorkflowScheduleSpec(ctx context.Context, arg UpsertWorkflowScheduleSpecParams) error {
	_, err := q.db.Exec(ctx, upsertWorkflowScheduleSpec,
		arg.WorkflowDefinitionID,
		arg.RepositoryID,
		arg.CronExpression,
		arg.NextFireAt,
	)
	return err
}
