// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow_runs_jjhub_tokens.sql

package clusterdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearWorkflowRunJJHubTokenID = `-- name: ClearWorkflowRunJJHubTokenID :exec
UPDATE workflow_runs
SET jjhub_token_id = NULL,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ClearWorkflowRunJJHubTokenID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, clearWorkflowRunJJHubTokenID, id)
	return err
}

const getWorkflowRunJJHubTokenID = `-- name: GetWorkflowRunJJHubTokenID :one
SELECT jjhub_token_id
FROM workflow_runs
WHERE id = $1
`

func (q *Queries) GetWorkflowRunJJHubTokenID(ctx context.Context, id int64) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, getWorkflowRunJJHubTokenID, id)
	var jjhub_token_id pgtype.Int8
	err := row.Scan(&jjhub_token_id)
	return jjhub_token_id, err
}

const updateWorkflowRunJJHubTokenID = `-- name: UpdateWorkflowRunJJHubTokenID :exec
UPDATE workflow_runs
SET jjhub_token_id = $1,
    updated_at = NOW()
WHERE id = $2
`

type UpdateWorkflowRunJJHubTokenIDParams struct {
	JjhubTokenID pgtype.Int8 `json:"jjhub_token_id"`
	ID           int64       `json:"id"`
}

func (q *Queries) UpdateWorkflowRunJJHubTokenID(ctx context.Context, arg UpdateWorkflowRunJJHubTokenIDParams) error {
	_, err := q.db.Exec(ctx, updateWorkflowRunJJHubTokenID, arg.JjhubTokenID, arg.ID)
	return err
}
