/*
 * Renders the browser-tab favicon: the wordmark's "S" (the first 8 columns of
 * Wordmark.ts) as a 64x64 tile, in the app's colors — #3a756b on #f7f6f1 in
 * light, #9bd5c6 on #101e24 in dark via a prefers-color-scheme media query.
 * Writes the SVG to apps/site/public and apps/app/src/mainview/public, then
 * rasterizes every desktop, website, and documentation icon with rsvg-convert.
 */
import { sites } from "../../docs/shared/manifest.mjs"
import { WORDMARK } from "../src/mainview/Wordmark.ts"

const S = WORDMARK.map((row) => [...row].slice(0, 8))
const W = 4.5
const H = 8.0 // IBM Plex Mono cell ~0.6em wide, line-height 1.07
const X0 = (64 - 8 * W) / 2
const Y0 = (64 - 6 * H) / 2
const DW = W * 0.2
const DH = H * 0.14
const SW = 0.7 // double-line offsets and stroke width

function f(v: number): string {
  return v.toFixed(2).replace(/0+$/, "").replace(/\.$/, "")
}

type Point = [number, number]

export function buildFaviconSvg(): string {
  const parts: string[] = []
  for (const [r, row] of S.entries()) {
    for (const [c, ch] of row.entries()) {
      const x = X0 + c * W
      const y = Y0 + r * H
      const cx = x + W / 2
      const cy = y + H / 2
      if (ch === "█") continue
      const paths: Record<string, Point[][]> = {
        "═": [
          [[x, cy - DH], [x + W, cy - DH]],
          [[x, cy + DH], [x + W, cy + DH]],
        ],
        "║": [
          [[cx - DW, y], [cx - DW, y + H]],
          [[cx + DW, y], [cx + DW, y + H]],
        ],
        "╗": [
          [[x, cy - DH], [cx + DW, cy - DH], [cx + DW, y + H]],
          [[x, cy + DH], [cx - DW, cy + DH], [cx - DW, y + H]],
        ],
        "╔": [
          [[x + W, cy - DH], [cx - DW, cy - DH], [cx - DW, y + H]],
          [[x + W, cy + DH], [cx + DW, cy + DH], [cx + DW, y + H]],
        ],
        "╚": [
          [[cx - DW, y], [cx - DW, cy + DH], [x + W, cy + DH]],
          [[cx + DW, y], [cx + DW, cy - DH], [x + W, cy - DH]],
        ],
        "╝": [
          [[cx + DW, y], [cx + DW, cy + DH], [x, cy + DH]],
          [[cx - DW, y], [cx - DW, cy - DH], [x, cy - DH]],
        ],
      }
      for (const p of paths[ch]) {
        parts.push(
          '<polyline class="ln" points="' + p.map(([a, b]) => `${f(a)},${f(b)}`).join(" ") + '"/>',
        )
      }
    }
  }
  const runs: string[] = []
  for (const [r, row] of S.entries()) {
    let c = 0
    while (c < row.length) {
      if (row[c] !== "█") {
        c += 1
        continue
      }
      const start = c
      while (c < row.length && row[c] === "█") c += 1
      const x = X0 + start * W
      const y = Y0 + r * H
      runs.push(`M${f(x)} ${f(y)}h${f((c - start) * W)}v${f(H + 0.02)}h${f(-(c - start) * W)}z`)
    }
  }
  parts.unshift('<path class="fg" d="' + runs.join("") + '"/>')
  const style =
    `.bg{fill:#f7f6f1}.fg{fill:#3a756b}.ln{fill:none;stroke:#3a756b;stroke-width:${SW}}` +
    "@media (prefers-color-scheme:dark){.bg{fill:#101e24}.fg{fill:#9bd5c6}.ln{stroke:#9bd5c6}}"
  return (
    "<!-- Generated by apps/app/scripts/render-favicon.ts from Wordmark.ts; do not edit. -->\n" +
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64" role="img" aria-label="Smithers">' +
    `<style>${style}</style><rect class="bg" width="64" height="64" rx="12"/>` +
    parts.join("") +
    "</svg>\n"
  )
}

/** Every shipped raster mark is rendered from the same wordmark SVG. */
export const rasterIcons: ReadonlyArray<readonly [number, URL]> = [
  ...([[32, "public/favicon.png"], [256, "public/icon.png"],
    [256, "public/apple-touch-icon.png"], [256, "src/docs-assets/logo.png"],
    [32, "src/docs-assets/favicon.png"]] as const).map(([size, path]) =>
    [size, new URL(`../../site/${path}`, import.meta.url)] as const),
  [256, new URL("../../docs/shared/assets/logo.png", import.meta.url)],
  [32, new URL("../../docs/shared/assets/favicon.png", import.meta.url)],
  ...sites.flatMap((site) => [
    [256, new URL(`../../docs/${site.slug}/src/docs-assets/logo.png`, import.meta.url)] as const,
    [32, new URL(`../../docs/${site.slug}/public/favicon.png`, import.meta.url)] as const,
  ]),
  ...[16, 32, 128, 256, 512].flatMap((size) => [1, 2].map((scale) =>
    [size * scale, new URL(`../icon.iconset/icon_${size}x${size}${scale === 2 ? "@2x" : ""}.png`, import.meta.url)] as const)),
]

if (import.meta.main) {
  const rsvg = Bun.which("rsvg-convert")
  if (!rsvg) throw new Error("Install librsvg (rsvg-convert) to render branding assets")
  const siteSvg = new URL("../../site/public/favicon.svg", import.meta.url)
  const appSvg = new URL("../src/mainview/public/favicon.svg", import.meta.url)
  const svg = buildFaviconSvg()
  await Bun.write(siteSvg, svg)
  await Bun.write(appSvg, svg)
  for (const [size, png] of rasterIcons) {
    const proc = Bun.spawnSync(
      [rsvg, "-w", String(size), "-h", String(size), siteSvg.pathname, "-o", png.pathname],
    )
    if (!proc.success) {
      throw new Error(`rsvg-convert failed for ${png.pathname}: ${proc.stderr.toString()}`)
    }
  }
  console.log(`wrote favicon.svg x2 and ${rasterIcons.length} raster branding assets`)
}
