// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_analytics.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminSetUserSynthetic = `-- name: AdminSetUserSynthetic :one
UPDATE users SET is_synthetic=$1::boolean, updated_at=now()
WHERE lower_username=$2::text RETURNING id, username, lower_username, email, lower_email, display_name, bio, search_vector, avatar_url, wallet_address, user_type, is_active, is_admin, prohibit_login, email_notifications_enabled, last_login_at, deleted_at, created_at, updated_at, is_synthetic
`

type AdminSetUserSyntheticParams struct {
	Synthetic     bool   `json:"synthetic"`
	LowerUsername string `json:"lower_username"`
}

// Update the explicit synthetic classification; the admin user service emits admin.user.set_synthetic.
func (q *Queries) AdminSetUserSynthetic(ctx context.Context, arg AdminSetUserSyntheticParams) (User, error) {
	row := q.db.QueryRow(ctx, adminSetUserSynthetic, arg.Synthetic, arg.LowerUsername)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.LowerUsername,
		&i.Email,
		&i.LowerEmail,
		&i.DisplayName,
		&i.Bio,
		&i.SearchVector,
		&i.AvatarUrl,
		&i.WalletAddress,
		&i.UserType,
		&i.IsActive,
		&i.IsAdmin,
		&i.ProhibitLogin,
		&i.EmailNotificationsEnabled,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSynthetic,
	)
	return i, err
}

const analyticsActivation = `-- name: AnalyticsActivation :one
SELECT count(*)::bigint AS signup,
 count(*) FILTER (WHERE EXISTS (SELECT 1 FROM oauth_accounts a WHERE a.user_id=u.id AND a.provider='github'))::bigint AS github_connected,
 count(*) FILTER (WHERE EXISTS (SELECT 1 FROM repositories r WHERE r.user_id=u.id))::bigint AS first_repo,
 count(*) FILTER (WHERE EXISTS (SELECT 1 FROM workspaces w WHERE w.user_id=u.id AND w.started_at IS NOT NULL))::bigint AS workspace_booted,
 count(*) FILTER (WHERE EXISTS (SELECT 1 FROM agent_sessions a WHERE a.user_id=u.id))::bigint AS first_agent_run,
 count(*) FILTER (WHERE EXISTS (SELECT 1 FROM landing_requests l WHERE l.author_id=u.id AND l.merged_at IS NOT NULL))::bigint AS first_landing_merged
FROM users u WHERE ($1::boolean OR NOT u.is_synthetic)
`

type AnalyticsActivationRow struct {
	Signup             int64 `json:"signup"`
	GithubConnected    int64 `json:"github_connected"`
	FirstRepo          int64 `json:"first_repo"`
	WorkspaceBooted    int64 `json:"workspace_booted"`
	FirstAgentRun      int64 `json:"first_agent_run"`
	FirstLandingMerged int64 `json:"first_landing_merged"`
}

// All-time first-occurrence counts per user, not a sequential funnel. Non-synthetic by default; include_synthetic disables this filter too. GitHub requires provider github, boot requires started_at, merged landing requires authored merged_at.
func (q *Queries) AnalyticsActivation(ctx context.Context, includeSynthetic bool) (AnalyticsActivationRow, error) {
	row := q.db.QueryRow(ctx, analyticsActivation, includeSynthetic)
	var i AnalyticsActivationRow
	err := row.Scan(
		&i.Signup,
		&i.GithubConnected,
		&i.FirstRepo,
		&i.WorkspaceBooted,
		&i.FirstAgentRun,
		&i.FirstLandingMerged,
	)
	return i, err
}

const analyticsAgents = `-- name: AnalyticsAgents :one
SELECT count(*)::bigint AS sessions_total,
 coalesce(percentile_cont(0.5) WITHIN GROUP (ORDER BY extract(epoch FROM (a.finished_at-a.started_at))),0)::float8 AS duration_p50_seconds,
 coalesce(percentile_cont(0.95) WITHIN GROUP (ORDER BY extract(epoch FROM (a.finished_at-a.started_at))),0)::float8 AS duration_p95_seconds,
 count(*) FILTER (WHERE EXISTS (SELECT 1 FROM change_revisions c WHERE c.agent_session_id=a.id AND c.source='agent'))::bigint AS with_revisions,
 count(*) FILTER (WHERE EXISTS (SELECT 1 FROM landing_requests l WHERE l.author_agent_session_id=a.id))::bigint AS with_landing_request,
 count(*) FILTER (WHERE EXISTS (SELECT 1 FROM landing_requests l WHERE l.author_agent_session_id=a.id AND l.merged_at IS NOT NULL))::bigint AS merged
 FROM agent_sessions a JOIN users u ON u.id=a.user_id WHERE a.created_at >= $1::timestamptz AND a.created_at < $2::timestamptz AND ($3::boolean OR NOT u.is_synthetic)
`

type AnalyticsAgentsParams struct {
	RangeStart       time.Time `json:"range_start"`
	RangeEnd         time.Time `json:"range_end"`
	IncludeSynthetic bool      `json:"include_synthetic"`
}

type AnalyticsAgentsRow struct {
	SessionsTotal      int64   `json:"sessions_total"`
	DurationP50Seconds float64 `json:"duration_p50_seconds"`
	DurationP95Seconds float64 `json:"duration_p95_seconds"`
	WithRevisions      int64   `json:"with_revisions"`
	WithLandingRequest int64   `json:"with_landing_request"`
	Merged             int64   `json:"merged"`
}

// Sessions created in range, filtered by session owning user_id. Duration is finished_at minus started_at; empty percentiles are zero. Revision and landing metrics count sessions once via EXISTS, with revisions restricted to source agent; merged requires merged_at.
func (q *Queries) AnalyticsAgents(ctx context.Context, arg AnalyticsAgentsParams) (AnalyticsAgentsRow, error) {
	row := q.db.QueryRow(ctx, analyticsAgents, arg.RangeStart, arg.RangeEnd, arg.IncludeSynthetic)
	var i AnalyticsAgentsRow
	err := row.Scan(
		&i.SessionsTotal,
		&i.DurationP50Seconds,
		&i.DurationP95Seconds,
		&i.WithRevisions,
		&i.WithLandingRequest,
		&i.Merged,
	)
	return i, err
}

const analyticsAgentsByStatus = `-- name: AnalyticsAgentsByStatus :many
SELECT a.status, count(*)::bigint AS count FROM agent_sessions a JOIN users u ON u.id=a.user_id WHERE a.created_at >= $1::timestamptz AND a.created_at < $2::timestamptz AND ($3::boolean OR NOT u.is_synthetic) GROUP BY a.status ORDER BY a.status
`

type AnalyticsAgentsByStatusParams struct {
	RangeStart       time.Time `json:"range_start"`
	RangeEnd         time.Time `json:"range_end"`
	IncludeSynthetic bool      `json:"include_synthetic"`
}

type AnalyticsAgentsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

// Current status counts for sessions created in range, filtered by session owner.
func (q *Queries) AnalyticsAgentsByStatus(ctx context.Context, arg AnalyticsAgentsByStatusParams) ([]AnalyticsAgentsByStatusRow, error) {
	rows, err := q.db.Query(ctx, analyticsAgentsByStatus, arg.RangeStart, arg.RangeEnd, arg.IncludeSynthetic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsAgentsByStatusRow{}
	for rows.Next() {
		var i AnalyticsAgentsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsImportFailures = `-- name: AnalyticsImportFailures :many
SELECT i.error AS reason,count(*)::bigint AS count FROM import_jobs i JOIN users u ON u.id=i.user_id WHERE i.created_at >= $1::timestamptz AND i.created_at < $2::timestamptz AND ($3::boolean OR NOT u.is_synthetic) AND i.status='failed' GROUP BY i.error ORDER BY count DESC,reason
`

type AnalyticsImportFailuresParams struct {
	RangeStart       time.Time `json:"range_start"`
	RangeEnd         time.Time `json:"range_end"`
	IncludeSynthetic bool      `json:"include_synthetic"`
}

type AnalyticsImportFailuresRow struct {
	Reason string `json:"reason"`
	Count  int64  `json:"count"`
}

// Failure reasons use import_jobs.error on failed jobs created in range, filtered by job owner.
func (q *Queries) AnalyticsImportFailures(ctx context.Context, arg AnalyticsImportFailuresParams) ([]AnalyticsImportFailuresRow, error) {
	rows, err := q.db.Query(ctx, analyticsImportFailures, arg.RangeStart, arg.RangeEnd, arg.IncludeSynthetic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsImportFailuresRow{}
	for rows.Next() {
		var i AnalyticsImportFailuresRow
		if err := rows.Scan(&i.Reason, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsImportsByStatus = `-- name: AnalyticsImportsByStatus :many
SELECT i.status,count(*)::bigint AS count FROM import_jobs i JOIN users u ON u.id=i.user_id WHERE i.created_at >= $1::timestamptz AND i.created_at < $2::timestamptz AND ($3::boolean OR NOT u.is_synthetic) GROUP BY i.status ORDER BY i.status
`

type AnalyticsImportsByStatusParams struct {
	RangeStart       time.Time `json:"range_start"`
	RangeEnd         time.Time `json:"range_end"`
	IncludeSynthetic bool      `json:"include_synthetic"`
}

type AnalyticsImportsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

// Current status counts for import jobs created in range, filtered by import_jobs.user_id.
func (q *Queries) AnalyticsImportsByStatus(ctx context.Context, arg AnalyticsImportsByStatusParams) ([]AnalyticsImportsByStatusRow, error) {
	rows, err := q.db.Query(ctx, analyticsImportsByStatus, arg.RangeStart, arg.RangeEnd, arg.IncludeSynthetic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsImportsByStatusRow{}
	for rows.Next() {
		var i AnalyticsImportsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsImportsFailedByStage = `-- name: AnalyticsImportsFailedByStage :many
SELECT i.stage,count(*)::bigint AS count FROM import_jobs i JOIN users u ON u.id=i.user_id WHERE i.created_at >= $1::timestamptz AND i.created_at < $2::timestamptz AND ($3::boolean OR NOT u.is_synthetic) AND i.status='failed' GROUP BY i.stage ORDER BY count DESC,i.stage
`

type AnalyticsImportsFailedByStageParams struct {
	RangeStart       time.Time `json:"range_start"`
	RangeEnd         time.Time `json:"range_end"`
	IncludeSynthetic bool      `json:"include_synthetic"`
}

type AnalyticsImportsFailedByStageRow struct {
	Stage string `json:"stage"`
	Count int64  `json:"count"`
}

// Failed stage uses import_jobs.stage, not status, on failed jobs created in range, filtered by job owner.
func (q *Queries) AnalyticsImportsFailedByStage(ctx context.Context, arg AnalyticsImportsFailedByStageParams) ([]AnalyticsImportsFailedByStageRow, error) {
	rows, err := q.db.Query(ctx, analyticsImportsFailedByStage, arg.RangeStart, arg.RangeEnd, arg.IncludeSynthetic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsImportsFailedByStageRow{}
	for rows.Next() {
		var i AnalyticsImportsFailedByStageRow
		if err := rows.Scan(&i.Stage, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsLanding = `-- name: AnalyticsLanding :one
SELECT coalesce(count(*) FILTER (WHERE l.merged_at IS NOT NULL)::float8 / nullif(count(*),0),0)::float8 AS merge_rate,
 count(*) FILTER (WHERE l.agent_authored)::bigint AS agent_authored,
 count(*) FILTER (WHERE l.agent_authored AND l.merged_at IS NOT NULL)::bigint AS agent_authored_merged FROM landing_requests l JOIN users u ON u.id=l.author_id WHERE l.created_at >= $1::timestamptz AND l.created_at < $2::timestamptz AND ($3::boolean OR NOT u.is_synthetic)
`

type AnalyticsLandingParams struct {
	RangeStart       time.Time `json:"range_start"`
	RangeEnd         time.Time `json:"range_end"`
	IncludeSynthetic bool      `json:"include_synthetic"`
}

type AnalyticsLandingRow struct {
	MergeRate           float64 `json:"merge_rate"`
	AgentAuthored       int64   `json:"agent_authored"`
	AgentAuthoredMerged int64   `json:"agent_authored_merged"`
}

// Merge rate is merged_at-present requests divided by all requests created in range (zero for no requests). Agent-authored counts use the flag, with merged_at for the merged subset; filtered by author.
func (q *Queries) AnalyticsLanding(ctx context.Context, arg AnalyticsLandingParams) (AnalyticsLandingRow, error) {
	row := q.db.QueryRow(ctx, analyticsLanding, arg.RangeStart, arg.RangeEnd, arg.IncludeSynthetic)
	var i AnalyticsLandingRow
	err := row.Scan(&i.MergeRate, &i.AgentAuthored, &i.AgentAuthoredMerged)
	return i, err
}

const analyticsLandingByState = `-- name: AnalyticsLandingByState :many
SELECT l.state,count(*)::bigint AS count FROM landing_requests l JOIN users u ON u.id=l.author_id WHERE l.created_at >= $1::timestamptz AND l.created_at < $2::timestamptz AND ($3::boolean OR NOT u.is_synthetic) GROUP BY l.state ORDER BY l.state
`

type AnalyticsLandingByStateParams struct {
	RangeStart       time.Time `json:"range_start"`
	RangeEnd         time.Time `json:"range_end"`
	IncludeSynthetic bool      `json:"include_synthetic"`
}

type AnalyticsLandingByStateRow struct {
	State string `json:"state"`
	Count int64  `json:"count"`
}

// Current state counts for landing requests created in range; synthetic ownership follows the author_id user.
func (q *Queries) AnalyticsLandingByState(ctx context.Context, arg AnalyticsLandingByStateParams) ([]AnalyticsLandingByStateRow, error) {
	rows, err := q.db.Query(ctx, analyticsLandingByState, arg.RangeStart, arg.RangeEnd, arg.IncludeSynthetic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsLandingByStateRow{}
	for rows.Next() {
		var i AnalyticsLandingByStateRow
		if err := rows.Scan(&i.State, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsLandingCycle = `-- name: AnalyticsLandingCycle :one
SELECT coalesce(percentile_cont(0.5) WITHIN GROUP (ORDER BY extract(epoch FROM (l.merged_at-l.created_at))),0)::float8 AS cycle_time_p50_seconds
FROM landing_requests l JOIN users u ON u.id=l.author_id WHERE l.merged_at >= $1::timestamptz AND l.merged_at < $2::timestamptz AND ($3::boolean OR NOT u.is_synthetic)
`

type AnalyticsLandingCycleParams struct {
	RangeStart       time.Time `json:"range_start"`
	RangeEnd         time.Time `json:"range_end"`
	IncludeSynthetic bool      `json:"include_synthetic"`
}

// Cycle time is merged_at minus created_at for requests merged in range, even if created earlier. Filtered by author; an empty population returns zero seconds.
func (q *Queries) AnalyticsLandingCycle(ctx context.Context, arg AnalyticsLandingCycleParams) (float64, error) {
	row := q.db.QueryRow(ctx, analyticsLandingCycle, arg.RangeStart, arg.RangeEnd, arg.IncludeSynthetic)
	var cycle_time_p50_seconds float64
	err := row.Scan(&cycle_time_p50_seconds)
	return cycle_time_p50_seconds, err
}

const analyticsRepos = `-- name: AnalyticsRepos :one
SELECT count(*)::bigint AS total, count(*) FILTER (WHERE r.created_at >= $1::timestamptz AND r.created_at < $2::timestamptz)::bigint AS created_in_range
FROM repositories r LEFT JOIN users u ON u.id=r.user_id WHERE ($3::boolean OR NOT coalesce(u.is_synthetic,false))
`

type AnalyticsReposParams struct {
	RangeStart       time.Time `json:"range_start"`
	RangeEnd         time.Time `json:"range_end"`
	IncludeSynthetic bool      `json:"include_synthetic"`
}

type AnalyticsReposRow struct {
	Total          int64 `json:"total"`
	CreatedInRange int64 `json:"created_in_range"`
}

// All-time repository total and creations in range, filtered through repositories.user_id. Org-owned repositories have no user owner and count as human.
func (q *Queries) AnalyticsRepos(ctx context.Context, arg AnalyticsReposParams) (AnalyticsReposRow, error) {
	row := q.db.QueryRow(ctx, analyticsRepos, arg.RangeStart, arg.RangeEnd, arg.IncludeSynthetic)
	var i AnalyticsReposRow
	err := row.Scan(&i.Total, &i.CreatedInRange)
	return i, err
}

const analyticsSignupsByDay = `-- name: AnalyticsSignupsByDay :many
WITH days AS (
 SELECT generate_series($1::timestamptz AT TIME ZONE 'UTC', date_trunc('day', $2::timestamptz AT TIME ZONE 'UTC'), interval '1 day') AS day
), counts AS (
 SELECT (u.created_at AT TIME ZONE 'UTC')::date AS day, count(*)::bigint AS count
 FROM users u WHERE u.created_at >= $1::timestamptz AND u.created_at < $2::timestamptz AND ($3::boolean OR NOT u.is_synthetic) GROUP BY 1
)
SELECT to_char(d.day, 'YYYY-MM-DD')::text AS day, coalesce(c.count,0)::bigint AS count
FROM days d LEFT JOIN counts c ON c.day=d.day::date ORDER BY d.day
`

type AnalyticsSignupsByDayParams struct {
	RangeStart       time.Time `json:"range_start"`
	RangeEnd         time.Time `json:"range_end"`
	IncludeSynthetic bool      `json:"include_synthetic"`
}

type AnalyticsSignupsByDayRow struct {
	Day   string `json:"day"`
	Count int64  `json:"count"`
}

// UTC calendar days, including zero days, counting users created in range after the synthetic filter.
func (q *Queries) AnalyticsSignupsByDay(ctx context.Context, arg AnalyticsSignupsByDayParams) ([]AnalyticsSignupsByDayRow, error) {
	rows, err := q.db.Query(ctx, analyticsSignupsByDay, arg.RangeStart, arg.RangeEnd, arg.IncludeSynthetic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsSignupsByDayRow{}
	for rows.Next() {
		var i AnalyticsSignupsByDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsStatementTimeout = `-- name: AnalyticsStatementTimeout :exec
SELECT set_config('statement_timeout', '20s', true)
`

// Transaction-local server-side timeout for the read-only analytics snapshot.
func (q *Queries) AnalyticsStatementTimeout(ctx context.Context) error {
	_, err := q.db.Exec(ctx, analyticsStatementTimeout)
	return err
}

const analyticsStuckAgents = `-- name: AnalyticsStuckAgents :many
SELECT a.id, a.created_at, floor(extract(epoch FROM ($1::timestamptz-a.created_at)))::bigint AS age_seconds,
 u.username AS username, (coalesce(ru.username,o.name)||'/'||r.name)::text AS repository
 FROM agent_sessions a JOIN users u ON u.id=a.user_id
 JOIN repositories r ON r.id=a.repository_id LEFT JOIN users ru ON ru.id=r.user_id LEFT JOIN organizations o ON o.id=r.org_id
 WHERE a.status='active' AND a.deleted_at IS NULL AND ($2::boolean OR NOT u.is_synthetic)
 AND ((a.started_at IS NULL AND a.created_at < $1::timestamptz-interval '1 hour') OR a.created_at < $1::timestamptz-interval '24 hours')
 ORDER BY a.created_at,a.id
`

type AnalyticsStuckAgentsParams struct {
	RangeEnd         time.Time `json:"range_end"`
	IncludeSynthetic bool      `json:"include_synthetic"`
}

type AnalyticsStuckAgentsRow struct {
	ID         string             `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	AgeSeconds int64              `json:"age_seconds"`
	Username   string             `json:"username"`
	Repository string             `json:"repository"`
}

// All-time live active sessions older than 1h without started_at, or older than 24h regardless of started_at. Owner filtering uses agent_sessions.user_id; repository names retain organization owners.
func (q *Queries) AnalyticsStuckAgents(ctx context.Context, arg AnalyticsStuckAgentsParams) ([]AnalyticsStuckAgentsRow, error) {
	rows, err := q.db.Query(ctx, analyticsStuckAgents, arg.RangeEnd, arg.IncludeSynthetic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsStuckAgentsRow{}
	for rows.Next() {
		var i AnalyticsStuckAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.AgeSeconds,
			&i.Username,
			&i.Repository,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsTopRepos = `-- name: AnalyticsTopRepos :many
WITH workspace_counts AS (
 SELECT w.repository_id,count(*)::bigint AS count FROM workspaces w JOIN users u ON u.id=w.user_id WHERE w.created_at >= $2::timestamptz AND w.created_at < $3::timestamptz AND ($1::boolean OR NOT u.is_synthetic) GROUP BY w.repository_id
), agent_counts AS (
 SELECT a.repository_id,count(*)::bigint AS count FROM agent_sessions a JOIN users u ON u.id=a.user_id WHERE a.created_at >= $2::timestamptz AND a.created_at < $3::timestamptz AND ($1::boolean OR NOT u.is_synthetic) GROUP BY a.repository_id
), landing_counts AS (
 SELECT l.repository_id,count(*)::bigint AS count FROM landing_requests l JOIN users u ON u.id=l.author_id WHERE l.created_at >= $2::timestamptz AND l.created_at < $3::timestamptz AND ($1::boolean OR NOT u.is_synthetic) GROUP BY l.repository_id
)
SELECT coalesce(u.username,o.name)::text AS owner,r.name,
 coalesce(w.count,0)::bigint AS workspaces,coalesce(a.count,0)::bigint AS agent_sessions,coalesce(l.count,0)::bigint AS landing_requests
FROM repositories r LEFT JOIN users u ON u.id=r.user_id LEFT JOIN organizations o ON o.id=r.org_id
LEFT JOIN workspace_counts w ON w.repository_id=r.id LEFT JOIN agent_counts a ON a.repository_id=r.id LEFT JOIN landing_counts l ON l.repository_id=r.id
WHERE ($1::boolean OR NOT coalesce(u.is_synthetic,false))
ORDER BY (coalesce(w.count,0)+coalesce(a.count,0)+coalesce(l.count,0)) DESC,owner,r.name,r.id LIMIT 10
`

type AnalyticsTopReposParams struct {
	IncludeSynthetic bool      `json:"include_synthetic"`
	RangeStart       time.Time `json:"range_start"`
	RangeEnd         time.Time `json:"range_end"`
}

type AnalyticsTopReposRow struct {
	Owner           string `json:"owner"`
	Name            string `json:"name"`
	Workspaces      int64  `json:"workspaces"`
	AgentSessions   int64  `json:"agent_sessions"`
	LandingRequests int64  `json:"landing_requests"`
}

// Top ten by workspace + session + landing creations in range. Each activity is filtered by its owning user (landing author); repository eligibility uses repositories.user_id, with org-owned repositories human. Separate aggregates prevent join multiplication; ties use owner/name/id.
func (q *Queries) AnalyticsTopRepos(ctx context.Context, arg AnalyticsTopReposParams) ([]AnalyticsTopReposRow, error) {
	rows, err := q.db.Query(ctx, analyticsTopRepos, arg.IncludeSynthetic, arg.RangeStart, arg.RangeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsTopReposRow{}
	for rows.Next() {
		var i AnalyticsTopReposRow
		if err := rows.Scan(
			&i.Owner,
			&i.Name,
			&i.Workspaces,
			&i.AgentSessions,
			&i.LandingRequests,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsUsers = `-- name: AnalyticsUsers :one

WITH active_users AS (
 SELECT w.user_id FROM workspaces w WHERE w.last_activity_at >= $2::timestamptz AND w.last_activity_at < $3::timestamptz
 UNION SELECT a.user_id FROM agent_sessions a WHERE a.created_at >= $2::timestamptz AND a.created_at < $3::timestamptz
 UNION SELECT l.author_id FROM landing_requests l WHERE l.created_at >= $2::timestamptz AND l.created_at < $3::timestamptz
 UNION SELECT a.user_id FROM auth_sessions a WHERE a.created_at >= $2::timestamptz AND a.created_at < $3::timestamptz
)
SELECT count(*)::bigint AS total,
 count(*) FILTER (WHERE NOT u.is_synthetic)::bigint AS human,
 count(*) FILTER (WHERE u.is_synthetic)::bigint AS synthetic,
 count(*) FILTER (WHERE ($1::boolean OR NOT u.is_synthetic) AND u.created_at >= $2::timestamptz AND u.created_at < $3::timestamptz)::bigint AS new_in_range,
 count(*) FILTER (WHERE ($1::boolean OR NOT u.is_synthetic) AND EXISTS (SELECT 1 FROM active_users a WHERE a.user_id=u.id))::bigint AS active_in_range
FROM users u
`

type AnalyticsUsersParams struct {
	IncludeSynthetic bool      `json:"include_synthetic"`
	RangeStart       time.Time `json:"range_start"`
	RangeEnd         time.Time `json:"range_end"`
}

type AnalyticsUsersRow struct {
	Total         int64 `json:"total"`
	Human         int64 `json:"human"`
	Synthetic     int64 `json:"synthetic"`
	NewInRange    int64 `json:"new_in_range"`
	ActiveInRange int64 `json:"active_in_range"`
}

// Product queries extracted from the transitional Plue source.
// Total/human/synthetic are all-time inventory (including synthetic users). New and active users respect the filter; active is the distinct union of workspace activity, agent creation, landing creation, and auth-session creation.
func (q *Queries) AnalyticsUsers(ctx context.Context, arg AnalyticsUsersParams) (AnalyticsUsersRow, error) {
	row := q.db.QueryRow(ctx, analyticsUsers, arg.IncludeSynthetic, arg.RangeStart, arg.RangeEnd)
	var i AnalyticsUsersRow
	err := row.Scan(
		&i.Total,
		&i.Human,
		&i.Synthetic,
		&i.NewInRange,
		&i.ActiveInRange,
	)
	return i, err
}

const analyticsWorkspaceBoot = `-- name: AnalyticsWorkspaceBoot :one
SELECT coalesce(percentile_cont(0.5) WITHIN GROUP (ORDER BY extract(epoch FROM (w.started_at-w.created_at))),0)::float8 AS boot_p50_seconds,
 coalesce(percentile_cont(0.95) WITHIN GROUP (ORDER BY extract(epoch FROM (w.started_at-w.created_at))),0)::float8 AS boot_p95_seconds
 FROM workspaces w JOIN users u ON u.id=w.user_id WHERE w.created_at >= $1::timestamptz AND w.created_at < $2::timestamptz AND ($3::boolean OR NOT u.is_synthetic) AND w.started_at IS NOT NULL
`

type AnalyticsWorkspaceBootParams struct {
	RangeStart       time.Time `json:"range_start"`
	RangeEnd         time.Time `json:"range_end"`
	IncludeSynthetic bool      `json:"include_synthetic"`
}

type AnalyticsWorkspaceBootRow struct {
	BootP50Seconds float64 `json:"boot_p50_seconds"`
	BootP95Seconds float64 `json:"boot_p95_seconds"`
}

// Boot percentiles are started_at minus created_at for workspaces created in range with started_at present. Empty populations return zero seconds.
func (q *Queries) AnalyticsWorkspaceBoot(ctx context.Context, arg AnalyticsWorkspaceBootParams) (AnalyticsWorkspaceBootRow, error) {
	row := q.db.QueryRow(ctx, analyticsWorkspaceBoot, arg.RangeStart, arg.RangeEnd, arg.IncludeSynthetic)
	var i AnalyticsWorkspaceBootRow
	err := row.Scan(&i.BootP50Seconds, &i.BootP95Seconds)
	return i, err
}

const analyticsWorkspaceFailures = `-- name: AnalyticsWorkspaceFailures :many
SELECT coalesce(w.failure_code,'')::text AS code, coalesce(w.failure_message,'')::text AS message, count(*)::bigint AS count FROM workspaces w JOIN users u ON u.id=w.user_id WHERE w.created_at >= $1::timestamptz AND w.created_at < $2::timestamptz AND ($3::boolean OR NOT u.is_synthetic) AND w.status='failed' GROUP BY w.failure_code,w.failure_message ORDER BY count DESC,code,message
`

type AnalyticsWorkspaceFailuresParams struct {
	RangeStart       time.Time `json:"range_start"`
	RangeEnd         time.Time `json:"range_end"`
	IncludeSynthetic bool      `json:"include_synthetic"`
}

type AnalyticsWorkspaceFailuresRow struct {
	Code    string `json:"code"`
	Message string `json:"message"`
	Count   int64  `json:"count"`
}

// Failure code/message counts for failed workspaces created in range, filtered by workspace owner.
func (q *Queries) AnalyticsWorkspaceFailures(ctx context.Context, arg AnalyticsWorkspaceFailuresParams) ([]AnalyticsWorkspaceFailuresRow, error) {
	rows, err := q.db.Query(ctx, analyticsWorkspaceFailures, arg.RangeStart, arg.RangeEnd, arg.IncludeSynthetic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsWorkspaceFailuresRow{}
	for rows.Next() {
		var i AnalyticsWorkspaceFailuresRow
		if err := rows.Scan(&i.Code, &i.Message, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsWorkspacesActive = `-- name: AnalyticsWorkspacesActive :one
SELECT count(*)::bigint FROM workspaces w JOIN users u ON u.id=w.user_id WHERE w.status='running' AND w.deleted_at IS NULL AND ($1::boolean OR NOT u.is_synthetic)
`

// Active now is non-deleted running workspaces across all creation dates, filtered by workspace owner.
func (q *Queries) AnalyticsWorkspacesActive(ctx context.Context, includeSynthetic bool) (int64, error) {
	row := q.db.QueryRow(ctx, analyticsWorkspacesActive, includeSynthetic)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const analyticsWorkspacesByDay = `-- name: AnalyticsWorkspacesByDay :many
WITH days AS (
 SELECT generate_series($1::timestamptz AT TIME ZONE 'UTC', date_trunc('day', $2::timestamptz AT TIME ZONE 'UTC'), interval '1 day') AS day
), counts AS (
 SELECT (w.created_at AT TIME ZONE 'UTC')::date AS day, count(*)::bigint AS count,
 count(*) FILTER (WHERE u.is_synthetic)::bigint AS synthetic_count
 FROM workspaces w JOIN users u ON u.id=w.user_id WHERE w.created_at >= $1::timestamptz AND w.created_at < $2::timestamptz AND ($3::boolean OR NOT u.is_synthetic) GROUP BY 1
)
SELECT to_char(d.day,'YYYY-MM-DD')::text AS day, coalesce(c.count,0)::bigint AS count,
 coalesce(c.synthetic_count,0)::bigint AS synthetic_count
FROM days d LEFT JOIN counts c ON c.day=d.day::date ORDER BY d.day
`

type AnalyticsWorkspacesByDayParams struct {
	RangeStart       time.Time `json:"range_start"`
	RangeEnd         time.Time `json:"range_end"`
	IncludeSynthetic bool      `json:"include_synthetic"`
}

type AnalyticsWorkspacesByDayRow struct {
	Day            string `json:"day"`
	Count          int64  `json:"count"`
	SyntheticCount int64  `json:"synthetic_count"`
}

// UTC day series with zeros. Count is all included creations; synthetic_count is zero unless synthetic rows are included. Ownership uses workspaces.user_id.
func (q *Queries) AnalyticsWorkspacesByDay(ctx context.Context, arg AnalyticsWorkspacesByDayParams) ([]AnalyticsWorkspacesByDayRow, error) {
	rows, err := q.db.Query(ctx, analyticsWorkspacesByDay, arg.RangeStart, arg.RangeEnd, arg.IncludeSynthetic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsWorkspacesByDayRow{}
	for rows.Next() {
		var i AnalyticsWorkspacesByDayRow
		if err := rows.Scan(&i.Day, &i.Count, &i.SyntheticCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsWorkspacesByKindStatus = `-- name: AnalyticsWorkspacesByKindStatus :many
SELECT w.kind, w.status, count(*)::bigint AS count FROM workspaces w JOIN users u ON u.id=w.user_id WHERE w.created_at >= $1::timestamptz AND w.created_at < $2::timestamptz AND ($3::boolean OR NOT u.is_synthetic) GROUP BY w.kind,w.status ORDER BY w.kind,w.status
`

type AnalyticsWorkspacesByKindStatusParams struct {
	RangeStart       time.Time `json:"range_start"`
	RangeEnd         time.Time `json:"range_end"`
	IncludeSynthetic bool      `json:"include_synthetic"`
}

type AnalyticsWorkspacesByKindStatusRow struct {
	Kind   string `json:"kind"`
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

// Current kind/status of workspaces created in range, filtered by workspace owning user_id.
func (q *Queries) AnalyticsWorkspacesByKindStatus(ctx context.Context, arg AnalyticsWorkspacesByKindStatusParams) ([]AnalyticsWorkspacesByKindStatusRow, error) {
	rows, err := q.db.Query(ctx, analyticsWorkspacesByKindStatus, arg.RangeStart, arg.RangeEnd, arg.IncludeSynthetic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsWorkspacesByKindStatusRow{}
	for rows.Next() {
		var i AnalyticsWorkspacesByKindStatusRow
		if err := rows.Scan(&i.Kind, &i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
