// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conflicts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteConflictsByChangeID = `-- name: DeleteConflictsByChangeID :execrows
DELETE FROM conflicts
WHERE repository_id = $1
  AND change_id = $2
`

type DeleteConflictsByChangeIDParams struct {
	RepositoryID int64  `json:"repository_id"`
	ChangeID     string `json:"change_id"`
}

func (q *Queries) DeleteConflictsByChangeID(ctx context.Context, arg DeleteConflictsByChangeIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConflictsByChangeID, arg.RepositoryID, arg.ChangeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConflictByPath = `-- name: GetConflictByPath :one
SELECT id, repository_id, change_id, file_path, conflict_type, resolved, resolved_by, resolution_method, resolved_at, created_at, updated_at
FROM conflicts
WHERE repository_id = $1
  AND change_id = $2
  AND file_path = $3
`

type GetConflictByPathParams struct {
	RepositoryID int64  `json:"repository_id"`
	ChangeID     string `json:"change_id"`
	FilePath     string `json:"file_path"`
}

func (q *Queries) GetConflictByPath(ctx context.Context, arg GetConflictByPathParams) (Conflict, error) {
	row := q.db.QueryRow(ctx, getConflictByPath, arg.RepositoryID, arg.ChangeID, arg.FilePath)
	var i Conflict
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.ChangeID,
		&i.FilePath,
		&i.ConflictType,
		&i.Resolved,
		&i.ResolvedBy,
		&i.ResolutionMethod,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConflictsByChangeID = `-- name: ListConflictsByChangeID :many
SELECT id, repository_id, change_id, file_path, conflict_type, resolved, resolved_by, resolution_method, resolved_at, created_at, updated_at
FROM conflicts
WHERE repository_id = $1
  AND change_id = $2
ORDER BY file_path ASC
LIMIT $4
OFFSET $3
`

type ListConflictsByChangeIDParams struct {
	RepositoryID int64  `json:"repository_id"`
	ChangeID     string `json:"change_id"`
	PageOffset   int32  `json:"page_offset"`
	PageSize     int32  `json:"page_size"`
}

func (q *Queries) ListConflictsByChangeID(ctx context.Context, arg ListConflictsByChangeIDParams) ([]Conflict, error) {
	rows, err := q.db.Query(ctx, listConflictsByChangeID,
		arg.RepositoryID,
		arg.ChangeID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conflict{}
	for rows.Next() {
		var i Conflict
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.ChangeID,
			&i.FilePath,
			&i.ConflictType,
			&i.Resolved,
			&i.ResolvedBy,
			&i.ResolutionMethod,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConflictResolved = `-- name: MarkConflictResolved :execrows
UPDATE conflicts
SET resolved = TRUE,
    resolved_by = $4,
    resolution_method = $5,
    resolved_at = NOW(),
    updated_at = NOW()
WHERE repository_id = $1
  AND change_id = $2
  AND file_path = $3
`

type MarkConflictResolvedParams struct {
	RepositoryID     int64       `json:"repository_id"`
	ChangeID         string      `json:"change_id"`
	FilePath         string      `json:"file_path"`
	ResolvedBy       pgtype.Int8 `json:"resolved_by"`
	ResolutionMethod string      `json:"resolution_method"`
}

func (q *Queries) MarkConflictResolved(ctx context.Context, arg MarkConflictResolvedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markConflictResolved,
		arg.RepositoryID,
		arg.ChangeID,
		arg.FilePath,
		arg.ResolvedBy,
		arg.ResolutionMethod,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertConflict = `-- name: UpsertConflict :one
INSERT INTO conflicts (repository_id, change_id, file_path, conflict_type)
VALUES ($1, $2, $3, $4)
ON CONFLICT (repository_id, change_id, file_path)
DO UPDATE SET
    conflict_type = EXCLUDED.conflict_type,
    resolved = FALSE,
    resolved_by = NULL,
    resolution_method = '',
    resolved_at = NULL,
    updated_at = NOW()
RETURNING id, repository_id, change_id, file_path, conflict_type, resolved, resolved_by, resolution_method, resolved_at, created_at, updated_at
`

type UpsertConflictParams struct {
	RepositoryID int64  `json:"repository_id"`
	ChangeID     string `json:"change_id"`
	FilePath     string `json:"file_path"`
	ConflictType string `json:"conflict_type"`
}

func (q *Queries) UpsertConflict(ctx context.Context, arg UpsertConflictParams) (Conflict, error) {
	row := q.db.QueryRow(ctx, upsertConflict,
		arg.RepositoryID,
		arg.ChangeID,
		arg.FilePath,
		arg.ConflictType,
	)
	var i Conflict
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.ChangeID,
		&i.FilePath,
		&i.ConflictType,
		&i.Resolved,
		&i.ResolvedBy,
		&i.ResolutionMethod,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
