// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: linear_integrations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeLinearSyncOpRetry = `-- name: CompleteLinearSyncOpRetry :one
UPDATE linear_sync_ops
SET status = $1, error_message = $2
WHERE id = $3 AND status = 'pending'
RETURNING id, integration_id, run_id, retry_of_id, source, target, entity, entity_id, action, status, error_message, payload, created_at
`

type CompleteLinearSyncOpRetryParams struct {
	Status       string `json:"status"`
	ErrorMessage string `json:"error_message"`
	ID           int64  `json:"id"`
}

func (q *Queries) CompleteLinearSyncOpRetry(ctx context.Context, arg CompleteLinearSyncOpRetryParams) (LinearSyncOp, error) {
	row := q.db.QueryRow(ctx, completeLinearSyncOpRetry, arg.Status, arg.ErrorMessage, arg.ID)
	var i LinearSyncOp
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.RunID,
		&i.RetryOfID,
		&i.Source,
		&i.Target,
		&i.Entity,
		&i.EntityID,
		&i.Action,
		&i.Status,
		&i.ErrorMessage,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const createLinearCommentMap = `-- name: CreateLinearCommentMap :one
INSERT INTO linear_comment_map (issue_map_id, jjhub_comment_id, linear_comment_id)
VALUES ($1, $2, $3)
RETURNING id, issue_map_id, jjhub_comment_id, linear_comment_id, created_at
`

type CreateLinearCommentMapParams struct {
	IssueMapID      int64  `json:"issue_map_id"`
	JjhubCommentID  int64  `json:"jjhub_comment_id"`
	LinearCommentID string `json:"linear_comment_id"`
}

func (q *Queries) CreateLinearCommentMap(ctx context.Context, arg CreateLinearCommentMapParams) (LinearCommentMap, error) {
	row := q.db.QueryRow(ctx, createLinearCommentMap, arg.IssueMapID, arg.JjhubCommentID, arg.LinearCommentID)
	var i LinearCommentMap
	err := row.Scan(
		&i.ID,
		&i.IssueMapID,
		&i.JjhubCommentID,
		&i.LinearCommentID,
		&i.CreatedAt,
	)
	return i, err
}

const createLinearIntegration = `-- name: CreateLinearIntegration :one
INSERT INTO linear_integrations (
    user_id, org_id, linear_team_id, linear_team_name, linear_team_key,
    access_token_encrypted, refresh_token_encrypted, token_expires_at,
    webhook_key, webhook_secret, jjhub_repo_id, jjhub_repo_owner, jjhub_repo_name,
    linear_actor_id, linear_actor_name, linear_actor_email
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, user_id, org_id, linear_team_id, linear_team_name, linear_team_key, access_token_encrypted, refresh_token_encrypted, token_expires_at, webhook_key, webhook_secret, jjhub_repo_id, jjhub_repo_owner, jjhub_repo_name, linear_actor_id, linear_actor_name, linear_actor_email, is_active, last_sync_at, created_at, updated_at
`

type CreateLinearIntegrationParams struct {
	UserID                int64              `json:"user_id"`
	OrgID                 pgtype.Int8        `json:"org_id"`
	LinearTeamID          string             `json:"linear_team_id"`
	LinearTeamName        string             `json:"linear_team_name"`
	LinearTeamKey         string             `json:"linear_team_key"`
	AccessTokenEncrypted  []byte             `json:"access_token_encrypted"`
	RefreshTokenEncrypted []byte             `json:"refresh_token_encrypted"`
	TokenExpiresAt        pgtype.Timestamptz `json:"token_expires_at"`
	WebhookKey            string             `json:"webhook_key"`
	WebhookSecret         string             `json:"webhook_secret"`
	JjhubRepoID           int64              `json:"jjhub_repo_id"`
	JjhubRepoOwner        string             `json:"jjhub_repo_owner"`
	JjhubRepoName         string             `json:"jjhub_repo_name"`
	LinearActorID         string             `json:"linear_actor_id"`
	LinearActorName       string             `json:"linear_actor_name"`
	LinearActorEmail      string             `json:"linear_actor_email"`
}

func (q *Queries) CreateLinearIntegration(ctx context.Context, arg CreateLinearIntegrationParams) (LinearIntegration, error) {
	row := q.db.QueryRow(ctx, createLinearIntegration,
		arg.UserID,
		arg.OrgID,
		arg.LinearTeamID,
		arg.LinearTeamName,
		arg.LinearTeamKey,
		arg.AccessTokenEncrypted,
		arg.RefreshTokenEncrypted,
		arg.TokenExpiresAt,
		arg.WebhookKey,
		arg.WebhookSecret,
		arg.JjhubRepoID,
		arg.JjhubRepoOwner,
		arg.JjhubRepoName,
		arg.LinearActorID,
		arg.LinearActorName,
		arg.LinearActorEmail,
	)
	var i LinearIntegration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.LinearTeamID,
		&i.LinearTeamName,
		&i.LinearTeamKey,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.TokenExpiresAt,
		&i.WebhookKey,
		&i.WebhookSecret,
		&i.JjhubRepoID,
		&i.JjhubRepoOwner,
		&i.JjhubRepoName,
		&i.LinearActorID,
		&i.LinearActorName,
		&i.LinearActorEmail,
		&i.IsActive,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLinearIssueMap = `-- name: CreateLinearIssueMap :one
INSERT INTO linear_issue_map (
    integration_id, jjhub_issue_id, jjhub_issue_number,
    linear_issue_id, linear_identifier
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, integration_id, jjhub_issue_id, jjhub_issue_number, linear_issue_id, linear_identifier, created_at, updated_at
`

type CreateLinearIssueMapParams struct {
	IntegrationID    int64  `json:"integration_id"`
	JjhubIssueID     int64  `json:"jjhub_issue_id"`
	JjhubIssueNumber int64  `json:"jjhub_issue_number"`
	LinearIssueID    string `json:"linear_issue_id"`
	LinearIdentifier string `json:"linear_identifier"`
}

func (q *Queries) CreateLinearIssueMap(ctx context.Context, arg CreateLinearIssueMapParams) (LinearIssueMap, error) {
	row := q.db.QueryRow(ctx, createLinearIssueMap,
		arg.IntegrationID,
		arg.JjhubIssueID,
		arg.JjhubIssueNumber,
		arg.LinearIssueID,
		arg.LinearIdentifier,
	)
	var i LinearIssueMap
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.JjhubIssueID,
		&i.JjhubIssueNumber,
		&i.LinearIssueID,
		&i.LinearIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLinearSyncOpRetry = `-- name: CreateLinearSyncOpRetry :one
INSERT INTO linear_sync_ops (
    integration_id, retry_of_id, source, target, entity, entity_id,
    action, status, error_message, payload
)
SELECT original.integration_id, original.id, original.source, original.target,
       original.entity, original.entity_id, original.action, 'pending', '', original.payload
FROM linear_sync_ops AS original
WHERE original.id = $1
  AND original.integration_id = $2
  AND original.status = 'failed'
RETURNING id, integration_id, run_id, retry_of_id, source, target, entity, entity_id, action, status, error_message, payload, created_at
`

type CreateLinearSyncOpRetryParams struct {
	OpID          int64 `json:"op_id"`
	IntegrationID int64 `json:"integration_id"`
}

func (q *Queries) CreateLinearSyncOpRetry(ctx context.Context, arg CreateLinearSyncOpRetryParams) (LinearSyncOp, error) {
	row := q.db.QueryRow(ctx, createLinearSyncOpRetry, arg.OpID, arg.IntegrationID)
	var i LinearSyncOp
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.RunID,
		&i.RetryOfID,
		&i.Source,
		&i.Target,
		&i.Entity,
		&i.EntityID,
		&i.Action,
		&i.Status,
		&i.ErrorMessage,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const createLinearSyncRun = `-- name: CreateLinearSyncRun :one
INSERT INTO linear_sync_runs (integration_id)
VALUES ($1)
RETURNING id, integration_id, state, issues_done, issues_total, issues_failed, comments_done, comments_total, comments_failed, started_at, finished_at, created_at
`

func (q *Queries) CreateLinearSyncRun(ctx context.Context, integrationID int64) (LinearSyncRun, error) {
	row := q.db.QueryRow(ctx, createLinearSyncRun, integrationID)
	var i LinearSyncRun
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.State,
		&i.IssuesDone,
		&i.IssuesTotal,
		&i.IssuesFailed,
		&i.CommentsDone,
		&i.CommentsTotal,
		&i.CommentsFailed,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLinearCommentMapByLinearComment = `-- name: DeleteLinearCommentMapByLinearComment :exec
DELETE FROM linear_comment_map
WHERE issue_map_id = $1 AND linear_comment_id = $2
`

type DeleteLinearCommentMapByLinearCommentParams struct {
	IssueMapID      int64  `json:"issue_map_id"`
	LinearCommentID string `json:"linear_comment_id"`
}

func (q *Queries) DeleteLinearCommentMapByLinearComment(ctx context.Context, arg DeleteLinearCommentMapByLinearCommentParams) error {
	_, err := q.db.Exec(ctx, deleteLinearCommentMapByLinearComment, arg.IssueMapID, arg.LinearCommentID)
	return err
}

const deleteLinearCommentMapBySmithersComment = `-- name: DeleteLinearCommentMapBySmithersComment :exec
DELETE FROM linear_comment_map
WHERE issue_map_id = $1 AND jjhub_comment_id = $2
`

type DeleteLinearCommentMapBySmithersCommentParams struct {
	IssueMapID     int64 `json:"issue_map_id"`
	JjhubCommentID int64 `json:"jjhub_comment_id"`
}

func (q *Queries) DeleteLinearCommentMapBySmithersComment(ctx context.Context, arg DeleteLinearCommentMapBySmithersCommentParams) error {
	_, err := q.db.Exec(ctx, deleteLinearCommentMapBySmithersComment, arg.IssueMapID, arg.JjhubCommentID)
	return err
}

const deleteLinearIntegration = `-- name: DeleteLinearIntegration :exec
DELETE FROM linear_integrations WHERE id = $1 AND user_id = $2
`

type DeleteLinearIntegrationParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteLinearIntegration(ctx context.Context, arg DeleteLinearIntegrationParams) error {
	_, err := q.db.Exec(ctx, deleteLinearIntegration, arg.ID, arg.UserID)
	return err
}

const deleteLinearIssueMapByID = `-- name: DeleteLinearIssueMapByID :execrows
DELETE FROM linear_issue_map WHERE id = $1
`

func (q *Queries) DeleteLinearIssueMapByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLinearIssueMapByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failLinearSyncRun = `-- name: FailLinearSyncRun :one
UPDATE linear_sync_runs
SET state = 'failed', finished_at = NOW()
WHERE id = $1 AND state IN ('pending', 'running')
RETURNING id, integration_id, state, issues_done, issues_total, issues_failed, comments_done, comments_total, comments_failed, started_at, finished_at, created_at
`

func (q *Queries) FailLinearSyncRun(ctx context.Context, id int64) (LinearSyncRun, error) {
	row := q.db.QueryRow(ctx, failLinearSyncRun, id)
	var i LinearSyncRun
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.State,
		&i.IssuesDone,
		&i.IssuesTotal,
		&i.IssuesFailed,
		&i.CommentsDone,
		&i.CommentsTotal,
		&i.CommentsFailed,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const finishLinearSyncRun = `-- name: FinishLinearSyncRun :one
UPDATE linear_sync_runs
SET state = CASE
        WHEN issues_failed > 0 OR comments_failed > 0 THEN 'failed'
        ELSE 'completed'
    END,
    finished_at = NOW()
WHERE id = $1 AND state = 'running'
RETURNING id, integration_id, state, issues_done, issues_total, issues_failed, comments_done, comments_total, comments_failed, started_at, finished_at, created_at
`

func (q *Queries) FinishLinearSyncRun(ctx context.Context, id int64) (LinearSyncRun, error) {
	row := q.db.QueryRow(ctx, finishLinearSyncRun, id)
	var i LinearSyncRun
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.State,
		&i.IssuesDone,
		&i.IssuesTotal,
		&i.IssuesFailed,
		&i.CommentsDone,
		&i.CommentsTotal,
		&i.CommentsFailed,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLinearCommentMapByLinearComment = `-- name: GetLinearCommentMapByLinearComment :one
SELECT id, issue_map_id, jjhub_comment_id, linear_comment_id, created_at FROM linear_comment_map
WHERE issue_map_id = $1 AND linear_comment_id = $2
`

type GetLinearCommentMapByLinearCommentParams struct {
	IssueMapID      int64  `json:"issue_map_id"`
	LinearCommentID string `json:"linear_comment_id"`
}

func (q *Queries) GetLinearCommentMapByLinearComment(ctx context.Context, arg GetLinearCommentMapByLinearCommentParams) (LinearCommentMap, error) {
	row := q.db.QueryRow(ctx, getLinearCommentMapByLinearComment, arg.IssueMapID, arg.LinearCommentID)
	var i LinearCommentMap
	err := row.Scan(
		&i.ID,
		&i.IssueMapID,
		&i.JjhubCommentID,
		&i.LinearCommentID,
		&i.CreatedAt,
	)
	return i, err
}

const getLinearCommentMapBySmithersComment = `-- name: GetLinearCommentMapBySmithersComment :one
SELECT id, issue_map_id, jjhub_comment_id, linear_comment_id, created_at FROM linear_comment_map
WHERE issue_map_id = $1 AND jjhub_comment_id = $2
`

type GetLinearCommentMapBySmithersCommentParams struct {
	IssueMapID     int64 `json:"issue_map_id"`
	JjhubCommentID int64 `json:"jjhub_comment_id"`
}

func (q *Queries) GetLinearCommentMapBySmithersComment(ctx context.Context, arg GetLinearCommentMapBySmithersCommentParams) (LinearCommentMap, error) {
	row := q.db.QueryRow(ctx, getLinearCommentMapBySmithersComment, arg.IssueMapID, arg.JjhubCommentID)
	var i LinearCommentMap
	err := row.Scan(
		&i.ID,
		&i.IssueMapID,
		&i.JjhubCommentID,
		&i.LinearCommentID,
		&i.CreatedAt,
	)
	return i, err
}

const getLinearCommentMapBySmithersCommentID = `-- name: GetLinearCommentMapBySmithersCommentID :one
SELECT lcm.id, lcm.issue_map_id, lcm.jjhub_comment_id, lcm.linear_comment_id, lcm.created_at
FROM linear_comment_map lcm
JOIN linear_issue_map lim ON lim.id = lcm.issue_map_id
WHERE lim.integration_id = $1
  AND lcm.jjhub_comment_id = $2
`

type GetLinearCommentMapBySmithersCommentIDParams struct {
	IntegrationID  int64 `json:"integration_id"`
	JjhubCommentID int64 `json:"jjhub_comment_id"`
}

func (q *Queries) GetLinearCommentMapBySmithersCommentID(ctx context.Context, arg GetLinearCommentMapBySmithersCommentIDParams) (LinearCommentMap, error) {
	row := q.db.QueryRow(ctx, getLinearCommentMapBySmithersCommentID, arg.IntegrationID, arg.JjhubCommentID)
	var i LinearCommentMap
	err := row.Scan(
		&i.ID,
		&i.IssueMapID,
		&i.JjhubCommentID,
		&i.LinearCommentID,
		&i.CreatedAt,
	)
	return i, err
}

const getLinearIntegration = `-- name: GetLinearIntegration :one
SELECT id, user_id, org_id, linear_team_id, linear_team_name, linear_team_key, access_token_encrypted, refresh_token_encrypted, token_expires_at, webhook_key, webhook_secret, jjhub_repo_id, jjhub_repo_owner, jjhub_repo_name, linear_actor_id, linear_actor_name, linear_actor_email, is_active, last_sync_at, created_at, updated_at FROM linear_integrations WHERE id = $1
`

func (q *Queries) GetLinearIntegration(ctx context.Context, id int64) (LinearIntegration, error) {
	row := q.db.QueryRow(ctx, getLinearIntegration, id)
	var i LinearIntegration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.LinearTeamID,
		&i.LinearTeamName,
		&i.LinearTeamKey,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.TokenExpiresAt,
		&i.WebhookKey,
		&i.WebhookSecret,
		&i.JjhubRepoID,
		&i.JjhubRepoOwner,
		&i.JjhubRepoName,
		&i.LinearActorID,
		&i.LinearActorName,
		&i.LinearActorEmail,
		&i.IsActive,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinearIntegrationByLinearTeamID = `-- name: GetLinearIntegrationByLinearTeamID :one
SELECT id, user_id, org_id, linear_team_id, linear_team_name, linear_team_key, access_token_encrypted, refresh_token_encrypted, token_expires_at, webhook_key, webhook_secret, jjhub_repo_id, jjhub_repo_owner, jjhub_repo_name, linear_actor_id, linear_actor_name, linear_actor_email, is_active, last_sync_at, created_at, updated_at FROM linear_integrations
WHERE linear_team_id = $1 AND is_active = TRUE
LIMIT 1
`

func (q *Queries) GetLinearIntegrationByLinearTeamID(ctx context.Context, linearTeamID string) (LinearIntegration, error) {
	row := q.db.QueryRow(ctx, getLinearIntegrationByLinearTeamID, linearTeamID)
	var i LinearIntegration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.LinearTeamID,
		&i.LinearTeamName,
		&i.LinearTeamKey,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.TokenExpiresAt,
		&i.WebhookKey,
		&i.WebhookSecret,
		&i.JjhubRepoID,
		&i.JjhubRepoOwner,
		&i.JjhubRepoName,
		&i.LinearActorID,
		&i.LinearActorName,
		&i.LinearActorEmail,
		&i.IsActive,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinearIntegrationByUserAndID = `-- name: GetLinearIntegrationByUserAndID :one
SELECT id, user_id, org_id, linear_team_id, linear_team_name, linear_team_key, access_token_encrypted, refresh_token_encrypted, token_expires_at, webhook_key, webhook_secret, jjhub_repo_id, jjhub_repo_owner, jjhub_repo_name, linear_actor_id, linear_actor_name, linear_actor_email, is_active, last_sync_at, created_at, updated_at FROM linear_integrations WHERE id = $1 AND user_id = $2
`

type GetLinearIntegrationByUserAndIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetLinearIntegrationByUserAndID(ctx context.Context, arg GetLinearIntegrationByUserAndIDParams) (LinearIntegration, error) {
	row := q.db.QueryRow(ctx, getLinearIntegrationByUserAndID, arg.ID, arg.UserID)
	var i LinearIntegration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.LinearTeamID,
		&i.LinearTeamName,
		&i.LinearTeamKey,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.TokenExpiresAt,
		&i.WebhookKey,
		&i.WebhookSecret,
		&i.JjhubRepoID,
		&i.JjhubRepoOwner,
		&i.JjhubRepoName,
		&i.LinearActorID,
		&i.LinearActorName,
		&i.LinearActorEmail,
		&i.IsActive,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinearIntegrationByWebhookKey = `-- name: GetLinearIntegrationByWebhookKey :one
SELECT id, user_id, org_id, linear_team_id, linear_team_name, linear_team_key, access_token_encrypted, refresh_token_encrypted, token_expires_at, webhook_key, webhook_secret, jjhub_repo_id, jjhub_repo_owner, jjhub_repo_name, linear_actor_id, linear_actor_name, linear_actor_email, is_active, last_sync_at, created_at, updated_at FROM linear_integrations
WHERE webhook_key = $1 AND is_active = TRUE
`

func (q *Queries) GetLinearIntegrationByWebhookKey(ctx context.Context, webhookKey string) (LinearIntegration, error) {
	row := q.db.QueryRow(ctx, getLinearIntegrationByWebhookKey, webhookKey)
	var i LinearIntegration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.LinearTeamID,
		&i.LinearTeamName,
		&i.LinearTeamKey,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.TokenExpiresAt,
		&i.WebhookKey,
		&i.WebhookSecret,
		&i.JjhubRepoID,
		&i.JjhubRepoOwner,
		&i.JjhubRepoName,
		&i.LinearActorID,
		&i.LinearActorName,
		&i.LinearActorEmail,
		&i.IsActive,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinearIssueMapByLinearIssue = `-- name: GetLinearIssueMapByLinearIssue :one
SELECT id, integration_id, jjhub_issue_id, jjhub_issue_number, linear_issue_id, linear_identifier, created_at, updated_at FROM linear_issue_map
WHERE integration_id = $1 AND linear_issue_id = $2
`

type GetLinearIssueMapByLinearIssueParams struct {
	IntegrationID int64  `json:"integration_id"`
	LinearIssueID string `json:"linear_issue_id"`
}

func (q *Queries) GetLinearIssueMapByLinearIssue(ctx context.Context, arg GetLinearIssueMapByLinearIssueParams) (LinearIssueMap, error) {
	row := q.db.QueryRow(ctx, getLinearIssueMapByLinearIssue, arg.IntegrationID, arg.LinearIssueID)
	var i LinearIssueMap
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.JjhubIssueID,
		&i.JjhubIssueNumber,
		&i.LinearIssueID,
		&i.LinearIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinearIssueMapBySmithersCommentID = `-- name: GetLinearIssueMapBySmithersCommentID :one
SELECT lim.id, lim.integration_id, lim.jjhub_issue_id, lim.jjhub_issue_number, lim.linear_issue_id, lim.linear_identifier, lim.created_at, lim.updated_at
FROM linear_issue_map lim
JOIN linear_comment_map lcm ON lcm.issue_map_id = lim.id
WHERE lim.integration_id = $1
  AND lcm.jjhub_comment_id = $2
`

type GetLinearIssueMapBySmithersCommentIDParams struct {
	IntegrationID  int64 `json:"integration_id"`
	JjhubCommentID int64 `json:"jjhub_comment_id"`
}

func (q *Queries) GetLinearIssueMapBySmithersCommentID(ctx context.Context, arg GetLinearIssueMapBySmithersCommentIDParams) (LinearIssueMap, error) {
	row := q.db.QueryRow(ctx, getLinearIssueMapBySmithersCommentID, arg.IntegrationID, arg.JjhubCommentID)
	var i LinearIssueMap
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.JjhubIssueID,
		&i.JjhubIssueNumber,
		&i.LinearIssueID,
		&i.LinearIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinearIssueMapBySmithersIssue = `-- name: GetLinearIssueMapBySmithersIssue :one
SELECT id, integration_id, jjhub_issue_id, jjhub_issue_number, linear_issue_id, linear_identifier, created_at, updated_at FROM linear_issue_map
WHERE integration_id = $1 AND jjhub_issue_id = $2
`

type GetLinearIssueMapBySmithersIssueParams struct {
	IntegrationID int64 `json:"integration_id"`
	JjhubIssueID  int64 `json:"jjhub_issue_id"`
}

func (q *Queries) GetLinearIssueMapBySmithersIssue(ctx context.Context, arg GetLinearIssueMapBySmithersIssueParams) (LinearIssueMap, error) {
	row := q.db.QueryRow(ctx, getLinearIssueMapBySmithersIssue, arg.IntegrationID, arg.JjhubIssueID)
	var i LinearIssueMap
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.JjhubIssueID,
		&i.JjhubIssueNumber,
		&i.LinearIssueID,
		&i.LinearIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinearIssueMapBySmithersIssueID = `-- name: GetLinearIssueMapBySmithersIssueID :one
SELECT id, integration_id, jjhub_issue_id, jjhub_issue_number, linear_issue_id, linear_identifier, created_at, updated_at FROM linear_issue_map
WHERE jjhub_issue_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLinearIssueMapBySmithersIssueID(ctx context.Context, jjhubIssueID int64) (LinearIssueMap, error) {
	row := q.db.QueryRow(ctx, getLinearIssueMapBySmithersIssueID, jjhubIssueID)
	var i LinearIssueMap
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.JjhubIssueID,
		&i.JjhubIssueNumber,
		&i.LinearIssueID,
		&i.LinearIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinearSyncOp = `-- name: GetLinearSyncOp :one
SELECT id, integration_id, run_id, retry_of_id, source, target, entity, entity_id, action, status, error_message, payload, created_at
FROM linear_sync_ops
WHERE id = $1 AND integration_id = $2
`

type GetLinearSyncOpParams struct {
	ID            int64 `json:"id"`
	IntegrationID int64 `json:"integration_id"`
}

func (q *Queries) GetLinearSyncOp(ctx context.Context, arg GetLinearSyncOpParams) (LinearSyncOp, error) {
	row := q.db.QueryRow(ctx, getLinearSyncOp, arg.ID, arg.IntegrationID)
	var i LinearSyncOp
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.RunID,
		&i.RetryOfID,
		&i.Source,
		&i.Target,
		&i.Entity,
		&i.EntityID,
		&i.Action,
		&i.Status,
		&i.ErrorMessage,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getLinearSyncRun = `-- name: GetLinearSyncRun :one
SELECT id, integration_id, state, issues_done, issues_total, issues_failed, comments_done, comments_total, comments_failed, started_at, finished_at, created_at
FROM linear_sync_runs
WHERE id = $1 AND integration_id = $2
`

type GetLinearSyncRunParams struct {
	ID            int64 `json:"id"`
	IntegrationID int64 `json:"integration_id"`
}

func (q *Queries) GetLinearSyncRun(ctx context.Context, arg GetLinearSyncRunParams) (LinearSyncRun, error) {
	row := q.db.QueryRow(ctx, getLinearSyncRun, arg.ID, arg.IntegrationID)
	var i LinearSyncRun
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.State,
		&i.IssuesDone,
		&i.IssuesTotal,
		&i.IssuesFailed,
		&i.CommentsDone,
		&i.CommentsTotal,
		&i.CommentsFailed,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveLinearIntegrations = `-- name: ListActiveLinearIntegrations :many
SELECT id, user_id, org_id, linear_team_id, linear_team_name, linear_team_key, access_token_encrypted, refresh_token_encrypted, token_expires_at, webhook_key, webhook_secret, jjhub_repo_id, jjhub_repo_owner, jjhub_repo_name, linear_actor_id, linear_actor_name, linear_actor_email, is_active, last_sync_at, created_at, updated_at FROM linear_integrations
WHERE is_active = TRUE
ORDER BY id
`

func (q *Queries) ListActiveLinearIntegrations(ctx context.Context) ([]LinearIntegration, error) {
	rows, err := q.db.Query(ctx, listActiveLinearIntegrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LinearIntegration{}
	for rows.Next() {
		var i LinearIntegration
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.LinearTeamID,
			&i.LinearTeamName,
			&i.LinearTeamKey,
			&i.AccessTokenEncrypted,
			&i.RefreshTokenEncrypted,
			&i.TokenExpiresAt,
			&i.WebhookKey,
			&i.WebhookSecret,
			&i.JjhubRepoID,
			&i.JjhubRepoOwner,
			&i.JjhubRepoName,
			&i.LinearActorID,
			&i.LinearActorName,
			&i.LinearActorEmail,
			&i.IsActive,
			&i.LastSyncAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinearIntegrationsByRepo = `-- name: ListLinearIntegrationsByRepo :many
SELECT id, user_id, org_id, linear_team_id, linear_team_name, linear_team_key, access_token_encrypted, refresh_token_encrypted, token_expires_at, webhook_key, webhook_secret, jjhub_repo_id, jjhub_repo_owner, jjhub_repo_name, linear_actor_id, linear_actor_name, linear_actor_email, is_active, last_sync_at, created_at, updated_at FROM linear_integrations
WHERE jjhub_repo_id = $1 AND is_active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListLinearIntegrationsByRepo(ctx context.Context, jjhubRepoID int64) ([]LinearIntegration, error) {
	rows, err := q.db.Query(ctx, listLinearIntegrationsByRepo, jjhubRepoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LinearIntegration{}
	for rows.Next() {
		var i LinearIntegration
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.LinearTeamID,
			&i.LinearTeamName,
			&i.LinearTeamKey,
			&i.AccessTokenEncrypted,
			&i.RefreshTokenEncrypted,
			&i.TokenExpiresAt,
			&i.WebhookKey,
			&i.WebhookSecret,
			&i.JjhubRepoID,
			&i.JjhubRepoOwner,
			&i.JjhubRepoName,
			&i.LinearActorID,
			&i.LinearActorName,
			&i.LinearActorEmail,
			&i.IsActive,
			&i.LastSyncAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinearIntegrationsByUser = `-- name: ListLinearIntegrationsByUser :many
SELECT id, user_id, org_id, linear_team_id, linear_team_name, linear_team_key, access_token_encrypted, refresh_token_encrypted, token_expires_at, webhook_key, webhook_secret, jjhub_repo_id, jjhub_repo_owner, jjhub_repo_name, linear_actor_id, linear_actor_name, linear_actor_email, is_active, last_sync_at, created_at, updated_at FROM linear_integrations
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListLinearIntegrationsByUser(ctx context.Context, userID int64) ([]LinearIntegration, error) {
	rows, err := q.db.Query(ctx, listLinearIntegrationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LinearIntegration{}
	for rows.Next() {
		var i LinearIntegration
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.LinearTeamID,
			&i.LinearTeamName,
			&i.LinearTeamKey,
			&i.AccessTokenEncrypted,
			&i.RefreshTokenEncrypted,
			&i.TokenExpiresAt,
			&i.WebhookKey,
			&i.WebhookSecret,
			&i.JjhubRepoID,
			&i.JjhubRepoOwner,
			&i.JjhubRepoName,
			&i.LinearActorID,
			&i.LinearActorName,
			&i.LinearActorEmail,
			&i.IsActive,
			&i.LastSyncAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinearIssueMaps = `-- name: ListLinearIssueMaps :many
SELECT id, integration_id, jjhub_issue_id, jjhub_issue_number, linear_issue_id, linear_identifier, created_at, updated_at FROM linear_issue_map
WHERE integration_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListLinearIssueMaps(ctx context.Context, integrationID int64) ([]LinearIssueMap, error) {
	rows, err := q.db.Query(ctx, listLinearIssueMaps, integrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LinearIssueMap{}
	for rows.Next() {
		var i LinearIssueMap
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.JjhubIssueID,
			&i.JjhubIssueNumber,
			&i.LinearIssueID,
			&i.LinearIdentifier,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinearSyncOps = `-- name: ListLinearSyncOps :many
SELECT id, integration_id, run_id, retry_of_id, source, target, entity, entity_id, action, status, error_message, payload, created_at
FROM linear_sync_ops
WHERE integration_id = $1
  AND ($2::text = '' OR status = $2::text)
  AND ($3::timestamptz IS NULL OR created_at >= $3::timestamptz)
  AND (
      $4::timestamptz IS NULL
      OR (created_at, id) < (
          $4::timestamptz,
          $5::bigint
      )
  )
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type ListLinearSyncOpsParams struct {
	IntegrationID   int64              `json:"integration_id"`
	StatusFilter    string             `json:"status_filter"`
	Since           pgtype.Timestamptz `json:"since"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.Int8        `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListLinearSyncOps(ctx context.Context, arg ListLinearSyncOpsParams) ([]LinearSyncOp, error) {
	rows, err := q.db.Query(ctx, listLinearSyncOps,
		arg.IntegrationID,
		arg.StatusFilter,
		arg.Since,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LinearSyncOp{}
	for rows.Next() {
		var i LinearSyncOp
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.RunID,
			&i.RetryOfID,
			&i.Source,
			&i.Target,
			&i.Entity,
			&i.EntityID,
			&i.Action,
			&i.Status,
			&i.ErrorMessage,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logLinearSyncOp = `-- name: LogLinearSyncOp :one
INSERT INTO linear_sync_ops (
    integration_id, run_id, source, target, entity, entity_id, action, status, error_message, payload
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, COALESCE($10::jsonb, '{}'::jsonb)
)
RETURNING id, integration_id, run_id, retry_of_id, source, target, entity, entity_id, action, status, error_message, payload, created_at
`

type LogLinearSyncOpParams struct {
	IntegrationID int64       `json:"integration_id"`
	RunID         pgtype.Int8 `json:"run_id"`
	Source        string      `json:"source"`
	Target        string      `json:"target"`
	Entity        string      `json:"entity"`
	EntityID      string      `json:"entity_id"`
	Action        string      `json:"action"`
	Status        string      `json:"status"`
	ErrorMessage  string      `json:"error_message"`
	Payload       []byte      `json:"payload"`
}

func (q *Queries) LogLinearSyncOp(ctx context.Context, arg LogLinearSyncOpParams) (LinearSyncOp, error) {
	row := q.db.QueryRow(ctx, logLinearSyncOp,
		arg.IntegrationID,
		arg.RunID,
		arg.Source,
		arg.Target,
		arg.Entity,
		arg.EntityID,
		arg.Action,
		arg.Status,
		arg.ErrorMessage,
		arg.Payload,
	)
	var i LinearSyncOp
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.RunID,
		&i.RetryOfID,
		&i.Source,
		&i.Target,
		&i.Entity,
		&i.EntityID,
		&i.Action,
		&i.Status,
		&i.ErrorMessage,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const markLinearSyncRunRunning = `-- name: MarkLinearSyncRunRunning :one
UPDATE linear_sync_runs
SET state = 'running', started_at = NOW()
WHERE id = $1 AND state = 'pending'
RETURNING id, integration_id, state, issues_done, issues_total, issues_failed, comments_done, comments_total, comments_failed, started_at, finished_at, created_at
`

func (q *Queries) MarkLinearSyncRunRunning(ctx context.Context, id int64) (LinearSyncRun, error) {
	row := q.db.QueryRow(ctx, markLinearSyncRunRunning, id)
	var i LinearSyncRun
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.State,
		&i.IssuesDone,
		&i.IssuesTotal,
		&i.IssuesFailed,
		&i.CommentsDone,
		&i.CommentsTotal,
		&i.CommentsFailed,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const recentLinearSyncOpExists = `-- name: RecentLinearSyncOpExists :one
SELECT EXISTS (
    SELECT 1 FROM linear_sync_ops
    WHERE integration_id = $1
      AND entity = $2
      AND entity_id = $3
      AND action = $4
      AND status = 'success'
      AND created_at > NOW() - INTERVAL '5 seconds'
) AS exists
`

type RecentLinearSyncOpExistsParams struct {
	IntegrationID int64  `json:"integration_id"`
	Entity        string `json:"entity"`
	EntityID      string `json:"entity_id"`
	Action        string `json:"action"`
}

func (q *Queries) RecentLinearSyncOpExists(ctx context.Context, arg RecentLinearSyncOpExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, recentLinearSyncOpExists,
		arg.IntegrationID,
		arg.Entity,
		arg.EntityID,
		arg.Action,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const recordLinearSyncRunResult = `-- name: RecordLinearSyncRunResult :one
UPDATE linear_sync_runs
SET issues_done = issues_done + CASE
        WHEN $1::text = 'issue' AND NOT $2::boolean THEN 1 ELSE 0 END,
    issues_failed = issues_failed + CASE
        WHEN $1::text = 'issue' AND $2::boolean THEN 1 ELSE 0 END,
    comments_done = comments_done + CASE
        WHEN $1::text = 'comment' AND NOT $2::boolean THEN 1 ELSE 0 END,
    comments_failed = comments_failed + CASE
        WHEN $1::text = 'comment' AND $2::boolean THEN 1 ELSE 0 END
WHERE id = $3 AND state = 'running'
RETURNING id, integration_id, state, issues_done, issues_total, issues_failed, comments_done, comments_total, comments_failed, started_at, finished_at, created_at
`

type RecordLinearSyncRunResultParams struct {
	Entity string `json:"entity"`
	Failed bool   `json:"failed"`
	ID     int64  `json:"id"`
}

func (q *Queries) RecordLinearSyncRunResult(ctx context.Context, arg RecordLinearSyncRunResultParams) (LinearSyncRun, error) {
	row := q.db.QueryRow(ctx, recordLinearSyncRunResult, arg.Entity, arg.Failed, arg.ID)
	var i LinearSyncRun
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.State,
		&i.IssuesDone,
		&i.IssuesTotal,
		&i.IssuesFailed,
		&i.CommentsDone,
		&i.CommentsTotal,
		&i.CommentsFailed,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const setLinearSyncRunTotals = `-- name: SetLinearSyncRunTotals :one
UPDATE linear_sync_runs
SET issues_total = $1,
    comments_total = $2
WHERE id = $3 AND state = 'running'
RETURNING id, integration_id, state, issues_done, issues_total, issues_failed, comments_done, comments_total, comments_failed, started_at, finished_at, created_at
`

type SetLinearSyncRunTotalsParams struct {
	IssuesTotal   int32 `json:"issues_total"`
	CommentsTotal int32 `json:"comments_total"`
	ID            int64 `json:"id"`
}

func (q *Queries) SetLinearSyncRunTotals(ctx context.Context, arg SetLinearSyncRunTotalsParams) (LinearSyncRun, error) {
	row := q.db.QueryRow(ctx, setLinearSyncRunTotals, arg.IssuesTotal, arg.CommentsTotal, arg.ID)
	var i LinearSyncRun
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.State,
		&i.IssuesDone,
		&i.IssuesTotal,
		&i.IssuesFailed,
		&i.CommentsDone,
		&i.CommentsTotal,
		&i.CommentsFailed,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateLinearIntegrationActive = `-- name: UpdateLinearIntegrationActive :exec
UPDATE linear_integrations
SET is_active = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateLinearIntegrationActiveParams struct {
	ID       int64 `json:"id"`
	IsActive bool  `json:"is_active"`
}

func (q *Queries) UpdateLinearIntegrationActive(ctx context.Context, arg UpdateLinearIntegrationActiveParams) error {
	_, err := q.db.Exec(ctx, updateLinearIntegrationActive, arg.ID, arg.IsActive)
	return err
}

const updateLinearIntegrationLastSync = `-- name: UpdateLinearIntegrationLastSync :exec
UPDATE linear_integrations
SET last_sync_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateLinearIntegrationLastSync(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateLinearIntegrationLastSync, id)
	return err
}

const updateLinearIntegrationTokens = `-- name: UpdateLinearIntegrationTokens :exec
UPDATE linear_integrations
SET access_token_encrypted = $2,
    refresh_token_encrypted = $3,
    token_expires_at = $4,
    updated_at = NOW()
WHERE id = $1
`

type UpdateLinearIntegrationTokensParams struct {
	ID                    int64              `json:"id"`
	AccessTokenEncrypted  []byte             `json:"access_token_encrypted"`
	RefreshTokenEncrypted []byte             `json:"refresh_token_encrypted"`
	TokenExpiresAt        pgtype.Timestamptz `json:"token_expires_at"`
}

func (q *Queries) UpdateLinearIntegrationTokens(ctx context.Context, arg UpdateLinearIntegrationTokensParams) error {
	_, err := q.db.Exec(ctx, updateLinearIntegrationTokens,
		arg.ID,
		arg.AccessTokenEncrypted,
		arg.RefreshTokenEncrypted,
		arg.TokenExpiresAt,
	)
	return err
}
