// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: social.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPublicUserStarredRepos = `-- name: CountPublicUserStarredRepos :one
SELECT COUNT(*)
FROM stars s
JOIN repositories r ON r.id = s.repository_id
WHERE s.user_id = $1
  AND r.is_public = TRUE
`

func (q *Queries) CountPublicUserStarredRepos(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicUserStarredRepos, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRepoStars = `-- name: CountRepoStars :one
SELECT COUNT(*)
FROM stars
WHERE repository_id = $1
`

func (q *Queries) CountRepoStars(ctx context.Context, repositoryID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRepoStars, repositoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRepoWatchers = `-- name: CountRepoWatchers :one
SELECT COUNT(*)
FROM watches
WHERE repository_id = $1
`

func (q *Queries) CountRepoWatchers(ctx context.Context, repositoryID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRepoWatchers, repositoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserStarredRepos = `-- name: CountUserStarredRepos :one
SELECT COUNT(*)
FROM stars
WHERE user_id = $1
`

func (q *Queries) CountUserStarredRepos(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUserStarredRepos, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserWatchedRepos = `-- name: CountUserWatchedRepos :one
SELECT COUNT(*)
FROM watches
WHERE user_id = $1
`

func (q *Queries) CountUserWatchedRepos(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUserWatchedRepos, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWatchStatus = `-- name: GetWatchStatus :one
SELECT id, user_id, repository_id, mode, created_at, updated_at
FROM watches
WHERE user_id = $1
  AND repository_id = $2
`

type GetWatchStatusParams struct {
	UserID       int64 `json:"user_id"`
	RepositoryID int64 `json:"repository_id"`
}

func (q *Queries) GetWatchStatus(ctx context.Context, arg GetWatchStatusParams) (Watch, error) {
	row := q.db.QueryRow(ctx, getWatchStatus, arg.UserID, arg.RepositoryID)
	var i Watch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RepositoryID,
		&i.Mode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isRepoStarred = `-- name: IsRepoStarred :one
SELECT EXISTS (
    SELECT 1
    FROM stars
    WHERE user_id = $1
      AND repository_id = $2
)
`

type IsRepoStarredParams struct {
	UserID       int64 `json:"user_id"`
	RepositoryID int64 `json:"repository_id"`
}

func (q *Queries) IsRepoStarred(ctx context.Context, arg IsRepoStarredParams) (bool, error) {
	row := q.db.QueryRow(ctx, isRepoStarred, arg.UserID, arg.RepositoryID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listActiveWatchersForRepo = `-- name: ListActiveWatchersForRepo :many
SELECT u.id, u.email_notifications_enabled
FROM watches w
JOIN users u ON u.id = w.user_id
WHERE w.repository_id = $1
  AND w.mode IN ('watching', 'participating')
ORDER BY u.id ASC
`

type ListActiveWatchersForRepoRow struct {
	ID                        int64 `json:"id"`
	EmailNotificationsEnabled bool  `json:"email_notifications_enabled"`
}

// Returns all users watching a repo with mode 'watching' or 'participating'.
// Used to fan-out notifications when new issues or landing requests are opened.
func (q *Queries) ListActiveWatchersForRepo(ctx context.Context, repositoryID int64) ([]ListActiveWatchersForRepoRow, error) {
	rows, err := q.db.Query(ctx, listActiveWatchersForRepo, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveWatchersForRepoRow{}
	for rows.Next() {
		var i ListActiveWatchersForRepoRow
		if err := rows.Scan(&i.ID, &i.EmailNotificationsEnabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicUserStarredRepos = `-- name: ListPublicUserStarredRepos :many
SELECT r.id, r.user_id, r.org_id, r.name, r.lower_name, r.description, r.is_public, r.default_bookmark, r.topics, r.search_vector, r.next_issue_number, r.next_landing_number, r.is_fork, r.fork_id, r.is_template, r.template_id, r.is_archived, r.archived_at, r.is_mirror, r.mirror_destination, r.mirror_status, r.last_mirror_at, r.last_mirror_error, r.last_mirror_github_head, r.mirror_behind_refs, r.mirror_failed_refs, r.workspace_idle_timeout_secs, r.workspace_persistence, r.workspace_dependencies, r.clone_depth, r.landing_queue_mode, r.landing_queue_required_checks, r.num_stars, r.num_forks, r.num_watches, r.num_issues, r.num_closed_issues, r.created_at, r.updated_at
FROM stars s
JOIN repositories r ON r.id = s.repository_id
WHERE s.user_id = $1
  AND r.is_public = TRUE
ORDER BY s.created_at DESC, s.id DESC
LIMIT $3
OFFSET $2
`

type ListPublicUserStarredReposParams struct {
	UserID     int64 `json:"user_id"`
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListPublicUserStarredRepos(ctx context.Context, arg ListPublicUserStarredReposParams) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listPublicUserStarredRepos, arg.UserID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.Name,
			&i.LowerName,
			&i.Description,
			&i.IsPublic,
			&i.DefaultBookmark,
			&i.Topics,
			&i.SearchVector,
			&i.NextIssueNumber,
			&i.NextLandingNumber,
			&i.IsFork,
			&i.ForkID,
			&i.IsTemplate,
			&i.TemplateID,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.IsMirror,
			&i.MirrorDestination,
			&i.MirrorStatus,
			&i.LastMirrorAt,
			&i.LastMirrorError,
			&i.LastMirrorGithubHead,
			&i.MirrorBehindRefs,
			&i.MirrorFailedRefs,
			&i.WorkspaceIdleTimeoutSecs,
			&i.WorkspacePersistence,
			&i.WorkspaceDependencies,
			&i.CloneDepth,
			&i.LandingQueueMode,
			&i.LandingQueueRequiredChecks,
			&i.NumStars,
			&i.NumForks,
			&i.NumWatches,
			&i.NumIssues,
			&i.NumClosedIssues,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoStargazers = `-- name: ListRepoStargazers :many
SELECT u.id, u.username, u.lower_username, u.email, u.lower_email, u.display_name, u.bio, u.search_vector, u.avatar_url, u.wallet_address, u.user_type, u.is_active, u.is_admin, u.prohibit_login, u.email_notifications_enabled, u.last_login_at, u.deleted_at, u.created_at, u.updated_at, u.is_synthetic
FROM stars s
JOIN users u ON u.id = s.user_id
WHERE s.repository_id = $1
ORDER BY u.id ASC
LIMIT $3
OFFSET $2
`

type ListRepoStargazersParams struct {
	RepositoryID int64 `json:"repository_id"`
	PageOffset   int32 `json:"page_offset"`
	PageSize     int32 `json:"page_size"`
}

func (q *Queries) ListRepoStargazers(ctx context.Context, arg ListRepoStargazersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listRepoStargazers, arg.RepositoryID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.LowerUsername,
			&i.Email,
			&i.LowerEmail,
			&i.DisplayName,
			&i.Bio,
			&i.SearchVector,
			&i.AvatarUrl,
			&i.WalletAddress,
			&i.UserType,
			&i.IsActive,
			&i.IsAdmin,
			&i.ProhibitLogin,
			&i.EmailNotificationsEnabled,
			&i.LastLoginAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsSynthetic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoWatchers = `-- name: ListRepoWatchers :many
SELECT
    u.id, u.username, u.lower_username, u.email, u.lower_email, u.display_name, u.bio, u.search_vector, u.avatar_url, u.wallet_address, u.user_type, u.is_active, u.is_admin, u.prohibit_login, u.email_notifications_enabled, u.last_login_at, u.deleted_at, u.created_at, u.updated_at, u.is_synthetic,
    w.mode
FROM watches w
JOIN users u ON u.id = w.user_id
WHERE w.repository_id = $1
ORDER BY u.id ASC
LIMIT $3
OFFSET $2
`

type ListRepoWatchersParams struct {
	RepositoryID int64 `json:"repository_id"`
	PageOffset   int32 `json:"page_offset"`
	PageSize     int32 `json:"page_size"`
}

type ListRepoWatchersRow struct {
	ID                        int64              `json:"id"`
	Username                  string             `json:"username"`
	LowerUsername             string             `json:"lower_username"`
	Email                     pgtype.Text        `json:"email"`
	LowerEmail                pgtype.Text        `json:"lower_email"`
	DisplayName               string             `json:"display_name"`
	Bio                       string             `json:"bio"`
	SearchVector              string             `json:"-"`
	AvatarUrl                 string             `json:"avatar_url"`
	WalletAddress             pgtype.Text        `json:"wallet_address"`
	UserType                  string             `json:"user_type"`
	IsActive                  bool               `json:"is_active"`
	IsAdmin                   bool               `json:"is_admin"`
	ProhibitLogin             bool               `json:"prohibit_login"`
	EmailNotificationsEnabled bool               `json:"email_notifications_enabled"`
	LastLoginAt               pgtype.Timestamptz `json:"last_login_at"`
	DeletedAt                 pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt                 time.Time          `json:"created_at"`
	UpdatedAt                 time.Time          `json:"updated_at"`
	IsSynthetic               bool               `json:"is_synthetic"`
	Mode                      string             `json:"mode"`
}

func (q *Queries) ListRepoWatchers(ctx context.Context, arg ListRepoWatchersParams) ([]ListRepoWatchersRow, error) {
	rows, err := q.db.Query(ctx, listRepoWatchers, arg.RepositoryID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRepoWatchersRow{}
	for rows.Next() {
		var i ListRepoWatchersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.LowerUsername,
			&i.Email,
			&i.LowerEmail,
			&i.DisplayName,
			&i.Bio,
			&i.SearchVector,
			&i.AvatarUrl,
			&i.WalletAddress,
			&i.UserType,
			&i.IsActive,
			&i.IsAdmin,
			&i.ProhibitLogin,
			&i.EmailNotificationsEnabled,
			&i.LastLoginAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsSynthetic,
			&i.Mode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserStarredRepos = `-- name: ListUserStarredRepos :many
SELECT r.id, r.user_id, r.org_id, r.name, r.lower_name, r.description, r.is_public, r.default_bookmark, r.topics, r.search_vector, r.next_issue_number, r.next_landing_number, r.is_fork, r.fork_id, r.is_template, r.template_id, r.is_archived, r.archived_at, r.is_mirror, r.mirror_destination, r.mirror_status, r.last_mirror_at, r.last_mirror_error, r.last_mirror_github_head, r.mirror_behind_refs, r.mirror_failed_refs, r.workspace_idle_timeout_secs, r.workspace_persistence, r.workspace_dependencies, r.clone_depth, r.landing_queue_mode, r.landing_queue_required_checks, r.num_stars, r.num_forks, r.num_watches, r.num_issues, r.num_closed_issues, r.created_at, r.updated_at
FROM stars s
JOIN repositories r ON r.id = s.repository_id
WHERE s.user_id = $1
ORDER BY s.created_at DESC, s.id DESC
LIMIT $3
OFFSET $2
`

type ListUserStarredReposParams struct {
	UserID     int64 `json:"user_id"`
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListUserStarredRepos(ctx context.Context, arg ListUserStarredReposParams) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listUserStarredRepos, arg.UserID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.Name,
			&i.LowerName,
			&i.Description,
			&i.IsPublic,
			&i.DefaultBookmark,
			&i.Topics,
			&i.SearchVector,
			&i.NextIssueNumber,
			&i.NextLandingNumber,
			&i.IsFork,
			&i.ForkID,
			&i.IsTemplate,
			&i.TemplateID,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.IsMirror,
			&i.MirrorDestination,
			&i.MirrorStatus,
			&i.LastMirrorAt,
			&i.LastMirrorError,
			&i.LastMirrorGithubHead,
			&i.MirrorBehindRefs,
			&i.MirrorFailedRefs,
			&i.WorkspaceIdleTimeoutSecs,
			&i.WorkspacePersistence,
			&i.WorkspaceDependencies,
			&i.CloneDepth,
			&i.LandingQueueMode,
			&i.LandingQueueRequiredChecks,
			&i.NumStars,
			&i.NumForks,
			&i.NumWatches,
			&i.NumIssues,
			&i.NumClosedIssues,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserWatchedRepos = `-- name: ListUserWatchedRepos :many
SELECT
    r.id, r.user_id, r.org_id, r.name, r.lower_name, r.description, r.is_public, r.default_bookmark, r.topics, r.search_vector, r.next_issue_number, r.next_landing_number, r.is_fork, r.fork_id, r.is_template, r.template_id, r.is_archived, r.archived_at, r.is_mirror, r.mirror_destination, r.mirror_status, r.last_mirror_at, r.last_mirror_error, r.last_mirror_github_head, r.mirror_behind_refs, r.mirror_failed_refs, r.workspace_idle_timeout_secs, r.workspace_persistence, r.workspace_dependencies, r.clone_depth, r.landing_queue_mode, r.landing_queue_required_checks, r.num_stars, r.num_forks, r.num_watches, r.num_issues, r.num_closed_issues, r.created_at, r.updated_at,
    w.mode AS watch_mode
FROM watches w
JOIN repositories r ON r.id = w.repository_id
WHERE w.user_id = $1
ORDER BY w.updated_at DESC
LIMIT $3
OFFSET $2
`

type ListUserWatchedReposParams struct {
	UserID     int64 `json:"user_id"`
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

type ListUserWatchedReposRow struct {
	ID                         int64              `json:"id"`
	UserID                     pgtype.Int8        `json:"user_id"`
	OrgID                      pgtype.Int8        `json:"org_id"`
	Name                       string             `json:"name"`
	LowerName                  string             `json:"lower_name"`
	Description                string             `json:"description"`
	IsPublic                   bool               `json:"is_public"`
	DefaultBookmark            string             `json:"default_bookmark"`
	Topics                     []string           `json:"topics"`
	SearchVector               string             `json:"-"`
	NextIssueNumber            int64              `json:"next_issue_number"`
	NextLandingNumber          int64              `json:"next_landing_number"`
	IsFork                     bool               `json:"is_fork"`
	ForkID                     pgtype.Int8        `json:"fork_id"`
	IsTemplate                 bool               `json:"is_template"`
	TemplateID                 pgtype.Int8        `json:"template_id"`
	IsArchived                 bool               `json:"is_archived"`
	ArchivedAt                 pgtype.Timestamptz `json:"archived_at"`
	IsMirror                   bool               `json:"is_mirror"`
	MirrorDestination          string             `json:"mirror_destination"`
	MirrorStatus               string             `json:"mirror_status"`
	LastMirrorAt               pgtype.Timestamptz `json:"last_mirror_at"`
	LastMirrorError            pgtype.Text        `json:"last_mirror_error"`
	LastMirrorGithubHead       pgtype.Text        `json:"last_mirror_github_head"`
	MirrorBehindRefs           int32              `json:"mirror_behind_refs"`
	MirrorFailedRefs           int32              `json:"mirror_failed_refs"`
	WorkspaceIdleTimeoutSecs   int32              `json:"workspace_idle_timeout_secs"`
	WorkspacePersistence       string             `json:"workspace_persistence"`
	WorkspaceDependencies      []string           `json:"workspace_dependencies"`
	CloneDepth                 int32              `json:"clone_depth"`
	LandingQueueMode           string             `json:"landing_queue_mode"`
	LandingQueueRequiredChecks []string           `json:"landing_queue_required_checks"`
	NumStars                   int64              `json:"num_stars"`
	NumForks                   int64              `json:"num_forks"`
	NumWatches                 int64              `json:"num_watches"`
	NumIssues                  int64              `json:"num_issues"`
	NumClosedIssues            int64              `json:"num_closed_issues"`
	CreatedAt                  time.Time          `json:"created_at"`
	UpdatedAt                  time.Time          `json:"updated_at"`
	WatchMode                  string             `json:"watch_mode"`
}

func (q *Queries) ListUserWatchedRepos(ctx context.Context, arg ListUserWatchedReposParams) ([]ListUserWatchedReposRow, error) {
	rows, err := q.db.Query(ctx, listUserWatchedRepos, arg.UserID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserWatchedReposRow{}
	for rows.Next() {
		var i ListUserWatchedReposRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.Name,
			&i.LowerName,
			&i.Description,
			&i.IsPublic,
			&i.DefaultBookmark,
			&i.Topics,
			&i.SearchVector,
			&i.NextIssueNumber,
			&i.NextLandingNumber,
			&i.IsFork,
			&i.ForkID,
			&i.IsTemplate,
			&i.TemplateID,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.IsMirror,
			&i.MirrorDestination,
			&i.MirrorStatus,
			&i.LastMirrorAt,
			&i.LastMirrorError,
			&i.LastMirrorGithubHead,
			&i.MirrorBehindRefs,
			&i.MirrorFailedRefs,
			&i.WorkspaceIdleTimeoutSecs,
			&i.WorkspacePersistence,
			&i.WorkspaceDependencies,
			&i.CloneDepth,
			&i.LandingQueueMode,
			&i.LandingQueueRequiredChecks,
			&i.NumStars,
			&i.NumForks,
			&i.NumWatches,
			&i.NumIssues,
			&i.NumClosedIssues,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WatchMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const starRepo = `-- name: StarRepo :one
INSERT INTO stars (user_id, repository_id)
VALUES ($1, $2)
ON CONFLICT (user_id, repository_id) DO NOTHING
RETURNING id, user_id, repository_id, created_at
`

type StarRepoParams struct {
	UserID       int64 `json:"user_id"`
	RepositoryID int64 `json:"repository_id"`
}

// DO NOTHING (rather than erroring) on a concurrent duplicate star: no row is
// returned, callers treat that as already-starred and skip counter/webhook
// side effects. repositories.num_stars is maintained by trg_stars_count_*.
func (q *Queries) StarRepo(ctx context.Context, arg StarRepoParams) (Star, error) {
	row := q.db.QueryRow(ctx, starRepo, arg.UserID, arg.RepositoryID)
	var i Star
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RepositoryID,
		&i.CreatedAt,
	)
	return i, err
}

const unstarRepo = `-- name: UnstarRepo :execrows
DELETE FROM stars
WHERE user_id = $1
  AND repository_id = $2
`

type UnstarRepoParams struct {
	UserID       int64 `json:"user_id"`
	RepositoryID int64 `json:"repository_id"`
}

// Returns rows affected so callers only emit star webhooks when this call
// actually removed the row (concurrent unstars race to a single winner).
func (q *Queries) UnstarRepo(ctx context.Context, arg UnstarRepoParams) (int64, error) {
	result, err := q.db.Exec(ctx, unstarRepo, arg.UserID, arg.RepositoryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unwatchRepo = `-- name: UnwatchRepo :execrows
DELETE FROM watches
WHERE user_id = $1
  AND repository_id = $2
`

type UnwatchRepoParams struct {
	UserID       int64 `json:"user_id"`
	RepositoryID int64 `json:"repository_id"`
}

func (q *Queries) UnwatchRepo(ctx context.Context, arg UnwatchRepoParams) (int64, error) {
	result, err := q.db.Exec(ctx, unwatchRepo, arg.UserID, arg.RepositoryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const watchRepo = `-- name: WatchRepo :one
INSERT INTO watches (user_id, repository_id, mode)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, repository_id)
DO UPDATE SET mode = EXCLUDED.mode, updated_at = NOW()
RETURNING id, user_id, repository_id, mode, created_at, updated_at
`

type WatchRepoParams struct {
	UserID       int64  `json:"user_id"`
	RepositoryID int64  `json:"repository_id"`
	Mode         string `json:"mode"`
}

// repositories.num_watches is maintained by trg_watches_count_ins, which only
// fires on the insert arm of this upsert — a mode change never recounts.
func (q *Queries) WatchRepo(ctx context.Context, arg WatchRepoParams) (Watch, error) {
	row := q.db.QueryRow(ctx, watchRepo, arg.UserID, arg.RepositoryID, arg.Mode)
	var i Watch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RepositoryID,
		&i.Mode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
