// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_capabilities.sql

package db

import (
	"context"
)

const bindWorkspaceCapability = `-- name: BindWorkspaceCapability :exec
INSERT INTO workspace_capability_bindings(repository_id,user_id,required_capability,workspace_id)
SELECT $1,$2,$3,w.id FROM workspaces w
WHERE w.id=$4::uuid AND w.repository_id=$1 AND w.user_id=$2 AND w.deleted_at IS NULL
`

type BindWorkspaceCapabilityParams struct {
	RepositoryID       int64  `json:"repository_id"`
	UserID             int64  `json:"user_id"`
	RequiredCapability string `json:"required_capability"`
	WorkspaceID        string `json:"workspace_id"`
}

func (q *Queries) BindWorkspaceCapability(ctx context.Context, arg BindWorkspaceCapabilityParams) error {
	_, err := q.db.Exec(ctx, bindWorkspaceCapability,
		arg.RepositoryID,
		arg.UserID,
		arg.RequiredCapability,
		arg.WorkspaceID,
	)
	return err
}

const getWorkspaceCapability = `-- name: GetWorkspaceCapability :one
SELECT w.id, w.repository_id, w.user_id, w.name, w.is_fork, w.parent_workspace_id, w.target_bookmark, w.source_snapshot_id, w.kind, w.environment_source, w.environment_revision, w.environment_closure_hash, w.agent_session_id, w.head_push_token_id, w.environment_image, w.desktop_session_id, w.desktop_session_token_hash, w.desktop_session_expires_at, w.vm_id, w.provisioning_generation, w.status, w.failure_code, w.failure_message, w.provisioning_stage, w.last_activity_at, w.idle_timeout_secs, w.suspended_at, w.started_at, w.resumed_at, w.head_change_id, w.head_commit_id, w.ahead, w.behind, w.last_accessed_at, w.deleted_at, w.created_at, w.updated_at FROM workspace_capability_bindings b JOIN workspaces w ON w.id=b.workspace_id
WHERE b.repository_id=$1 AND b.user_id=$2 AND b.required_capability=$3
FOR SHARE OF b
`

type GetWorkspaceCapabilityParams struct {
	RepositoryID       int64  `json:"repository_id"`
	UserID             int64  `json:"user_id"`
	RequiredCapability string `json:"required_capability"`
}

func (q *Queries) GetWorkspaceCapability(ctx context.Context, arg GetWorkspaceCapabilityParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceCapability, arg.RepositoryID, arg.UserID, arg.RequiredCapability)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.UserID,
		&i.Name,
		&i.IsFork,
		&i.ParentWorkspaceID,
		&i.TargetBookmark,
		&i.SourceSnapshotID,
		&i.Kind,
		&i.EnvironmentSource,
		&i.EnvironmentRevision,
		&i.EnvironmentClosureHash,
		&i.AgentSessionID,
		&i.HeadPushTokenID,
		&i.EnvironmentImage,
		&i.DesktopSessionID,
		&i.DesktopSessionTokenHash,
		&i.DesktopSessionExpiresAt,
		&i.VmID,
		&i.ProvisioningGeneration,
		&i.Status,
		&i.FailureCode,
		&i.FailureMessage,
		&i.ProvisioningStage,
		&i.LastActivityAt,
		&i.IdleTimeoutSecs,
		&i.SuspendedAt,
		&i.StartedAt,
		&i.ResumedAt,
		&i.HeadChangeID,
		&i.HeadCommitID,
		&i.Ahead,
		&i.Behind,
		&i.LastAccessedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRegisteredJobWorkspaceIDs = `-- name: ListRegisteredJobWorkspaceIDs :many
SELECT DISTINCT workspace_id FROM repository_job_registrations WHERE repository_id=$1 AND user_id=$2
`

type ListRegisteredJobWorkspaceIDsParams struct {
	RepositoryID int64 `json:"repository_id"`
	UserID       int64 `json:"user_id"`
}

func (q *Queries) ListRegisteredJobWorkspaceIDs(ctx context.Context, arg ListRegisteredJobWorkspaceIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listRegisteredJobWorkspaceIDs, arg.RepositoryID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var workspace_id string
		if err := rows.Scan(&workspace_id); err != nil {
			return nil, err
		}
		items = append(items, workspace_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkspaceCapability = `-- name: LockWorkspaceCapability :exec
SELECT pg_advisory_xact_lock(hashtextextended('workspace-capability:' || $1::bigint::text || ':' || $2::bigint::text,0))
`

type LockWorkspaceCapabilityParams struct {
	RepositoryID int64 `json:"repository_id"`
	UserID       int64 `json:"user_id"`
}

func (q *Queries) LockWorkspaceCapability(ctx context.Context, arg LockWorkspaceCapabilityParams) error {
	_, err := q.db.Exec(ctx, lockWorkspaceCapability, arg.RepositoryID, arg.UserID)
	return err
}
