import { expect, test } from '@playwright/test'

test.use({ contextOptions: { reducedMotion: 'reduce' }, actionTimeout: 3_000, navigationTimeout: 10_000 })
test.setTimeout(30_000)

test('Chat Tab reaches Send, Mode, Close, and the footer without trapping focus', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Chat', exact: true }).click()
  const input = page.getByTestId('composer-input')
  const send = page.getByTestId('composer-send')
  const mode = page.getByRole('dialog', { name: 'Chat' }).getByRole('button', { name: 'Mode: Normal', exact: true })
  const close = page.getByRole('button', { name: 'Close Chat', exact: true })
  await input.fill('hello there')
  await page.keyboard.press('Tab')
  await expect(send).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(mode).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(close).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Enable tutorial sounds', exact: true })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(close).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(mode).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('menuitemradio', { name: 'Normal' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(mode).toBeFocused()
  const hint = (await page.locator('.palette-foot').boundingBox())!
  expect((await mode.boundingBox())!.y).toBeGreaterThanOrEqual(hint.y + hint.height)
  await page.keyboard.press('Shift+Tab')
  await expect(send).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(input).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(page.getByRole('button', { name: 'Review changes', exact: true })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(page.getByRole('button', { name: 'Show issues', exact: true })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(page.getByRole('log', { name: 'Onboarding chat history' })).toBeFocused()
})

for (const colorScheme of ['light', 'dark'] as const) test(`palette and Mode paint opaque surfaces (${colorScheme})`, async ({ page }) => {
  await page.emulateMedia({ colorScheme })
  for (const path of ['/', '/smithersai/smithers/']) {
    await page.goto(path)
    await page.getByRole('button', { name: 'Mode: Normal', exact: true }).click()
    await expect(page.getByRole('menu', { name: 'Input mode' })).toHaveCSS('background-color', /^rgb\(/)
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: 'Chat', exact: true }).click()
    // The tutorial palette shares its opaque parent panel.
    const panel = path === '/' ? page.locator('.guide-composer-layer') : page.getByTestId('palette')
    await expect(panel).toHaveCSS('background-color', /^rgb\(/)
  }
})

test('Mode selects on release, dismisses accessibly, persists, and Vim navigates without activating', async ({ page }) => {
  await page.goto('/')
  const mode = page.getByRole('button', { name: 'Mode: Normal', exact: true })
  await expect(mode).toBeVisible()
  await page.keyboard.down('m')
  await expect(mode).toHaveAttribute('data-pressed', '')
  await expect(page.getByRole('menu')).toHaveCount(0)
  await page.keyboard.up('m')
  await expect(page.getByRole('menuitemradio', { name: 'Normal' })).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await page.keyboard.down('Enter')
  await expect(page.getByRole('menuitemradio', { name: 'Vim' })).toHaveAttribute('aria-checked', 'false')
  await page.keyboard.up('Enter')
  await expect(page.getByRole('button', { name: 'Mode: Vim', exact: true })).toBeFocused()
  await expect(page.getByTestId('composer-input')).toBeHidden()
  const issues = page.getByRole('button', { name: 'Show issues', exact: true })
  const changes = page.getByRole('button', { name: 'Review changes', exact: true })
  await issues.focus()
  await page.keyboard.down('l')
  await expect(changes).toBeFocused()
  await expect(changes).not.toHaveAttribute('data-pressed', '')
  await page.keyboard.up('l')
  await expect(changes).toBeFocused()
  await expect(page.locator('.guide-shell')).toHaveAttribute('data-stage', '1')
  await page.keyboard.press('h')
  await expect(issues).toBeFocused()
  await page.keyboard.press('m')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('menu')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Mode: Vim', exact: true })).toBeFocused()
  await page.keyboard.press('m')
  await page.locator('.guide-goal').click()
  await expect(page.getByRole('menu')).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('button', { name: 'Mode: Vim', exact: true })).toBeVisible()
  await page.keyboard.press('Meta+k')
  const input = page.getByTestId('composer-input')
  await expect(input).toBeFocused()
  await input.pressSequentially('chjklm')
  await expect(input).toHaveValue('chjklm')
  await expect(page.getByRole('menu')).toHaveCount(0)
})

test('switching away from Dictation stops capture without reopening Chat', async ({ page }) => {
  await page.addInitScript(() => {
    const host = window as any
    host.SpeechRecognition = class {
      onend: any
      start() { host.starts = (host.starts ?? 0) + 1 }
      stop() { this.onend?.() }
      abort() { host.aborts = (host.aborts ?? 0) + 1 }
    }
  })
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Mode: Normal', exact: true })).toBeVisible()
  await page.keyboard.press('m')
  await page.getByRole('menuitemradio', { name: 'Dictation' }).click()
  expect(await page.evaluate(() => (window as any).starts ?? 0)).toBe(0)
  await page.keyboard.press('Meta+k')
  await expect(page.getByTestId('composer-input')).toBeVisible()
  await expect.poll(() => page.evaluate(() => (window as any).starts)).toBe(1)
  await page.getByRole('button', { name: 'Mode: Dictation', exact: true }).click()
  await page.getByRole('menuitemradio', { name: 'Normal' }).click()
  await expect.poll(() => page.evaluate(() => (window as any).aborts)).toBe(1)
  await expect(page.getByRole('button', { name: 'Stop dictation' })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await page.keyboard.press('Meta+k')
  await expect.poll(() => page.evaluate(() => (window as any).starts)).toBe(1)
})

for (const key of ['Enter', 'Escape']) test(`${key} on dictation Stop releases capture before Chat`, async ({ page }) => {
  await page.addInitScript(() => {
    const host = window as any
    host.SpeechRecognition = class {
      onend: any
      start() {}
      stop() { this.onend?.() }
      abort() { host.aborts = (host.aborts ?? 0) + 1 }
    }
  })
  await page.goto('/')
  await page.getByRole('button', { name: 'Mode: Normal', exact: true }).click()
  await page.getByRole('menuitemradio', { name: 'Dictation', exact: true }).click()
  await page.keyboard.press('Meta+k')
  const input = page.getByTestId('composer-input')
  const stop = page.getByRole('button', { name: 'Stop dictation', exact: true })
  await expect(stop).toBeVisible()
  await input.fill('keep this dictation draft')
  const send = page.getByTestId('composer-send')
  const mode = page.getByRole('button', { name: 'Mode: Dictation', exact: true })
  await input.press('Tab')
  await expect(send).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(mode).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Close Chat', exact: true })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(mode).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(send).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(input).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(stop).toBeFocused()
  await stop.press(key)
  await expect(stop).toHaveCount(0)
  await expect(input).toBeFocused()
  await expect(input).toHaveValue('keep this dictation draft')
  await expect(page.getByTestId('palette')).toBeVisible()
  await input.press('Escape')
  await expect(input).toBeHidden()
  if (key === 'Escape') expect(await page.evaluate(() => (window as any).aborts)).toBe(1)
})

test('repository pages share Chat and Mode without duplicating tutorial controls', async ({ page }) => {
  await page.goto('/smithersai/smithers/')
  await expect(page.locator('.guide-shell')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Mode: Normal', exact: true })).toHaveCount(1)
  await page.keyboard.press('m')
  await page.getByRole('menuitemradio', { name: 'Vim' }).click()
  await expect(page.getByRole('button', { name: 'Mode: Vim', exact: true })).toBeVisible()
  await page.keyboard.press('Meta+k')
  await expect(page.getByTestId('composer-input')).toBeFocused()
})

test('unsupported Dictation is disabled with a reason and Chat stays in Normal mode', async ({ page }) => {
  await page.addInitScript(() => { delete (window as any).SpeechRecognition; delete (window as any).webkitSpeechRecognition })
  await page.goto('/')
  await page.getByRole('button', { name: 'Mode: Normal', exact: true }).click()
  const dictation = page.getByRole('menuitemradio', { name: 'Dictation', exact: true })
  await expect(dictation).toHaveAttribute('aria-disabled', 'true')
  await expect(dictation).toHaveAccessibleDescription('Dictation needs a browser with speech recognition')
  await page.keyboard.press('End')
  await expect(dictation).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('menu')).toBeVisible()
  await page.keyboard.press('Escape')
  await page.keyboard.press('Meta+k')
  await expect(page.getByTestId('composer-input')).toBeFocused()
  await expect(page.getByRole('dialog', { name: 'Chat' }).getByRole('button', { name: 'Mode: Normal', exact: true })).toBeVisible()
  await expect(page.getByText("/chat.open didn't run", { exact: true })).toHaveCount(0)
})

test('Vim skips unrelated lesson fields and the page has one named banner and heading', async ({ page }) => {
  await page.goto('/smithersai/smithers/?tutorial')
  await page.getByRole('button', { name: 'Mode: Normal', exact: true }).click()
  await page.getByRole('menuitemradio', { name: 'Vim', exact: true }).click()
  await page.keyboard.press('i')
  await expect(page.getByRole('button', { name: 'Read issue #3', exact: true })).toBeVisible()
  await page.keyboard.press('r')
  await expect(page.locator('.guide-shell')).toHaveAttribute('data-stage', '3')
  await expect(page.getByRole('banner')).toHaveCount(1)
  await expect(page.getByRole('banner')).toHaveAccessibleName('Smithers')
  await expect(page.getByRole('heading', { level: 1, name: 'Smithers' })).toHaveCount(1)
  const comment = page.locator('textarea[id^="ghc-comment-"]')
  await expect(comment).toHaveCount(1)
  expect(await page.evaluate(() => {
    const ids = [...document.querySelectorAll('[id]')].map(node => node.id)
    return ids.length === new Set(ids).size && [...document.querySelectorAll('[aria-controls]')].every(node => document.getElementById(node.getAttribute('aria-controls')!))
  })).toBe(true)
  await expect(page.locator('nav[aria-label="Frame history"]')).toHaveCount(1)
  await expect(page.locator('aside[aria-label="Issue #3 details"]')).toHaveCount(1)
  const issueFlows = page.getByRole('button', { name: 'Issue flows', exact: true })
  await issueFlows.focus()
  await page.keyboard.press('l')
  await expect(page.getByRole('button', { name: 'Research / repro', exact: true })).toBeFocused()
  await page.keyboard.press('h')
  await expect(issueFlows).toBeFocused()
  for (let step = 0; step < 20; step++) {
    await page.keyboard.press('j')
    await expect(comment).not.toBeFocused()
  }
  await expect(comment).toHaveValue('')
  await comment.focus()
  await page.keyboard.press('Escape')
  await expect(comment).toBeFocused()
  await expect(comment).toHaveAttribute('data-vim-mode', 'normal')
  await page.keyboard.press('m')
  await expect(page.getByRole('menu', { name: 'Input mode' })).toHaveCount(0)
  await expect(comment).toHaveValue('')
  await page.keyboard.press('Control+b')
  await page.keyboard.press('q')
  const controlsPane = page.locator('.keyboard-pane-number').filter({ hasText: 'Tutorial controls' })
  await page.keyboard.press((await controlsPane.locator('kbd').textContent())!)
  await page.keyboard.press('m')
  await expect(page.getByRole('menu', { name: 'Input mode' })).toBeVisible()
})

test('touch guidance and repository footer use taps without key chips', async ({ browser, baseURL }) => {
  const context = await browser.newContext({ baseURL, viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, reducedMotion: 'reduce' })
  context.setDefaultTimeout(3_000)
  context.setDefaultNavigationTimeout(10_000)
  const page = await context.newPage()
  await page.goto('/smithersai/smithers/?tutorial')
  await expect(page.getByRole('button', { name: 'Show issues', exact: true })).toBeVisible()
  await expect(page.locator('.guide-chat-controls kbd').first()).toBeHidden()
  await expect(page.getByRole('note', { name: 'Help' })).not.toContainText(/pressing C/)
  await page.getByRole('button', { name: 'Skip tutorial', exact: true }).tap()
  await expect(page.locator('.guide-shell')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Skip tutorial', exact: true })).toHaveCount(0)
  await page.goto('/smithersai/smithers/')
  await expect(page.getByRole('button', { name: 'Chat', exact: true })).toBeVisible()
  for (const key of await page.locator('.app-chat-controls kbd').all()) await expect(key).toBeHidden()
  await context.close()
})


test('Vim roves into Chat in normal mode, inserts explicitly, and leaves on j or a second Escape', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Mode: Normal', exact: true }).click()
  await page.getByRole('menuitemradio', { name: 'Vim', exact: true }).click()
  await page.keyboard.press('Meta+k')
  const input = page.getByTestId('composer-input')
  const send = page.getByTestId('composer-send')
  await input.fill('draft')
  await input.press('Tab')
  await expect(send).toBeFocused()
  await page.keyboard.press('k')
  await expect(input).toBeFocused()
  await expect(input).toHaveAttribute('data-vim-mode', 'normal')
  await page.keyboard.press('j')
  await expect(send).toBeFocused()
  await expect(input).toHaveValue('draft')
  await page.keyboard.press('h')
  await page.keyboard.press('i')
  await expect(input).toHaveAttribute('data-vim-mode', 'insert')
  await input.press('End')
  await page.keyboard.type(' hjkl')
  await expect(input).toHaveValue('draft hjkl')
  await page.keyboard.press('Escape')
  await expect(input).toBeFocused()
  await expect(input).toHaveAttribute('data-vim-mode', 'normal')
  await page.keyboard.press('Enter')
  await expect(input).toHaveAttribute('data-vim-mode', 'insert')
  await expect(input).toHaveValue('draft hjkl')
  await page.keyboard.press('Escape')
  await page.keyboard.press('Escape')
  await expect(input).not.toBeFocused()
  await expect(page.getByRole('dialog', { name: 'Chat' })).toBeVisible()
  await page.keyboard.press('j')
  await expect(input).toBeFocused()
  await expect(input).toHaveAttribute('data-vim-mode', 'normal')
})
