import { expect, test } from '@playwright/test'

test.use({ contextOptions: { reducedMotion: 'reduce' } })

test('Chat Tab reaches Send and Mode and cycles inside the dialog', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Chat', exact: true }).click()
  const input = page.getByTestId('composer-input')
  const send = page.getByTestId('composer-send')
  const mode = page.getByRole('dialog', { name: 'Chat' }).getByRole('button', { name: 'Mode: Normal', exact: true })
  await input.fill('hello there')
  await page.keyboard.press('Tab')
  await expect(send).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(mode).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(input).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(mode).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('menuitemradio', { name: 'Normal' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(mode).toBeFocused()
  const hint = (await page.locator('.palette-foot').boundingBox())!
  expect((await mode.boundingBox())!.y).toBeGreaterThanOrEqual(hint.y + hint.height)
})

for (const colorScheme of ['light', 'dark'] as const) test(`palette and Mode paint opaque surfaces (${colorScheme})`, async ({ page }) => {
  await page.emulateMedia({ colorScheme })
  for (const path of ['/', '/smithersai/smithers/']) {
    await page.goto(path)
    await page.getByRole('button', { name: 'Mode: Normal', exact: true }).click()
    await expect(page.getByRole('menu', { name: 'Input mode' })).toHaveCSS('background-color', /^rgb\(/)
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: 'Chat', exact: true }).click()
    // The tutorial palette shares its opaque parent panel.
    const panel = path === '/' ? page.locator('.guide-composer-layer') : page.getByTestId('palette')
    await expect(panel).toHaveCSS('background-color', /^rgb\(/)
  }
})

test('Mode selects on release, dismisses accessibly, persists, and Vim navigates without activating', async ({ page }) => {
  await page.goto('/')
  const mode = page.getByRole('button', { name: 'Mode: Normal', exact: true })
  await expect(mode).toBeVisible()
  await page.keyboard.down('m')
  await expect(mode).toHaveAttribute('data-pressed', '')
  await expect(page.getByRole('menu')).toHaveCount(0)
  await page.keyboard.up('m')
  await expect(page.getByRole('menuitemradio', { name: 'Normal' })).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await page.keyboard.down('Enter')
  await expect(page.getByRole('menuitemradio', { name: 'Vim' })).toHaveAttribute('aria-checked', 'false')
  await page.keyboard.up('Enter')
  await expect(page.getByRole('button', { name: 'Mode: Vim', exact: true })).toBeFocused()
  await expect(page.getByTestId('composer-input')).toBeHidden()
  const issues = page.getByRole('button', { name: 'Show issues', exact: true })
  const changes = page.getByRole('button', { name: 'Review changes', exact: true })
  await issues.focus()
  await page.keyboard.down('l')
  await expect(issues).toBeFocused()
  await expect(changes).toHaveAttribute('data-pressed', '')
  await page.keyboard.up('l')
  await expect(changes).toBeFocused()
  await expect(page.locator('.guide-shell')).toHaveAttribute('data-stage', '1')
  await page.keyboard.press('h')
  await expect(issues).toBeFocused()
  await page.keyboard.press('m')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('menu')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Mode: Vim', exact: true })).toBeFocused()
  await page.keyboard.press('m')
  await page.locator('.guide-goal').click()
  await expect(page.getByRole('menu')).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('button', { name: 'Mode: Vim', exact: true })).toBeVisible()
  await page.keyboard.press('c')
  const input = page.getByTestId('composer-input')
  await expect(input).toBeFocused()
  await input.pressSequentially('chjklm')
  await expect(input).toHaveValue('chjklm')
  await expect(page.getByRole('menu')).toHaveCount(0)
})

test('switching away from Dictation stops capture without reopening Chat', async ({ page }) => {
  await page.addInitScript(() => {
    const host = window as any
    host.SpeechRecognition = class {
      onend: any
      start() { host.starts = (host.starts ?? 0) + 1 }
      stop() { this.onend?.() }
      abort() { host.aborts = (host.aborts ?? 0) + 1 }
    }
  })
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Mode: Normal', exact: true })).toBeVisible()
  await page.keyboard.press('m')
  await page.getByRole('menuitemradio', { name: 'Dictation' }).click()
  expect(await page.evaluate(() => (window as any).starts ?? 0)).toBe(0)
  await page.keyboard.press('c')
  await expect(page.getByTestId('composer-input')).toBeVisible()
  await expect.poll(() => page.evaluate(() => (window as any).starts)).toBe(1)
  await page.getByRole('button', { name: 'Mode: Dictation', exact: true }).click()
  await page.getByRole('menuitemradio', { name: 'Normal' }).click()
  await expect.poll(() => page.evaluate(() => (window as any).aborts)).toBe(1)
  await expect(page.getByRole('button', { name: 'Stop dictation' })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await page.keyboard.press('c')
  await expect.poll(() => page.evaluate(() => (window as any).starts)).toBe(1)
})

test('repository pages share Chat and Mode without duplicating tutorial controls', async ({ page }) => {
  await page.goto('/smithersai/smithers/')
  await expect(page.locator('.guide-shell')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Mode: Normal', exact: true })).toHaveCount(1)
  await page.keyboard.press('m')
  await page.getByRole('menuitemradio', { name: 'Vim' }).click()
  await expect(page.getByRole('button', { name: 'Mode: Vim', exact: true })).toBeVisible()
  await page.keyboard.press('c')
  await expect(page.getByTestId('composer-input')).toBeFocused()
})

test('unsupported Dictation is disabled with a reason and Chat stays in Normal mode', async ({ page }) => {
  await page.addInitScript(() => { delete (window as any).SpeechRecognition; delete (window as any).webkitSpeechRecognition })
  await page.goto('/')
  await page.getByRole('button', { name: 'Mode: Normal', exact: true }).click()
  const dictation = page.getByRole('menuitemradio', { name: 'Dictation', exact: true })
  await expect(dictation).toHaveAttribute('aria-disabled', 'true')
  await expect(dictation).toHaveAccessibleDescription('Dictation needs a browser with speech recognition')
  await page.keyboard.press('End')
  await expect(dictation).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('menu')).toBeVisible()
  await page.keyboard.press('Escape')
  await page.keyboard.press('c')
  await expect(page.getByTestId('composer-input')).toBeFocused()
  await expect(page.getByRole('dialog', { name: 'Chat' }).getByRole('button', { name: 'Mode: Normal', exact: true })).toBeVisible()
  await expect(page.getByText("/chat.open didn't run", { exact: true })).toHaveCount(0)
})

test('Vim walks only controls through the practice issue; Escape exits a manually opened field', async ({ page }) => {
  await page.goto('/smithersai/smithers/?tutorial')
  await page.getByRole('button', { name: 'Mode: Normal', exact: true }).click()
  await page.getByRole('menuitemradio', { name: 'Vim', exact: true }).click()
  await page.keyboard.press('i')
  await expect(page.getByRole('button', { name: 'Read issue #3', exact: true })).toBeVisible()
  await page.keyboard.press('r')
  await expect(page.locator('.guide-shell')).toHaveAttribute('data-stage', '3')
  const comment = page.locator('textarea[id^="ghc-comment-"]')
  await expect(comment).toHaveCount(1)
  expect(await page.evaluate(() => {
    const ids = [...document.querySelectorAll('[id]')].map(node => node.id)
    return ids.length === new Set(ids).size && [...document.querySelectorAll('[aria-controls]')].every(node => document.getElementById(node.getAttribute('aria-controls')!))
  })).toBe(true)
  await expect(page.locator('nav[aria-label="Frame history"]')).toHaveCount(1)
  await expect(page.locator('aside[aria-label="Issue #3 details"]')).toHaveCount(1)
  await page.getByRole('button', { name: 'View issue flows', exact: true }).focus()
  for (const key of ['k', 'k', 'k', 'j', 'j', 'j', 'h', 'l']) {
    await page.keyboard.press(key)
    expect(await page.evaluate(() => document.activeElement?.matches('button,a[href],[role="button"],[role="link"]'))).toBe(true)
  }
  await expect(comment).toHaveValue('')
  await comment.focus()
  await page.keyboard.press('Escape')
  await page.keyboard.press('m')
  await expect(page.getByRole('menu', { name: 'Input mode' })).toBeVisible()
})

test('touch guidance and repository footer use taps without key chips', async ({ browser, baseURL }) => {
  const context = await browser.newContext({ baseURL, viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, reducedMotion: 'reduce' })
  const page = await context.newPage()
  await page.goto('/smithersai/smithers/?tutorial')
  await expect(page.getByRole('button', { name: 'Show issues', exact: true })).toBeVisible()
  await expect(page.locator('.guide-chat-controls kbd').first()).toBeHidden()
  await expect(page.getByRole('note', { name: 'Help' })).not.toContainText(/pressing C/)
  await page.getByRole('button', { name: 'Skip tutorial', exact: true }).tap()
  await page.getByRole('button', { name: 'Not now', exact: true }).tap()
  await expect(page.locator('[data-message-step="13"]')).toContainText(/[Tt]ap Chat/)
  await expect(page.locator('[data-message-step="13"]')).not.toContainText(/Press M|press C|H\/J\/K\/L/)
  await page.goto('/smithersai/smithers/')
  await expect(page.getByRole('button', { name: 'Chat', exact: true })).toBeVisible()
  for (const key of await page.locator('.app-chat-controls kbd').all()) await expect(key).toBeHidden()
  await context.close()
})
