import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.route('**/api/bootstrap', route => route.fulfill({ json: {
    apiVersion: 1, host: 'cloud', version: 'test', buildSha: 'test',
    capabilities: ['identity', 'cloud', 'agent'], authFlow: 'redirect', sandbox: null,
  } }))
  await page.route('**/api/auth/session', route => route.fulfill({ json: { status: 'signed-out' } }))
  await page.route('**/api/user', route => route.fulfill({ status: 401, json: { message: 'Sign in' } }))
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Mode: Normal' })).toBeVisible()
  await page.keyboard.press('m')
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: 'Mode: Vim' })).toBeVisible()
})

test('edit a Vim buffer and navigate back to the workspace without closing its draft', async ({ page }) => {
  await page.keyboard.press('Meta+k')
  const input = page.getByTestId('composer-input')
  await expect(input).toBeFocused()
  await input.fill('alpha beta')
  await page.keyboard.press('Escape')
  await expect(input).toBeFocused()
  await expect(page.locator('.keyboard-hints')).toContainText('VIM NORMAL')
  await page.keyboard.press('0')
  await page.keyboard.press('d')
  await page.keyboard.press('w')
  await expect(input).toHaveValue('beta')
  await page.keyboard.press('u')
  await expect(input).toHaveValue('alpha beta')
  await page.keyboard.press('Control+b')
  await expect(page.locator('.keyboard-hints')).toContainText('next key')
  await page.keyboard.press('q')
  await expect(page.locator('.keyboard-hints')).toContainText('Choose a pane')
  const navigation = page.locator('.keyboard-pane-number').filter({ hasText: /^0 Navigation$/ })
  const index = await navigation.locator('kbd').textContent()
  await page.keyboard.press(index!)
  await expect(page.getByTestId('chrome-sign-in')).toBeFocused()
  await expect(input).toBeVisible()
  await expect(input).toHaveValue('alpha beta')
  await page.keyboard.press('Control+b')
  await page.keyboard.press(';')
  await expect(input).toBeFocused()
  await expect(page.locator('.keyboard-hints')).toContainText('VIM NORMAL')
  await page.keyboard.press('A')
  await page.keyboard.type(' gamma')
  await expect(input).toHaveValue('alpha beta gamma')
  await page.keyboard.press('Control+b')
  await page.keyboard.press('q')
  await page.screenshot({ path: '/tmp/smithers-keyboard-panes.png' })
})

test('pane selection enters search results and Escape cancels the prefix without editing', async ({ page }) => {
  await page.keyboard.press('Meta+k')
  const input = page.getByTestId('composer-input')
  await input.fill('/')
  await page.keyboard.press('Control+b')
  await page.keyboard.press('Escape')
  await expect(input).toHaveValue('/')
  await expect(input).toBeFocused()
  await page.keyboard.press('Control+b')
  await page.keyboard.press('q')
  const results = page.locator('.keyboard-pane-number').filter({ hasText: 'Search results' })
  await page.keyboard.press((await results.locator('kbd').textContent())!)
  const options = page.getByRole('listbox', { name: 'Search palette' }).getByRole('option')
  await expect(options.first()).toBeFocused()
  await page.keyboard.press('j')
  await expect(options.nth(1)).toBeFocused()
  await page.keyboard.press('Control+b')
  await page.keyboard.press(';')
  await expect(input).toBeFocused()
  await expect(input).toHaveValue('/')
  await page.keyboard.press('Control+b')
  await page.keyboard.press('?')
  await expect(page.locator('.keyboard-hints')).toContainText('Vim and pane shortcuts')
  await page.keyboard.press('q')
  const mode = page.locator('.keyboard-pane-number').filter({ hasText: 'Input mode' })
  await page.keyboard.press((await mode.locator('kbd').textContent())!)
  await page.keyboard.press('Enter')
  await page.keyboard.press('ArrowUp')
  await page.keyboard.press('Enter')
  await expect(page.locator('.keyboard-hints')).toHaveCount(0)
  await expect(page.getByTestId('composer-overlay')).toBeVisible()
})
