import { expect, test } from "@playwright/test"

for (const viewport of [{ width: 1365, height: 900 }, { width: 390, height: 844 }]) test(`global sidebar and tutorial finish at ${viewport.width}px`, async ({ page }) => {
  await page.setViewportSize(viewport)
  await page.addInitScript(() => {
    class Recognition {
      continuous = false; interimResults = false; lang = "en-US"
      onresult: ((event: unknown) => void) | null = null
      onerror: ((event: unknown) => void) | null = null
      onend: (() => void) | null = null
      start() {} stop() { this.onend?.() } abort() { this.onend?.() }
    }
    Object.assign(window, { SpeechRecognition: Recognition })
  })
  await page.goto("/")
  const logo = page.getByRole("button", { name: "Smithers", exact: true })
  await expect(logo).toBeVisible()
  await expect(logo).toHaveAttribute("aria-expanded", "false")
  await expect(page.locator("#session-sidebar")).toHaveCount(0)
  await logo.click()
  await expect(page.locator("#session-sidebar")).toBeVisible()
  await expect(page.getByTestId("workspace-name")).toHaveText("Chat")
  const markBox = await logo.boundingBox()
  const sidebarBox = await page.locator("#session-sidebar").boundingBox()
  expect(sidebarBox!.y).toBeGreaterThanOrEqual(markBox!.y + markBox!.height)
  await page.keyboard.press("w")
  await expect(page.locator("#session-sidebar")).toHaveCount(0)
  await page.keyboard.press("w")
  await expect(page.locator("#session-sidebar")).toBeVisible()
  await page.reload()
  await expect(logo).toHaveAttribute("aria-expanded", "false")
  await page.keyboard.press("Control+k")
  const input = page.getByTestId("composer-input")
  await expect(input).toBeVisible()
  await input.fill("w")
  await input.press("w")
  await expect(input).toHaveValue("ww")
  await expect(logo).toHaveAttribute("aria-expanded", "false")
  await input.fill("")
  await page.keyboard.press("Escape")
  await expect(page.locator(".guide-shell")).toHaveAttribute("data-stage", "1")
  await page.keyboard.press("q")
  await expect(page.locator(".guide-shell")).toHaveAttribute("data-stage", "10")
  if (await input.isVisible()) await page.keyboard.press("Escape")
  await page.getByRole("button", { name: "Not now" }).click()
  await expect(page.locator(".guide-shell")).toHaveAttribute("data-stage", "13")
  await page.keyboard.press("Control+k")
  await expect(page.locator(".guide-shell")).toHaveAttribute("data-stage", "14")
  await page.keyboard.press("Escape")
  await expect(page.getByRole("button", { name: "Finish tutorial", exact: true })).toBeVisible()
  await page.getByRole("button", { name: "Finish tutorial", exact: true }).click()
  await expect(page.locator(".guide-shell")).toHaveCount(0)
  await logo.click()
  await expect(page.locator("#session-sidebar")).toBeVisible()
  await page.screenshot({ path: `/tmp/smithers-sidebar-${viewport.width}.png`, fullPage: true })
  await logo.click()
  const chat = page.locator('.app-chat-controls [data-flow="palette.open"]')
  const dictate = page.locator('.app-chat-controls [data-flow="chat.dictate"]')
  await expect(chat).toBeVisible()
  await expect(dictate).toBeVisible()
  await expect(page.locator('.guide-chat-controls')).toHaveCount(0)
  await dictate.click()
  await expect(dictate).toHaveAttribute("aria-pressed", "true")
  await expect(input).toBeVisible()
  await dictate.click()
  await expect(dictate).toHaveAttribute("aria-pressed", "false")
  await page.keyboard.press("Escape")
  await chat.click()
  await expect(input).toBeVisible()
  await input.fill("/files.read src/hello.ts practice:smithersai/hello-server")
  await input.press("Enter")
  await expect(input).toBeHidden()
  await chat.click()
  await expect(input).toBeVisible()
  await input.fill("Hello Smithers")
  await input.press("Enter")
  await expect(input).toBeHidden()
  await page.reload()
  await expect(page.locator(".guide-shell")).toHaveCount(0)
  await expect(logo).toHaveAttribute("aria-expanded", "false")
})
