/**
 * No shipped Node composition installs an HTTP client that ignores the egress
 * proxy its environment names.
 *
 * `@effect/platform-node` ships `NodeHttpClient.layerUndici`, whose dispatcher
 * is a bare Undici `Agent`. A bare `Agent` dials every origin directly: it does
 * not read `HTTP_PROXY`, `HTTPS_PROXY` or `NO_PROXY`. Provided under a layer
 * that takes `HttpClient` from context — a judge, a model transport, a fetch
 * rule, a host bundle — it also *shadows* whatever proxy-aware client the host
 * built, and the call site reads as correct either way. That is the whole
 * defect: invisible on a developer machine with open egress, fatal inside a
 * microsandbox whose only way out is a proxy, where the request leaves for the
 * origin, the firewall drops it, and the symptom surfaces as
 * `completion_unjudged` far from the composition that chose the client.
 *
 * The replacement is one constructor,
 * `@smthrs/platform-node/EgressHttpClient`'s `layer(environment)`, which routes
 * through the proxy the environment names and is exactly the plain Undici pool
 * when it names none — so an unproxied host is unchanged and there is no reason
 * for a composition to reach past it.
 *
 * Scope is shipped source. Test trees are deliberately outside: a test that
 * names `layerUndici` is pinning a transport it owns end to end, against a
 * loopback server, with no proxy in the picture, and it is exactly where a
 * direct pool should be spelled out. `@effect/platform-node` itself, under
 * `node_modules`, is not read.
 *
 * Run it with `node --test "scripts/repo-contract/*.test.mjs"`.
 */
import assert from "node:assert/strict"
import { readdirSync, readFileSync } from "node:fs"
import { join, relative, sep } from "node:path"
import { describe, it } from "node:test"

import { repoRoot as root } from "../workspace-packages.mjs"

/** The trees that hold shipped source. `scripts/` is absent on purpose: this file names the banned spelling. */
const scanned = ["packages", "apps", "flows", "examples"]

/**
 * Directory names that hold no shipped source wherever they appear, or hold a
 * copy of somebody else's.
 *
 * `build` is deliberately absent. Pruning that name at any depth would drop
 * `packages/smithers/build/` — @smthrs/build-cli, @smthrs/infra and
 * @smthrs/targets, three shipped packages holding one of the very sites this
 * gate exists for, `FetchExecutor.ts` — and the two `create-app` template
 * directories that are tracked source. Generated `build/` output is named by
 * path in {@link skippedPaths} instead.
 */
const skippedDirectories = new Set([
  "node_modules",
  "dist",
  "coverage",
  "test",
  "tests",
  "e2e",
  "fixtures",
  "__fixtures__",
  ".git",
  ".jj",
  ".astro",
  ".turbo",
  ".vite"
])

/** Generated trees, pruned by repository-relative path so no shipped package sharing a name goes with them. */
const skippedPaths = new Set([
  // Electrobun output: a packaged `.app` holding a bundled copy of this
  // workspace and its dependencies. Gitignored, regenerated by every dev run.
  "apps/app/build"
])

/** Source files, never a test double and never a declaration. */
const isSource = (name) =>
  (name.endsWith(".ts") || name.endsWith(".tsx") || name.endsWith(".mjs"))
  && !name.endsWith(".d.ts")
  && !/\.(test|spec)\.[cm]?tsx?$/.test(name)
  && !/\.(test|spec)\.mjs$/.test(name)

/** Every shipped source file under {@link scanned}, as repository-relative paths. */
export const sources = (repositoryRoot = root) => {
  const found = []
  const walk = (directory) => {
    let entries
    try {
      entries = readdirSync(directory, { withFileTypes: true })
    } catch {
      return
    }
    for (const entry of entries) {
      const path = relative(repositoryRoot, join(directory, entry.name)).split(sep).join("/")
      if (entry.isDirectory()) {
        if (!skippedDirectories.has(entry.name) && !skippedPaths.has(path)) walk(join(directory, entry.name))
      } else if (entry.isFile() && isSource(entry.name)) {
        found.push(path)
      }
    }
  }
  for (const tree of scanned) walk(join(repositoryRoot, tree))
  return found.sort()
}

/** Prose, which may name the banned spelling to explain why it is banned. */
const isComment = (line) => {
  const trimmed = line.trimStart()
  return trimmed.startsWith("//") || trimmed.startsWith("*") || trimmed.startsWith("/*")
}

/**
 * The bare, proxy-blind spellings.
 *
 * `\b` after the name is what keeps `layerUndiciNoDispatcher` out of the ban:
 * that one takes its dispatcher from context, which is how the replacement is
 * built in the first place.
 */
const banned = [
  { pattern: /\blayerUndici\b/, name: "NodeHttpClient.layerUndici" },
  { pattern: /\bmakeDispatcher\b/, name: "NodeHttpClient.makeDispatcher" }
]

/**
 * The one file allowed to name them in code: the constructor that wraps them.
 * Anything else added here has to carry the sentence that says why the
 * environment's proxy does not apply to it.
 */
const defines = "packages/smithers/flows/platform-node/src/EgressHttpClient.ts"

describe("the outbound HTTP client shipped compositions install", () => {
  it("reads shipped source from every tree that composes a Node host", () => {
    const found = sources()
    assert.ok(found.length > 500, `only ${found.length} shipped sources found under ${scanned.join(", ")}`)
    for (const tree of scanned) {
      assert.ok(found.some((path) => path.startsWith(`${tree}/`)), `no shipped source found under ${tree}/`)
    }
    // Named files, not a count: a count stays green while a whole package
    // tree silently leaves the scan. Pruning the bare name `build` at any
    // depth is exactly how the first two of these were invisible to this gate,
    // and the first is one of the sites the gate was written for.
    for (const path of [
      "packages/smithers/build/build-cli/src/internal/rules/FetchExecutor.ts",
      "packages/smithers/create-app/template/aomi/flows/build/flow.ts",
      "packages/smithers/src/internal/NodeControlHost.ts",
      "flows/repository/jev-checks.ts",
      "apps/app/src/bun/BrowserFetch.ts"
    ]) {
      assert.ok(found.includes(path), `${path} is shipped source this gate never read`)
    }
    // Packaged Electrobun output carries a bundled copy of this workspace.
    assert.deepEqual(found.filter((path) => path.startsWith("apps/app/build/")), [])
  })

  it("installs the environment's client everywhere, and the bare pool nowhere", () => {
    const offenders = []
    let installs = 0
    for (const path of sources()) {
      let content
      try {
        content = readFileSync(join(root, path), "utf8")
      } catch {
        continue
      }
      if (content.includes("EgressHttpClient.layer(") || content.includes("layerEgressHttpClient(")) installs += 1
      if (path === defines) continue
      for (const [index, line] of content.split("\n").entries()) {
        if (isComment(line)) continue
        for (const { pattern, name } of banned) {
          if (pattern.test(line)) offenders.push(`${path}:${index + 1} ${name}`)
        }
      }
    }
    // A gate whose subject has vanished is a gate that cannot fail. The
    // replacement has to be installed somewhere for the ban to mean anything.
    assert.ok(installs >= 10, `the environment's client is installed in only ${installs} shipped sources`)
    assert.deepEqual(
      offenders,
      [],
      "a bare Undici pool ignores HTTP_PROXY/HTTPS_PROXY and dials every origin directly, so a host inside a "
        + "default-deny sandbox reaches nothing. Install `EgressHttpClient.layer(environment)` from "
        + "`@smthrs/platform-node`, which is the same plain pool when no proxy is named:\n  "
        + offenders.join("\n  ")
    )
  })
})
