#!/usr/bin/env python3
"""Build the hosted SQLC/test schema from the two authored schema sources.

Product DDL is authored only in product/migrations. The private baseline and
cluster migrations contain deployment-owned objects. schema.sql is generated;
never edit it directly.
"""

import argparse
import csv
import hashlib
import json
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "schema.sql"
PLUE_MANIFEST = ROOT / "cluster" / "plue_sources.json"


def migrations(directory: Path) -> list[Path]:
    files = sorted(directory.glob("[0-9][0-9][0-9][0-9]_*.sql"))
    if not files:
        raise ValueError(f"no migrations in {directory}")
    for version, path in enumerate(files, start=1):
        if int(path.name[:4]) != version:
            raise ValueError(f"migration sequence has a gap at {path}")
    return files


def verify_private_snapshots(plue_root: Path | None, sync_plue: bool) -> None:
    manifest = json.loads(PLUE_MANIFEST.read_text())
    if manifest["authority"] != "plue":
        raise ValueError(f"unexpected private schema authority in {PLUE_MANIFEST}")
    snapshots = {entry["snapshot"] for entry in manifest["files"]}
    expected = {
        str(path.relative_to(ROOT / "cluster"))
        for path in migrations(ROOT / "cluster" / "migrations")
    }
    if snapshots != expected:
        raise ValueError("Plue source manifest does not cover every private migration")
    if plue_root is not None:
        tracked = {entry["upstream"] for entry in manifest["files"]}
        for directory in manifest.get("complete_upstream_directories", []):
            root = plue_root / directory
            upstream_files = {
                str(path.relative_to(plue_root)) for path in root.glob("*.sql")
            }
            if not root.is_dir() or upstream_files != {
                path for path in tracked if Path(path).parent == Path(directory)
            }:
                raise ValueError(
                    f"Plue private migration file set differs from {PLUE_MANIFEST}: {root}"
                )
    for entry in manifest["files"]:
        snapshot = ROOT / "cluster" / entry["snapshot"]
        upstream = plue_root / entry["upstream"] if plue_root else None
        if sync_plue:
            if upstream is None:
                raise ValueError("--sync-plue requires --plue-root")
            if not upstream.is_file():
                raise ValueError(f"private Plue migration is missing: {upstream}")
            data = upstream.read_bytes()
            snapshot.write_bytes(data)
            entry["sha256"] = hashlib.sha256(data).hexdigest()
        data = snapshot.read_bytes()
        if hashlib.sha256(data).hexdigest() != entry["sha256"]:
            raise ValueError(f"private snapshot checksum differs from {PLUE_MANIFEST}: {snapshot}")
        if upstream is not None:
            if not upstream.is_file():
                raise ValueError(f"private Plue migration is missing: {upstream}")
            if upstream.read_bytes() != data:
                raise ValueError(f"private snapshot differs from Plue authority: {upstream}")
    if sync_plue:
        PLUE_MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n")


def generated_schema() -> str:
    product = migrations(ROOT / "product" / "migrations")
    private = [ROOT / "cluster" / "private_baseline.sql"] + migrations(
        ROOT / "cluster" / "migrations"
    )
    with (ROOT / "ownership.csv").open(newline="") as manifest:
        product_tables = {
            row["table"]
            for row in csv.DictReader(manifest)
            if row["target_owner"] == "product"
        }
    for source in private:
        sql = source.read_text()
        if not sql.strip():
            raise ValueError(f"empty private schema source: {source}")
        for match in re.finditer(
            r"(?im)^CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:public\.)?([a-z][a-z0-9_]*)\s*\(",
            sql,
        ):
            if match.group(1) in product_tables:
                raise ValueError(
                    f"{source} duplicates product table {match.group(1)}"
                )
    chunks = [
        "-- Code generated by packages/backend/db/generate_schema.py; DO NOT EDIT.\n",
        "-- Product DDL: product/migrations. Private DDL: cluster/private_baseline.sql\n",
        "-- and cluster/migrations. Apply product migrations separately in production.\n",
        "SET check_function_bodies = false;\n",
    ]
    for source in product + private:
        chunks.append(f"\n-- BEGIN {source.relative_to(ROOT)}\n")
        chunks.append(source.read_text().rstrip() + "\n")
        chunks.append(f"-- END {source.relative_to(ROOT)}\n")
        if source == private[0]:
            chunks.append("CREATE SCHEMA IF NOT EXISTS plue_storage;\n")
    return "".join(chunks)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if schema.sql differs")
    parser.add_argument("--plue-root", type=Path, help="verify the exact private source in a Plue checkout")
    parser.add_argument("--sync-plue", action="store_true", help="copy and checksum Plue's private migrations")
    args = parser.parse_args()
    if args.sync_plue and (args.check or args.plue_root is None):
        parser.error("--sync-plue requires --plue-root and cannot be combined with --check")
    verify_private_snapshots(args.plue_root, args.sync_plue)
    generated = generated_schema()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != generated:
            print(f"{OUTPUT} is stale; run {Path(__file__).name}", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
