import { Effect } from "effect";
import type { OpenApiSpec, OpenApiToolsOptions, ParsedOperation } from "../types";
export declare function buildAuthHeaders(options: OpenApiToolsOptions): Record<string, string>;
export declare function buildUrl(baseUrl: string, path: string, pathParams: Record<string, string>, queryParams: Record<string, string>, options: OpenApiToolsOptions): string;
export declare function executeRequest(operation: ParsedOperation, args: Record<string, any>, baseUrl: string, options: OpenApiToolsOptions): Promise<unknown>;
export declare function executeToolEffect(operation: ParsedOperation, args: Record<string, any>, baseUrl: string, options: OpenApiToolsOptions): Effect.Effect<unknown, unknown, never>;
export declare function createToolFromOperation(operation: ParsedOperation, spec: OpenApiSpec, baseUrl: string, options: OpenApiToolsOptions): any;
export declare function resolveBaseUrl(spec: OpenApiSpec, options: OpenApiToolsOptions): string;
export declare function createOpenApiToolsFromSpec(spec: OpenApiSpec, options: OpenApiToolsOptions): Record<string, any>;
export declare function createOpenApiToolFromSpec(spec: OpenApiSpec, operationId: string, options: OpenApiToolsOptions): any;
