/**
 * Targets for std.smithers.sh, the @smthrs/std documentation site.
 * Generated by apps/docs/shared/gen-sites.mjs from apps/docs/shared/manifest.mjs. Edit the generator, then rerun it: node apps/docs/shared/gen-sites.mjs
 *
 * The content edge is the source package's docsFiles filegroup, imported by
 * label: input globs are package scoped, so a glob declared here could never
 * reach packages/smithers/agent/std. The kit edge is apps/docs/shared's sources group:
 * astro.config.mjs imports its config factory, which mounts its release
 * notice middleware, so the rendered HTML changes when the kit does.
 */
import { Smithers } from "@smthrs/targets"
import { Package as stdPackage } from "../../../packages/smithers/agent/std/PACKAGE.ts"
import { Package as docsSharedPackage } from "../shared/PACKAGE.ts"

const cwd = "apps/docs/std"

/** The site's config, content, styles, scripts, public assets, and tsconfig. */
const sources = [
  Smithers.glob("//apps/docs/std/src/**/*"),
  Smithers.glob("//apps/docs/std/public/**/*"),
  Smithers.file("//apps/docs/std/astro.config.mjs"),
  Smithers.file("//apps/docs/std/package.json"),
  Smithers.file("//apps/docs/std/tsconfig.json")
]

/** The shared Starlight kit the config imports; a filegroup is an edge, and its digest reaches this package's keys. */
const kit = docsSharedPackage.sources

/** `astro check`: the site typechecks against its package tsconfig. */
const check = Smithers.ToolRun({
  command: "pnpm",
  args: ["run", "check"],
  inputs: sources,
  deps: [kit],
  cwd
})

/** `astro build`: the static site into `apps/docs/std/dist`. */
const build = Smithers.ToolBuild({
  tool: "astro",
  command: "pnpm",
  args: ["run", "build"],
  inputs: sources,
  outputs: ["dist"],
  deps: [kit],
  env: {},
  cache: true,
  cwd
})

/**
 * The committed content tree, stitched from @smthrs/std's colocated docs by
 * apps/docs/shared/sync-content.mjs. The committed copy is the cache:
 * `smithers-build lint //apps/docs/std:contentSync` fails on drift,
 * `smithers-build run //apps/docs/std:contentSync` applies.
 */
const contentSync = Smithers.Generate({
  summary: "Sync @smthrs/std's colocated docs into the site content tree; check drift under lint.",
  script: Smithers.file("//apps/docs/shared/sync-content.mjs"),
  env: { SMITHERS_DOCS_SLUG: "std" },
  data: [stdPackage.docsFiles],
  changes: ["src/content/docs/**"]
})

export const Package = Smithers.Package({
  targets: { check, build, contentSync }
})
