"""
Smithers: Build AI agent workflows the way you build software.

Smithers is a Python framework for composing LLM agents into type-safe,
cacheable, parallel workflows.
"""

from smithers.analytics import (
    BudgetExceededAction,
    BudgetExceededError,
    ModelPricing,
    TokenBudget,
    UsageAnalytics,
    UsageSummary,
    calculate_cost,
    clear_custom_pricing,
    get_daily_usage,
    get_model_pricing,
    get_run_cost,
    get_run_tokens,
    recalculate_run_costs,
    register_model_pricing,
)
from smithers.cache import Cache, SqliteCache
from smithers.claude import claude
from smithers.composition import (
    CompositionError,
    EmptyReduceError,
    GraphMergeConflict,
    branch,
    chain,
    compose_graphs,
    get_composition_info,
    map_workflow,
    parallel,
    pipeline,
    reduce_workflow,
    subgraph,
)
from smithers.conditions import (
    Condition,
    ConditionNotMetError,
    ConditionPolicy,
    all_of,
    always,
    any_of,
    dep_succeeded,
    evaluate_condition,
    field_equals,
    field_gt,
    field_gte,
    field_in,
    field_lt,
    get_condition_policy,
    has_attr,
    has_condition,
    never,
    not_,
    run_if,
    skip_if,
    when,
)
from smithers.config import configure
from smithers.errors import (
    ApprovalRejected,
    ClaudeError,
    GraphTimeoutError,
    RateLimitError,
    SmithersTimeoutError,
    WorkflowError,
    WorkflowTimeoutError,
)
from smithers.events import (
    Event,
    EventBus,
    EventTypes,
    Subscription,
    get_event_bus,
    reset_event_bus,
    set_event_bus,
)
from smithers.executor import PauseExecution, resume_run, run_graph_with_store
from smithers.graph import build_graph, run_graph
from smithers.hashing import cache_key, canonical_json, hash_json, hash_string
from smithers.metrics import (
    CounterMetric,
    GaugeMetric,
    HistogramMetric,
    MetricsCollector,
    get_metrics_collector,
    record_llm_call,
    record_tool_call,
    record_workflow_run,
    reset_metrics_collector,
    set_metrics_collector,
)
from smithers.ralph_loop import (
    RalphLoopConfig,
    RalphLoopWorkflow,
    execute_ralph_loop,
    is_ralph_loop,
    ralph_loop,
)
from smithers.ratelimit import (
    CLAUDE_TIER_1_LIMITS,
    CLAUDE_TIER_2_LIMITS,
    CLAUDE_TIER_3_LIMITS,
    CLAUDE_TIER_4_LIMITS,
    RateLimitConfig,
    RateLimiter,
    RateLimitExceededAction,
    RateLimitExceededError,
    RateLimitStats,
    RateLimitStrategy,
    clear_model_rate_limiters,
    configure_claude_rate_limits,
    create_rate_limiter,
    get_rate_limiter,
    register_model_rate_limiter,
    reset_all_rate_limiters,
    set_rate_limiter,
)
from smithers.runtime import (
    RuntimeContext,
    get_current_context,
    runtime_context,
)
from smithers.snapshot import (
    ChangeCategory,
    ChangeType,
    EdgeChange,
    GraphDiff,
    NodeChange,
    NodeSnapshot,
    SnapshotStore,
    WorkflowSnapshot,
    create_snapshot,
    diff_snapshots,
    save_snapshot_to_file,
    snapshot_from_json_file,
    snapshots_equal,
)
from smithers.store.sqlite import LoopIteration, SqliteStore
from smithers.testing import (
    FakeLLMProvider,
    RecordingStore,
    ReplayLLMProvider,
    WorkflowTestCase,
    assert_graph_has_dependency,
    assert_graph_has_nodes,
    assert_graph_is_dag,
    assert_graph_levels,
    assert_workflow_depends_on,
    assert_workflow_produces,
    create_test_graph,
    mock_output,
    use_fake_llm,
    use_recording,
    use_recording_or_replay,
    use_replay,
    use_runtime,
    workflow_call_count,
)
from smithers.timeout import (
    LONG_TIMEOUT,
    MEDIUM_TIMEOUT,
    NO_TIMEOUT,
    SHORT_TIMEOUT,
    TimeoutAction,
    TimeoutPolicy,
    TimeoutState,
    execute_with_timeout,
    get_effective_timeout,
    timeout,
)
from smithers.tools import Tool
from smithers.types import (
    NO_RETRY,
    RETRY_ONCE,
    RETRY_THREE_TIMES,
    RETRY_WITH_BACKOFF,
    CacheStats,
    ExecutionResult,
    RetryPolicy,
    WorkflowGraph,
)
from smithers.verification import (
    CacheVerificationResult,
    GraphVerificationResult,
    IssueCode,
    IssueSeverity,
    OutputVerificationResult,
    VerificationIssue,
    full_verification,
    verify_cache_entry,
    verify_cache_integrity,
    verify_graph,
    verify_output,
    verify_run_state,
    verify_workflow_output,
)
from smithers.visualization import (
    GraphVisualization,
    NodeState,
    NodeStatus,
    ProgressVisualizer,
    create_progress_callback,
    print_graph,
    visualize_graph,
)
from smithers.websocket import (
    ClientConnection,
    ConnectionStats,
    WebSocketMessage,
    WebSocketServer,
    error_message,
    get_websocket_server,
    progress_message,
    reset_websocket_server,
    set_websocket_server,
    status_message,
)
from smithers.workflow import require_approval, require_approval_async, retry, skip, workflow

# Re-export timeout from smithers.timeout for convenience
# Already imported above, but including here for documentation

__version__ = "0.1.0"

__all__ = [
    "CLAUDE_TIER_1_LIMITS",
    "CLAUDE_TIER_2_LIMITS",
    "CLAUDE_TIER_3_LIMITS",
    "CLAUDE_TIER_4_LIMITS",
    # Timeout exports
    "LONG_TIMEOUT",
    "MEDIUM_TIMEOUT",
    "NO_RETRY",
    "NO_TIMEOUT",
    "RETRY_ONCE",
    "RETRY_THREE_TIMES",
    "RETRY_WITH_BACKOFF",
    "SHORT_TIMEOUT",
    # Other exports
    "ApprovalRejected",
    "BudgetExceededAction",
    "BudgetExceededError",
    "Cache",
    "CacheStats",
    "CacheVerificationResult",
    "ChangeCategory",
    "ChangeType",
    "ClaudeError",
    # WebSocket
    "ClientConnection",
    # Composition
    "CompositionError",
    # Conditional execution
    "Condition",
    "ConditionNotMetError",
    "ConditionPolicy",
    "ConnectionStats",
    # Metrics
    "CounterMetric",
    "EdgeChange",
    "EmptyReduceError",
    "Event",
    "EventBus",
    "EventTypes",
    "ExecutionResult",
    "FakeLLMProvider",
    "GaugeMetric",
    "GraphDiff",
    "GraphMergeConflict",
    "GraphTimeoutError",
    "GraphVerificationResult",
    # Visualization
    "GraphVisualization",
    "HistogramMetric",
    "IssueCode",
    "IssueSeverity",
    "LoopIteration",
    "MetricsCollector",
    "ModelPricing",
    "NodeChange",
    "NodeSnapshot",
    "NodeState",
    "NodeStatus",
    "OutputVerificationResult",
    "PauseExecution",
    "ProgressVisualizer",
    "RalphLoopConfig",
    "RalphLoopWorkflow",
    "RateLimitConfig",
    "RateLimitError",
    "RateLimitExceededAction",
    "RateLimitExceededError",
    "RateLimitStats",
    "RateLimitStrategy",
    "RateLimiter",
    "RecordingStore",
    "ReplayLLMProvider",
    "RetryPolicy",
    "RuntimeContext",
    "SmithersTimeoutError",
    "SnapshotStore",
    "SqliteCache",
    "SqliteStore",
    "Subscription",
    "TimeoutAction",
    "TimeoutPolicy",
    "TimeoutState",
    "TokenBudget",
    "Tool",
    "UsageAnalytics",
    "UsageSummary",
    "VerificationIssue",
    "WebSocketMessage",
    "WebSocketServer",
    "WorkflowError",
    "WorkflowGraph",
    "WorkflowSnapshot",
    # Testing helpers
    "WorkflowTestCase",
    "WorkflowTimeoutError",
    "__version__",
    "all_of",
    "always",
    "any_of",
    "assert_graph_has_dependency",
    "assert_graph_has_nodes",
    "assert_graph_is_dag",
    "assert_graph_levels",
    "assert_workflow_depends_on",
    "assert_workflow_produces",
    "branch",
    "build_graph",
    "cache_key",
    "calculate_cost",
    "canonical_json",
    "chain",
    "claude",
    "clear_custom_pricing",
    "clear_model_rate_limiters",
    "compose_graphs",
    "configure",
    "configure_claude_rate_limits",
    "create_progress_callback",
    "create_rate_limiter",
    "create_snapshot",
    "create_test_graph",
    "dep_succeeded",
    "diff_snapshots",
    "error_message",
    "evaluate_condition",
    "execute_ralph_loop",
    "execute_with_timeout",
    "field_equals",
    "field_gt",
    "field_gte",
    "field_in",
    "field_lt",
    "full_verification",
    "get_composition_info",
    "get_condition_policy",
    "get_current_context",
    "get_daily_usage",
    "get_effective_timeout",
    "get_event_bus",
    "get_metrics_collector",
    "get_model_pricing",
    "get_rate_limiter",
    "get_run_cost",
    "get_run_tokens",
    "get_websocket_server",
    "has_attr",
    "has_condition",
    "hash_json",
    "hash_string",
    "is_ralph_loop",
    "map_workflow",
    "mock_output",
    "never",
    "not_",
    "parallel",
    "pipeline",
    "print_graph",
    "progress_message",
    "ralph_loop",
    "recalculate_run_costs",
    "record_llm_call",
    "record_tool_call",
    "record_workflow_run",
    "reduce_workflow",
    "register_model_pricing",
    "register_model_rate_limiter",
    "require_approval",
    "require_approval_async",
    "reset_all_rate_limiters",
    "reset_event_bus",
    "reset_metrics_collector",
    "reset_websocket_server",
    "resume_run",
    "retry",
    "run_graph",
    "run_graph_with_store",
    "run_if",
    "runtime_context",
    "save_snapshot_to_file",
    "set_event_bus",
    "set_metrics_collector",
    "set_rate_limiter",
    "set_websocket_server",
    "skip",
    "skip_if",
    "snapshot_from_json_file",
    "snapshots_equal",
    "status_message",
    "subgraph",
    "timeout",
    "use_fake_llm",
    "use_recording",
    "use_recording_or_replay",
    "use_replay",
    "use_runtime",
    "verify_cache_entry",
    "verify_cache_integrity",
    "verify_graph",
    "verify_output",
    "verify_run_state",
    "verify_workflow_output",
    "visualize_graph",
    "when",
    "workflow",
    "workflow_call_count",
]
