export type SmithersNodeType =
  | "workflow"
  | "task"
  | "sequence"
  | "parallel"
  | "merge-queue"
  | "branch"
  | "loop"
  | "worktree"
  | "approval"
  | "timer"
  | "subflow"
  | "wait-for-event"
  | "saga"
  | "try-catch"
  | "fragment"
  | "unknown";
