// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_manage.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminListAgentSessions = `-- name: AdminListAgentSessions :many
SELECT s.id, s.repository_id, s.user_id, s.workflow_run_id, s.title, s.status, s.metadata, s.workspace_id, s.started_at, s.finished_at, s.created_at, s.updated_at, s.deleted_at, u.username AS username,
       (COALESCE(ru.username, o.name, '') || '/' || r.name)::text AS repository
FROM agent_sessions s JOIN users u ON u.id = s.user_id
JOIN repositories r ON r.id = s.repository_id
LEFT JOIN users ru ON ru.id = r.user_id LEFT JOIN organizations o ON o.id = r.org_id
WHERE s.deleted_at IS NULL AND ($1::text = 'all' OR s.status = $1)
AND ($2::boolean OR NOT u.is_synthetic)
ORDER BY s.created_at DESC, s.id DESC LIMIT $3::int
`

type AdminListAgentSessionsParams struct {
	Status           string `json:"status"`
	IncludeSynthetic bool   `json:"include_synthetic"`
	RowLimit         int32  `json:"row_limit"`
}

type AdminListAgentSessionsRow struct {
	AgentSession AgentSession `json:"agent_session"`
	Username     string       `json:"username"`
	Repository   string       `json:"repository"`
}

func (q *Queries) AdminListAgentSessions(ctx context.Context, arg AdminListAgentSessionsParams) ([]AdminListAgentSessionsRow, error) {
	rows, err := q.db.Query(ctx, adminListAgentSessions, arg.Status, arg.IncludeSynthetic, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListAgentSessionsRow{}
	for rows.Next() {
		var i AdminListAgentSessionsRow
		if err := rows.Scan(
			&i.AgentSession.ID,
			&i.AgentSession.RepositoryID,
			&i.AgentSession.UserID,
			&i.AgentSession.WorkflowRunID,
			&i.AgentSession.Title,
			&i.AgentSession.Status,
			&i.AgentSession.Metadata,
			&i.AgentSession.WorkspaceID,
			&i.AgentSession.StartedAt,
			&i.AgentSession.FinishedAt,
			&i.AgentSession.CreatedAt,
			&i.AgentSession.UpdatedAt,
			&i.AgentSession.DeletedAt,
			&i.Username,
			&i.Repository,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListSandboxHosts = `-- name: AdminListSandboxHosts :many
SELECT h.id, h.provider, h.identity_public_key, h.identity_signed_at, h.base_url, h.boot_id, h.state, h.placement_generation, h.capacity_cpu_millis, h.capacity_memory_bytes, h.capacity_disk_bytes, h.capacity_vms, h.allocated_cpu_millis, h.allocated_memory_bytes, h.allocated_disk_bytes, h.allocated_vms, h.observed_allocated_cpu_millis, h.observed_allocated_memory_bytes, h.observed_allocated_disk_bytes, h.observed_allocated_vms, h.capabilities, h.runtime_version, h.worker_image, h.heartbeat_at, h.lease_expires_at, h.created_at, h.updated_at, (SELECT count(*) FROM sandbox_instances i WHERE i.worker_id = h.id AND i.deleted_at IS NULL)::bigint AS instance_count
FROM sandbox_hosts h ORDER BY h.id
`

type AdminListSandboxHostsRow struct {
	SandboxHost   SandboxHost `json:"sandbox_host"`
	InstanceCount int64       `json:"instance_count"`
}

func (q *Queries) AdminListSandboxHosts(ctx context.Context) ([]AdminListSandboxHostsRow, error) {
	rows, err := q.db.Query(ctx, adminListSandboxHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListSandboxHostsRow{}
	for rows.Next() {
		var i AdminListSandboxHostsRow
		if err := rows.Scan(
			&i.SandboxHost.ID,
			&i.SandboxHost.Provider,
			&i.SandboxHost.IdentityPublicKey,
			&i.SandboxHost.IdentitySignedAt,
			&i.SandboxHost.BaseUrl,
			&i.SandboxHost.BootID,
			&i.SandboxHost.State,
			&i.SandboxHost.PlacementGeneration,
			&i.SandboxHost.CapacityCpuMillis,
			&i.SandboxHost.CapacityMemoryBytes,
			&i.SandboxHost.CapacityDiskBytes,
			&i.SandboxHost.CapacityVms,
			&i.SandboxHost.AllocatedCpuMillis,
			&i.SandboxHost.AllocatedMemoryBytes,
			&i.SandboxHost.AllocatedDiskBytes,
			&i.SandboxHost.AllocatedVms,
			&i.SandboxHost.ObservedAllocatedCpuMillis,
			&i.SandboxHost.ObservedAllocatedMemoryBytes,
			&i.SandboxHost.ObservedAllocatedDiskBytes,
			&i.SandboxHost.ObservedAllocatedVms,
			&i.SandboxHost.Capabilities,
			&i.SandboxHost.RuntimeVersion,
			&i.SandboxHost.WorkerImage,
			&i.SandboxHost.HeartbeatAt,
			&i.SandboxHost.LeaseExpiresAt,
			&i.SandboxHost.CreatedAt,
			&i.SandboxHost.UpdatedAt,
			&i.InstanceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListTokens = `-- name: AdminListTokens :many
SELECT t.id, t.name, u.username, t.scopes, t.last_used_at, t.expires_at, t.created_at
FROM access_tokens t JOIN users u ON u.id = t.user_id
WHERE ($1::int = 0 OR COALESCE(t.last_used_at, t.created_at) < now() - make_interval(days => $1::int))
AND ($2::text = '' OR $2 = ANY(regexp_split_to_array(t.scopes, '[,[:space:]]+')))
AND ($3::int = 0 OR (t.expires_at >= now() AND t.expires_at <= now() + make_interval(days => $3::int)))
ORDER BY t.created_at DESC, t.id DESC LIMIT $4::int
`

type AdminListTokensParams struct {
	UnusedDays   int32  `json:"unused_days"`
	Scope        string `json:"scope"`
	ExpiringDays int32  `json:"expiring_days"`
	RowLimit     int32  `json:"row_limit"`
}

type AdminListTokensRow struct {
	ID         int64              `json:"id"`
	Name       string             `json:"name"`
	Username   string             `json:"username"`
	Scopes     string             `json:"scopes"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

func (q *Queries) AdminListTokens(ctx context.Context, arg AdminListTokensParams) ([]AdminListTokensRow, error) {
	rows, err := q.db.Query(ctx, adminListTokens,
		arg.UnusedDays,
		arg.Scope,
		arg.ExpiringDays,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListTokensRow{}
	for rows.Next() {
		var i AdminListTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Scopes,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListWorkspaces = `-- name: AdminListWorkspaces :many
SELECT w.id, w.repository_id, w.user_id, w.name, w.is_fork, w.parent_workspace_id, w.target_bookmark, w.source_snapshot_id, w.kind, w.environment_source, w.environment_revision, w.environment_closure_hash, w.agent_session_id, w.head_push_token_id, w.environment_image, w.desktop_session_id, w.desktop_session_token_hash, w.desktop_session_expires_at, w.vm_id, w.provisioning_generation, w.status, w.failure_code, w.failure_message, w.provisioning_stage, w.last_activity_at, w.idle_timeout_secs, w.suspended_at, w.started_at, w.resumed_at, w.head_change_id, w.head_commit_id, w.ahead, w.behind, w.last_accessed_at, w.deleted_at, w.created_at, w.updated_at, u.username AS owner,
       (COALESCE(ru.username, o.name, '') || '/' || r.name)::text AS repository
FROM workspaces w JOIN users u ON u.id = w.user_id
JOIN repositories r ON r.id = w.repository_id
LEFT JOIN users ru ON ru.id = r.user_id LEFT JOIN organizations o ON o.id = r.org_id
WHERE w.deleted_at IS NULL
AND ($1::text = '' OR w.status = $1)
AND ($2::text = '' OR w.kind = $2)
AND ($3::text = '' OR u.lower_username = lower($3))
AND ($4::boolean OR NOT u.is_synthetic)
ORDER BY w.created_at DESC, w.id DESC LIMIT $5::int
`

type AdminListWorkspacesParams struct {
	Status           string `json:"status"`
	Kind             string `json:"kind"`
	Owner            string `json:"owner"`
	IncludeSynthetic bool   `json:"include_synthetic"`
	RowLimit         int32  `json:"row_limit"`
}

type AdminListWorkspacesRow struct {
	Workspace  Workspace `json:"workspace"`
	Owner      string    `json:"owner"`
	Repository string    `json:"repository"`
}

func (q *Queries) AdminListWorkspaces(ctx context.Context, arg AdminListWorkspacesParams) ([]AdminListWorkspacesRow, error) {
	rows, err := q.db.Query(ctx, adminListWorkspaces,
		arg.Status,
		arg.Kind,
		arg.Owner,
		arg.IncludeSynthetic,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListWorkspacesRow{}
	for rows.Next() {
		var i AdminListWorkspacesRow
		if err := rows.Scan(
			&i.Workspace.ID,
			&i.Workspace.RepositoryID,
			&i.Workspace.UserID,
			&i.Workspace.Name,
			&i.Workspace.IsFork,
			&i.Workspace.ParentWorkspaceID,
			&i.Workspace.TargetBookmark,
			&i.Workspace.SourceSnapshotID,
			&i.Workspace.Kind,
			&i.Workspace.EnvironmentSource,
			&i.Workspace.EnvironmentRevision,
			&i.Workspace.EnvironmentClosureHash,
			&i.Workspace.AgentSessionID,
			&i.Workspace.HeadPushTokenID,
			&i.Workspace.EnvironmentImage,
			&i.Workspace.DesktopSessionID,
			&i.Workspace.DesktopSessionTokenHash,
			&i.Workspace.DesktopSessionExpiresAt,
			&i.Workspace.VmID,
			&i.Workspace.ProvisioningGeneration,
			&i.Workspace.Status,
			&i.Workspace.FailureCode,
			&i.Workspace.FailureMessage,
			&i.Workspace.ProvisioningStage,
			&i.Workspace.LastActivityAt,
			&i.Workspace.IdleTimeoutSecs,
			&i.Workspace.SuspendedAt,
			&i.Workspace.StartedAt,
			&i.Workspace.ResumedAt,
			&i.Workspace.HeadChangeID,
			&i.Workspace.HeadCommitID,
			&i.Workspace.Ahead,
			&i.Workspace.Behind,
			&i.Workspace.LastAccessedAt,
			&i.Workspace.DeletedAt,
			&i.Workspace.CreatedAt,
			&i.Workspace.UpdatedAt,
			&i.Owner,
			&i.Repository,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminPruneStaleSandboxHosts = `-- name: AdminPruneStaleSandboxHosts :one
WITH pruned AS (
    DELETE FROM sandbox_hosts h
    WHERE h.lease_expires_at < now() - make_interval(hours => $1::int)
    AND NOT EXISTS (SELECT 1 FROM sandbox_instances i WHERE i.worker_id = h.id AND i.deleted_at IS NULL)
    RETURNING h.id
), audited AS (
    INSERT INTO audit_log (event_type, actor_id, actor_name, target_type, target_name, action, metadata, ip_address)
    SELECT 'admin.sandbox_host.prune', $2::bigint, $3::text,
           'sandbox_host', '', 'prune',
           jsonb_build_object('outcome', 'succeeded', 'older_than_hours', $1::int,
                              'pruned', count(*), 'host_ids', COALESCE(jsonb_agg(id ORDER BY id), '[]'::jsonb)),
           $4::text
    FROM pruned
    RETURNING id
)
SELECT count(*)::bigint AS pruned FROM pruned WHERE EXISTS (SELECT 1 FROM audited)
`

type AdminPruneStaleSandboxHostsParams struct {
	OlderThanHours int32       `json:"older_than_hours"`
	ActorID        pgtype.Int8 `json:"actor_id"`
	ActorName      string      `json:"actor_name"`
	IpAddress      string      `json:"ip_address"`
}

// The deletion and its exact affected targets commit with the audit, or neither
// commits. A retry cannot erase the original target list from the audit trail.
func (q *Queries) AdminPruneStaleSandboxHosts(ctx context.Context, arg AdminPruneStaleSandboxHostsParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminPruneStaleSandboxHosts,
		arg.OlderThanHours,
		arg.ActorID,
		arg.ActorName,
		arg.IpAddress,
	)
	var pruned int64
	err := row.Scan(&pruned)
	return pruned, err
}

const failNeverStartedAgentSession = `-- name: FailNeverStartedAgentSession :one
UPDATE agent_sessions SET status = 'failed', finished_at = now(), updated_at = now(),
metadata = metadata || '{"failure_reason":"never_started"}'::jsonb
WHERE id = $1 AND status = 'active' AND started_at IS NULL
AND deleted_at IS NULL AND created_at < $2::timestamptz
RETURNING id, repository_id, user_id, workflow_run_id, title, status, metadata, workspace_id, started_at, finished_at, created_at, updated_at, deleted_at
`

type FailNeverStartedAgentSessionParams struct {
	ID     string    `json:"id"`
	Cutoff time.Time `json:"cutoff"`
}

func (q *Queries) FailNeverStartedAgentSession(ctx context.Context, arg FailNeverStartedAgentSessionParams) (AgentSession, error) {
	row := q.db.QueryRow(ctx, failNeverStartedAgentSession, arg.ID, arg.Cutoff)
	var i AgentSession
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.UserID,
		&i.WorkflowRunID,
		&i.Title,
		&i.Status,
		&i.Metadata,
		&i.WorkspaceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listNeverStartedAgentSessions = `-- name: ListNeverStartedAgentSessions :many
SELECT id, repository_id, user_id, workflow_run_id, title, status, metadata, workspace_id, started_at, finished_at, created_at, updated_at, deleted_at FROM agent_sessions WHERE status = 'active' AND started_at IS NULL
AND deleted_at IS NULL AND created_at < $1::timestamptz
ORDER BY created_at, id LIMIT 200
`

func (q *Queries) ListNeverStartedAgentSessions(ctx context.Context, cutoff time.Time) ([]AgentSession, error) {
	rows, err := q.db.Query(ctx, listNeverStartedAgentSessions, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentSession{}
	for rows.Next() {
		var i AgentSession
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.UserID,
			&i.WorkflowRunID,
			&i.Title,
			&i.Status,
			&i.Metadata,
			&i.WorkspaceID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
