// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devtools_snapshots.sql

package db

import (
	"context"
	"encoding/json"
)

const getDevtoolsSnapshot = `-- name: GetDevtoolsSnapshot :one
SELECT session_id, repository_id, kind, payload, timestamp FROM devtools_snapshots
WHERE session_id = $1 AND kind = $2
`

type GetDevtoolsSnapshotParams struct {
	SessionID string `json:"session_id"`
	Kind      string `json:"kind"`
}

// Admin/debug helper: fetch the current snapshot for a (session, kind) pair.
// Does NOT filter on repository_id; the caller is expected to enforce repo
// scoping using the row's repository_id value.
func (q *Queries) GetDevtoolsSnapshot(ctx context.Context, arg GetDevtoolsSnapshotParams) (DevtoolsSnapshot, error) {
	row := q.db.QueryRow(ctx, getDevtoolsSnapshot, arg.SessionID, arg.Kind)
	var i DevtoolsSnapshot
	err := row.Scan(
		&i.SessionID,
		&i.RepositoryID,
		&i.Kind,
		&i.Payload,
		&i.Timestamp,
	)
	return i, err
}

const listDevtoolsSnapshotsBySession = `-- name: ListDevtoolsSnapshotsBySession :many
SELECT session_id, repository_id, kind, payload, timestamp FROM devtools_snapshots
WHERE repository_id = $1 AND session_id = $2
ORDER BY kind
`

type ListDevtoolsSnapshotsBySessionParams struct {
	RepositoryID int64  `json:"repository_id"`
	SessionID    string `json:"session_id"`
}

// Admin/debug helper: list every current snapshot kind for a session. Not on
// the hot path — realtime stream is the production read path for clients.
func (q *Queries) ListDevtoolsSnapshotsBySession(ctx context.Context, arg ListDevtoolsSnapshotsBySessionParams) ([]DevtoolsSnapshot, error) {
	rows, err := q.db.Query(ctx, listDevtoolsSnapshotsBySession, arg.RepositoryID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DevtoolsSnapshot{}
	for rows.Next() {
		var i DevtoolsSnapshot
		if err := rows.Scan(
			&i.SessionID,
			&i.RepositoryID,
			&i.Kind,
			&i.Payload,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDevtoolsSnapshot = `-- name: UpsertDevtoolsSnapshot :one

INSERT INTO devtools_snapshots (
    session_id, repository_id, kind, payload, timestamp
)
VALUES (
    $1, $2, $3, $4, NOW()
)
ON CONFLICT (session_id, kind) DO UPDATE
SET payload       = EXCLUDED.payload,
    -- repository_id is derived from the session context on the server, so
    -- it should never change for a given session_id. Update it defensively
    -- in case of a schema-level migration or a recovered session rebind.
    repository_id = EXCLUDED.repository_id,
    timestamp     = NOW()
RETURNING session_id, repository_id, kind, payload, timestamp
`

type UpsertDevtoolsSnapshotParams struct {
	SessionID    string          `json:"session_id"`
	RepositoryID int64           `json:"repository_id"`
	Kind         string          `json:"kind"`
	Payload      json.RawMessage `json:"payload"`
}

// Ticket 0107: devtools snapshot surface queries.
//
// Write path: guest-agent -> plue host -> UpsertDevtoolsSnapshot. The UPSERT
// shape enforces the "latest-per-kind" retention policy at the SQL level so
// the service layer never has to race a DELETE + INSERT against concurrent
// writers on the same (session_id, kind).
//
// Read path: the realtime stream `devtools_snapshots` is the production
// reader. Server-side reads are admin/debug helpers only.
// Insert-or-replace a snapshot for (session_id, kind). The ON CONFLICT
// clause keys off the composite PRIMARY KEY and atomically replaces the
// payload + timestamp. Latest-per-kind is a schema invariant; callers
// cannot accidentally produce a second row for the same pair.
func (q *Queries) UpsertDevtoolsSnapshot(ctx context.Context, arg UpsertDevtoolsSnapshotParams) (DevtoolsSnapshot, error) {
	row := q.db.QueryRow(ctx, upsertDevtoolsSnapshot,
		arg.SessionID,
		arg.RepositoryID,
		arg.Kind,
		arg.Payload,
	)
	var i DevtoolsSnapshot
	err := row.Scan(
		&i.SessionID,
		&i.RepositoryID,
		&i.Kind,
		&i.Payload,
		&i.Timestamp,
	)
	return i, err
}
