// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github_repo_listings.sql

package db

import (
	"context"
	"encoding/json"
)

const claimGitHubRepoListingSync = `-- name: ClaimGitHubRepoListingSync :execrows
UPDATE github_repo_listings
SET syncing_since = NOW(),
    updated_at = NOW()
WHERE user_id = $1
  AND (syncing_since IS NULL OR syncing_since < NOW() - INTERVAL '2 minutes')
`

// Singleflight claim for a background refresh: only one caller wins while a
// claim is live; claims older than 2 minutes are considered abandoned (the
// refresher crashed or timed out) and may be taken over.
func (q *Queries) ClaimGitHubRepoListingSync(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, claimGitHubRepoListingSync, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGitHubRepoListing = `-- name: DeleteGitHubRepoListing :exec
DELETE FROM github_repo_listings
WHERE user_id = $1
`

// Invalidate a user's cached listing. Used when a background refresh proves
// the stored GitHub credential is definitively gone (revoked/unlinked): the
// next request must block on the live path and surface the honest 401 that
// clients key their reconnect CTA off, instead of stale repos forever.
func (q *Queries) DeleteGitHubRepoListing(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteGitHubRepoListing, userID)
	return err
}

const getGitHubRepoListing = `-- name: GetGitHubRepoListing :one

SELECT user_id, payload, synced_at, sync_error, syncing_since, created_at, updated_at
FROM github_repo_listings
WHERE user_id = $1
`

// ---- GitHub repo listing cache (stale-while-revalidate /user/repos) ----
func (q *Queries) GetGitHubRepoListing(ctx context.Context, userID int64) (GithubRepoListing, error) {
	row := q.db.QueryRow(ctx, getGitHubRepoListing, userID)
	var i GithubRepoListing
	err := row.Scan(
		&i.UserID,
		&i.Payload,
		&i.SyncedAt,
		&i.SyncError,
		&i.SyncingSince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setGitHubRepoListingSyncError = `-- name: SetGitHubRepoListingSyncError :exec
UPDATE github_repo_listings
SET sync_error = $1::text,
    syncing_since = NULL,
    updated_at = NOW()
WHERE user_id = $2
`

type SetGitHubRepoListingSyncErrorParams struct {
	SyncError string `json:"sync_error"`
	UserID    int64  `json:"user_id"`
}

// Record a background refresh failure WITHOUT touching the last-good payload,
// and release the singleflight claim.
func (q *Queries) SetGitHubRepoListingSyncError(ctx context.Context, arg SetGitHubRepoListingSyncErrorParams) error {
	_, err := q.db.Exec(ctx, setGitHubRepoListingSyncError, arg.SyncError, arg.UserID)
	return err
}

const upsertGitHubRepoListing = `-- name: UpsertGitHubRepoListing :one
INSERT INTO github_repo_listings (user_id, payload, synced_at, sync_error, syncing_since)
VALUES ($1, $2, NOW(), NULL, NULL)
ON CONFLICT (user_id) DO UPDATE
SET payload = EXCLUDED.payload,
    synced_at = NOW(),
    sync_error = NULL,
    syncing_since = NULL,
    updated_at = NOW()
RETURNING user_id, payload, synced_at, sync_error, syncing_since, created_at, updated_at
`

type UpsertGitHubRepoListingParams struct {
	UserID  int64           `json:"user_id"`
	Payload json.RawMessage `json:"payload"`
}

// Store a fresh last-good listing. Clears any recorded sync error and
// releases the singleflight claim.
func (q *Queries) UpsertGitHubRepoListing(ctx context.Context, arg UpsertGitHubRepoListingParams) (GithubRepoListing, error) {
	row := q.db.QueryRow(ctx, upsertGitHubRepoListing, arg.UserID, arg.Payload)
	var i GithubRepoListing
	err := row.Scan(
		&i.UserID,
		&i.Payload,
		&i.SyncedAt,
		&i.SyncError,
		&i.SyncingSince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
