// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issues.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addIssueAssignee = `-- name: AddIssueAssignee :one
WITH repository_lock AS MATERIALIZED (
    SELECT r.id FROM repositories r JOIN issues i ON i.repository_id = r.id
    WHERE i.id = $1 FOR UPDATE OF r
)
INSERT INTO issue_assignees (issue_id, user_id)
SELECT $1, $2 FROM repository_lock
ON CONFLICT DO NOTHING
RETURNING id, issue_id, user_id, created_at
`

type AddIssueAssigneeParams struct {
	IssueID int64       `json:"issue_id"`
	UserID  pgtype.Int8 `json:"user_id"`
}

// ON CONFLICT DO NOTHING handles the partial unique index
// uq_issue_assignees_issue_user (active rows only).
func (q *Queries) AddIssueAssignee(ctx context.Context, arg AddIssueAssigneeParams) (IssueAssignee, error) {
	row := q.db.QueryRow(ctx, addIssueAssignee, arg.IssueID, arg.UserID)
	var i IssueAssignee
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const countIssueCommentsByIssue = `-- name: CountIssueCommentsByIssue :one
SELECT COUNT(*)
FROM issue_comments
WHERE issue_id = $1
`

func (q *Queries) CountIssueCommentsByIssue(ctx context.Context, issueID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countIssueCommentsByIssue, issueID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIssuesByRepoFiltered = `-- name: CountIssuesByRepoFiltered :one
SELECT COUNT(*)
FROM issues
WHERE repository_id = $1
  AND ($2::text = '' OR state = $2::text)
`

type CountIssuesByRepoFilteredParams struct {
	RepositoryID int64  `json:"repository_id"`
	State        string `json:"state"`
}

func (q *Queries) CountIssuesByRepoFiltered(ctx context.Context, arg CountIssuesByRepoFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIssuesByRepoFiltered, arg.RepositoryID, arg.State)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIssue = `-- name: CreateIssue :one
INSERT INTO issues (repository_id, number, title, body, state, author_id, milestone_id)
VALUES ($1, get_next_issue_number($1), $2, $3, 'open', $4, $5)
RETURNING id, repository_id, number, title, body, search_vector, state, author_id, milestone_id, comment_count, closed_at, fixed_by_id, fixed_by_agent_session_id, fixed_at, verified_by_id, verified_by_agent_session_id, verified_at, created_at, updated_at
`

type CreateIssueParams struct {
	RepositoryID int64       `json:"repository_id"`
	Title        string      `json:"title"`
	Body         string      `json:"body"`
	AuthorID     int64       `json:"author_id"`
	MilestoneID  pgtype.Int8 `json:"milestone_id"`
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, createIssue,
		arg.RepositoryID,
		arg.Title,
		arg.Body,
		arg.AuthorID,
		arg.MilestoneID,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Number,
		&i.Title,
		&i.Body,
		&i.SearchVector,
		&i.State,
		&i.AuthorID,
		&i.MilestoneID,
		&i.CommentCount,
		&i.ClosedAt,
		&i.FixedByID,
		&i.FixedByAgentSessionID,
		&i.FixedAt,
		&i.VerifiedByID,
		&i.VerifiedByAgentSessionID,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIssueComment = `-- name: CreateIssueComment :one
WITH repository_lock AS MATERIALIZED (
    SELECT r.id FROM repositories r JOIN issues i ON i.repository_id = r.id
    WHERE i.id = $1 FOR UPDATE OF r
)
INSERT INTO issue_comments (issue_id, user_id, body, commenter, type)
SELECT $1, $2, $3, $4, 'comment' FROM repository_lock
RETURNING id, issue_id, user_id, commenter, body, type, created_at, updated_at
`

type CreateIssueCommentParams struct {
	IssueID   int64       `json:"issue_id"`
	UserID    pgtype.Int8 `json:"user_id"`
	Body      string      `json:"body"`
	Commenter string      `json:"commenter"`
}

func (q *Queries) CreateIssueComment(ctx context.Context, arg CreateIssueCommentParams) (IssueComment, error) {
	row := q.db.QueryRow(ctx, createIssueComment,
		arg.IssueID,
		arg.UserID,
		arg.Body,
		arg.Commenter,
	)
	var i IssueComment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.UserID,
		&i.Commenter,
		&i.Body,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIssueEvent = `-- name: CreateIssueEvent :one
INSERT INTO issue_events (issue_id, actor_id, event_type, payload)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, issue_id, actor_id, event_type, payload, created_at
`

type CreateIssueEventParams struct {
	IssueID   int64           `json:"issue_id"`
	ActorID   pgtype.Int8     `json:"actor_id"`
	EventType string          `json:"event_type"`
	Payload   json.RawMessage `json:"payload"`
}

func (q *Queries) CreateIssueEvent(ctx context.Context, arg CreateIssueEventParams) (IssueEvent, error) {
	row := q.db.QueryRow(ctx, createIssueEvent,
		arg.IssueID,
		arg.ActorID,
		arg.EventType,
		arg.Payload,
	)
	var i IssueEvent
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.ActorID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIssueAssignees = `-- name: DeleteIssueAssignees :exec
WITH repository_lock AS MATERIALIZED (
    SELECT r.id FROM repositories r JOIN issues i ON i.repository_id = r.id
    WHERE i.id = $1 FOR UPDATE OF r
)
DELETE FROM issue_assignees USING repository_lock
WHERE issue_id = $1
`

func (q *Queries) DeleteIssueAssignees(ctx context.Context, issueID int64) error {
	_, err := q.db.Exec(ctx, deleteIssueAssignees, issueID)
	return err
}

const deleteIssueComment = `-- name: DeleteIssueComment :exec
WITH repository_lock AS MATERIALIZED (
    SELECT r.id FROM repositories r JOIN issues i ON i.repository_id = r.id
    JOIN issue_comments c ON c.issue_id = i.id WHERE c.id = $1 FOR UPDATE OF r
)
DELETE FROM issue_comments USING repository_lock
WHERE issue_comments.id = $1
`

func (q *Queries) DeleteIssueComment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteIssueComment, id)
	return err
}

const deleteIssueLabels = `-- name: DeleteIssueLabels :exec
WITH repository_lock AS MATERIALIZED (
    SELECT r.id FROM repositories r JOIN issues i ON i.repository_id = r.id
    WHERE i.id = $1 FOR UPDATE OF r
)
DELETE FROM issue_labels USING repository_lock
WHERE issue_id = $1
`

func (q *Queries) DeleteIssueLabels(ctx context.Context, issueID int64) error {
	_, err := q.db.Exec(ctx, deleteIssueLabels, issueID)
	return err
}

const fixIssuesForLanding = `-- name: FixIssuesForLanding :many
WITH repository_lock AS MATERIALIZED (
    SELECT r.id FROM repositories r JOIN landing_requests lr ON lr.repository_id = r.id
    WHERE lr.id = $1 FOR UPDATE OF r
), linked AS MATERIALIZED (
    SELECT
        i.id AS issue_id,
        i.state AS before_state,
        ARRAY_AGG(DISTINCT lrc.change_id ORDER BY lrc.change_id) AS change_ids
    FROM landing_requests AS lr
    JOIN repository_lock locked ON locked.id = lr.repository_id
    JOIN landing_request_changes AS lrc
      ON lrc.landing_request_id = lr.id
    JOIN issue_change_links AS icl
      ON icl.repository_id = lr.repository_id
     AND icl.change_id = lrc.change_id
    JOIN issues AS i
      ON i.repository_id = icl.repository_id
     AND i.id = icl.issue_id
    WHERE lr.id = $1
      AND i.state NOT IN ('fixed', 'verified')
    GROUP BY i.id, i.state
), fixed AS (
    UPDATE issues AS i
    SET state = 'fixed',
        closed_at = COALESCE(i.closed_at, NOW()),
        fixed_by_id = $2,
        fixed_by_agent_session_id = NULLIF($3::text, '')::uuid,
        fixed_at = NOW(),
        verified_by_id = NULL,
        verified_by_agent_session_id = NULL,
        verified_at = NULL,
        updated_at = NOW()
    FROM linked
    WHERE i.id = linked.issue_id
    RETURNING i.id, linked.before_state, linked.change_ids, i.fixed_at
), recorded AS (
    INSERT INTO issue_events (issue_id, actor_id, event_type, payload)
    SELECT
        fixed.id,
        $2,
        'fixed',
        jsonb_build_object(
            'type', 'fixed',
            'before', jsonb_build_object('state', fixed.before_state),
            'after', jsonb_build_object(
                'state', 'fixed',
                'fixed_by', $2::bigint,
                'fixed_by_agent_session_id', NULLIF($3::text, ''),
                'fixed_at', fixed.fixed_at,
                'linked_changes', to_jsonb(fixed.change_ids),
                'landing_request_id', $1::bigint
            )
        )
    FROM fixed
    RETURNING issue_id
)
SELECT issue_id FROM recorded ORDER BY issue_id
`

type FixIssuesForLandingParams struct {
	LandingRequestID      int64       `json:"landing_request_id"`
	FixedByID             pgtype.Int8 `json:"fixed_by_id"`
	FixedByAgentSessionID string      `json:"fixed_by_agent_session_id"`
}

func (q *Queries) FixIssuesForLanding(ctx context.Context, arg FixIssuesForLandingParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, fixIssuesForLanding, arg.LandingRequestID, arg.FixedByID, arg.FixedByAgentSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var issue_id int64
		if err := rows.Scan(&issue_id); err != nil {
			return nil, err
		}
		items = append(items, issue_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIssueByCommentID = `-- name: GetIssueByCommentID :one
SELECT i.id, i.repository_id, i.number, i.title, i.body, i.search_vector, i.state, i.author_id, i.milestone_id, i.comment_count, i.closed_at, i.fixed_by_id, i.fixed_by_agent_session_id, i.fixed_at, i.verified_by_id, i.verified_by_agent_session_id, i.verified_at, i.created_at, i.updated_at
FROM issues i
JOIN issue_comments ic ON ic.issue_id = i.id
WHERE ic.id = $1
`

func (q *Queries) GetIssueByCommentID(ctx context.Context, id int64) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssueByCommentID, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Number,
		&i.Title,
		&i.Body,
		&i.SearchVector,
		&i.State,
		&i.AuthorID,
		&i.MilestoneID,
		&i.CommentCount,
		&i.ClosedAt,
		&i.FixedByID,
		&i.FixedByAgentSessionID,
		&i.FixedAt,
		&i.VerifiedByID,
		&i.VerifiedByAgentSessionID,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIssueByID = `-- name: GetIssueByID :one
SELECT id, repository_id, number, title, body, search_vector, state, author_id, milestone_id, comment_count, closed_at, fixed_by_id, fixed_by_agent_session_id, fixed_at, verified_by_id, verified_by_agent_session_id, verified_at, created_at, updated_at
FROM issues
WHERE id = $1
`

func (q *Queries) GetIssueByID(ctx context.Context, id int64) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssueByID, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Number,
		&i.Title,
		&i.Body,
		&i.SearchVector,
		&i.State,
		&i.AuthorID,
		&i.MilestoneID,
		&i.CommentCount,
		&i.ClosedAt,
		&i.FixedByID,
		&i.FixedByAgentSessionID,
		&i.FixedAt,
		&i.VerifiedByID,
		&i.VerifiedByAgentSessionID,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIssueByNumber = `-- name: GetIssueByNumber :one
SELECT id, repository_id, number, title, body, search_vector, state, author_id, milestone_id, comment_count, closed_at, fixed_by_id, fixed_by_agent_session_id, fixed_at, verified_by_id, verified_by_agent_session_id, verified_at, created_at, updated_at
FROM issues
WHERE repository_id = $1
  AND number = $2
`

type GetIssueByNumberParams struct {
	RepositoryID int64 `json:"repository_id"`
	Number       int64 `json:"number"`
}

func (q *Queries) GetIssueByNumber(ctx context.Context, arg GetIssueByNumberParams) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssueByNumber, arg.RepositoryID, arg.Number)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Number,
		&i.Title,
		&i.Body,
		&i.SearchVector,
		&i.State,
		&i.AuthorID,
		&i.MilestoneID,
		&i.CommentCount,
		&i.ClosedAt,
		&i.FixedByID,
		&i.FixedByAgentSessionID,
		&i.FixedAt,
		&i.VerifiedByID,
		&i.VerifiedByAgentSessionID,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIssueCommentByID = `-- name: GetIssueCommentByID :one
SELECT id, issue_id, user_id, commenter, body, type, created_at, updated_at
FROM issue_comments
WHERE id = $1
`

func (q *Queries) GetIssueCommentByID(ctx context.Context, id int64) (IssueComment, error) {
	row := q.db.QueryRow(ctx, getIssueCommentByID, id)
	var i IssueComment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.UserID,
		&i.Commenter,
		&i.Body,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIssueAssignees = `-- name: ListIssueAssignees :many
SELECT u.id, u.username, u.display_name, u.avatar_url
FROM issue_assignees ia
JOIN users u ON u.id = ia.user_id
WHERE ia.issue_id = $1
  AND ia.user_id IS NOT NULL
ORDER BY u.username ASC
`

type ListIssueAssigneesRow struct {
	ID          int64  `json:"id"`
	Username    string `json:"username"`
	DisplayName string `json:"display_name"`
	AvatarUrl   string `json:"avatar_url"`
}

// Excludes tombstone rows (user_id IS NULL from ON DELETE SET NULL) since
// the user record is gone and there is nothing to display.
func (q *Queries) ListIssueAssignees(ctx context.Context, issueID int64) ([]ListIssueAssigneesRow, error) {
	rows, err := q.db.Query(ctx, listIssueAssignees, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssueAssigneesRow{}
	for rows.Next() {
		var i ListIssueAssigneesRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueComments = `-- name: ListIssueComments :many
SELECT id, issue_id, user_id, commenter, body, type, created_at, updated_at
FROM issue_comments
WHERE issue_id = $1
ORDER BY created_at ASC, id ASC
LIMIT $3
OFFSET $2
`

type ListIssueCommentsParams struct {
	IssueID    int64 `json:"issue_id"`
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListIssueComments(ctx context.Context, arg ListIssueCommentsParams) ([]IssueComment, error) {
	rows, err := q.db.Query(ctx, listIssueComments, arg.IssueID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueComment{}
	for rows.Next() {
		var i IssueComment
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.UserID,
			&i.Commenter,
			&i.Body,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueCommentsByIssueKeyset = `-- name: ListIssueCommentsByIssueKeyset :many
SELECT id, issue_id, user_id, commenter, body, type, created_at, updated_at
FROM issue_comments
WHERE issue_id = $1
  AND ($2::bigint = 0 OR id > $2::bigint)
ORDER BY id ASC
LIMIT $3
`

type ListIssueCommentsByIssueKeysetParams struct {
	IssueID  int64 `json:"issue_id"`
	AfterID  int64 `json:"after_id"`
	PageSize int32 `json:"page_size"`
}

// Stable cursor pagination for issue comments: returns comments with id > after_id (ASC),
// or all comments when after_id = 0 (first page).
func (q *Queries) ListIssueCommentsByIssueKeyset(ctx context.Context, arg ListIssueCommentsByIssueKeysetParams) ([]IssueComment, error) {
	rows, err := q.db.Query(ctx, listIssueCommentsByIssueKeyset, arg.IssueID, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueComment{}
	for rows.Next() {
		var i IssueComment
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.UserID,
			&i.Commenter,
			&i.Body,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueEventsByIssue = `-- name: ListIssueEventsByIssue :many
SELECT id, issue_id, actor_id, event_type, payload, created_at
FROM issue_events
WHERE issue_id = $1
ORDER BY created_at ASC, id ASC
LIMIT $3
OFFSET $2
`

type ListIssueEventsByIssueParams struct {
	IssueID    int64 `json:"issue_id"`
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListIssueEventsByIssue(ctx context.Context, arg ListIssueEventsByIssueParams) ([]IssueEvent, error) {
	rows, err := q.db.Query(ctx, listIssueEventsByIssue, arg.IssueID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueEvent{}
	for rows.Next() {
		var i IssueEvent
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.ActorID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesByRepoFiltered = `-- name: ListIssuesByRepoFiltered :many
SELECT id, repository_id, number, title, body, search_vector, state, author_id, milestone_id, comment_count, closed_at, fixed_by_id, fixed_by_agent_session_id, fixed_at, verified_by_id, verified_by_agent_session_id, verified_at, created_at, updated_at
FROM issues
WHERE repository_id = $1
  AND ($2::text = '' OR state = $2::text)
ORDER BY number DESC
LIMIT $4
OFFSET $3
`

type ListIssuesByRepoFilteredParams struct {
	RepositoryID int64  `json:"repository_id"`
	State        string `json:"state"`
	PageOffset   int32  `json:"page_offset"`
	PageSize     int32  `json:"page_size"`
}

func (q *Queries) ListIssuesByRepoFiltered(ctx context.Context, arg ListIssuesByRepoFilteredParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssuesByRepoFiltered,
		arg.RepositoryID,
		arg.State,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Number,
			&i.Title,
			&i.Body,
			&i.SearchVector,
			&i.State,
			&i.AuthorID,
			&i.MilestoneID,
			&i.CommentCount,
			&i.ClosedAt,
			&i.FixedByID,
			&i.FixedByAgentSessionID,
			&i.FixedAt,
			&i.VerifiedByID,
			&i.VerifiedByAgentSessionID,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesByRepoFilteredKeyset = `-- name: ListIssuesByRepoFilteredKeyset :many

SELECT id, repository_id, number, title, body, search_vector, state, author_id, milestone_id, comment_count, closed_at, fixed_by_id, fixed_by_agent_session_id, fixed_at, verified_by_id, verified_by_agent_session_id, verified_at, created_at, updated_at
FROM issues
WHERE repository_id = $1
  AND ($2::text = '' OR state = $2::text)
  AND ($3::bigint = 0 OR number < $3::bigint)
ORDER BY number DESC
LIMIT $4
`

type ListIssuesByRepoFilteredKeysetParams struct {
	RepositoryID int64  `json:"repository_id"`
	State        string `json:"state"`
	AfterNumber  int64  `json:"after_number"`
	PageSize     int32  `json:"page_size"`
}

// issues.comment_count and repositories.num_issues / num_closed_issues are
// maintained by database triggers (trg_issue_comments_count_*,
// trg_issues_repo_counts_*); there are intentionally no increment/decrement
// queries for them.
// Stable cursor pagination: returns issues with number < after_number (DESC),
// or all issues when after_number = 0 (first page).
func (q *Queries) ListIssuesByRepoFilteredKeyset(ctx context.Context, arg ListIssuesByRepoFilteredKeysetParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssuesByRepoFilteredKeyset,
		arg.RepositoryID,
		arg.State,
		arg.AfterNumber,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Number,
			&i.Title,
			&i.Body,
			&i.SearchVector,
			&i.State,
			&i.AuthorID,
			&i.MilestoneID,
			&i.CommentCount,
			&i.ClosedAt,
			&i.FixedByID,
			&i.FixedByAgentSessionID,
			&i.FixedAt,
			&i.VerifiedByID,
			&i.VerifiedByAgentSessionID,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkedChangesForIssue = `-- name: ListLinkedChangesForIssue :many
SELECT
    c.change_id,
    c.commit_id,
    c.description,
    icl.link_type,
    icl.created_at
FROM issue_change_links AS icl
JOIN changes AS c
  ON c.repository_id = icl.repository_id
 AND c.change_id = icl.change_id
WHERE icl.issue_id = $1
ORDER BY icl.created_at ASC, c.change_id ASC
`

type ListLinkedChangesForIssueRow struct {
	ChangeID    string    `json:"change_id"`
	CommitID    string    `json:"commit_id"`
	Description string    `json:"description"`
	LinkType    string    `json:"link_type"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ListLinkedChangesForIssue(ctx context.Context, issueID int64) ([]ListLinkedChangesForIssueRow, error) {
	rows, err := q.db.Query(ctx, listLinkedChangesForIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinkedChangesForIssueRow{}
	for rows.Next() {
		var i ListLinkedChangesForIssueRow
		if err := rows.Scan(
			&i.ChangeID,
			&i.CommitID,
			&i.Description,
			&i.LinkType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceIssueAssignees = `-- name: ReplaceIssueAssignees :exec
WITH repository_lock AS MATERIALIZED (
    SELECT r.id FROM repositories r JOIN issues i ON i.repository_id = r.id
    WHERE i.id = $1 FOR UPDATE OF r
), wanted AS (
    SELECT DISTINCT u AS user_id
    FROM UNNEST(COALESCE($2::bigint[], '{}'::bigint[])) AS u
), removed AS (
    DELETE FROM issue_assignees USING repository_lock
    WHERE issue_assignees.issue_id = $1
      AND (issue_assignees.user_id IS NULL
           OR issue_assignees.user_id <> ALL(COALESCE($2::bigint[], '{}'::bigint[])))
)
INSERT INTO issue_assignees (issue_id, user_id)
SELECT $1, w.user_id FROM wanted w, repository_lock
WHERE NOT EXISTS (
    SELECT 1 FROM issue_assignees ia
    WHERE ia.issue_id = $1 AND ia.user_id = w.user_id
)
ON CONFLICT DO NOTHING
`

type ReplaceIssueAssigneesParams struct {
	IssueID int64   `json:"issue_id"`
	UserIds []int64 `json:"user_ids"`
}

// Replaces the issue's assignee set in one statement. Set-diff, not
// delete-all + re-add, so unchanged rows fire no issue_state_facts or
// repository_job_events. Tombstones (user_id NULL from ON DELETE SET NULL) are
// always removed. COALESCE: pgx encodes a nil slice as NULL, and
// `<> ALL(NULL)` is NULL. ON CONFLICT DO NOTHING absorbs a concurrent
// AddIssueAssignee for the same user (partial index
// uq_issue_assignees_issue_user).
func (q *Queries) ReplaceIssueAssignees(ctx context.Context, arg ReplaceIssueAssigneesParams) error {
	_, err := q.db.Exec(ctx, replaceIssueAssignees, arg.IssueID, arg.UserIds)
	return err
}

const replaceIssueLabels = `-- name: ReplaceIssueLabels :exec
WITH repository_lock AS MATERIALIZED (
    SELECT r.id FROM repositories r JOIN issues i ON i.repository_id = r.id
    WHERE i.id = $1 FOR UPDATE OF r
), wanted AS (
    SELECT DISTINCT l AS label_id
    FROM UNNEST(COALESCE($2::bigint[], '{}'::bigint[])) AS l
), removed AS (
    DELETE FROM issue_labels USING repository_lock
    WHERE issue_labels.issue_id = $1
      AND issue_labels.label_id <> ALL(COALESCE($2::bigint[], '{}'::bigint[]))
)
INSERT INTO issue_labels (issue_id, label_id)
SELECT $1, w.label_id FROM wanted w, repository_lock
WHERE NOT EXISTS (
    SELECT 1 FROM issue_labels il
    WHERE il.issue_id = $1 AND il.label_id = w.label_id
)
ON CONFLICT DO NOTHING
`

type ReplaceIssueLabelsParams struct {
	IssueID  int64   `json:"issue_id"`
	LabelIds []int64 `json:"label_ids"`
}

// Replaces the issue's label set in one statement. Set-diff, so unchanged
// labels fire no unlabeled/labeled journal facts or job events.
func (q *Queries) ReplaceIssueLabels(ctx context.Context, arg ReplaceIssueLabelsParams) error {
	_, err := q.db.Exec(ctx, replaceIssueLabels, arg.IssueID, arg.LabelIds)
	return err
}

const updateIssue = `-- name: UpdateIssue :one
WITH repository_lock AS MATERIALIZED (
    SELECT r.id FROM repositories r JOIN issues i ON i.repository_id = r.id
    WHERE i.id = $12 FOR UPDATE OF r
)
UPDATE issues
SET title = $1,
    body = $2,
    state = $3,
    milestone_id = $4,
    closed_at = $5,
    fixed_by_id = $6,
    fixed_by_agent_session_id = NULLIF($7::text, '')::uuid,
    fixed_at = $8,
    verified_by_id = $9,
    verified_by_agent_session_id = NULLIF($10::text, '')::uuid,
    verified_at = $11,
    updated_at = NOW()
FROM repository_lock
WHERE issues.id = $12 AND issues.repository_id = repository_lock.id
RETURNING issues.id, issues.repository_id, issues.number, issues.title, issues.body, issues.search_vector, issues.state, issues.author_id, issues.milestone_id, issues.comment_count, issues.closed_at, issues.fixed_by_id, issues.fixed_by_agent_session_id, issues.fixed_at, issues.verified_by_id, issues.verified_by_agent_session_id, issues.verified_at, issues.created_at, issues.updated_at
`

type UpdateIssueParams struct {
	Title                    string             `json:"title"`
	Body                     string             `json:"body"`
	State                    string             `json:"state"`
	MilestoneID              pgtype.Int8        `json:"milestone_id"`
	ClosedAt                 pgtype.Timestamptz `json:"closed_at"`
	FixedByID                pgtype.Int8        `json:"fixed_by_id"`
	FixedByAgentSessionID    string             `json:"fixed_by_agent_session_id"`
	FixedAt                  pgtype.Timestamptz `json:"fixed_at"`
	VerifiedByID             pgtype.Int8        `json:"verified_by_id"`
	VerifiedByAgentSessionID string             `json:"verified_by_agent_session_id"`
	VerifiedAt               pgtype.Timestamptz `json:"verified_at"`
	ID                       int64              `json:"id"`
}

func (q *Queries) UpdateIssue(ctx context.Context, arg UpdateIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, updateIssue,
		arg.Title,
		arg.Body,
		arg.State,
		arg.MilestoneID,
		arg.ClosedAt,
		arg.FixedByID,
		arg.FixedByAgentSessionID,
		arg.FixedAt,
		arg.VerifiedByID,
		arg.VerifiedByAgentSessionID,
		arg.VerifiedAt,
		arg.ID,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Number,
		&i.Title,
		&i.Body,
		&i.SearchVector,
		&i.State,
		&i.AuthorID,
		&i.MilestoneID,
		&i.CommentCount,
		&i.ClosedAt,
		&i.FixedByID,
		&i.FixedByAgentSessionID,
		&i.FixedAt,
		&i.VerifiedByID,
		&i.VerifiedByAgentSessionID,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIssueComment = `-- name: UpdateIssueComment :one
UPDATE issue_comments
SET body = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, issue_id, user_id, commenter, body, type, created_at, updated_at
`

type UpdateIssueCommentParams struct {
	Body string `json:"body"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateIssueComment(ctx context.Context, arg UpdateIssueCommentParams) (IssueComment, error) {
	row := q.db.QueryRow(ctx, updateIssueComment, arg.Body, arg.ID)
	var i IssueComment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.UserID,
		&i.Commenter,
		&i.Body,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
