// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lfs.sql

package db

import (
	"context"
	"time"
)

const countLFSLocks = `-- name: CountLFSLocks :one
SELECT COUNT(*)
FROM lfs_locks
WHERE repository_id = $1
`

func (q *Queries) CountLFSLocks(ctx context.Context, repositoryID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLFSLocks, repositoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLFSObjects = `-- name: CountLFSObjects :one
SELECT COUNT(*)
FROM lfs_objects
WHERE repository_id = $1
`

func (q *Queries) CountLFSObjects(ctx context.Context, repositoryID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLFSObjects, repositoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLFSLock = `-- name: CreateLFSLock :one
INSERT INTO lfs_locks (repository_id, path, owner_id)
VALUES ($1, $2, $3)
RETURNING id, repository_id, path, owner_id, created_at
`

type CreateLFSLockParams struct {
	RepositoryID int64  `json:"repository_id"`
	Path         string `json:"path"`
	OwnerID      int64  `json:"owner_id"`
}

func (q *Queries) CreateLFSLock(ctx context.Context, arg CreateLFSLockParams) (LfsLock, error) {
	row := q.db.QueryRow(ctx, createLFSLock, arg.RepositoryID, arg.Path, arg.OwnerID)
	var i LfsLock
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Path,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const createLFSObject = `-- name: CreateLFSObject :one
INSERT INTO lfs_objects (repository_id, oid, size, gcs_path)
VALUES ($1, $2, $3, $4)
RETURNING id, repository_id, oid, size, gcs_path, created_at
`

type CreateLFSObjectParams struct {
	RepositoryID int64  `json:"repository_id"`
	Oid          string `json:"oid"`
	Size         int64  `json:"size"`
	GcsPath      string `json:"gcs_path"`
}

func (q *Queries) CreateLFSObject(ctx context.Context, arg CreateLFSObjectParams) (LfsObject, error) {
	row := q.db.QueryRow(ctx, createLFSObject,
		arg.RepositoryID,
		arg.Oid,
		arg.Size,
		arg.GcsPath,
	)
	var i LfsObject
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Oid,
		&i.Size,
		&i.GcsPath,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredLFSUploadReservation = `-- name: DeleteExpiredLFSUploadReservation :execrows
DELETE FROM lfs_upload_reservations
WHERE repository_id = $1
  AND oid = $2
  AND expires_at <= NOW()
`

type DeleteExpiredLFSUploadReservationParams struct {
	RepositoryID int64  `json:"repository_id"`
	Oid          string `json:"oid"`
}

func (q *Queries) DeleteExpiredLFSUploadReservation(ctx context.Context, arg DeleteExpiredLFSUploadReservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredLFSUploadReservation, arg.RepositoryID, arg.Oid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLFSLockByID = `-- name: DeleteLFSLockByID :exec
DELETE FROM lfs_locks
WHERE repository_id = $1
  AND id = $2
`

type DeleteLFSLockByIDParams struct {
	RepositoryID int64 `json:"repository_id"`
	ID           int64 `json:"id"`
}

func (q *Queries) DeleteLFSLockByID(ctx context.Context, arg DeleteLFSLockByIDParams) error {
	_, err := q.db.Exec(ctx, deleteLFSLockByID, arg.RepositoryID, arg.ID)
	return err
}

const deleteLFSLockByPath = `-- name: DeleteLFSLockByPath :exec
DELETE FROM lfs_locks
WHERE repository_id = $1
  AND path = $2
`

type DeleteLFSLockByPathParams struct {
	RepositoryID int64  `json:"repository_id"`
	Path         string `json:"path"`
}

func (q *Queries) DeleteLFSLockByPath(ctx context.Context, arg DeleteLFSLockByPathParams) error {
	_, err := q.db.Exec(ctx, deleteLFSLockByPath, arg.RepositoryID, arg.Path)
	return err
}

const deleteLFSObject = `-- name: DeleteLFSObject :execrows
DELETE FROM lfs_objects
WHERE id = $1
  AND repository_id = $2
  AND oid = $3
`

type DeleteLFSObjectParams struct {
	ID           int64  `json:"id"`
	RepositoryID int64  `json:"repository_id"`
	Oid          string `json:"oid"`
}

// Exact-identity metadata CAS. The user-facing delete path must distinguish a
// successful removal from a stale/repeated delete after it has purged the blob.
func (q *Queries) DeleteLFSObject(ctx context.Context, arg DeleteLFSObjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLFSObject, arg.ID, arg.RepositoryID, arg.Oid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLFSUploadReservation = `-- name: DeleteLFSUploadReservation :exec
DELETE FROM lfs_upload_reservations
WHERE repository_id = $1
  AND oid = $2
`

type DeleteLFSUploadReservationParams struct {
	RepositoryID int64  `json:"repository_id"`
	Oid          string `json:"oid"`
}

func (q *Queries) DeleteLFSUploadReservation(ctx context.Context, arg DeleteLFSUploadReservationParams) error {
	_, err := q.db.Exec(ctx, deleteLFSUploadReservation, arg.RepositoryID, arg.Oid)
	return err
}

const deleteUnissuedLFSUploadReservation = `-- name: DeleteUnissuedLFSUploadReservation :execrows
DELETE FROM lfs_upload_reservations
WHERE repository_id = $1::bigint
  AND oid = $2::text
  AND size = $3::bigint
  AND expires_at = $4::timestamptz
  AND created_at = $5::timestamptz
  AND updated_at = $6::timestamptz
`

type DeleteUnissuedLFSUploadReservationParams struct {
	RepositoryID int64     `json:"repository_id"`
	Oid          string    `json:"oid"`
	Size         int64     `json:"size"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// Signer-failure rollback only. Match the complete reservation snapshot so a
// refresh/replacement that may own an escaped capability is never removed.
func (q *Queries) DeleteUnissuedLFSUploadReservation(ctx context.Context, arg DeleteUnissuedLFSUploadReservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUnissuedLFSUploadReservation,
		arg.RepositoryID,
		arg.Oid,
		arg.Size,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLFSLockByPath = `-- name: GetLFSLockByPath :one
SELECT id, repository_id, path, owner_id, created_at
FROM lfs_locks
WHERE repository_id = $1
  AND path = $2
`

type GetLFSLockByPathParams struct {
	RepositoryID int64  `json:"repository_id"`
	Path         string `json:"path"`
}

func (q *Queries) GetLFSLockByPath(ctx context.Context, arg GetLFSLockByPathParams) (LfsLock, error) {
	row := q.db.QueryRow(ctx, getLFSLockByPath, arg.RepositoryID, arg.Path)
	var i LfsLock
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Path,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getLFSObjectByOID = `-- name: GetLFSObjectByOID :one
SELECT id, repository_id, oid, size, gcs_path, created_at
FROM lfs_objects
WHERE repository_id = $1
  AND oid = $2
`

type GetLFSObjectByOIDParams struct {
	RepositoryID int64  `json:"repository_id"`
	Oid          string `json:"oid"`
}

func (q *Queries) GetLFSObjectByOID(ctx context.Context, arg GetLFSObjectByOIDParams) (LfsObject, error) {
	row := q.db.QueryRow(ctx, getLFSObjectByOID, arg.RepositoryID, arg.Oid)
	var i LfsObject
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Oid,
		&i.Size,
		&i.GcsPath,
		&i.CreatedAt,
	)
	return i, err
}

const getLFSUploadReservation = `-- name: GetLFSUploadReservation :one
SELECT id, repository_id, oid, size, expires_at, created_at, updated_at
FROM lfs_upload_reservations
WHERE repository_id = $1
  AND oid = $2
`

type GetLFSUploadReservationParams struct {
	RepositoryID int64  `json:"repository_id"`
	Oid          string `json:"oid"`
}

func (q *Queries) GetLFSUploadReservation(ctx context.Context, arg GetLFSUploadReservationParams) (LfsUploadReservation, error) {
	row := q.db.QueryRow(ctx, getLFSUploadReservation, arg.RepositoryID, arg.Oid)
	var i LfsUploadReservation
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Oid,
		&i.Size,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiredLFSUploadReservationsByOwner = `-- name: ListExpiredLFSUploadReservationsByOwner :many
SELECT lur.id, lur.repository_id, lur.oid, lur.size, lur.expires_at, lur.created_at, lur.updated_at
FROM lfs_upload_reservations lur
WHERE lur.repository_id = $1
  AND lur.expires_at <= NOW()
ORDER BY lur.oid
LIMIT 256
`

// The caller holds only this repository's ownership lock through physical
// deletion. Selecting owner siblings here would let one of those repositories
// transfer and refresh its upload while cleanup removes its bytes.
func (q *Queries) ListExpiredLFSUploadReservationsByOwner(ctx context.Context, repositoryID int64) ([]LfsUploadReservation, error) {
	rows, err := q.db.Query(ctx, listExpiredLFSUploadReservationsByOwner, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LfsUploadReservation{}
	for rows.Next() {
		var i LfsUploadReservation
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Oid,
			&i.Size,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLFSLocks = `-- name: ListLFSLocks :many
SELECT id, repository_id, path, owner_id, created_at
FROM lfs_locks
WHERE repository_id = $1
ORDER BY id ASC
LIMIT $3
OFFSET $2
`

type ListLFSLocksParams struct {
	RepositoryID int64 `json:"repository_id"`
	PageOffset   int32 `json:"page_offset"`
	PageSize     int32 `json:"page_size"`
}

func (q *Queries) ListLFSLocks(ctx context.Context, arg ListLFSLocksParams) ([]LfsLock, error) {
	rows, err := q.db.Query(ctx, listLFSLocks, arg.RepositoryID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LfsLock{}
	for rows.Next() {
		var i LfsLock
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Path,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLFSObjects = `-- name: ListLFSObjects :many
SELECT id, repository_id, oid, size, gcs_path, created_at
FROM lfs_objects
WHERE repository_id = $1
ORDER BY id ASC
LIMIT $3
OFFSET $2
`

type ListLFSObjectsParams struct {
	RepositoryID int64 `json:"repository_id"`
	PageOffset   int32 `json:"page_offset"`
	PageSize     int32 `json:"page_size"`
}

func (q *Queries) ListLFSObjects(ctx context.Context, arg ListLFSObjectsParams) ([]LfsObject, error) {
	rows, err := q.db.Query(ctx, listLFSObjects, arg.RepositoryID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LfsObject{}
	for rows.Next() {
		var i LfsObject
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Oid,
			&i.Size,
			&i.GcsPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLFSUploadReservation = `-- name: UpsertLFSUploadReservation :one
INSERT INTO lfs_upload_reservations (repository_id, oid, size, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (repository_id, oid) DO UPDATE
SET size = EXCLUDED.size,
    -- Never shorten the fence for a capability issued by an older process
    -- with a longer configured lifetime. A config-lowering restart may
    -- refresh the same deterministic pending key while that older signed URL
    -- is still usable.
    expires_at = GREATEST(lfs_upload_reservations.expires_at, EXCLUDED.expires_at),
    updated_at = NOW()
RETURNING id, repository_id, oid, size, expires_at, created_at, updated_at
`

type UpsertLFSUploadReservationParams struct {
	RepositoryID int64     `json:"repository_id"`
	Oid          string    `json:"oid"`
	Size         int64     `json:"size"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) UpsertLFSUploadReservation(ctx context.Context, arg UpsertLFSUploadReservationParams) (LfsUploadReservation, error) {
	row := q.db.QueryRow(ctx, upsertLFSUploadReservation,
		arg.RepositoryID,
		arg.Oid,
		arg.Size,
		arg.ExpiresAt,
	)
	var i LfsUploadReservation
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Oid,
		&i.Size,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
