// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_preferences.sql

package db

import (
	"context"
)

const getNotificationPreferences = `-- name: GetNotificationPreferences :one
SELECT user_id, notify_issues, notify_landings, notify_mentions, created_at, updated_at
FROM user_notification_preferences
WHERE user_id = $1
`

func (q *Queries) GetNotificationPreferences(ctx context.Context, userID int64) (UserNotificationPreference, error) {
	row := q.db.QueryRow(ctx, getNotificationPreferences, userID)
	var i UserNotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.NotifyIssues,
		&i.NotifyLandings,
		&i.NotifyMentions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNotificationPreferences = `-- name: UpsertNotificationPreferences :one
INSERT INTO user_notification_preferences (user_id, notify_issues, notify_landings, notify_mentions)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (user_id)
DO UPDATE SET
    notify_issues   = EXCLUDED.notify_issues,
    notify_landings = EXCLUDED.notify_landings,
    notify_mentions = EXCLUDED.notify_mentions,
    updated_at      = NOW()
RETURNING user_id, notify_issues, notify_landings, notify_mentions, created_at, updated_at
`

type UpsertNotificationPreferencesParams struct {
	UserID         int64 `json:"user_id"`
	NotifyIssues   bool  `json:"notify_issues"`
	NotifyLandings bool  `json:"notify_landings"`
	NotifyMentions bool  `json:"notify_mentions"`
}

func (q *Queries) UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) (UserNotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPreferences,
		arg.UserID,
		arg.NotifyIssues,
		arg.NotifyLandings,
		arg.NotifyMentions,
	)
	var i UserNotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.NotifyIssues,
		&i.NotifyLandings,
		&i.NotifyMentions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
