// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider_connections.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProviderConnectionGrant = `-- name: AddProviderConnectionGrant :one
INSERT INTO provider_connection_grants (connection_id, repository_id, org_id, all_repositories)
VALUES ($1, $2, $3, $4)
RETURNING id, connection_id, repository_id, org_id, all_repositories, created_at
`

type AddProviderConnectionGrantParams struct {
	ConnectionID    string      `json:"connection_id"`
	RepositoryID    pgtype.Int8 `json:"repository_id"`
	OrgID           pgtype.Int8 `json:"org_id"`
	AllRepositories bool        `json:"all_repositories"`
}

func (q *Queries) AddProviderConnectionGrant(ctx context.Context, arg AddProviderConnectionGrantParams) (ProviderConnectionGrant, error) {
	row := q.db.QueryRow(ctx, addProviderConnectionGrant,
		arg.ConnectionID,
		arg.RepositoryID,
		arg.OrgID,
		arg.AllRepositories,
	)
	var i ProviderConnectionGrant
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.RepositoryID,
		&i.OrgID,
		&i.AllRepositories,
		&i.CreatedAt,
	)
	return i, err
}

const claimProviderConnectionForRefresh = `-- name: ClaimProviderConnectionForRefresh :one
WITH due AS (
    SELECT id
    FROM provider_connections
    WHERE state = 'active'
      AND refresh_token_encrypted IS NOT NULL
      AND (access_expires_at IS NULL OR access_expires_at <= $2::timestamptz)
      AND (next_refresh_at IS NULL OR next_refresh_at <= NOW())
    ORDER BY access_expires_at ASC NULLS FIRST, id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE provider_connections pc
SET next_refresh_at = $1::timestamptz, updated_at = NOW()
FROM due
WHERE pc.id = due.id
RETURNING pc.id, pc.owner_type, pc.user_id, pc.org_id, pc.provider, pc.kind, pc.label, pc.account_email, pc.account_id, pc.plan, pc.access_token_encrypted, pc.refresh_token_encrypted, pc.access_expires_at, pc.state, pc.last_refresh_at, pc.next_refresh_at, pc.refresh_failures, pc.last_error, pc.created_by, pc.created_at, pc.updated_at
`

type ClaimProviderConnectionForRefreshParams struct {
	LeaseUntil    time.Time `json:"lease_until"`
	ExpiresBefore time.Time `json:"expires_before"`
}

// Leases one refreshable connection whose access token expires within the
// horizon (or already did) by pushing next_refresh_at forward; the caller
// refreshes outside the transaction and then records the result.
func (q *Queries) ClaimProviderConnectionForRefresh(ctx context.Context, arg ClaimProviderConnectionForRefreshParams) (ProviderConnection, error) {
	row := q.db.QueryRow(ctx, claimProviderConnectionForRefresh, arg.LeaseUntil, arg.ExpiresBefore)
	var i ProviderConnection
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.UserID,
		&i.OrgID,
		&i.Provider,
		&i.Kind,
		&i.Label,
		&i.AccountEmail,
		&i.AccountID,
		&i.Plan,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.AccessExpiresAt,
		&i.State,
		&i.LastRefreshAt,
		&i.NextRefreshAt,
		&i.RefreshFailures,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProviderConnection = `-- name: CreateProviderConnection :one
INSERT INTO provider_connections (
    owner_type, user_id, org_id, provider, kind, label, account_email, account_id, plan,
    access_token_encrypted, refresh_token_encrypted, access_expires_at, next_refresh_at, created_by
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12,
    $13, $14
)
RETURNING id, owner_type, user_id, org_id, provider, kind, label, account_email, account_id, plan, access_token_encrypted, refresh_token_encrypted, access_expires_at, state, last_refresh_at, next_refresh_at, refresh_failures, last_error, created_by, created_at, updated_at
`

type CreateProviderConnectionParams struct {
	OwnerType             string             `json:"owner_type"`
	UserID                pgtype.Int8        `json:"user_id"`
	OrgID                 pgtype.Int8        `json:"org_id"`
	Provider              string             `json:"provider"`
	Kind                  string             `json:"kind"`
	Label                 string             `json:"label"`
	AccountEmail          string             `json:"account_email"`
	AccountID             string             `json:"account_id"`
	Plan                  string             `json:"plan"`
	AccessTokenEncrypted  []byte             `json:"access_token_encrypted"`
	RefreshTokenEncrypted []byte             `json:"refresh_token_encrypted"`
	AccessExpiresAt       pgtype.Timestamptz `json:"access_expires_at"`
	NextRefreshAt         pgtype.Timestamptz `json:"next_refresh_at"`
	CreatedBy             pgtype.Int8        `json:"created_by"`
}

func (q *Queries) CreateProviderConnection(ctx context.Context, arg CreateProviderConnectionParams) (ProviderConnection, error) {
	row := q.db.QueryRow(ctx, createProviderConnection,
		arg.OwnerType,
		arg.UserID,
		arg.OrgID,
		arg.Provider,
		arg.Kind,
		arg.Label,
		arg.AccountEmail,
		arg.AccountID,
		arg.Plan,
		arg.AccessTokenEncrypted,
		arg.RefreshTokenEncrypted,
		arg.AccessExpiresAt,
		arg.NextRefreshAt,
		arg.CreatedBy,
	)
	var i ProviderConnection
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.UserID,
		&i.OrgID,
		&i.Provider,
		&i.Kind,
		&i.Label,
		&i.AccountEmail,
		&i.AccountID,
		&i.Plan,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.AccessExpiresAt,
		&i.State,
		&i.LastRefreshAt,
		&i.NextRefreshAt,
		&i.RefreshFailures,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProviderConnectionGrant = `-- name: DeleteProviderConnectionGrant :execrows
DELETE FROM provider_connection_grants WHERE id = $1 AND connection_id = $2
`

type DeleteProviderConnectionGrantParams struct {
	ID           int64  `json:"id"`
	ConnectionID string `json:"connection_id"`
}

func (q *Queries) DeleteProviderConnectionGrant(ctx context.Context, arg DeleteProviderConnectionGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProviderConnectionGrant, arg.ID, arg.ConnectionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProviderConnection = `-- name: GetProviderConnection :one
SELECT id, owner_type, user_id, org_id, provider, kind, label, account_email, account_id, plan, access_token_encrypted, refresh_token_encrypted, access_expires_at, state, last_refresh_at, next_refresh_at, refresh_failures, last_error, created_by, created_at, updated_at FROM provider_connections WHERE id = $1
`

func (q *Queries) GetProviderConnection(ctx context.Context, id string) (ProviderConnection, error) {
	row := q.db.QueryRow(ctx, getProviderConnection, id)
	var i ProviderConnection
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.UserID,
		&i.OrgID,
		&i.Provider,
		&i.Kind,
		&i.Label,
		&i.AccountEmail,
		&i.AccountID,
		&i.Plan,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.AccessExpiresAt,
		&i.State,
		&i.LastRefreshAt,
		&i.NextRefreshAt,
		&i.RefreshFailures,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryProviderConnectionPreference = `-- name: GetRepositoryProviderConnectionPreference :one
SELECT provider_connection_preference FROM repository_agent_environments WHERE repository_id = $1
`

func (q *Queries) GetRepositoryProviderConnectionPreference(ctx context.Context, repositoryID int64) (string, error) {
	row := q.db.QueryRow(ctx, getRepositoryProviderConnectionPreference, repositoryID)
	var provider_connection_preference string
	err := row.Scan(&provider_connection_preference)
	return provider_connection_preference, err
}

const listOrgProviderConnections = `-- name: ListOrgProviderConnections :many
SELECT id, owner_type, user_id, org_id, provider, kind, label, account_email, account_id, plan, access_token_encrypted, refresh_token_encrypted, access_expires_at, state, last_refresh_at, next_refresh_at, refresh_failures, last_error, created_by, created_at, updated_at FROM provider_connections
WHERE owner_type = 'org' AND org_id = $1
ORDER BY created_at DESC, id
`

func (q *Queries) ListOrgProviderConnections(ctx context.Context, orgID pgtype.Int8) ([]ProviderConnection, error) {
	rows, err := q.db.Query(ctx, listOrgProviderConnections, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderConnection{}
	for rows.Next() {
		var i ProviderConnection
		if err := rows.Scan(
			&i.ID,
			&i.OwnerType,
			&i.UserID,
			&i.OrgID,
			&i.Provider,
			&i.Kind,
			&i.Label,
			&i.AccountEmail,
			&i.AccountID,
			&i.Plan,
			&i.AccessTokenEncrypted,
			&i.RefreshTokenEncrypted,
			&i.AccessExpiresAt,
			&i.State,
			&i.LastRefreshAt,
			&i.NextRefreshAt,
			&i.RefreshFailures,
			&i.LastError,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderConnectionGrants = `-- name: ListProviderConnectionGrants :many
SELECT id, connection_id, repository_id, org_id, all_repositories, created_at FROM provider_connection_grants WHERE connection_id = $1 ORDER BY id
`

func (q *Queries) ListProviderConnectionGrants(ctx context.Context, connectionID string) ([]ProviderConnectionGrant, error) {
	rows, err := q.db.Query(ctx, listProviderConnectionGrants, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderConnectionGrant{}
	for rows.Next() {
		var i ProviderConnectionGrant
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.RepositoryID,
			&i.OrgID,
			&i.AllRepositories,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProviderConnections = `-- name: ListUserProviderConnections :many
SELECT id, owner_type, user_id, org_id, provider, kind, label, account_email, account_id, plan, access_token_encrypted, refresh_token_encrypted, access_expires_at, state, last_refresh_at, next_refresh_at, refresh_failures, last_error, created_by, created_at, updated_at FROM provider_connections
WHERE owner_type = 'user' AND user_id = $1
ORDER BY created_at DESC, id
`

func (q *Queries) ListUserProviderConnections(ctx context.Context, userID pgtype.Int8) ([]ProviderConnection, error) {
	rows, err := q.db.Query(ctx, listUserProviderConnections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderConnection{}
	for rows.Next() {
		var i ProviderConnection
		if err := rows.Scan(
			&i.ID,
			&i.OwnerType,
			&i.UserID,
			&i.OrgID,
			&i.Provider,
			&i.Kind,
			&i.Label,
			&i.AccountEmail,
			&i.AccountID,
			&i.Plan,
			&i.AccessTokenEncrypted,
			&i.RefreshTokenEncrypted,
			&i.AccessExpiresAt,
			&i.State,
			&i.LastRefreshAt,
			&i.NextRefreshAt,
			&i.RefreshFailures,
			&i.LastError,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProviderConnectionRefreshFailure = `-- name: MarkProviderConnectionRefreshFailure :exec
UPDATE provider_connections
SET refresh_failures = $2,
    next_refresh_at = $3,
    last_error = $4,
    state = $5,
    updated_at = NOW()
WHERE id = $1
`

type MarkProviderConnectionRefreshFailureParams struct {
	ID              string             `json:"id"`
	RefreshFailures int32              `json:"refresh_failures"`
	NextRefreshAt   pgtype.Timestamptz `json:"next_refresh_at"`
	LastError       string             `json:"last_error"`
	State           string             `json:"state"`
}

func (q *Queries) MarkProviderConnectionRefreshFailure(ctx context.Context, arg MarkProviderConnectionRefreshFailureParams) error {
	_, err := q.db.Exec(ctx, markProviderConnectionRefreshFailure,
		arg.ID,
		arg.RefreshFailures,
		arg.NextRefreshAt,
		arg.LastError,
		arg.State,
	)
	return err
}

const resolveActiveOrgProviderConnection = `-- name: ResolveActiveOrgProviderConnection :one
SELECT id, owner_type, user_id, org_id, provider, kind, label, account_email, account_id, plan, access_token_encrypted, refresh_token_encrypted, access_expires_at, state, last_refresh_at, next_refresh_at, refresh_failures, last_error, created_by, created_at, updated_at FROM provider_connections
WHERE owner_type = 'org' AND org_id = $1 AND provider = $2 AND state = 'active'
ORDER BY updated_at DESC, id
LIMIT 1
`

type ResolveActiveOrgProviderConnectionParams struct {
	OrgID    pgtype.Int8 `json:"org_id"`
	Provider string      `json:"provider"`
}

func (q *Queries) ResolveActiveOrgProviderConnection(ctx context.Context, arg ResolveActiveOrgProviderConnectionParams) (ProviderConnection, error) {
	row := q.db.QueryRow(ctx, resolveActiveOrgProviderConnection, arg.OrgID, arg.Provider)
	var i ProviderConnection
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.UserID,
		&i.OrgID,
		&i.Provider,
		&i.Kind,
		&i.Label,
		&i.AccountEmail,
		&i.AccountID,
		&i.Plan,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.AccessExpiresAt,
		&i.State,
		&i.LastRefreshAt,
		&i.NextRefreshAt,
		&i.RefreshFailures,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveActiveUserProviderConnectionForRepository = `-- name: ResolveActiveUserProviderConnectionForRepository :one
SELECT c.id, c.owner_type, c.user_id, c.org_id, c.provider, c.kind, c.label, c.account_email, c.account_id, c.plan, c.access_token_encrypted, c.refresh_token_encrypted, c.access_expires_at, c.state, c.last_refresh_at, c.next_refresh_at, c.refresh_failures, c.last_error, c.created_by, c.created_at, c.updated_at FROM provider_connections c
WHERE c.owner_type = 'user' AND c.user_id = $1 AND c.provider = $2 AND c.state = 'active'
  AND (
      EXISTS (SELECT 1 FROM repositories r WHERE r.id = $3 AND r.user_id = $1)
      OR EXISTS (
          SELECT 1 FROM provider_connection_grants g
          WHERE g.connection_id = c.id
            AND (
                g.all_repositories
                OR g.repository_id = $3
                OR g.org_id = (SELECT r2.org_id FROM repositories r2 WHERE r2.id = $3)
            )
      )
  )
ORDER BY c.updated_at DESC, c.id
LIMIT 1
`

type ResolveActiveUserProviderConnectionForRepositoryParams struct {
	UserID       pgtype.Int8 `json:"user_id"`
	Provider     string      `json:"provider"`
	RepositoryID int64       `json:"repository_id"`
}

// A user's connection applies to repositories the user owns, and to any other
// repository or organization the connection was explicitly granted to.
func (q *Queries) ResolveActiveUserProviderConnectionForRepository(ctx context.Context, arg ResolveActiveUserProviderConnectionForRepositoryParams) (ProviderConnection, error) {
	row := q.db.QueryRow(ctx, resolveActiveUserProviderConnectionForRepository, arg.UserID, arg.Provider, arg.RepositoryID)
	var i ProviderConnection
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.UserID,
		&i.OrgID,
		&i.Provider,
		&i.Kind,
		&i.Label,
		&i.AccountEmail,
		&i.AccountID,
		&i.Plan,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.AccessExpiresAt,
		&i.State,
		&i.LastRefreshAt,
		&i.NextRefreshAt,
		&i.RefreshFailures,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeProviderConnection = `-- name: RevokeProviderConnection :execrows
UPDATE provider_connections
SET state = 'revoked', last_error = $2, updated_at = NOW()
WHERE id = $1 AND state <> 'revoked'
`

type RevokeProviderConnectionParams struct {
	ID        string `json:"id"`
	LastError string `json:"last_error"`
}

func (q *Queries) RevokeProviderConnection(ctx context.Context, arg RevokeProviderConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeProviderConnection, arg.ID, arg.LastError)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProviderConnectionTokens = `-- name: UpdateProviderConnectionTokens :exec
UPDATE provider_connections
SET access_token_encrypted = $2,
    refresh_token_encrypted = $3,
    access_expires_at = $4,
    next_refresh_at = $5,
    last_refresh_at = NOW(),
    refresh_failures = 0,
    last_error = '',
    state = 'active',
    updated_at = NOW()
WHERE id = $1
`

type UpdateProviderConnectionTokensParams struct {
	ID                    string             `json:"id"`
	AccessTokenEncrypted  []byte             `json:"access_token_encrypted"`
	RefreshTokenEncrypted []byte             `json:"refresh_token_encrypted"`
	AccessExpiresAt       pgtype.Timestamptz `json:"access_expires_at"`
	NextRefreshAt         pgtype.Timestamptz `json:"next_refresh_at"`
}

func (q *Queries) UpdateProviderConnectionTokens(ctx context.Context, arg UpdateProviderConnectionTokensParams) error {
	_, err := q.db.Exec(ctx, updateProviderConnectionTokens,
		arg.ID,
		arg.AccessTokenEncrypted,
		arg.RefreshTokenEncrypted,
		arg.AccessExpiresAt,
		arg.NextRefreshAt,
	)
	return err
}

const upsertRepositoryProviderConnectionPreference = `-- name: UpsertRepositoryProviderConnectionPreference :exec
INSERT INTO repository_agent_environments (repository_id, provider_connection_preference)
VALUES ($1, $2)
ON CONFLICT (repository_id)
DO UPDATE SET provider_connection_preference = EXCLUDED.provider_connection_preference, updated_at = NOW()
`

type UpsertRepositoryProviderConnectionPreferenceParams struct {
	RepositoryID int64  `json:"repository_id"`
	Preference   string `json:"preference"`
}

func (q *Queries) UpsertRepositoryProviderConnectionPreference(ctx context.Context, arg UpsertRepositoryProviderConnectionPreferenceParams) error {
	_, err := q.db.Exec(ctx, upsertRepositoryProviderConnectionPreference, arg.RepositoryID, arg.Preference)
	return err
}
