// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repos.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCollaborator = `-- name: AddCollaborator :one
INSERT INTO collaborators (repository_id, user_id, permission)
VALUES ($1, $2, $3)
RETURNING id, repository_id, user_id, permission, created_at
`

type AddCollaboratorParams struct {
	RepositoryID int64       `json:"repository_id"`
	UserID       pgtype.Int8 `json:"user_id"`
	Permission   string      `json:"permission"`
}

func (q *Queries) AddCollaborator(ctx context.Context, arg AddCollaboratorParams) (Collaborator, error) {
	row := q.db.QueryRow(ctx, addCollaborator, arg.RepositoryID, arg.UserID, arg.Permission)
	var i Collaborator
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.UserID,
		&i.Permission,
		&i.CreatedAt,
	)
	return i, err
}

const archiveRepo = `-- name: ArchiveRepo :one
UPDATE repositories
SET is_archived = TRUE,
    archived_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, org_id, name, lower_name, description, storage_set_id, is_public, default_bookmark, topics, search_vector, next_issue_number, next_landing_number, is_fork, fork_id, is_template, template_id, is_archived, archived_at, is_mirror, mirror_destination, mirror_status, last_mirror_at, last_mirror_error, last_mirror_github_head, mirror_behind_refs, mirror_failed_refs, workspace_idle_timeout_secs, workspace_persistence, workspace_dependencies, clone_depth, landing_queue_mode, landing_queue_required_checks, num_stars, num_forks, num_watches, num_issues, num_closed_issues, created_at, updated_at
`

func (q *Queries) ArchiveRepo(ctx context.Context, id int64) (Repository, error) {
	row := q.db.QueryRow(ctx, archiveRepo, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Name,
		&i.LowerName,
		&i.Description,
		&i.StorageSetID,
		&i.IsPublic,
		&i.DefaultBookmark,
		&i.Topics,
		&i.SearchVector,
		&i.NextIssueNumber,
		&i.NextLandingNumber,
		&i.IsFork,
		&i.ForkID,
		&i.IsTemplate,
		&i.TemplateID,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.IsMirror,
		&i.MirrorDestination,
		&i.MirrorStatus,
		&i.LastMirrorAt,
		&i.LastMirrorError,
		&i.LastMirrorGithubHead,
		&i.MirrorBehindRefs,
		&i.MirrorFailedRefs,
		&i.WorkspaceIdleTimeoutSecs,
		&i.WorkspacePersistence,
		&i.WorkspaceDependencies,
		&i.CloneDepth,
		&i.LandingQueueMode,
		&i.LandingQueueRequiredChecks,
		&i.NumStars,
		&i.NumForks,
		&i.NumWatches,
		&i.NumIssues,
		&i.NumClosedIssues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countAllRepos = `-- name: CountAllRepos :one
SELECT COUNT(*)
FROM repositories
`

func (q *Queries) CountAllRepos(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllRepos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrgRepos = `-- name: CountOrgRepos :one
SELECT COUNT(*)
FROM repositories
WHERE org_id = $1
`

func (q *Queries) CountOrgRepos(ctx context.Context, orgID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countOrgRepos, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublicOrgRepos = `-- name: CountPublicOrgRepos :one
SELECT COUNT(*)
FROM repositories
WHERE org_id = $1
  AND is_public = TRUE
`

func (q *Queries) CountPublicOrgRepos(ctx context.Context, orgID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicOrgRepos, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublicUserRepos = `-- name: CountPublicUserRepos :one
SELECT COUNT(*)
FROM repositories
WHERE user_id = $1
  AND is_public = TRUE
`

func (q *Queries) CountPublicUserRepos(ctx context.Context, userID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicUserRepos, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReadableReposForUser = `-- name: CountReadableReposForUser :one
SELECT COUNT(DISTINCT r.id)
FROM repositories r
WHERE
        (r.user_id IS NOT NULL AND r.user_id = $1::bigint)
     OR (r.org_id IS NOT NULL AND EXISTS (
            SELECT 1 FROM org_members om
            WHERE om.organization_id = r.org_id
              AND om.user_id = $1::bigint
              AND om.role = 'owner'
        ))
     OR (r.org_id IS NOT NULL AND EXISTS (
            SELECT 1 FROM team_repos tr
            JOIN teams t ON t.id = tr.team_id
            JOIN team_members tm ON tm.team_id = t.id
            WHERE tr.repository_id = r.id
              AND tm.user_id = $1::bigint
        ))
     OR EXISTS (
            SELECT 1 FROM collaborators c
            WHERE c.repository_id = r.id
              AND c.user_id = $1::bigint
        )
     OR r.is_public
`

func (q *Queries) CountReadableReposForUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countReadableReposForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRepoForks = `-- name: CountRepoForks :one
SELECT COUNT(*)
FROM repositories
WHERE fork_id = $1
`

func (q *Queries) CountRepoForks(ctx context.Context, forkID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countRepoForks, forkID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserRepos = `-- name: CountUserRepos :one

SELECT COUNT(*)
FROM repositories
WHERE user_id = $1
`

// num_stars / num_forks / num_watches are maintained by database triggers
// (trg_stars_count_*, trg_repositories_fork_count_*, trg_watches_count_*);
// there are intentionally no increment/decrement queries for them.
func (q *Queries) CountUserRepos(ctx context.Context, userID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countUserRepos, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createForkRepo = `-- name: CreateForkRepo :one
INSERT INTO repositories (user_id, name, lower_name, description, storage_set_id, is_public, default_bookmark, is_fork, fork_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, TRUE, $8)
RETURNING id, user_id, org_id, name, lower_name, description, storage_set_id, is_public, default_bookmark, topics, search_vector, next_issue_number, next_landing_number, is_fork, fork_id, is_template, template_id, is_archived, archived_at, is_mirror, mirror_destination, mirror_status, last_mirror_at, last_mirror_error, last_mirror_github_head, mirror_behind_refs, mirror_failed_refs, workspace_idle_timeout_secs, workspace_persistence, workspace_dependencies, clone_depth, landing_queue_mode, landing_queue_required_checks, num_stars, num_forks, num_watches, num_issues, num_closed_issues, created_at, updated_at
`

type CreateForkRepoParams struct {
	UserID          pgtype.Int8 `json:"user_id"`
	Name            string      `json:"name"`
	LowerName       string      `json:"lower_name"`
	Description     string      `json:"description"`
	StorageSetID    string      `json:"storage_set_id"`
	IsPublic        bool        `json:"is_public"`
	DefaultBookmark string      `json:"default_bookmark"`
	ForkID          pgtype.Int8 `json:"fork_id"`
}

func (q *Queries) CreateForkRepo(ctx context.Context, arg CreateForkRepoParams) (Repository, error) {
	row := q.db.QueryRow(ctx, createForkRepo,
		arg.UserID,
		arg.Name,
		arg.LowerName,
		arg.Description,
		arg.StorageSetID,
		arg.IsPublic,
		arg.DefaultBookmark,
		arg.ForkID,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Name,
		&i.LowerName,
		&i.Description,
		&i.StorageSetID,
		&i.IsPublic,
		&i.DefaultBookmark,
		&i.Topics,
		&i.SearchVector,
		&i.NextIssueNumber,
		&i.NextLandingNumber,
		&i.IsFork,
		&i.ForkID,
		&i.IsTemplate,
		&i.TemplateID,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.IsMirror,
		&i.MirrorDestination,
		&i.MirrorStatus,
		&i.LastMirrorAt,
		&i.LastMirrorError,
		&i.LastMirrorGithubHead,
		&i.MirrorBehindRefs,
		&i.MirrorFailedRefs,
		&i.WorkspaceIdleTimeoutSecs,
		&i.WorkspacePersistence,
		&i.WorkspaceDependencies,
		&i.CloneDepth,
		&i.LandingQueueMode,
		&i.LandingQueueRequiredChecks,
		&i.NumStars,
		&i.NumForks,
		&i.NumWatches,
		&i.NumIssues,
		&i.NumClosedIssues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrgRepo = `-- name: CreateOrgRepo :one
INSERT INTO repositories (org_id, name, lower_name, description, storage_set_id, is_public, default_bookmark)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, org_id, name, lower_name, description, storage_set_id, is_public, default_bookmark, topics, search_vector, next_issue_number, next_landing_number, is_fork, fork_id, is_template, template_id, is_archived, archived_at, is_mirror, mirror_destination, mirror_status, last_mirror_at, last_mirror_error, last_mirror_github_head, mirror_behind_refs, mirror_failed_refs, workspace_idle_timeout_secs, workspace_persistence, workspace_dependencies, clone_depth, landing_queue_mode, landing_queue_required_checks, num_stars, num_forks, num_watches, num_issues, num_closed_issues, created_at, updated_at
`

type CreateOrgRepoParams struct {
	OrgID           pgtype.Int8 `json:"org_id"`
	Name            string      `json:"name"`
	LowerName       string      `json:"lower_name"`
	Description     string      `json:"description"`
	StorageSetID    string      `json:"storage_set_id"`
	IsPublic        bool        `json:"is_public"`
	DefaultBookmark string      `json:"default_bookmark"`
}

func (q *Queries) CreateOrgRepo(ctx context.Context, arg CreateOrgRepoParams) (Repository, error) {
	row := q.db.QueryRow(ctx, createOrgRepo,
		arg.OrgID,
		arg.Name,
		arg.LowerName,
		arg.Description,
		arg.StorageSetID,
		arg.IsPublic,
		arg.DefaultBookmark,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Name,
		&i.LowerName,
		&i.Description,
		&i.StorageSetID,
		&i.IsPublic,
		&i.DefaultBookmark,
		&i.Topics,
		&i.SearchVector,
		&i.NextIssueNumber,
		&i.NextLandingNumber,
		&i.IsFork,
		&i.ForkID,
		&i.IsTemplate,
		&i.TemplateID,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.IsMirror,
		&i.MirrorDestination,
		&i.MirrorStatus,
		&i.LastMirrorAt,
		&i.LastMirrorError,
		&i.LastMirrorGithubHead,
		&i.MirrorBehindRefs,
		&i.MirrorFailedRefs,
		&i.WorkspaceIdleTimeoutSecs,
		&i.WorkspacePersistence,
		&i.WorkspaceDependencies,
		&i.CloneDepth,
		&i.LandingQueueMode,
		&i.LandingQueueRequiredChecks,
		&i.NumStars,
		&i.NumForks,
		&i.NumWatches,
		&i.NumIssues,
		&i.NumClosedIssues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRepo = `-- name: CreateRepo :one
INSERT INTO repositories (user_id, name, lower_name, description, storage_set_id, is_public, default_bookmark)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, org_id, name, lower_name, description, storage_set_id, is_public, default_bookmark, topics, search_vector, next_issue_number, next_landing_number, is_fork, fork_id, is_template, template_id, is_archived, archived_at, is_mirror, mirror_destination, mirror_status, last_mirror_at, last_mirror_error, last_mirror_github_head, mirror_behind_refs, mirror_failed_refs, workspace_idle_timeout_secs, workspace_persistence, workspace_dependencies, clone_depth, landing_queue_mode, landing_queue_required_checks, num_stars, num_forks, num_watches, num_issues, num_closed_issues, created_at, updated_at
`

type CreateRepoParams struct {
	UserID          pgtype.Int8 `json:"user_id"`
	Name            string      `json:"name"`
	LowerName       string      `json:"lower_name"`
	Description     string      `json:"description"`
	StorageSetID    string      `json:"storage_set_id"`
	IsPublic        bool        `json:"is_public"`
	DefaultBookmark string      `json:"default_bookmark"`
}

func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) (Repository, error) {
	row := q.db.QueryRow(ctx, createRepo,
		arg.UserID,
		arg.Name,
		arg.LowerName,
		arg.Description,
		arg.StorageSetID,
		arg.IsPublic,
		arg.DefaultBookmark,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Name,
		&i.LowerName,
		&i.Description,
		&i.StorageSetID,
		&i.IsPublic,
		&i.DefaultBookmark,
		&i.Topics,
		&i.SearchVector,
		&i.NextIssueNumber,
		&i.NextLandingNumber,
		&i.IsFork,
		&i.ForkID,
		&i.IsTemplate,
		&i.TemplateID,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.IsMirror,
		&i.MirrorDestination,
		&i.MirrorStatus,
		&i.LastMirrorAt,
		&i.LastMirrorError,
		&i.LastMirrorGithubHead,
		&i.MirrorBehindRefs,
		&i.MirrorFailedRefs,
		&i.WorkspaceIdleTimeoutSecs,
		&i.WorkspacePersistence,
		&i.WorkspaceDependencies,
		&i.CloneDepth,
		&i.LandingQueueMode,
		&i.LandingQueueRequiredChecks,
		&i.NumStars,
		&i.NumForks,
		&i.NumWatches,
		&i.NumIssues,
		&i.NumClosedIssues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCollaboratorsByRepo = `-- name: DeleteCollaboratorsByRepo :exec
DELETE FROM collaborators
WHERE repository_id = $1
`

func (q *Queries) DeleteCollaboratorsByRepo(ctx context.Context, repositoryID int64) error {
	_, err := q.db.Exec(ctx, deleteCollaboratorsByRepo, repositoryID)
	return err
}

const deleteRepo = `-- name: DeleteRepo :exec
DELETE FROM repositories WHERE id = $1
`

func (q *Queries) DeleteRepo(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRepo, id)
	return err
}

const deleteTeamReposByRepo = `-- name: DeleteTeamReposByRepo :exec
DELETE FROM team_repos
WHERE repository_id = $1
`

func (q *Queries) DeleteTeamReposByRepo(ctx context.Context, repositoryID int64) error {
	_, err := q.db.Exec(ctx, deleteTeamReposByRepo, repositoryID)
	return err
}

const getCollaboratorPermissionForRepoUser = `-- name: GetCollaboratorPermissionForRepoUser :one
SELECT COALESCE(
    (SELECT permission FROM collaborators WHERE repository_id = $1 AND user_id = $2),
    ''
)::text AS permission
`

type GetCollaboratorPermissionForRepoUserParams struct {
	RepositoryID int64       `json:"repository_id"`
	UserID       pgtype.Int8 `json:"user_id"`
}

func (q *Queries) GetCollaboratorPermissionForRepoUser(ctx context.Context, arg GetCollaboratorPermissionForRepoUserParams) (string, error) {
	row := q.db.QueryRow(ctx, getCollaboratorPermissionForRepoUser, arg.RepositoryID, arg.UserID)
	var permission string
	err := row.Scan(&permission)
	return permission, err
}

const getHighestTeamPermissionForRepoUser = `-- name: GetHighestTeamPermissionForRepoUser :one
SELECT COALESCE((
  SELECT t.permission
  FROM team_repos tr
  JOIN teams t ON t.id = tr.team_id
  JOIN team_members tm ON tm.team_id = t.id
  JOIN repositories r ON r.id = tr.repository_id
  JOIN org_members om ON om.organization_id = t.organization_id AND om.user_id = tm.user_id
  WHERE tr.repository_id = $1
    AND tm.user_id = $2
    AND r.org_id = t.organization_id
  ORDER BY CASE t.permission
    WHEN 'admin' THEN 3
    WHEN 'write' THEN 2
    WHEN 'read' THEN 1
    ELSE 0
  END DESC
  LIMIT 1
), '')::text
`

type GetHighestTeamPermissionForRepoUserParams struct {
	RepositoryID int64 `json:"repository_id"`
	UserID       int64 `json:"user_id"`
}

// A team grant only counts when the team belongs to the repository's CURRENT
// organization and the user is still an org member. This keeps stale
// team_repos/team_members rows (e.g. left behind by a raced repo transfer or
// org-member removal) from granting cross-org or post-removal access.
func (q *Queries) GetHighestTeamPermissionForRepoUser(ctx context.Context, arg GetHighestTeamPermissionForRepoUserParams) (string, error) {
	row := q.db.QueryRow(ctx, getHighestTeamPermissionForRepoUser, arg.RepositoryID, arg.UserID)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const getRepoByID = `-- name: GetRepoByID :one
SELECT id, user_id, org_id, name, lower_name, description, storage_set_id, is_public, default_bookmark, topics, search_vector, next_issue_number, next_landing_number, is_fork, fork_id, is_template, template_id, is_archived, archived_at, is_mirror, mirror_destination, mirror_status, last_mirror_at, last_mirror_error, last_mirror_github_head, mirror_behind_refs, mirror_failed_refs, workspace_idle_timeout_secs, workspace_persistence, workspace_dependencies, clone_depth, landing_queue_mode, landing_queue_required_checks, num_stars, num_forks, num_watches, num_issues, num_closed_issues, created_at, updated_at
FROM repositories
WHERE id = $1
`

func (q *Queries) GetRepoByID(ctx context.Context, id int64) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepoByID, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Name,
		&i.LowerName,
		&i.Description,
		&i.StorageSetID,
		&i.IsPublic,
		&i.DefaultBookmark,
		&i.Topics,
		&i.SearchVector,
		&i.NextIssueNumber,
		&i.NextLandingNumber,
		&i.IsFork,
		&i.ForkID,
		&i.IsTemplate,
		&i.TemplateID,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.IsMirror,
		&i.MirrorDestination,
		&i.MirrorStatus,
		&i.LastMirrorAt,
		&i.LastMirrorError,
		&i.LastMirrorGithubHead,
		&i.MirrorBehindRefs,
		&i.MirrorFailedRefs,
		&i.WorkspaceIdleTimeoutSecs,
		&i.WorkspacePersistence,
		&i.WorkspaceDependencies,
		&i.CloneDepth,
		&i.LandingQueueMode,
		&i.LandingQueueRequiredChecks,
		&i.NumStars,
		&i.NumForks,
		&i.NumWatches,
		&i.NumIssues,
		&i.NumClosedIssues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoByIDForUpdate = `-- name: GetRepoByIDForUpdate :one
SELECT id, user_id, org_id, name, lower_name, description, storage_set_id, is_public, default_bookmark, topics, search_vector, next_issue_number, next_landing_number, is_fork, fork_id, is_template, template_id, is_archived, archived_at, is_mirror, mirror_destination, mirror_status, last_mirror_at, last_mirror_error, last_mirror_github_head, mirror_behind_refs, mirror_failed_refs, workspace_idle_timeout_secs, workspace_persistence, workspace_dependencies, clone_depth, landing_queue_mode, landing_queue_required_checks, num_stars, num_forks, num_watches, num_issues, num_closed_issues, created_at, updated_at
FROM repositories
WHERE id = $1
FOR UPDATE
`

// Locks the repository row for the duration of the transaction. Ownership
// transactions (transfer/delete/settings) re-read through this so writers that
// lock the same row before depending on ownership (e.g. AddTeamRepoIfOrgRepo)
// serialize with the whole transaction instead of only its final UPDATE.
func (q *Queries) GetRepoByIDForUpdate(ctx context.Context, id int64) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepoByIDForUpdate, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Name,
		&i.LowerName,
		&i.Description,
		&i.StorageSetID,
		&i.IsPublic,
		&i.DefaultBookmark,
		&i.Topics,
		&i.SearchVector,
		&i.NextIssueNumber,
		&i.NextLandingNumber,
		&i.IsFork,
		&i.ForkID,
		&i.IsTemplate,
		&i.TemplateID,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.IsMirror,
		&i.MirrorDestination,
		&i.MirrorStatus,
		&i.LastMirrorAt,
		&i.LastMirrorError,
		&i.LastMirrorGithubHead,
		&i.MirrorBehindRefs,
		&i.MirrorFailedRefs,
		&i.WorkspaceIdleTimeoutSecs,
		&i.WorkspacePersistence,
		&i.WorkspaceDependencies,
		&i.CloneDepth,
		&i.LandingQueueMode,
		&i.LandingQueueRequiredChecks,
		&i.NumStars,
		&i.NumForks,
		&i.NumWatches,
		&i.NumIssues,
		&i.NumClosedIssues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoByOwnerAndLowerName = `-- name: GetRepoByOwnerAndLowerName :one
SELECT r.id, r.user_id, r.org_id, r.name, r.lower_name, r.description, r.storage_set_id, r.is_public, r.default_bookmark, r.topics, r.search_vector, r.next_issue_number, r.next_landing_number, r.is_fork, r.fork_id, r.is_template, r.template_id, r.is_archived, r.archived_at, r.is_mirror, r.mirror_destination, r.mirror_status, r.last_mirror_at, r.last_mirror_error, r.last_mirror_github_head, r.mirror_behind_refs, r.mirror_failed_refs, r.workspace_idle_timeout_secs, r.workspace_persistence, r.workspace_dependencies, r.clone_depth, r.landing_queue_mode, r.landing_queue_required_checks, r.num_stars, r.num_forks, r.num_watches, r.num_issues, r.num_closed_issues, r.created_at, r.updated_at
FROM repositories r
JOIN owner_namespaces ns
  ON ns.lower_slug = LOWER($1)
 AND (
   (ns.owner_type = 'user' AND ns.user_id = r.user_id)
   OR
   (ns.owner_type = 'org' AND ns.org_id = r.org_id)
 )
WHERE r.lower_name = LOWER($2)
`

type GetRepoByOwnerAndLowerNameParams struct {
	Owner     string `json:"owner"`
	LowerName string `json:"lower_name"`
}

func (q *Queries) GetRepoByOwnerAndLowerName(ctx context.Context, arg GetRepoByOwnerAndLowerNameParams) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepoByOwnerAndLowerName, arg.Owner, arg.LowerName)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Name,
		&i.LowerName,
		&i.Description,
		&i.StorageSetID,
		&i.IsPublic,
		&i.DefaultBookmark,
		&i.Topics,
		&i.SearchVector,
		&i.NextIssueNumber,
		&i.NextLandingNumber,
		&i.IsFork,
		&i.ForkID,
		&i.IsTemplate,
		&i.TemplateID,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.IsMirror,
		&i.MirrorDestination,
		&i.MirrorStatus,
		&i.LastMirrorAt,
		&i.LastMirrorError,
		&i.LastMirrorGithubHead,
		&i.MirrorBehindRefs,
		&i.MirrorFailedRefs,
		&i.WorkspaceIdleTimeoutSecs,
		&i.WorkspacePersistence,
		&i.WorkspaceDependencies,
		&i.CloneDepth,
		&i.LandingQueueMode,
		&i.LandingQueueRequiredChecks,
		&i.NumStars,
		&i.NumForks,
		&i.NumWatches,
		&i.NumIssues,
		&i.NumClosedIssues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoByOwnerAndName = `-- name: GetRepoByOwnerAndName :one
SELECT r.id, r.user_id, r.org_id, r.name, r.lower_name, r.is_public, r.is_archived
FROM repositories r
JOIN owner_namespaces ns
  ON ns.lower_slug = LOWER($1)
 AND (
   (ns.owner_type = 'user' AND ns.user_id = r.user_id)
   OR
   (ns.owner_type = 'org' AND ns.org_id = r.org_id)
 )
WHERE r.lower_name = LOWER($2)
`

type GetRepoByOwnerAndNameParams struct {
	Owner string `json:"owner"`
	Name  string `json:"name"`
}

type GetRepoByOwnerAndNameRow struct {
	ID         int64       `json:"id"`
	UserID     pgtype.Int8 `json:"user_id"`
	OrgID      pgtype.Int8 `json:"org_id"`
	Name       string      `json:"name"`
	LowerName  string      `json:"lower_name"`
	IsPublic   bool        `json:"is_public"`
	IsArchived bool        `json:"is_archived"`
}

func (q *Queries) GetRepoByOwnerAndName(ctx context.Context, arg GetRepoByOwnerAndNameParams) (GetRepoByOwnerAndNameRow, error) {
	row := q.db.QueryRow(ctx, getRepoByOwnerAndName, arg.Owner, arg.Name)
	var i GetRepoByOwnerAndNameRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Name,
		&i.LowerName,
		&i.IsPublic,
		&i.IsArchived,
	)
	return i, err
}

const getRepositoryCloneDepth = `-- name: GetRepositoryCloneDepth :one
SELECT clone_depth
FROM repositories
WHERE id = $1
`

func (q *Queries) GetRepositoryCloneDepth(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRow(ctx, getRepositoryCloneDepth, id)
	var clone_depth int32
	err := row.Scan(&clone_depth)
	return clone_depth, err
}

const isOrgOwnerForRepoUser = `-- name: IsOrgOwnerForRepoUser :one
SELECT EXISTS (
  SELECT 1
  FROM repositories r
  JOIN org_members om ON om.organization_id = r.org_id
  WHERE r.id = $1
    AND om.user_id = $2
    AND om.role = 'owner'
)
`

type IsOrgOwnerForRepoUserParams struct {
	RepositoryID int64 `json:"repository_id"`
	UserID       int64 `json:"user_id"`
}

func (q *Queries) IsOrgOwnerForRepoUser(ctx context.Context, arg IsOrgOwnerForRepoUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, isOrgOwnerForRepoUser, arg.RepositoryID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAllRepos = `-- name: ListAllRepos :many
SELECT id, user_id, org_id, name, lower_name, description, storage_set_id, is_public, default_bookmark, topics, search_vector, next_issue_number, next_landing_number, is_fork, fork_id, is_template, template_id, is_archived, archived_at, is_mirror, mirror_destination, mirror_status, last_mirror_at, last_mirror_error, last_mirror_github_head, mirror_behind_refs, mirror_failed_refs, workspace_idle_timeout_secs, workspace_persistence, workspace_dependencies, clone_depth, landing_queue_mode, landing_queue_required_checks, num_stars, num_forks, num_watches, num_issues, num_closed_issues, created_at, updated_at
FROM repositories
ORDER BY updated_at DESC, id DESC
LIMIT $2
OFFSET $1
`

type ListAllReposParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListAllRepos(ctx context.Context, arg ListAllReposParams) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listAllRepos, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.Name,
			&i.LowerName,
			&i.Description,
			&i.StorageSetID,
			&i.IsPublic,
			&i.DefaultBookmark,
			&i.Topics,
			&i.SearchVector,
			&i.NextIssueNumber,
			&i.NextLandingNumber,
			&i.IsFork,
			&i.ForkID,
			&i.IsTemplate,
			&i.TemplateID,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.IsMirror,
			&i.MirrorDestination,
			&i.MirrorStatus,
			&i.LastMirrorAt,
			&i.LastMirrorError,
			&i.LastMirrorGithubHead,
			&i.MirrorBehindRefs,
			&i.MirrorFailedRefs,
			&i.WorkspaceIdleTimeoutSecs,
			&i.WorkspacePersistence,
			&i.WorkspaceDependencies,
			&i.CloneDepth,
			&i.LandingQueueMode,
			&i.LandingQueueRequiredChecks,
			&i.NumStars,
			&i.NumForks,
			&i.NumWatches,
			&i.NumIssues,
			&i.NumClosedIssues,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollaboratorsByRepo = `-- name: ListCollaboratorsByRepo :many
SELECT id, repository_id, user_id, permission, created_at
FROM collaborators
WHERE repository_id = $1
  AND user_id IS NOT NULL
ORDER BY id ASC
`

// Excludes tombstone rows (user_id IS NULL from ON DELETE SET NULL) since
// there is no live user record to display or authorize.
func (q *Queries) ListCollaboratorsByRepo(ctx context.Context, repositoryID int64) ([]Collaborator, error) {
	rows, err := q.db.Query(ctx, listCollaboratorsByRepo, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collaborator{}
	for rows.Next() {
		var i Collaborator
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.UserID,
			&i.Permission,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgRepos = `-- name: ListOrgRepos :many
SELECT id, user_id, org_id, name, lower_name, description, storage_set_id, is_public, default_bookmark, topics, search_vector, next_issue_number, next_landing_number, is_fork, fork_id, is_template, template_id, is_archived, archived_at, is_mirror, mirror_destination, mirror_status, last_mirror_at, last_mirror_error, last_mirror_github_head, mirror_behind_refs, mirror_failed_refs, workspace_idle_timeout_secs, workspace_persistence, workspace_dependencies, clone_depth, landing_queue_mode, landing_queue_required_checks, num_stars, num_forks, num_watches, num_issues, num_closed_issues, created_at, updated_at
FROM repositories
WHERE org_id = $1
ORDER BY updated_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListOrgReposParams struct {
	OrgID      pgtype.Int8 `json:"org_id"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

func (q *Queries) ListOrgRepos(ctx context.Context, arg ListOrgReposParams) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listOrgRepos, arg.OrgID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.Name,
			&i.LowerName,
			&i.Description,
			&i.StorageSetID,
			&i.IsPublic,
			&i.DefaultBookmark,
			&i.Topics,
			&i.SearchVector,
			&i.NextIssueNumber,
			&i.NextLandingNumber,
			&i.IsFork,
			&i.ForkID,
			&i.IsTemplate,
			&i.TemplateID,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.IsMirror,
			&i.MirrorDestination,
			&i.MirrorStatus,
			&i.LastMirrorAt,
			&i.LastMirrorError,
			&i.LastMirrorGithubHead,
			&i.MirrorBehindRefs,
			&i.MirrorFailedRefs,
			&i.WorkspaceIdleTimeoutSecs,
			&i.WorkspacePersistence,
			&i.WorkspaceDependencies,
			&i.CloneDepth,
			&i.LandingQueueMode,
			&i.LandingQueueRequiredChecks,
			&i.NumStars,
			&i.NumForks,
			&i.NumWatches,
			&i.NumIssues,
			&i.NumClosedIssues,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicOrgRepos = `-- name: ListPublicOrgRepos :many
SELECT id, user_id, org_id, name, lower_name, description, storage_set_id, is_public, default_bookmark, topics, search_vector, next_issue_number, next_landing_number, is_fork, fork_id, is_template, template_id, is_archived, archived_at, is_mirror, mirror_destination, mirror_status, last_mirror_at, last_mirror_error, last_mirror_github_head, mirror_behind_refs, mirror_failed_refs, workspace_idle_timeout_secs, workspace_persistence, workspace_dependencies, clone_depth, landing_queue_mode, landing_queue_required_checks, num_stars, num_forks, num_watches, num_issues, num_closed_issues, created_at, updated_at
FROM repositories
WHERE org_id = $1
  AND is_public = TRUE
ORDER BY updated_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListPublicOrgReposParams struct {
	OrgID      pgtype.Int8 `json:"org_id"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

func (q *Queries) ListPublicOrgRepos(ctx context.Context, arg ListPublicOrgReposParams) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listPublicOrgRepos, arg.OrgID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.Name,
			&i.LowerName,
			&i.Description,
			&i.StorageSetID,
			&i.IsPublic,
			&i.DefaultBookmark,
			&i.Topics,
			&i.SearchVector,
			&i.NextIssueNumber,
			&i.NextLandingNumber,
			&i.IsFork,
			&i.ForkID,
			&i.IsTemplate,
			&i.TemplateID,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.IsMirror,
			&i.MirrorDestination,
			&i.MirrorStatus,
			&i.LastMirrorAt,
			&i.LastMirrorError,
			&i.LastMirrorGithubHead,
			&i.MirrorBehindRefs,
			&i.MirrorFailedRefs,
			&i.WorkspaceIdleTimeoutSecs,
			&i.WorkspacePersistence,
			&i.WorkspaceDependencies,
			&i.CloneDepth,
			&i.LandingQueueMode,
			&i.LandingQueueRequiredChecks,
			&i.NumStars,
			&i.NumForks,
			&i.NumWatches,
			&i.NumIssues,
			&i.NumClosedIssues,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicUserRepos = `-- name: ListPublicUserRepos :many
SELECT id, user_id, org_id, name, lower_name, description, storage_set_id, is_public, default_bookmark, topics, search_vector, next_issue_number, next_landing_number, is_fork, fork_id, is_template, template_id, is_archived, archived_at, is_mirror, mirror_destination, mirror_status, last_mirror_at, last_mirror_error, last_mirror_github_head, mirror_behind_refs, mirror_failed_refs, workspace_idle_timeout_secs, workspace_persistence, workspace_dependencies, clone_depth, landing_queue_mode, landing_queue_required_checks, num_stars, num_forks, num_watches, num_issues, num_closed_issues, created_at, updated_at
FROM repositories
WHERE user_id = $1
  AND is_public = TRUE
ORDER BY updated_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListPublicUserReposParams struct {
	UserID     pgtype.Int8 `json:"user_id"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

func (q *Queries) ListPublicUserRepos(ctx context.Context, arg ListPublicUserReposParams) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listPublicUserRepos, arg.UserID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.Name,
			&i.LowerName,
			&i.Description,
			&i.StorageSetID,
			&i.IsPublic,
			&i.DefaultBookmark,
			&i.Topics,
			&i.SearchVector,
			&i.NextIssueNumber,
			&i.NextLandingNumber,
			&i.IsFork,
			&i.ForkID,
			&i.IsTemplate,
			&i.TemplateID,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.IsMirror,
			&i.MirrorDestination,
			&i.MirrorStatus,
			&i.LastMirrorAt,
			&i.LastMirrorError,
			&i.LastMirrorGithubHead,
			&i.MirrorBehindRefs,
			&i.MirrorFailedRefs,
			&i.WorkspaceIdleTimeoutSecs,
			&i.WorkspacePersistence,
			&i.WorkspaceDependencies,
			&i.CloneDepth,
			&i.LandingQueueMode,
			&i.LandingQueueRequiredChecks,
			&i.NumStars,
			&i.NumForks,
			&i.NumWatches,
			&i.NumIssues,
			&i.NumClosedIssues,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadableReposForUser = `-- name: ListReadableReposForUser :many
SELECT
    r.id,
    COALESCE(u.username, o.name, '')::text AS owner,
    r.name,
    r.updated_at
FROM repositories r
LEFT JOIN users u ON u.id = r.user_id
LEFT JOIN organizations o ON o.id = r.org_id
WHERE
        (r.user_id IS NOT NULL AND r.user_id = $1::bigint)
     OR (r.org_id IS NOT NULL AND EXISTS (
            SELECT 1 FROM org_members om
            WHERE om.organization_id = r.org_id
              AND om.user_id = $1::bigint
              AND om.role = 'owner'
        ))
     OR (r.org_id IS NOT NULL AND EXISTS (
            SELECT 1 FROM team_repos tr
            JOIN teams t ON t.id = tr.team_id
            JOIN team_members tm ON tm.team_id = t.id
            WHERE tr.repository_id = r.id
              AND tm.user_id = $1::bigint
        ))
     OR EXISTS (
            SELECT 1 FROM collaborators c
            WHERE c.repository_id = r.id
              AND c.user_id = $1::bigint
        )
     OR r.is_public
ORDER BY r.updated_at DESC, r.id DESC
LIMIT $3 OFFSET $2
`

type ListReadableReposForUserParams struct {
	UserID     int64 `json:"user_id"`
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

type ListReadableReposForUserRow struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Ticket 0135: returns every repository the given user can read (owner +
// org-owner + team permission + direct collaborator + public). Used by the
// /api/user/repos list route and the workspaces realtime stream filter on
// the client. Must match the readability predicate used by
// the repository permission resolver.
func (q *Queries) ListReadableReposForUser(ctx context.Context, arg ListReadableReposForUserParams) ([]ListReadableReposForUserRow, error) {
	rows, err := q.db.Query(ctx, listReadableReposForUser, arg.UserID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReadableReposForUserRow{}
	for rows.Next() {
		var i ListReadableReposForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Name,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoForks = `-- name: ListRepoForks :many
SELECT id, user_id, org_id, name, lower_name, description, storage_set_id, is_public, default_bookmark, topics, search_vector, next_issue_number, next_landing_number, is_fork, fork_id, is_template, template_id, is_archived, archived_at, is_mirror, mirror_destination, mirror_status, last_mirror_at, last_mirror_error, last_mirror_github_head, mirror_behind_refs, mirror_failed_refs, workspace_idle_timeout_secs, workspace_persistence, workspace_dependencies, clone_depth, landing_queue_mode, landing_queue_required_checks, num_stars, num_forks, num_watches, num_issues, num_closed_issues, created_at, updated_at
FROM repositories
WHERE fork_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListRepoForksParams struct {
	ForkID     pgtype.Int8 `json:"fork_id"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

func (q *Queries) ListRepoForks(ctx context.Context, arg ListRepoForksParams) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepoForks, arg.ForkID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.Name,
			&i.LowerName,
			&i.Description,
			&i.StorageSetID,
			&i.IsPublic,
			&i.DefaultBookmark,
			&i.Topics,
			&i.SearchVector,
			&i.NextIssueNumber,
			&i.NextLandingNumber,
			&i.IsFork,
			&i.ForkID,
			&i.IsTemplate,
			&i.TemplateID,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.IsMirror,
			&i.MirrorDestination,
			&i.MirrorStatus,
			&i.LastMirrorAt,
			&i.LastMirrorError,
			&i.LastMirrorGithubHead,
			&i.MirrorBehindRefs,
			&i.MirrorFailedRefs,
			&i.WorkspaceIdleTimeoutSecs,
			&i.WorkspacePersistence,
			&i.WorkspaceDependencies,
			&i.CloneDepth,
			&i.LandingQueueMode,
			&i.LandingQueueRequiredChecks,
			&i.NumStars,
			&i.NumForks,
			&i.NumWatches,
			&i.NumIssues,
			&i.NumClosedIssues,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamReposByRepo = `-- name: ListTeamReposByRepo :many
SELECT id, team_id, repository_id, created_at
FROM team_repos
WHERE repository_id = $1
ORDER BY id ASC
`

func (q *Queries) ListTeamReposByRepo(ctx context.Context, repositoryID int64) ([]TeamRepo, error) {
	rows, err := q.db.Query(ctx, listTeamReposByRepo, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamRepo{}
	for rows.Next() {
		var i TeamRepo
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.RepositoryID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRepos = `-- name: ListUserRepos :many
SELECT id, user_id, org_id, name, lower_name, description, storage_set_id, is_public, default_bookmark, topics, search_vector, next_issue_number, next_landing_number, is_fork, fork_id, is_template, template_id, is_archived, archived_at, is_mirror, mirror_destination, mirror_status, last_mirror_at, last_mirror_error, last_mirror_github_head, mirror_behind_refs, mirror_failed_refs, workspace_idle_timeout_secs, workspace_persistence, workspace_dependencies, clone_depth, landing_queue_mode, landing_queue_required_checks, num_stars, num_forks, num_watches, num_issues, num_closed_issues, created_at, updated_at
FROM repositories
WHERE user_id = $1
ORDER BY updated_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListUserReposParams struct {
	UserID     pgtype.Int8 `json:"user_id"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

func (q *Queries) ListUserRepos(ctx context.Context, arg ListUserReposParams) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listUserRepos, arg.UserID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.Name,
			&i.LowerName,
			&i.Description,
			&i.StorageSetID,
			&i.IsPublic,
			&i.DefaultBookmark,
			&i.Topics,
			&i.SearchVector,
			&i.NextIssueNumber,
			&i.NextLandingNumber,
			&i.IsFork,
			&i.ForkID,
			&i.IsTemplate,
			&i.TemplateID,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.IsMirror,
			&i.MirrorDestination,
			&i.MirrorStatus,
			&i.LastMirrorAt,
			&i.LastMirrorError,
			&i.LastMirrorGithubHead,
			&i.MirrorBehindRefs,
			&i.MirrorFailedRefs,
			&i.WorkspaceIdleTimeoutSecs,
			&i.WorkspacePersistence,
			&i.WorkspaceDependencies,
			&i.CloneDepth,
			&i.LandingQueueMode,
			&i.LandingQueueRequiredChecks,
			&i.NumStars,
			&i.NumForks,
			&i.NumWatches,
			&i.NumIssues,
			&i.NumClosedIssues,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRepositoryCloneDepth = `-- name: SetRepositoryCloneDepth :exec
UPDATE repositories
SET clone_depth = $1,
    updated_at = NOW()
WHERE id = $2
`

type SetRepositoryCloneDepthParams struct {
	CloneDepth int32 `json:"clone_depth"`
	ID         int64 `json:"id"`
}

func (q *Queries) SetRepositoryCloneDepth(ctx context.Context, arg SetRepositoryCloneDepthParams) error {
	_, err := q.db.Exec(ctx, setRepositoryCloneDepth, arg.CloneDepth, arg.ID)
	return err
}

const transferRepoToOrg = `-- name: TransferRepoToOrg :one
UPDATE repositories
SET org_id = $1,
    user_id = NULL,
    updated_at = NOW()
WHERE id = $2
RETURNING id, user_id, org_id, name, lower_name, description, storage_set_id, is_public, default_bookmark, topics, search_vector, next_issue_number, next_landing_number, is_fork, fork_id, is_template, template_id, is_archived, archived_at, is_mirror, mirror_destination, mirror_status, last_mirror_at, last_mirror_error, last_mirror_github_head, mirror_behind_refs, mirror_failed_refs, workspace_idle_timeout_secs, workspace_persistence, workspace_dependencies, clone_depth, landing_queue_mode, landing_queue_required_checks, num_stars, num_forks, num_watches, num_issues, num_closed_issues, created_at, updated_at
`

type TransferRepoToOrgParams struct {
	NewOrgID pgtype.Int8 `json:"new_org_id"`
	ID       int64       `json:"id"`
}

func (q *Queries) TransferRepoToOrg(ctx context.Context, arg TransferRepoToOrgParams) (Repository, error) {
	row := q.db.QueryRow(ctx, transferRepoToOrg, arg.NewOrgID, arg.ID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Name,
		&i.LowerName,
		&i.Description,
		&i.StorageSetID,
		&i.IsPublic,
		&i.DefaultBookmark,
		&i.Topics,
		&i.SearchVector,
		&i.NextIssueNumber,
		&i.NextLandingNumber,
		&i.IsFork,
		&i.ForkID,
		&i.IsTemplate,
		&i.TemplateID,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.IsMirror,
		&i.MirrorDestination,
		&i.MirrorStatus,
		&i.LastMirrorAt,
		&i.LastMirrorError,
		&i.LastMirrorGithubHead,
		&i.MirrorBehindRefs,
		&i.MirrorFailedRefs,
		&i.WorkspaceIdleTimeoutSecs,
		&i.WorkspacePersistence,
		&i.WorkspaceDependencies,
		&i.CloneDepth,
		&i.LandingQueueMode,
		&i.LandingQueueRequiredChecks,
		&i.NumStars,
		&i.NumForks,
		&i.NumWatches,
		&i.NumIssues,
		&i.NumClosedIssues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transferRepoToUser = `-- name: TransferRepoToUser :one
UPDATE repositories
SET user_id = $1,
    org_id = NULL,
    updated_at = NOW()
WHERE id = $2
RETURNING id, user_id, org_id, name, lower_name, description, storage_set_id, is_public, default_bookmark, topics, search_vector, next_issue_number, next_landing_number, is_fork, fork_id, is_template, template_id, is_archived, archived_at, is_mirror, mirror_destination, mirror_status, last_mirror_at, last_mirror_error, last_mirror_github_head, mirror_behind_refs, mirror_failed_refs, workspace_idle_timeout_secs, workspace_persistence, workspace_dependencies, clone_depth, landing_queue_mode, landing_queue_required_checks, num_stars, num_forks, num_watches, num_issues, num_closed_issues, created_at, updated_at
`

type TransferRepoToUserParams struct {
	NewUserID pgtype.Int8 `json:"new_user_id"`
	ID        int64       `json:"id"`
}

func (q *Queries) TransferRepoToUser(ctx context.Context, arg TransferRepoToUserParams) (Repository, error) {
	row := q.db.QueryRow(ctx, transferRepoToUser, arg.NewUserID, arg.ID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Name,
		&i.LowerName,
		&i.Description,
		&i.StorageSetID,
		&i.IsPublic,
		&i.DefaultBookmark,
		&i.Topics,
		&i.SearchVector,
		&i.NextIssueNumber,
		&i.NextLandingNumber,
		&i.IsFork,
		&i.ForkID,
		&i.IsTemplate,
		&i.TemplateID,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.IsMirror,
		&i.MirrorDestination,
		&i.MirrorStatus,
		&i.LastMirrorAt,
		&i.LastMirrorError,
		&i.LastMirrorGithubHead,
		&i.MirrorBehindRefs,
		&i.MirrorFailedRefs,
		&i.WorkspaceIdleTimeoutSecs,
		&i.WorkspacePersistence,
		&i.WorkspaceDependencies,
		&i.CloneDepth,
		&i.LandingQueueMode,
		&i.LandingQueueRequiredChecks,
		&i.NumStars,
		&i.NumForks,
		&i.NumWatches,
		&i.NumIssues,
		&i.NumClosedIssues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unarchiveRepo = `-- name: UnarchiveRepo :one
UPDATE repositories
SET is_archived = FALSE,
    archived_at = NULL,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, org_id, name, lower_name, description, storage_set_id, is_public, default_bookmark, topics, search_vector, next_issue_number, next_landing_number, is_fork, fork_id, is_template, template_id, is_archived, archived_at, is_mirror, mirror_destination, mirror_status, last_mirror_at, last_mirror_error, last_mirror_github_head, mirror_behind_refs, mirror_failed_refs, workspace_idle_timeout_secs, workspace_persistence, workspace_dependencies, clone_depth, landing_queue_mode, landing_queue_required_checks, num_stars, num_forks, num_watches, num_issues, num_closed_issues, created_at, updated_at
`

func (q *Queries) UnarchiveRepo(ctx context.Context, id int64) (Repository, error) {
	row := q.db.QueryRow(ctx, unarchiveRepo, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Name,
		&i.LowerName,
		&i.Description,
		&i.StorageSetID,
		&i.IsPublic,
		&i.DefaultBookmark,
		&i.Topics,
		&i.SearchVector,
		&i.NextIssueNumber,
		&i.NextLandingNumber,
		&i.IsFork,
		&i.ForkID,
		&i.IsTemplate,
		&i.TemplateID,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.IsMirror,
		&i.MirrorDestination,
		&i.MirrorStatus,
		&i.LastMirrorAt,
		&i.LastMirrorError,
		&i.LastMirrorGithubHead,
		&i.MirrorBehindRefs,
		&i.MirrorFailedRefs,
		&i.WorkspaceIdleTimeoutSecs,
		&i.WorkspacePersistence,
		&i.WorkspaceDependencies,
		&i.CloneDepth,
		&i.LandingQueueMode,
		&i.LandingQueueRequiredChecks,
		&i.NumStars,
		&i.NumForks,
		&i.NumWatches,
		&i.NumIssues,
		&i.NumClosedIssues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRepo = `-- name: UpdateRepo :one
UPDATE repositories
SET name = $1,
    lower_name = $2,
    description = $3,
    is_public = $4,
    default_bookmark = $5,
    topics = $6,
    landing_queue_mode = $7,
    landing_queue_required_checks = COALESCE($8::text[], '{}'::text[]),
    updated_at = NOW()
WHERE id = $9
RETURNING id, user_id, org_id, name, lower_name, description, storage_set_id, is_public, default_bookmark, topics, search_vector, next_issue_number, next_landing_number, is_fork, fork_id, is_template, template_id, is_archived, archived_at, is_mirror, mirror_destination, mirror_status, last_mirror_at, last_mirror_error, last_mirror_github_head, mirror_behind_refs, mirror_failed_refs, workspace_idle_timeout_secs, workspace_persistence, workspace_dependencies, clone_depth, landing_queue_mode, landing_queue_required_checks, num_stars, num_forks, num_watches, num_issues, num_closed_issues, created_at, updated_at
`

type UpdateRepoParams struct {
	Name                       string   `json:"name"`
	LowerName                  string   `json:"lower_name"`
	Description                string   `json:"description"`
	IsPublic                   bool     `json:"is_public"`
	DefaultBookmark            string   `json:"default_bookmark"`
	Topics                     []string `json:"topics"`
	LandingQueueMode           string   `json:"landing_queue_mode"`
	LandingQueueRequiredChecks []string `json:"landing_queue_required_checks"`
	ID                         int64    `json:"id"`
}

func (q *Queries) UpdateRepo(ctx context.Context, arg UpdateRepoParams) (Repository, error) {
	row := q.db.QueryRow(ctx, updateRepo,
		arg.Name,
		arg.LowerName,
		arg.Description,
		arg.IsPublic,
		arg.DefaultBookmark,
		arg.Topics,
		arg.LandingQueueMode,
		arg.LandingQueueRequiredChecks,
		arg.ID,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Name,
		&i.LowerName,
		&i.Description,
		&i.StorageSetID,
		&i.IsPublic,
		&i.DefaultBookmark,
		&i.Topics,
		&i.SearchVector,
		&i.NextIssueNumber,
		&i.NextLandingNumber,
		&i.IsFork,
		&i.ForkID,
		&i.IsTemplate,
		&i.TemplateID,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.IsMirror,
		&i.MirrorDestination,
		&i.MirrorStatus,
		&i.LastMirrorAt,
		&i.LastMirrorError,
		&i.LastMirrorGithubHead,
		&i.MirrorBehindRefs,
		&i.MirrorFailedRefs,
		&i.WorkspaceIdleTimeoutSecs,
		&i.WorkspacePersistence,
		&i.WorkspaceDependencies,
		&i.CloneDepth,
		&i.LandingQueueMode,
		&i.LandingQueueRequiredChecks,
		&i.NumStars,
		&i.NumForks,
		&i.NumWatches,
		&i.NumIssues,
		&i.NumClosedIssues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRepoConfigState = `-- name: UpdateRepoConfigState :one
UPDATE repositories
SET description = $1,
    is_public = $2,
    topics = COALESCE($3::text[], '{}'::text[]),
    is_mirror = $4,
    mirror_destination = $5,
    workspace_idle_timeout_secs = $6,
    workspace_persistence = $7,
    workspace_dependencies = COALESCE($8::text[], '{}'::text[]),
    landing_queue_mode = $9,
    landing_queue_required_checks = COALESCE($10::text[], '{}'::text[]),
    updated_at = NOW()
WHERE id = $11
RETURNING id, user_id, org_id, name, lower_name, description, storage_set_id, is_public, default_bookmark, topics, search_vector, next_issue_number, next_landing_number, is_fork, fork_id, is_template, template_id, is_archived, archived_at, is_mirror, mirror_destination, mirror_status, last_mirror_at, last_mirror_error, last_mirror_github_head, mirror_behind_refs, mirror_failed_refs, workspace_idle_timeout_secs, workspace_persistence, workspace_dependencies, clone_depth, landing_queue_mode, landing_queue_required_checks, num_stars, num_forks, num_watches, num_issues, num_closed_issues, created_at, updated_at
`

type UpdateRepoConfigStateParams struct {
	Description                string   `json:"description"`
	IsPublic                   bool     `json:"is_public"`
	Topics                     []string `json:"topics"`
	IsMirror                   bool     `json:"is_mirror"`
	MirrorDestination          string   `json:"mirror_destination"`
	WorkspaceIdleTimeoutSecs   int32    `json:"workspace_idle_timeout_secs"`
	WorkspacePersistence       string   `json:"workspace_persistence"`
	WorkspaceDependencies      []string `json:"workspace_dependencies"`
	LandingQueueMode           string   `json:"landing_queue_mode"`
	LandingQueueRequiredChecks []string `json:"landing_queue_required_checks"`
	ID                         int64    `json:"id"`
}

func (q *Queries) UpdateRepoConfigState(ctx context.Context, arg UpdateRepoConfigStateParams) (Repository, error) {
	row := q.db.QueryRow(ctx, updateRepoConfigState,
		arg.Description,
		arg.IsPublic,
		arg.Topics,
		arg.IsMirror,
		arg.MirrorDestination,
		arg.WorkspaceIdleTimeoutSecs,
		arg.WorkspacePersistence,
		arg.WorkspaceDependencies,
		arg.LandingQueueMode,
		arg.LandingQueueRequiredChecks,
		arg.ID,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Name,
		&i.LowerName,
		&i.Description,
		&i.StorageSetID,
		&i.IsPublic,
		&i.DefaultBookmark,
		&i.Topics,
		&i.SearchVector,
		&i.NextIssueNumber,
		&i.NextLandingNumber,
		&i.IsFork,
		&i.ForkID,
		&i.IsTemplate,
		&i.TemplateID,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.IsMirror,
		&i.MirrorDestination,
		&i.MirrorStatus,
		&i.LastMirrorAt,
		&i.LastMirrorError,
		&i.LastMirrorGithubHead,
		&i.MirrorBehindRefs,
		&i.MirrorFailedRefs,
		&i.WorkspaceIdleTimeoutSecs,
		&i.WorkspacePersistence,
		&i.WorkspaceDependencies,
		&i.CloneDepth,
		&i.LandingQueueMode,
		&i.LandingQueueRequiredChecks,
		&i.NumStars,
		&i.NumForks,
		&i.NumWatches,
		&i.NumIssues,
		&i.NumClosedIssues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRepoTopics = `-- name: UpdateRepoTopics :one
UPDATE repositories
SET topics = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, user_id, org_id, name, lower_name, description, storage_set_id, is_public, default_bookmark, topics, search_vector, next_issue_number, next_landing_number, is_fork, fork_id, is_template, template_id, is_archived, archived_at, is_mirror, mirror_destination, mirror_status, last_mirror_at, last_mirror_error, last_mirror_github_head, mirror_behind_refs, mirror_failed_refs, workspace_idle_timeout_secs, workspace_persistence, workspace_dependencies, clone_depth, landing_queue_mode, landing_queue_required_checks, num_stars, num_forks, num_watches, num_issues, num_closed_issues, created_at, updated_at
`

type UpdateRepoTopicsParams struct {
	Topics []string `json:"topics"`
	ID     int64    `json:"id"`
}

func (q *Queries) UpdateRepoTopics(ctx context.Context, arg UpdateRepoTopicsParams) (Repository, error) {
	row := q.db.QueryRow(ctx, updateRepoTopics, arg.Topics, arg.ID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Name,
		&i.LowerName,
		&i.Description,
		&i.StorageSetID,
		&i.IsPublic,
		&i.DefaultBookmark,
		&i.Topics,
		&i.SearchVector,
		&i.NextIssueNumber,
		&i.NextLandingNumber,
		&i.IsFork,
		&i.ForkID,
		&i.IsTemplate,
		&i.TemplateID,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.IsMirror,
		&i.MirrorDestination,
		&i.MirrorStatus,
		&i.LastMirrorAt,
		&i.LastMirrorError,
		&i.LastMirrorGithubHead,
		&i.MirrorBehindRefs,
		&i.MirrorFailedRefs,
		&i.WorkspaceIdleTimeoutSecs,
		&i.WorkspacePersistence,
		&i.WorkspaceDependencies,
		&i.CloneDepth,
		&i.LandingQueueMode,
		&i.LandingQueueRequiredChecks,
		&i.NumStars,
		&i.NumForks,
		&i.NumWatches,
		&i.NumIssues,
		&i.NumClosedIssues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
