// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sandbox_access_tokens.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSandboxAccessToken = `-- name: CreateSandboxAccessToken :one

INSERT INTO sandbox_access_tokens (
    workspace_id,
    vm_id,
    user_id,
    linux_user,
    token_hash,
    token_type,
    expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, vm_id, user_id, linux_user, token_hash, token_type, expires_at, used_at, created_at
`

type CreateSandboxAccessTokenParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	VmID        string      `json:"vm_id"`
	UserID      int64       `json:"user_id"`
	LinuxUser   string      `json:"linux_user"`
	TokenHash   []byte      `json:"token_hash"`
	TokenType   string      `json:"token_type"`
	ExpiresAt   time.Time   `json:"expires_at"`
}

// ---- Sandbox Access Tokens (SSH/Terminal gateway auth) ----
func (q *Queries) CreateSandboxAccessToken(ctx context.Context, arg CreateSandboxAccessTokenParams) (SandboxAccessToken, error) {
	row := q.db.QueryRow(ctx, createSandboxAccessToken,
		arg.WorkspaceID,
		arg.VmID,
		arg.UserID,
		arg.LinuxUser,
		arg.TokenHash,
		arg.TokenType,
		arg.ExpiresAt,
	)
	var i SandboxAccessToken
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.VmID,
		&i.UserID,
		&i.LinuxUser,
		&i.TokenHash,
		&i.TokenType,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSandboxAccessTokens = `-- name: DeleteExpiredSandboxAccessTokens :exec
DELETE FROM sandbox_access_tokens
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSandboxAccessTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSandboxAccessTokens)
	return err
}

const getSandboxAccessTokenByHash = `-- name: GetSandboxAccessTokenByHash :one
SELECT id, workspace_id, vm_id, user_id, linux_user, token_hash, token_type, expires_at, used_at, created_at
FROM sandbox_access_tokens
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > NOW()
`

func (q *Queries) GetSandboxAccessTokenByHash(ctx context.Context, tokenHash []byte) (SandboxAccessToken, error) {
	row := q.db.QueryRow(ctx, getSandboxAccessTokenByHash, tokenHash)
	var i SandboxAccessToken
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.VmID,
		&i.UserID,
		&i.LinuxUser,
		&i.TokenHash,
		&i.TokenType,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markSandboxAccessTokenUsed = `-- name: MarkSandboxAccessTokenUsed :exec
UPDATE sandbox_access_tokens
SET used_at = NOW()
WHERE id = $1
  AND used_at IS NULL
`

func (q *Queries) MarkSandboxAccessTokenUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markSandboxAccessTokenUsed, id)
	return err
}
