// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_provisioning.sql

package db

import (
	"context"
)

const completePendingWorkspaceSessions = `-- name: CompletePendingWorkspaceSessions :many
UPDATE workspace_sessions s SET status='running', updated_at=now()
FROM workspaces w
WHERE s.workspace_id=w.id AND w.id=$1::uuid
  AND w.status='running' AND w.deleted_at IS NULL
  AND s.status IN ('pending','starting')
RETURNING s.id
`

func (q *Queries) CompletePendingWorkspaceSessions(ctx context.Context, workspaceID string) ([]string, error) {
	rows, err := q.db.Query(ctx, completePendingWorkspaceSessions, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceProvisioningRecovery = `-- name: ListWorkspaceProvisioningRecovery :many
SELECT w.id, w.repository_id, w.user_id, w.target_bookmark,
       COALESCE(u.username, o.name, '')::text AS repository_owner,
       r.name AS repository_name
FROM workspaces w
JOIN repositories r ON r.id = w.repository_id
LEFT JOIN users u ON u.id = r.user_id
LEFT JOIN organizations o ON o.id = r.org_id
WHERE w.deleted_at IS NULL AND (w.status IN ('pending','starting')
 OR (w.status='running' AND EXISTS (SELECT 1 FROM workspace_sessions s WHERE s.workspace_id=w.id AND s.status IN ('pending','starting'))))
AND (w.status='running' OR w.updated_at < now()-interval '10 minutes')
ORDER BY w.updated_at, w.id
LIMIT 100
`

type ListWorkspaceProvisioningRecoveryRow struct {
	ID              string `json:"id"`
	RepositoryID    int64  `json:"repository_id"`
	UserID          int64  `json:"user_id"`
	TargetBookmark  string `json:"target_bookmark"`
	RepositoryOwner string `json:"repository_owner"`
	RepositoryName  string `json:"repository_name"`
}

// Older API replicas do not hold ownership locks. Allow their bounded
// ten-minute attempt to finish during the first rolling upgrade.
func (q *Queries) ListWorkspaceProvisioningRecovery(ctx context.Context) ([]ListWorkspaceProvisioningRecoveryRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceProvisioningRecovery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceProvisioningRecoveryRow{}
	for rows.Next() {
		var i ListWorkspaceProvisioningRecoveryRow
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.UserID,
			&i.TargetBookmark,
			&i.RepositoryOwner,
			&i.RepositoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tryLockWorkspaceProvisioning = `-- name: TryLockWorkspaceProvisioning :one
SELECT pg_try_advisory_xact_lock(hashtextextended('workspace-provision:' || $1::text, 0))::boolean AS acquired
`

// Transaction-scoped ownership is released on an API crash, not on row age.
func (q *Queries) TryLockWorkspaceProvisioning(ctx context.Context, workspaceID string) (bool, error) {
	row := q.db.QueryRow(ctx, tryLockWorkspaceProvisioning, workspaceID)
	var acquired bool
	err := row.Scan(&acquired)
	return acquired, err
}
