// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow_runs_agent_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWorkflowRunByAgentToken = `-- name: GetWorkflowRunByAgentToken :one
SELECT id, repository_id, workflow_definition_id, status, trigger_event, trigger_ref, trigger_commit_sha, dispatch_inputs, agent_token_hash, agent_token_expires_at, jjhub_token_id, check_run_id, check_run_url, started_at, completed_at, created_at, updated_at, execution_plane, log_bytes, log_entry_count, cancel_reason
FROM workflow_runs
WHERE agent_token_hash = $1
`

func (q *Queries) GetWorkflowRunByAgentToken(ctx context.Context, agentTokenHash pgtype.Text) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowRunByAgentToken, agentTokenHash)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.WorkflowDefinitionID,
		&i.Status,
		&i.TriggerEvent,
		&i.TriggerRef,
		&i.TriggerCommitSha,
		&i.DispatchInputs,
		&i.AgentTokenHash,
		&i.AgentTokenExpiresAt,
		&i.JjhubTokenID,
		&i.CheckRunID,
		&i.CheckRunUrl,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExecutionPlane,
		&i.LogBytes,
		&i.LogEntryCount,
		&i.CancelReason,
	)
	return i, err
}

const updateWorkflowRunAgentToken = `-- name: UpdateWorkflowRunAgentToken :one
UPDATE workflow_runs
SET agent_token_hash = $1,
    agent_token_expires_at = $2,
    updated_at = NOW()
WHERE id = $3
RETURNING id, repository_id, workflow_definition_id, status, trigger_event, trigger_ref, trigger_commit_sha, dispatch_inputs, agent_token_hash, agent_token_expires_at, jjhub_token_id, check_run_id, check_run_url, started_at, completed_at, created_at, updated_at, execution_plane, log_bytes, log_entry_count, cancel_reason
`

type UpdateWorkflowRunAgentTokenParams struct {
	AgentTokenHash      pgtype.Text        `json:"agent_token_hash"`
	AgentTokenExpiresAt pgtype.Timestamptz `json:"agent_token_expires_at"`
	ID                  int64              `json:"id"`
}

func (q *Queries) UpdateWorkflowRunAgentToken(ctx context.Context, arg UpdateWorkflowRunAgentTokenParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, updateWorkflowRunAgentToken, arg.AgentTokenHash, arg.AgentTokenExpiresAt, arg.ID)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.WorkflowDefinitionID,
		&i.Status,
		&i.TriggerEvent,
		&i.TriggerRef,
		&i.TriggerCommitSha,
		&i.DispatchInputs,
		&i.AgentTokenHash,
		&i.AgentTokenExpiresAt,
		&i.JjhubTokenID,
		&i.CheckRunID,
		&i.CheckRunUrl,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExecutionPlane,
		&i.LogBytes,
		&i.LogEntryCount,
		&i.CancelReason,
	)
	return i, err
}
