// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow_task_guest_tokens.sql

package db

import (
	"context"
	"time"
)

const getWorkflowRunByTaskGuestToken = `-- name: GetWorkflowRunByTaskGuestToken :one
SELECT wr.id, wr.repository_id, wr.workflow_definition_id, wr.status, wr.trigger_event, wr.trigger_ref, wr.trigger_commit_sha, wr.dispatch_inputs, wr.agent_token_hash, wr.agent_token_expires_at, wr.jjhub_token_id, wr.check_run_id, wr.check_run_url, wr.started_at, wr.completed_at, wr.created_at, wr.updated_at, wr.execution_plane, wr.log_bytes, wr.log_entry_count, wr.cancel_reason,
       wt.id AS workflow_task_id,
       wt.status AS task_status,
       gt.expires_at AS token_expires_at
FROM workflow_task_guest_tokens AS gt
JOIN workflow_tasks AS wt ON wt.id = gt.workflow_task_id
JOIN workflow_runs AS wr ON wr.id = wt.workflow_run_id AND wr.repository_id = wt.repository_id
WHERE gt.token_hash = $1
`

type GetWorkflowRunByTaskGuestTokenRow struct {
	WorkflowRun    WorkflowRun `json:"workflow_run"`
	WorkflowTaskID int64       `json:"workflow_task_id"`
	TaskStatus     string      `json:"task_status"`
	TokenExpiresAt time.Time   `json:"token_expires_at"`
}

// Resolves a job credential to its run. The caller still checks expiry, the
// task's status and the run's status; the join pins the run and the task to
// the same repository.
func (q *Queries) GetWorkflowRunByTaskGuestToken(ctx context.Context, tokenHash string) (GetWorkflowRunByTaskGuestTokenRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowRunByTaskGuestToken, tokenHash)
	var i GetWorkflowRunByTaskGuestTokenRow
	err := row.Scan(
		&i.WorkflowRun.ID,
		&i.WorkflowRun.RepositoryID,
		&i.WorkflowRun.WorkflowDefinitionID,
		&i.WorkflowRun.Status,
		&i.WorkflowRun.TriggerEvent,
		&i.WorkflowRun.TriggerRef,
		&i.WorkflowRun.TriggerCommitSha,
		&i.WorkflowRun.DispatchInputs,
		&i.WorkflowRun.AgentTokenHash,
		&i.WorkflowRun.AgentTokenExpiresAt,
		&i.WorkflowRun.JjhubTokenID,
		&i.WorkflowRun.CheckRunID,
		&i.WorkflowRun.CheckRunUrl,
		&i.WorkflowRun.StartedAt,
		&i.WorkflowRun.CompletedAt,
		&i.WorkflowRun.CreatedAt,
		&i.WorkflowRun.UpdatedAt,
		&i.WorkflowRun.ExecutionPlane,
		&i.WorkflowRun.LogBytes,
		&i.WorkflowRun.LogEntryCount,
		&i.WorkflowRun.CancelReason,
		&i.WorkflowTaskID,
		&i.TaskStatus,
		&i.TokenExpiresAt,
	)
	return i, err
}

const issueWorkflowTaskGuestToken = `-- name: IssueWorkflowTaskGuestToken :execrows
INSERT INTO workflow_task_guest_tokens (workflow_task_id, token_hash, expires_at)
SELECT wt.id, $1, $2
FROM workflow_tasks AS wt
WHERE wt.id = $3
  AND wt.workflow_run_id = $4
  AND wt.repository_id = $5
  AND wt.status = 'running'
ON CONFLICT (workflow_task_id) DO UPDATE
SET token_hash = EXCLUDED.token_hash,
    expires_at = EXCLUDED.expires_at,
    created_at = NOW()
`

type IssueWorkflowTaskGuestTokenParams struct {
	TokenHash      string    `json:"token_hash"`
	ExpiresAt      time.Time `json:"expires_at"`
	WorkflowTaskID int64     `json:"workflow_task_id"`
	WorkflowRunID  int64     `json:"workflow_run_id"`
	RepositoryID   int64     `json:"repository_id"`
}

// Mints (or replaces) the job credential for a task that is running now. A
// task that is not running, or that belongs to another run or repository,
// gets no credential.
func (q *Queries) IssueWorkflowTaskGuestToken(ctx context.Context, arg IssueWorkflowTaskGuestTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, issueWorkflowTaskGuestToken,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.WorkflowTaskID,
		arg.WorkflowRunID,
		arg.RepositoryID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeWorkflowRunGuestTokens = `-- name: RevokeWorkflowRunGuestTokens :exec
DELETE FROM workflow_task_guest_tokens AS gt
USING workflow_tasks AS wt
WHERE wt.id = gt.workflow_task_id
  AND wt.workflow_run_id = $1
`

func (q *Queries) RevokeWorkflowRunGuestTokens(ctx context.Context, workflowRunID int64) error {
	_, err := q.db.Exec(ctx, revokeWorkflowRunGuestTokens, workflowRunID)
	return err
}

const revokeWorkflowTaskGuestToken = `-- name: RevokeWorkflowTaskGuestToken :exec
DELETE FROM workflow_task_guest_tokens
WHERE workflow_task_id = $1
`

func (q *Queries) RevokeWorkflowTaskGuestToken(ctx context.Context, workflowTaskID int64) error {
	_, err := q.db.Exec(ctx, revokeWorkflowTaskGuestToken, workflowTaskID)
	return err
}
