-- Revision: 20260808120000.
-- Idle-suspend must release the worker reservation.
--
-- Before this column the allocator only ever gave a reservation back when the
-- instance row was deleted (PGStore.Release sets deleted_at). Stopping or
-- suspending a guest — which is what the 30-minute idle timeout does to every
-- repo-gateway and workspace VM — left allocated_cpu_millis/memory/disk/vms
-- pinned on sandbox_hosts forever, so N *lifetime* VMs exhausted a worker even
-- with every guest powered off. On a 7000-millis worker that is seven VMs, and
-- the pool wedged completely on 2026-08-07.
--
--   reservation_held   TRUE  while this instance's requested capacity is
--                            counted in sandbox_hosts.allocated_*.
--                      FALSE while the guest is stopped/suspended and its
--                            share has been handed back to the pool.
--
-- Existing rows default to TRUE, which is exactly the pre-migration accounting:
-- every live instance is currently counted. The first stop/suspend after deploy
-- flips them to FALSE and returns the capacity. The flag is the ONLY thing that
-- makes release/re-acquire idempotent under concurrent suspend/resume/delete,
-- so it is checked inside the same transaction that moves allocated_*.
ALTER TABLE sandbox_instances
    ADD COLUMN IF NOT EXISTS reservation_held BOOLEAN NOT NULL DEFAULT TRUE;
