/*
 * The practice repository (onboarding SCRIPT v4, section 4 "Core design"):
 * `practice:smithersai/hello-server` is a repository SOURCE, not a tutorial
 * UI. The same flows the user runs on their own repository (issues.list,
 * issues.view, prs.list, files.read, agent.change, agent.change.start,
 * runs.trace.select, change.open) answer from this bundle when they name the
 * practice key. Nothing here touches the network, an account or a clock.
 *
 * The fixtures are generated by scripts/record-practice-hello-server.ts from
 * a real git clone with pinned authors and dates; never hand-edit them.
 */
import type { Card } from "../AppState"
import type { PracticeCommits } from "../seams/CommitsSeam"
import snapshot from "./hello-server/snapshot.json"
import issues from "./hello-server/issues.json"
import prs from "./hello-server/prs.json"
import plan from "./hello-server/plan.json"
import commits from "./hello-server/commits.json"
import journal from "./hello-server/run.journal.json"
import stack23 from "./hello-server/stacks/2-3.json"
import stack123 from "./hello-server/stacks/1-2-3.json"
import stack12 from "./hello-server/stacks/1-2.json"
import stack2 from "./hello-server/stacks/2.json"

export const PRACTICE_REPO = "practice:smithersai/hello-server"
export const PRACTICE_NAME = "hello-server"
export const PRACTICE_BRANCH = commits.branch
export const PRACTICE_RUN_ID = journal.runId

/** True for the practice key: the one repository every host can read without an account. */
export const isPracticeRepo = (repo: string | null | undefined): boolean => repo === PRACTICE_REPO

/** True when a flow's raw arguments name the practice key as a token. */
export const namesPractice = (args: string | null | undefined): boolean =>
  (args ?? "").trim().split(/\s+/).includes(PRACTICE_REPO)

type CardOf<K extends Card["kind"]> = Extract<Card, { kind: K }>

/*
 * GitHub-like presentation facts (author login and avatar, label colors,
 * assignees, timestamps, draft, review requests) for the restyled issue and
 * PR cards. They ride on the payload as a spread: the store's card schema
 * keeps each one once it declares it and drops it until then, so the bundle
 * never has to wait on the schema. Avatars are data: URIs; nothing is fetched.
 */
const withPresentation = <T extends object>(base: T, extra: object): T => ({ ...base, ...extra }) as T

/** Label colors keyed by label name; the fixture's per-issue object literals widen to one record. */
const colorsOf = (value: object): Record<string, string> =>
  Object.fromEntries(Object.entries(value).filter((entry): entry is [string, string] => typeof entry[1] === "string"))

/** Stable ids: practice cards are idempotent, so a replayed beat replaces its card. */
export const PRACTICE_CARD = {
  issues: "practice-issues",
  issue: (number: number) => `practice-issue-${number}`,
  prs: "practice-prs",
  file: (path: string) => `practice-file-${path}`,
  plan: "practice-plan",
  run: `flow-run-${journal.runId}`,
  commits: "practice-commits",
} as const

export const practiceSnapshot = snapshot
export const practiceCommits = commits.commits
export const practicePlan: unknown = plan
export const practiceJournal = journal

export const practiceIssueList = (filter: "open" | "closed" | "all"): CardOf<"issue-list">["payload"] => ({
  repo: PRACTICE_REPO,
  filter,
  issues: issues
    .filter((issue) => filter === "all" || issue.state === filter)
    .map((issue) => withPresentation({
      number: issue.number,
      title: issue.title,
      state: issue.state as "open" | "closed",
      author: issue.author,
      comments: issue.comments.length,
      updatedAt: issue.updatedAt,
      labels: issue.labels,
    }, { authorLogin: issue.authorLogin, authorAvatar: issue.authorAvatar, labelColors: colorsOf(issue.labelColors),
      createdAt: issue.createdAt, assignees: issue.assignees })),
})

export const practiceIssue = (number: number): CardOf<"issue">["payload"] | undefined => {
  const issue = issues.find((row) => row.number === number)
  if (issue === undefined) return undefined
  return withPresentation({
    repo: PRACTICE_REPO,
    number: issue.number,
    title: issue.title,
    state: issue.state as "open" | "closed",
    author: issue.author,
    issueBody: issue.body,
    labels: issue.labels,
    comments: issue.comments.map((comment) => withPresentation(
      { author: comment.author, commentBody: comment.body, createdAt: comment.createdAt },
      { authorLogin: comment.authorLogin, authorAvatar: comment.authorAvatar })),
  }, { authorLogin: issue.authorLogin, authorAvatar: issue.authorAvatar, labelColors: colorsOf(issue.labelColors),
    createdAt: issue.createdAt, updatedAt: issue.updatedAt, assignees: issue.assignees })
}

export const practicePrList = (): CardOf<"pr-list">["payload"] => ({
  repo: PRACTICE_REPO,
  landings: prs.map((pr) => withPresentation({
    number: pr.number,
    title: pr.title,
    state: pr.state,
    author: pr.author,
    updatedAt: pr.updatedAt,
    branch: pr.branch,
    files: pr.files,
  }, { draft: pr.draft, baseBranch: pr.baseBranch, createdAt: pr.createdAt, comments: pr.comments, reviewsRequested: pr.reviewsRequested,
    labels: pr.labels, labelColors: colorsOf(pr.labelColors), authorLogin: pr.authorLogin, authorAvatar: pr.authorAvatar,
    additions: pr.additions, deletions: pr.deletions, assignees: pr.assignees, reviewers: pr.reviewers })),
})

/** The PR detail card (`prs.view 4 practice:…`): branch, commits and per-file patches from the recorded clone. */
export const practicePr = (number: number): CardOf<"pr">["payload"] | undefined => {
  const pr = prs.find((row) => row.number === number)
  if (pr === undefined) return undefined
  return withPresentation({
    repo: PRACTICE_REPO,
    number: pr.number,
    title: pr.title,
    state: pr.state,
    author: pr.author,
    prBody: pr.body,
    reviews: [],
    checks: [{ context: "test", state: "success" }],
  }, { branch: pr.branch, baseBranch: pr.baseBranch, draft: pr.draft, createdAt: pr.createdAt, labels: pr.labels,
    labelColors: colorsOf(pr.labelColors), authorLogin: pr.authorLogin, authorAvatar: pr.authorAvatar,
    commits: pr.commits, files: pr.filesDetail, reviewsRequested: pr.reviewsRequested })
}

export const practiceFile = (path: string): string | undefined =>
  (snapshot.files as Record<string, string | undefined>)[path.replace(/^\/+/, "")]

export const practiceFilePaths = (): ReadonlyArray<string> => Object.keys(snapshot.files).sort()

/** The picker's rows, bottom to top, all checked: the user decides what ships. */
export const practicePicker = (picked: ReadonlyArray<number> = commits.commits.map((commit) => commit.index)): CardOf<"commit-pick">["payload"] => ({
  repo: PRACTICE_REPO,
  branch: commits.branch,
  targetBookmark: "main",
  rows: commits.commits.map((commit) => ({
    index: commit.index,
    commitId: commit.commitId,
    changeId: commit.changeId,
    message: commit.message,
    additions: commit.additions,
    deletions: commit.deletions,
    locked: commit.locked,
    hint: commit.locked ? "the fix for #3" : commit.tag === "optional" ? "optional" : undefined,
  })),
  picked: [...picked].sort((a, b) => a - b),
})

const STACKS = [stack23, stack123, stack12, stack2]
export type PracticeStack = (typeof STACKS)[number]

/** The precomputed stack for a pick (every subset that keeps the locked fix), or why the pick is refused. */
export const practiceStack = (pick: ReadonlyArray<number>): PracticeStack | string => {
  const sorted = [...new Set(pick)].sort((a, b) => a - b)
  const locked = commits.commits.filter((commit) => commit.locked).map((commit) => commit.index)
  if (locked.some((index) => !sorted.includes(index))) return `Commit ${locked.join(", ")} is the fix for #3; it stays in the Change.`
  const found = STACKS.find((stack) => stack.pick.length === sorted.length && stack.pick.every((index, at) => index === sorted[at]))
  return found ?? `No commits ${sorted.join(", ")} on ${commits.branch}.`
}

/** Commit refs (full id, 7+ char prefix, change id, or 1-based index) to picker indexes. */
export const practicePickOf = (refs: ReadonlyArray<string>): ReadonlyArray<number> | string => {
  const picked: Array<number> = []
  for (const ref of refs) {
    const commit = commits.commits.find((row) =>
      String(row.index) === ref || row.changeId === ref || (ref.length >= 7 && row.commitId.startsWith(ref)))
    if (commit === undefined) return `No commit ${ref} on ${commits.branch}.`
    picked.push(commit.index)
  }
  return picked
}

/** The Change card the picker turns into: the stack, bottom to top, above its target. */
export const practiceChange = (stack: PracticeStack): CardOf<"change">["payload"] => {
  const top = stack.rows[stack.rows.length - 1]!
  return {
    repo: PRACTICE_REPO,
    changeId: top.changeId,
    description: "Fix /hello without a name (#3)",
    commitId: top.commitId,
    currentSeq: null,
    revisionCount: null,
    revisions: [],
    authorName: "Smithers",
    timestamp: null,
    repos: [{
      repo: PRACTICE_REPO,
      additions: stack.rows.reduce((sum, row) => sum + row.additions, 0),
      deletions: stack.rows.reduce((sum, row) => sum + row.deletions, 0),
    }],
    diff: null,
    checks: [{ context: "npm test", state: "success" }],
    findings: null,
    reviews: null,
    threads: null,
    conflicts: null,
    stack: {
      landingNumber: stack.landingNumber,
      state: "open",
      position: stack.rows.length,
      size: stack.rows.length,
      changeIds: stack.rows.map((row) => row.changeId),
      targetBookmark: stack.targetBookmark,
      conflictStatus: "clean",
      positionFrom: "request-order",
      rows: stack.rows.map((row) => {
        const moved = (row as { readonly rebased?: { readonly from: string; readonly to: string } }).rebased
        return {
          changeId: row.changeId,
          commitId: row.commitId,
          message: row.message,
          additions: row.additions,
          deletions: row.deletions,
          ...(moved === undefined ? {} : { rebased: { from: moved.from, to: moved.to } }),
        }
      }),
    },
    changeset: null,
  }
}

/** The trace node beat 7 opens: the turn that edits src/hello.ts. */
export const PRACTICE_EDIT_FRAME = journal.editFrame

type CommitDetail = (typeof commits.details)[keyof typeof commits.details]
const details = commits.details as Record<string, CommitDetail | undefined>
const branches = commits.branches as Record<string, ReadonlyArray<string> | undefined>
const summaryOf = (detail: CommitDetail) => ({
  commitId: detail.commitId, changeId: detail.changeId, title: detail.title,
  author: detail.author, authoredAt: detail.authoredAt, status: "success" as const,
})
/** A commit by full id, a 7+ character prefix, or its change id. */
const commitOf = (ref: string): CommitDetail | undefined =>
  Object.values(details).find((detail) => detail !== undefined &&
    (detail.commitId === ref || detail.changeId === ref || (ref.length >= 7 && detail.commitId.startsWith(ref))))

/*
 * The commits views on the practice repository (state/seams/CommitsSeam.ts):
 * `main` and `smithers/fix-hello-3`, newest first, each commit with its
 * author, time, parents, message and per-file patches from the recorded clone.
 */
export const practiceCommitsSource: PracticeCommits = {
  list: (branch) => {
    const name = branch ?? "main"
    const shas = branches[name]
    if (shas === undefined) return `No branch ${name} in ${PRACTICE_NAME}. Try main or ${commits.branch}.`
    return { branch: name, commits: shas.flatMap((sha) => { const detail = details[sha]; return detail === undefined ? [] : [summaryOf(detail)] }) }
  },
  read: (ref) => {
    const detail = commitOf(ref)
    if (detail === undefined) return `No commit ${ref} in ${PRACTICE_NAME}.`
    return {
      repo: PRACTICE_REPO,
      commit: summaryOf(detail),
      message: detail.message,
      parents: detail.parents.map((parent) => ({ commitId: parent.commitId, changeId: (parent as { changeId?: string }).changeId ?? null })),
      files: detail.files,
    }
  },
}
