export const DEFAULT_AGENT = "Claude Code"
export const DEFAULT_SMITHERS_BASE_URL = "http://localhost:7331"
export const DEFAULT_SMITHERS_MAX_CONCURRENCY = 4
export const DEFAULT_SMITHERS_MAX_BODY_BYTES = 1_048_576
export const DEFAULT_SMITHERS_PORT_BASE = 7440
export const DEFAULT_SMITHERS_MAX_WORKSPACE_INSTANCES = 1000
